src/objects/AACR_Session__c.object
<CustomObject>
    <description>A singular event session</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date of session</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of session</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End time of session</description>
        <label>End Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Event session is for</description>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipName>Sessions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start time of session</description>
        <label>Start Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <label>Live! Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live! Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <formula>IF ( DATEVALUE(Start_Date__c ) &gt;= DATE ( YEAR (DATEVALUE(Start_Date__c )),3,1)
+
(14- CASE( MOD(DATE ( YEAR (DATEVALUE(Start_Date__c )),3,1) - DATE (1900,1,7),7) ,0,7,MOD(DATE ( YEAR (DATEVALUE(Start_Date__c )),3,1) - DATE (1900,1,7),7)))

&amp;&amp;

DATEVALUE(Start_Date__c ) &lt; DATE(YEAR (DATEVALUE(Start_Date__c )),11,1) + (7- CASE( MOD(DATE ( YEAR (DATEVALUE(Start_Date__c )),11,1) - DATE (1900,1,7),7), 0,7,MOD(DATE ( YEAR (DATEVALUE(Start_Date__c )),11,1) - DATE (1900,1,7),7))),

IF( OR( VALUE( MID( TEXT( Start_Date__c  - (4/24) ), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Start_Date__c  - (4/24)), 12, 2 ) ) = 12 ), &quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Start_Date__c  - (4/24) ), 12, 2 ) ) - 
IF( VALUE( MID( TEXT( Start_Date__c  - (4/24)), 12, 2 ) ) &lt; 12, 0, 12 ) ) )
 &amp; &quot;:&quot; &amp; 
MID( TEXT( Start_Date__c  - (4/24)), 15, 2 )&amp;
 &quot; &quot; &amp;
IF( VALUE( MID( TEXT( Start_Date__c  - (4/24)), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; ), 
 
IF( OR( VALUE( MID( TEXT( Start_Date__c  - (5/24) ), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Start_Date__c  - (5/24)), 12, 2 ) ) = 12 ), &quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Start_Date__c  - (5/24) ), 12, 2 ) ) - 
IF( VALUE( MID( TEXT( Start_Date__c  - (5/24)), 12, 2 ) ) &lt; 12, 0, 12 ) ) ) &amp; &quot;:&quot; &amp; 
MID( TEXT( Start_Date__c  - (5/24)), 15, 2 )&amp;
 &quot; &quot; &amp;
IF( VALUE( MID( TEXT( Start_Date__c  - (5/24)), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; ))</formula>
        <label>Start Time</label>
        <type>Text</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session_Speaker__c.object
<CustomObject>
    <description>Speaker records associated with each session</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presentation_Time__c</fullName>
        <label>Presentation Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <description>Speaker roles for a particular session</description>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chair</fullName>
                </value>
                <value>
                    <fullName>Cochair</fullName>
                </value>
                <value>
                    <fullName>Program Committee Member</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Member</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Member</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Member</fullName>
                </value>
                <value>
                    <fullName>Program Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Program Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Keynote Speaker</fullName>
                </value>
                <value>
                    <fullName>Speaker</fullName>
                </value>
                <value>
                    <fullName>Session Chair</fullName>
                </value>
                <value>
                    <fullName>Discussant</fullName>
                </value>
                <value>
                    <fullName>Moderator</fullName>
                </value>
                <value>
                    <fullName>Panelist</fullName>
                </value>
                <value>
                    <fullName>Proffered Presenter</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Codirector</fullName>
                </value>
                <value>
                    <fullName>Faculty</fullName>
                </value>
                <value>
                    <fullName>Lab Director</fullName>
                </value>
                <value>
                    <fullName>Lab Assistant</fullName>
                </value>
                <value>
                    <fullName>Lecturer</fullName>
                </value>
                <value>
                    <fullName>Observer</fullName>
                </value>
                <value>
                    <fullName>Short-talk Presenter</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Abstract Review Committee Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session</label>
        <referenceTo>AACR_Session__c</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;--None--&quot;</defaultValue>
        <description>Status of speakers invitation</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Tentative</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Suggested</fullName>
                </value>
                <value>
                    <fullName>Considering</fullName>
                    <isActive>false</isActive>
                    <label>Considering</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <label>Presentation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventScheduleViewerController.cls
/**
 * Created by lauren.lezberg on 1/10/2020.
 */

public with sharing class EventScheduleViewerController {


    @AuraEnabled
    public static void deleteRecord(String recordId){

        try{
            Database.delete(recordId);
        }catch(Exception e){
            System.debug('Could not delete record: ' + e.getMessage());
            throw new AACRCustomException(recordId, e.getMessage(), e.getStackTraceString(), 'Event Schedule');
        }
    }


    /**
     * @purpose Retrieve full schedule for specified event. Creates a wrapper object of each daily schedule based of event dates.
     *
     * @param eventId
     *
     * @return ScheduleData wrapper object
     */
    @AuraEnabled
    public static ScheduleData getEventSchedule(String eventId){
        System.debug('getEventSchedule for event: ' + eventId);

        if(String.isBlank(eventId)){
            new AACRCustomException('EventId is null', 'EventScheduleViewerController.getEventSchedule', 'Event Schedule');
        }

        List<EventDaySchedule> eventSchedules = new List<EventDaySchedule>();
        //get all sessions and speakers for event
        List<AACR_Session__c> sessions = [SELECT Id, Date__c, Name, Start_Time__c, End_Time__c, Description__c, Event__r.Start_Date__c, Event__r.End_Date__c,
                                        (SELECT Id, Name,Speaker__c, Speaker__r.Name, Roles__c,Status__c, Presentation_Time__c FROM Session_Speakers__r WHERE RecordType.Name!='Chair Person' ORDER BY Presentation_Time__c ASC)
                                    FROM AACR_Session__c
                                    WHERE Event__c=: String.escapeSingleQuotes(eventId)
                                    ORDER BY Date__c, Start_Time__c];
//                                    AND RecordType.Name != 'CME Session'

        if(!sessions.isEmpty()) {
            List<Date> eventDates = new List<Date>();
            //get dates for event
            Date startDate = Date.newInstance(sessions[0].Event__r.Start_Date__c.year(),sessions[0].Event__r.Start_Date__c.month(), sessions[0].Event__r.Start_Date__c.day() );
            Date endDate = Date.newInstance(sessions[0].Event__r.End_Date__c.year(), sessions[0].Event__r.End_Date__c.month(), sessions[0].Event__r.End_Date__c.day());

            eventDates.add(startDate);

            if(endDate!=null) {
                Integer daysInBetween = startDate.daysBetween(endDate);

                for(Integer i=1; i<=daysInBetween;i++){
                    Date nextDay = startDate.addDays(i);
                    eventDates.add(nextDay);
                }

            }

            System.debug('Event Dates: ' + eventDates);

            //build list of schedules per day of sessions and speakers
            Integer idx =  0;
            for(Date evtDate : eventDates){
                EventDaySchedule daySchedule = new EventDaySchedule();
                daySchedule.eventDay = evtDate;
                daySchedule.sessionIdx = String.valueOf(idx);
                List<EventSession> daySessions = new List<EventSession>();

                    for (AACR_Session__c session : sessions) {
                        if (session.Date__c.format() == evtDate.format()) {
                            //build session wrapper object
                            EventSession eSession = new EventSession();
                            eSession.sessionId = session.Id;
                            eSession.sessionName = session.Name;
                            eSession.startTime = DateTime.newInstance(evtDate, session.Start_Time__c);
                            eSession.endTime = DateTime.newInstance(evtDate, session.End_Time__c);
                            eSession.description = session.Description__c;

                            List<Session_Speaker__c> speakerSessions = session.Session_Speakers__r;
                            List<SessionPanel> panels = new List<SessionPanel>();
                            for (Session_Speaker__c speaker : speakerSessions) {
                                //build presentation wrapper object
                                SessionPanel panel = new SessionPanel();
                                panel.panelId = speaker.Id;
                                panel.panelName = speaker.Name;
                                panel.speakerName = speaker.Speaker__r.Name;
                                panel.speakerRoles = speaker.Roles__c;
                                panel.speakerStatus = speaker.Status__c;
                                panel.speakerId = speaker.Speaker__c;
                                if (speaker.Presentation_Time__c != null) {
                                    panel.panelTime = DateTime.newInstance(evtDate, speaker.Presentation_Time__c);
                                }
                                panels.add(panel);
                            }

                            System.debug('presentations/panels: ' + panels);
                            eSession.panels = panels;
                            daySessions.add(eSession);
                        }
                        System.debug('sessions: ' + daySessions);
                        daySchedule.sessions = daySessions;
                    }

                eventSchedules.add(daySchedule);
                idx++;
            }

        } else { //if there are no sessions, get event dates
            List<Date> eventDates = new List<Date>();

            BR_Event__c evt = [SELECT Start_Date__c, End_Date__c FROM BR_Event__c WHERE Id=: eventId];

            Date startDate = Date.newInstance(evt.Start_Date__c.year(),evt.Start_Date__c.month(), evt.Start_Date__c.day() );
            eventDates.add(startDate);

            if(evt.End_Date__c!=null){
                Date endDate = Date.newInstance(evt.End_Date__c.year(),evt.End_Date__c.month(), evt.End_Date__c.day());
                Integer daysInBetween = startDate.daysBetween(endDate);

                for(Integer i=1; i<=daysInBetween;i++){
                    Date nextDay = startDate.addDays(i);
                    eventDates.add(nextDay);
                }
            }

            for(Date evtDate : eventDates) {
                EventDaySchedule daySchedule = new EventDaySchedule();
                daySchedule.eventDay = evtDate;
                List<EventSession> daySessions = new List<EventSession>();
                daySchedule.sessions = daySessions;

                eventSchedules.add(daySchedule);
            }
        }

        BR_Event__c event = [SELECT Id, Start_Date__c, End_Date__c FROM BR_Event__c WHERE Id=: eventId];

        return new ScheduleData(event,eventSchedules);

    }
    

    /**
     * Wrapper object for list of daily schedules for event
     */
    public class ScheduleData{
        @AuraEnabled
        public BR_Event__c event;

        @AuraEnabled
        public List<EventDaySchedule> schedule;


        public ScheduleData(BR_Event__c evt, List<EventDaySchedule> sched){
            this.event = evt;
            this.schedule = sched;
        }
    }


    /**
     * Wrapper object for an event daily schedule
     */
    public class EventDaySchedule{
        @AuraEnabled
        public Date eventDay;

        @AuraEnabled
        public String sessionIdx;

        @AuraEnabled
        public List<EventSession> sessions;

    }

    /**
     * Wrapper object for event session
     *
     * Needed to convert times to datetime in order to display in lightning component with correct formatting.
     */
    public class EventSession{
        @AuraEnabled
        public String sessionName;

        @AuraEnabled
        public Datetime startTime;

        @AuraEnabled
        public Datetime endTime;

        @AuraEnabled
        public String description;

        @AuraEnabled
        public String sessionId;

        @AuraEnabled
        public List<SessionPanel> panels;
    }

    /**
     * Wrapper object for event session speaker/presentation/panel
     *
     * Needed to convert presentation time to datetime in order to display in lightning component with correct formatting.
     */
    public class SessionPanel{
        @AuraEnabled
        public String speakerId;

        @AuraEnabled
        public String panelId;

        @AuraEnabled
        public String speakerName;

        @AuraEnabled
        public String speakerRoles;

        @AuraEnabled
        public String speakerStatus;

        @AuraEnabled
        public Datetime panelTime;

        @AuraEnabled
        public String panelName;
    }

}