src/objects/AACR_Error_Log__c.object
<CustomObject>
    <description>Holds aacr error log data</description>
    <fields>
        <fullName>Incident_Type__c</fullName>
        <label>Incident Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current salesforce user</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AACR_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AACR Error Log</label>
    <nameField>
        <label>AACR Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AACR Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AACRCustomException.cls
/**
 * Created by lauren.lezberg on 6/4/2020.
 */

public class AACRCustomException extends Exception{

    public AACRCustomException(String recordId, String errorMsg, String details, String category){
        try {
            AACR_Error_Log__c ae = ErrorHelper.buildErrorExceptionLog(errorMsg, details);
            ae.Incident_Type__c = category;
            ae.User__c = UserInfo.getUserId();
            insert ae;

            ErrorHelper.sendExceptionEmail(recordId, ae.Id, category, errorMsg, details);

            System.debug('success');
        } catch(Exception e){
            System.debug(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }


    public AACRCustomException(String errorMsg, String details, String category){
        try {
            AACR_Error_Log__c ae = ErrorHelper.buildErrorExceptionLog(errorMsg, details);
            ae.Incident_Type__c = category;
            ae.User__c = UserInfo.getUserId();
            insert ae;

            ErrorHelper.sendExceptionEmail(ae.Id, category, errorMsg, details);

            System.debug('success');
        } catch(Exception e){
            System.debug(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }

}