src/objects/AACR_Session__c.object
<CustomObject>
    <description>A singular event session</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date of session</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End time of session</description>
        <label>End Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Event session is for</description>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipName>Sessions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start time of session</description>
        <label>Start Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <label>Live! Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live! Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Preferences_Form_Fieldset__c</fullName>
        <label>Event Preferences Form Fieldset</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <formula>IF ( DATEVALUE(Start_Date__c ) &gt;= DATE ( YEAR (DATEVALUE(Start_Date__c )),3,1)
+
(14- CASE( MOD(DATE ( YEAR (DATEVALUE(Start_Date__c )),3,1) - DATE (1900,1,7),7) ,0,7,MOD(DATE ( YEAR (DATEVALUE(Start_Date__c )),3,1) - DATE (1900,1,7),7)))

&amp;&amp;

DATEVALUE(Start_Date__c ) &lt; DATE(YEAR (DATEVALUE(Start_Date__c )),11,1) + (7- CASE( MOD(DATE ( YEAR (DATEVALUE(Start_Date__c )),11,1) - DATE (1900,1,7),7), 0,7,MOD(DATE ( YEAR (DATEVALUE(Start_Date__c )),11,1) - DATE (1900,1,7),7))),

IF( OR( VALUE( MID( TEXT( Start_Date__c  - (4/24) ), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Start_Date__c  - (4/24)), 12, 2 ) ) = 12 ), &quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Start_Date__c  - (4/24) ), 12, 2 ) ) - 
IF( VALUE( MID( TEXT( Start_Date__c  - (4/24)), 12, 2 ) ) &lt; 12, 0, 12 ) ) )
 &amp; &quot;:&quot; &amp; 
MID( TEXT( Start_Date__c  - (4/24)), 15, 2 )&amp;
 &quot; &quot; &amp;
IF( VALUE( MID( TEXT( Start_Date__c  - (4/24)), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; ), 
 
IF( OR( VALUE( MID( TEXT( Start_Date__c  - (5/24) ), 12, 2 ) ) = 0, 
VALUE( MID( TEXT( Start_Date__c  - (5/24)), 12, 2 ) ) = 12 ), &quot;12&quot;, 
TEXT( VALUE( MID( TEXT( Start_Date__c  - (5/24) ), 12, 2 ) ) - 
IF( VALUE( MID( TEXT( Start_Date__c  - (5/24)), 12, 2 ) ) &lt; 12, 0, 12 ) ) ) &amp; &quot;:&quot; &amp; 
MID( TEXT( Start_Date__c  - (5/24)), 15, 2 )&amp;
 &quot; &quot; &amp;
IF( VALUE( MID( TEXT( Start_Date__c  - (5/24)), 12, 2 ) ) &lt; 12, &quot;AM&quot;, &quot;PM&quot; ))</formula>
        <label>Start Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue_Address__c</fullName>
        <label>Venue Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This object describes each session within an Event</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session_Speaker__c.object
<CustomObject>
    <description>Speaker records associated with each session</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session</label>
        <referenceTo>AACR_Session__c</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <label>Presentation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventDeleteButtonControllerTest.cls
/**
 * Created by lauren.lezberg on 8/17/2020.
 */

@IsTest
private class EventDeleteButtonControllerTest {

    @testSetup
    public static void setup(){
        BR_Event__c testEvent = new BR_Event__c(
                Name = 'Test event0',
                Start_Date__c = Datetime.newInstance(2016, 10, 15, 12, 30, 0),
                End_Date__c = Datetime.newInstance(2016, 10, 15, 17, 30, 0),
                Location__Latitude__s = 51.5156950,
                Location__Longitude__s = -0.0893931,
                Venue_Address__c = 'Test ave 12/20',
                Event_Preferences_Form_Fieldset__c = 'test'
        );
        insert testEvent;

        AACR_Session__c session = new AACR_Session__c(
                Name='Test Session',
                Event__c = testEvent.Id,
                Date__c = Date.newInstance(2016, 10,15),
                Start_Time__c = Time.newInstance(13, 0, 0, 0),
                End_Time__c = Time.newInstance(15, 0, 0, 0)
        );
        insert session;

        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        Session_Speaker__c sp = new Session_Speaker__c(
                Name='speaker 1',
                Session__c = session.Id,
                Speaker__c = con.Id
        );
        insert sp;

        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(alias = 'test',
                // AccountId = contactRecord1.AccountId,
                ProfileId = p.Id,
                email = 'test@testorg.com',
                emailencodingkey = 'UTF-8',
                lastname = 'Test User2',
                languagelocalekey = 'en_US',
                localesidkey = 'en_US',
                timezonesidkey = 'America/Los_Angeles',
                username = System.now().millisecond() + 'test@testorg2.com');
        insert u;


    }

    @isTest
    public static void test_showButton(){
        BR_Event__c testEvent = [SELECT Id FROM BR_Event__c WHERE Name='Test event0'];

        User u = [SELECT Id FROM User WHERE email= 'test@testorg.com'];

        PermissionSet ps = new PermissionSet();
        ps.Name = 'Test';
        ps.Label = 'Test';
        insert ps;

        SetupEntityAccess sea = new SetupEntityAccess();
        sea.ParentId = ps.Id;
        sea.SetupEntityId = [SELECT Id, DeveloperName FROM CustomPermission WHERE DeveloperName = 'Event_Delete'][0].Id;
        insert sea;

        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = ps.Id;
        insert psa;

        System.runAs(u) {
            Boolean showButton = EventDeleteButtonController.getShowButton(testEvent.Id);
            System.assertEquals(showButton, true);
        }
    }

    @isTest
    public static void test_deleteEvent(){
        BR_Event__c testEvent = [SELECT Id FROM BR_Event__c WHERE Name='Test event0'];

        Test.startTest();

        Map<Boolean, String> deleteMap = EventDeleteButtonController.deleteEvent(testEvent.Id);

        Test.stopTest();

        List<BR_Event__c> evts = [SELECT Name FROM BR_Event__c WHERE Id=: testEvent.Id];
        System.assert(evts.isEmpty(), 'Event Should be deleted');

        List<AACR_Session__c> sessions = [SELECT Id FRom AACR_Session__c WHERE Event__c=: testEvent.Id];
        System.assert(sessions.isEmpty(), 'Sessions Should be deleted');

        List<Session_Speaker__c> speakers = [SELECT Id FROM Session_Speaker__c WHERE Session__r.Event__c=: testEvent.Id];
        System.assert(speakers.isEmpty(), 'speakers Should be deleted');


    }
}