src/objects/AACR_Session__c.object
<CustomObject>
    <description>A singular event session</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Event session is for</description>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipName>Sessions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Live! Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live! Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session_Speaker__c.object
<CustomObject>
    <description>Speaker records associated with each session</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <description>Speaker roles for a particular session</description>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chair</fullName>
                </value>
                <value>
                    <fullName>Cochair</fullName>
                </value>
                <value>
                    <fullName>Program Committee Member</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Member</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Member</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Member</fullName>
                </value>
                <value>
                    <fullName>Program Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Program Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Keynote Speaker</fullName>
                </value>
                <value>
                    <fullName>Speaker</fullName>
                </value>
                <value>
                    <fullName>Session Chair</fullName>
                </value>
                <value>
                    <fullName>Discussant</fullName>
                </value>
                <value>
                    <fullName>Moderator</fullName>
                </value>
                <value>
                    <fullName>Panelist</fullName>
                </value>
                <value>
                    <fullName>Proffered Presenter</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Codirector</fullName>
                </value>
                <value>
                    <fullName>Faculty</fullName>
                </value>
                <value>
                    <fullName>Lab Director</fullName>
                </value>
                <value>
                    <fullName>Lab Assistant</fullName>
                </value>
                <value>
                    <fullName>Lecturer</fullName>
                </value>
                <value>
                    <fullName>Observer</fullName>
                </value>
                <value>
                    <fullName>Short-talk Presenter</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Abstract Review Committee Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <label>Presentation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChairPersonsControllerTest.cls
/**
 * Created by lauren.lezberg on 2/21/2020.
 */
@isTest
private with sharing class ChairPersonsControllerTest {

    @testSetup public static void setup(){
        Account acc = LiveTestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = LiveTestDataFactory.buildContact(acc.Id);
        insert con;

        BR_Event__c event = LiveTestDataFactory.buildEvent('Test Event', false, false);
        insert event;

        AACR_Session__c eventSession = LiveTestDataFactory.buildSession(event.Id, 'Test Session', Date.valueOf(event.Start_Date__c), Time.newInstance(11, 0, 0, 0), Time.newInstance(11, 30, 0, 0) );
        insert eventSession; 

        Id cpRecordTypeId = Schema.SObjectType.Session_Speaker__c.getRecordTypeInfosByName().get('Chair Person').getRecordTypeId();
        Session_Speaker__c speaker = LiveTestDataFactory.buildSessionSpeaker(eventSession.Id, 'Test Presentation', con.Id);
        speaker.Roles__c = 'Chair';
        speaker.Event__c = event.Id;
        speaker.RecordTypeId = cpRecordTypeId;
        insert speaker;
    }

    @isTest
    public static void test_getChairPersons(){
        Id cpRecordTypeId = Schema.SObjectType.Session_Speaker__c.getRecordTypeInfosByName().get('Chair Person').getRecordTypeId();
        String eventId = [SELECT Id FROM BR_Event__c LIMIT 1].Id;

        Test.startTest();
        ChairPersonsController.ChairPersonsData cpd = ChairPersonsController.getChairPersonsData(eventId);
        System.assertNotEquals(null, cpd);
        System.assertEquals(1, cpd.persons.size());
        System.assertEquals(cpRecordTypeId, cpd.cpRecordTypeId);

        cpd = ChairPersonsController.getChairPersonsData(null);
        System.assertEquals(null, cpd);

        Test.stopTest();



    }

    @isTest
    public static void test_deleteChairPerson(){
        Id cpRecordTypeId = Schema.SObjectType.Session_Speaker__c.getRecordTypeInfosByName().get('Chair Person').getRecordTypeId();
        String eventId = [SELECT Id FROM BR_Event__c LIMIT 1].Id;

        Test.startTest();
        ChairPersonsController.ChairPersonsData cpd = ChairPersonsController.getChairPersonsData(eventId);

        ChairPersonsController.deleteChairperson(cpd.persons[0].Id);

        Test.stopTest();
    }
}