src/objects/AACR_Error_Log__c.object
<CustomObject>
    <description>Holds aacr error log data</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact record who created the error</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AACR Error Logs</relationshipLabel>
        <relationshipName>AACR_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Type__c</fullName>
        <label>Incident Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AACR Error Log</label>
    <nameField>
        <label>AACR Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AACR Error Logs</pluralLabel>
    <recordTypes>
        <fullName>Error_Exception</fullName>
        <active>true</active>
        <description>Automatic error exception</description>
        <label>Error Exception</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_DeleteErrorExceptionLogsTest.cls
/**
 * Created by lauren.lezberg on 7/1/2020.
 */
@isTest
private with sharing class Batch_DeleteErrorExceptionLogsTest {

    @testSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        Datetime logCutoffDate = Datetime.newInstance(Date.today().year(), Date.today().month() - 7, Date.today().day());
        List<AACR_Error_Log__c> logs = new List<AACR_Error_Log__c>();

        Id recordTypeId = [SELECT Id FROM RecordType
                WHERE DeveloperName = 'Error_Exception' AND sObjectType = 'AACR_Error_Log__c'].Id;

        for(Integer i = 0; i<200; i++){
            AACR_Error_Log__c log = new AACR_Error_Log__c();
            log.RecordTypeId = recordTypeId;
            log.Contact__c = con.Id;
            log.Incident_Type__c = 'TEST';
            logs.add(log);
        }

        insert logs;

        for(AACR_Error_Log__c log : logs){
            Test.setCreatedDate(log.Id, logCutoffDate);
        }

    }


    @isTest
    public static void test_BatchDelete(){
        Test.startTest();


        database.executeBatch(new Batch_DeleteErrorExceptionLogs());

        Test.stopTest();
    }
}