src/objects/AC_Event_User_Segment__c.object
<CustomObject>
    <description>This object relates the User Segment to the actual event.</description>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Early_Bird_Price_Deadline__c</fullName>
        <label>Early Bird Price Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Early_Bird_Price__c</fullName>
        <label>Early Bird Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>On_Demand_Price__c</fullName>
        <label>On Demand Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>AC Event User Segment</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>AC Event User Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AC Event User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Advocate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advocate</label>
        <type>Checkbox</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>BR Participations</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fon_Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>AC_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Advocate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this individual as a member of the Survivor and Patient Advocacy program.</description>
        <inlineHelpText>Eligible for discounted patient advocate rate</inlineHelpText>
        <label>Advocate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DonorApi__Suffix__c</fullName>
        <description>List of common academic, honorary, professional, and generational suffixes.</description>
        <inlineHelpText>List of common academic, honorary, professional, and generational suffixes.</inlineHelpText>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Esq.</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
                <value>
                    <fullName>III</fullName>
                </value>
                <value>
                    <fullName>IV</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>Jr.</fullName>
                </value>
                <value>
                    <fullName>Ret.</fullName>
                </value>
                <value>
                    <fullName>Sr.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Stakeholder_Other__c</fullName>
        <label>Primary Stakeholder Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Stakeholder__c</fullName>
        <label>Primary Stakeholder</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Patient</fullName>
                </value>
                <value>
                    <fullName>Survivor</fullName>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Researcher</fullName>
                </value>
                <value>
                    <fullName>Clinician</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Government Agencies</fullName>
                </value>
                <value>
                    <fullName>Hospitals and Health Systems</fullName>
                </value>
                <value>
                    <fullName>Policy Maker</fullName>
                </value>
                <value>
                    <fullName>Academic/Training Institutions</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Information Technology</fullName>
                </value>
                <value>
                    <fullName>AACR Staff</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Stakeholder_Other__c</fullName>
        <label>Secondary Stakeholder Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Stakeholder__c</fullName>
        <label>Secondary Stakeholder</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Patient</fullName>
                </value>
                <value>
                    <fullName>Survivor</fullName>
                </value>
                <value>
                    <fullName>Caregiver</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Researcher</fullName>
                </value>
                <value>
                    <fullName>Clinician</fullName>
                </value>
                <value>
                    <fullName>Payer</fullName>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Government Agencies</fullName>
                </value>
                <value>
                    <fullName>Hospitals and Health Systems</fullName>
                </value>
                <value>
                    <fullName>Policy Maker</fullName>
                </value>
                <value>
                    <fullName>Academic/Training Institutions</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Information Technology</fullName>
                </value>
                <value>
                    <fullName>AACR Staff</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                    <isActive>false</isActive>
                    <label>Technology</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Advocate</fullName>
        <active>true</active>
        <label>Advocate</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <description>**System Calculated**. Subtotal +</description>
        <formula>OrderApi__Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>**System Calculated** Subtotal +</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sale_Price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</description>
        <inlineHelpText>**System Calculated/Override** The price per-unit for the item sold on the sales order line.</inlineHelpText>
        <label>Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>**System Calculated** Total amount of Sales Order Line</description>
        <inlineHelpText>**System Calculated** Total amount of Sales Order Line</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdvocateAppReviewController.cls
/**
 * Created by lauren.lezberg on 7/15/2021.
 */

public with sharing class AdvocateAppReviewController {

    public class AdvocateInfoDTO{
        @AuraEnabled
        public Contact con;

        @AuraEnabled
        public List<BR_Participation__c> tickets;

        public AdvocateInfoDTO(Contact c, List<BR_Participation__c> participations){
            this.con = c;
            this.tickets = new List<BR_Participation__c>();
            this.tickets.addAll(participations);
        }
    }


    @AuraEnabled
    public static Boolean getButtonVisibility(String contactId){
        Boolean showButton = true;
        Contact con = [SELECT Advocate__c FROM Contact WHERE Id=:contactId];
        if(con.Advocate__c){
            showButton = false;
        }
        return showButton && FeatureManagement.checkPermission('Advocate Review');
    }

    @AuraEnabled
    public static AdvocateInfoDTO getAdvocateInfo(String contactId){
        Contact con = [SELECT Advocate__c, Primary_Stakeholder__c, Primary_Stakeholder_Other__c,
                        Secondary_Stakeholder__c, Secondary_Stakeholder_Other__c, Name
                        FROM Contact d
                        WHERE Id=:contactId];
        List<BR_Participation__c> participations = [SELECT Id, BR_Event__r.Name, AC_User_Segment__r.Name, Fon_Sales_Order__c, Fon_Sales_Order__r.Name, Fon_Sales_Order__r.OrderApi__Total__c
                                                FROM BR_Participation__c WHERE Participate__c = 'Pending Approval'];

        return new AdvocateInfoDTO(con, participations);

    }

    @AuraEnabled
    public static Boolean approveAdvocate(String contactId){
        //get & update contact for ticket pricing
        Contact con = [SELECT Advocate__c, Primary_Stakeholder__c, Primary_Stakeholder_Other__c,
                        Secondary_Stakeholder__c, Secondary_Stakeholder_Other__c
                        FROM Contact
                        WHERE Id=:contactId];
        con.Advocate__c = true;
        update con;

        //get user to calculate ticket price
        User u = [SELECT Id FROM User WHERE ContactId=:contactId];

        //get participation records
        List<BR_Participation__c> participations = [SELECT Id, BR_Event__c, Contact__r.Name, Contact__r.FirstName, Contact__r.LastName,
                                                    Contact__r.DonorApi__Suffix__c, Contact__r.Salutation,
                                                    BR_Event__r.Name, AC_User_Segment__r.Name, Fon_Sales_Order__c
                                                    FROM BR_Participation__c
                                                    WHERE Contact__c=:contactId AND Participate__c = 'Pending Approval'];

        if(!participations.isEmpty()) {
            List<OrderApi__Sales_Order_Line__c> linesToUpdate = new List<OrderApi__Sales_Order_Line__c>();
            //loop through participation records to update with status and price
            for (BR_Participation__c p : participations) {
                //get sales order lines to update
                List<OrderApi__Sales_Order_Line__c> lines = [
                        SELECT OrderApi__Sales_Order__c, OrderApi__Sale_Price__c,
                                AC_User_Segment__c
                        FROM OrderApi__Sales_Order_Line__c
                        WHERE OrderApi__Sales_Order__c = :p.Fon_Sales_Order__c
                ];

                //recalculate price
                Map<String, AC_Event_User_Segment__c> priceMap = brEventParticipationManager.getTicketPrice(p.BR_Event__c, u.Id);
                System.debug('priceMap: ' + priceMap);
                DOuble ticketPrice = 0.0;
                AC_Event_User_Segment__c uSegment = null;
                for (String key : priceMap.keySet()) {
                    if (priceMap.get(key).Early_Bird_Price__c != null && Datetime.now() < priceMap.get(key).Early_Bird_Price_Deadline__c) {
                        ticketPrice = priceMap.get(key).Early_Bird_Price__c;
                    } else if (priceMap.get(key).On_Demand_Price__c != null && Datetime.now() >= priceMap.get(key).On_Demand_Start_Date__c) {
                        System.debug('on demand: ' + priceMap.get(key).On_Demand_Price__c);
                        ticketPrice = priceMap.get(key).On_Demand_Price__c;
                    } else {
                        ticketPrice = priceMap.get(key).Price__c;
                    }

                    uSegment = priceMap.get(key);
                }
                //update line
                lines[0].OrderApi__Sale_Price__c = ticketPrice;
                lines[0].AC_User_Segment__c = uSegment.AC_User_Segment__c;
                linesToUpdate.add(lines[0]);

                //update participant fields
                p.Participate__c = 'Awaiting Payment';
                p.AC_User_Segment__c = uSegment.AC_User_Segment__c;
            }


            try {

                update linesToUpdate;

                update participations;

                //send approval emails
                sendAdvocateApprovalEmails(participations);
                return true;
            } catch (Exception e) {
                System.debug('Exception: ' + e);
                new AACRCustomException(contactId, e.getMessage(), e.getStackTraceString(), 'Advocate Rate Approval');
                return false;
            }
        }

        return true;

    }

    @AuraEnabled
    public static Boolean rejectAdvocate(String contactId, String rejectMsg){
       Contact con = [SELECT Advocate__c, Primary_Stakeholder__c, Primary_Stakeholder_Other__c,
                    Secondary_Stakeholder__c, Secondary_Stakeholder_Other__c
                    FROM Contact
                    WHERE Id=:contactId];

        con.Advocate__c = false;
        con.Primary_Stakeholder__c = null;
        con.Primary_Stakeholder_Other__c = null;
        con.Secondary_Stakeholder__c = null;
        con.Secondary_Stakeholder_Other__c = null;


        List<BR_Participation__c> participations = [SELECT Id, BR_Event__c, Contact__r.Name, Contact__r.FirstName,
                                                    Contact__r.LastName, Contact__r.DonorApi__Suffix__c,
                                                    Contact__r.Salutation, BR_Event__r.Name, AC_User_Segment__r.Name,
                                                    Fon_Sales_Order__c
                                                    FROM BR_Participation__c
                                                    WHERE Contact__c=:contactId AND Participate__c = 'Pending Approval'];

        for(BR_Participation__c p : participations){
            p.Participate__c = 'Incomplete';
        }

        if(!participations.isEmpty()) {
            try {
                update con;

                update participations;

                //send approval emails
                sendAdvocateRejectionEmails(participations, rejectMsg);
                return true;
            } catch (Exception e) {
                System.debug('Exception: ' + e);
                new AACRCustomException(contactId, e.getMessage(), e.getStackTraceString(), 'Advocate Rate Rejection');
                return false;
            }
        }

        return true;

    }

    private static void sendAdvocateRejectionEmails(List<BR_Participation__c> participations, String msg){
        System.debug('sendAdvocateRejectionEmails....');
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage>();
        EmailTemplate et = [SELECT Id, HtmlValue, Body FROM EmailTemplate WHERE Name='Advocate Rate Rejection'];

        String orgWideEmailId = BrEventsHelper.getConfigValue('org wide email id');

        for(BR_Participation__c participation : participations) {
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setTargetObjectId(participation.Contact__c);
            message.setWhatId(participation.BR_Event__c);
            message.setOrgWideEmailAddressId(orgWideEmailId);
            message.setTreatTargetObjectAsRecipient(true);


            String body = et.HtmlValue.replace('{!Contact.FirstName}', participation.Contact__c != null ? participation.Contact__r.FirstName : '')
                    .replace('{!Contact.LastName}', participation.Contact__r.LastName)
                    .replace('{!Contact.Salutation}', participation.Contact__r.Salutation!=null?participation.Contact__r.Salutation:'')
                    .replace('{!Contact.DonorApi__Suffix__c}', participation.Contact__r.DonorApi__Suffix__c!=null?participation.Contact__r.DonorApi__Suffix__c:'')
                    .replace('{!BR_Event__r.Name}', participation.BR_Event__r.Name)
                    .replace('{!SalesOrderId}', participation.Fon_Sales_Order__c)
                    .replace('{!rejectionMsg}', msg!=null?msg:'');
            message.setHtmlBody(body);
            message.setTemplateId(et.Id);

            messages.add(message);
        }

        if (!messages.isEmpty()) {
            try {
                Messaging.sendEmail(messages);
            } catch (EmailException ex) {
                new AACRCustomException(ex.getMessage(), ex.getStackTraceString(), 'Advocate Rate Rejection Email');
            }
        }
    }


    private static void sendAdvocateApprovalEmails(List<BR_Participation__c> participations){
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage>();
        EmailTemplate et = [SELECT Id, HtmlValue, Body FROM EmailTemplate WHERE Name='Advocate Rate Approval'];
        String orgWideEmailId = BrEventsHelper.getConfigValue('org wide email id');

        for(BR_Participation__c participation : participations) {
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setTargetObjectId(participation.Contact__c);
            message.setWhatId(participation.BR_Event__c);
            message.setOrgWideEmailAddressId(orgWideEmailId);
            message.setTreatTargetObjectAsRecipient(true);
            message.setReplyTo('advocacy@aacr.org');


            String body = et.HtmlValue.replace('{!Contact.FirstName}', participation.Contact__c != null ? participation.Contact__r.FirstName : '')
                        .replace('{!Contact.LastName}', participation.Contact__r.LastName)
                        .replace('{!Contact.Salutation}', participation.Contact__r.Salutation!=null?participation.Contact__r.Salutation:'')
                        .replace('{!SalesOrderId}', participation.Fon_Sales_Order__c);
            message.setHtmlBody(body);
            message.setTemplateId(et.Id);

            messages.add(message);
        }

        if (!messages.isEmpty()) {
            try {
                Messaging.sendEmail(messages);
            } catch (EmailException ex) {
                new AACRCustomException(ex.getMessage(), ex.getStackTraceString(), 'Advocate Rate Approval Email');
            }
        }
    }

}