src/objects/AC_Event_User_Segment__c.object
<CustomObject>
    <description>This object relates the User Segment to the actual event.</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Early_Bird_Price_Deadline__c</fullName>
        <label>Early Bird Price Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Early_Bird_Price__c</fullName>
        <label>Early Bird Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>On_Demand_Price__c</fullName>
        <label>On Demand Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>On_Demand_Start_Date__c</fullName>
        <label>On Demand Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>AC Event User Segment</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>AC Event User Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AC Event User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AC_User_Segment__c.object
<CustomObject>
    <description>Actual user groups (ex. all members)</description>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>AC User Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JP_EventTicketSelectionControllerTest.cls
/**
 * Created by lauren.lezberg on 6/11/2020.
 */
@isTest
public with sharing class JP_EventTicketSelectionControllerTest {

    @testSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;

        BR_Event__c evt = LiveTestDataFactory.buildEvent('Test Event', false, false);
        insert evt;

        AC_User_Segment__c uSeg = LiveTestDataFactory.buildUserSegment('Default');
        uSeg.Query__c = 'SELECT Id FROM User WHERE IsActive = true';
        insert uSeg;

        AC_Event_User_Segment__c euSeg = LiveTestDataFactory.buildEventUserSegment(evt.Id, uSeg.Id, null);
        euSeg.Price__c = 100;
        euSeg.Early_Bird_Price__c=50;
        euSeg.Early_Bird_Price_Deadline__c = System.now().addDays(-5);
        insert euSeg;

        AC_User_Segment__c uSeg2 = LiveTestDataFactory.buildUserSegment('Portal Users');
        uSeg.Query__c = 'SELECT Id FROM User WHERE IsActive = true AND ContactId!=null';
        insert uSeg2;

        AC_Event_User_Segment__c euSeg2 = LiveTestDataFactory.buildEventUserSegment(evt.Id, uSeg.Id, null);
        euSeg2.Price__c = 200;
        euSeg2.On_Demand_Price__c = 150;
        euSeg2.On_Demand_Start_Date__c = Date.today();
        insert euSeg2;

        OrderApi__Item_Class__c iClass = TestDataFactory.buildItemClass('Live Event Tickets');
        insert iClass;

        OrderApi__Item__c ticketItem = TestDataFactory.buildItem(iClass.Id, 'Test Event Ticket');
        ticketItem.AC_Event__c = evt.Id;
        insert ticketItem;
    }

    @isTest
    public static void test_getUserPrice(){
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name = 'Test Account'];

        User u = [SELECT Id FROM User WHERE ContactId=: con.Id];

        BR_Event__c evt = [SELECT Id FROM BR_Event__c WHERE Name = 'Test Event'];

        OrderApi__Sales_Order__c so = TestDataFactory.buildOpenSalesOrder(con.AccountId, con.Id);
        insert so;

        OrderApi__Item_Class__c iClass = [SELECT Id FROM OrderApi__Item_Class__c];
        OrderApi__Item__c item = [SELECT Id FROM OrderApi__Item__c];



        Test.startTest();
        System.runAs(u) {
            JP_EventTicketSelectionController.EventTickets tickets = JP_EventTicketSelectionController.getUserTicketPrice(evt.Id, so.Id);
            System.assertNotEquals(null, tickets);

            OrderApi__Sales_Order_Line__c line = TestDataFactory.buildSOLine(so.Id, item.Id, iClass.Id);
            insert line;

            tickets = JP_EventTicketSelectionController.getUserTicketPrice(evt.Id, so.Id);
            System.assertNotEquals(null, tickets);

        }

        Test.stopTest();
    }

    @isTest
    public static void test_getUserSegments(){
        BR_Event__c evt = [SELECT Id FROM BR_Event__c WHERE Name = 'Test Event'];

        Test.startTest();
        Map<String,Decimal> segments = JP_EventTicketSelectionController.getUserSegments(evt.Id);
        System.assertEquals(3, segments.size());

        Test.stopTest();
    }

    @isTest
    public static void test_addTicketToSalesOrder(){
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name = 'Test Account'];

        User u = [SELECT Id FROM User WHERE ContactId=: con.Id];

        BR_Event__c evt = [SELECT Id FROM BR_Event__c WHERE Name = 'Test Event'];

        OrderApi__Sales_Order__c so = TestDataFactory.buildOpenSalesOrder(con.AccountId, con.Id);
        insert so;

        System.runAs(u) {

            Test.startTest();

            Boolean ticketAdded = JP_EventTicketSelectionController.addTicketToSalesOrder(so.Id, evt.Id, 100.00, 'Default');
            System.assertEquals(true, ticketAdded);

            Test.stopTest();
        }
    }


    @isTest
    public static void test_getUserTicketPrice() {
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name = 'Test Account'];

        User u = [SELECT Id FROM User WHERE ContactId=: con.Id];

        OrderApi__Item__c item = [SELECT Id, OrderApi__Item_Class__c, AC_Event__c FROM OrderApi__Item__c WHERE Name = 'Test Event Ticket'];

        OrderApi__Sales_Order__c so = TestDataFactory.buildOpenSalesOrder(con.AccountId, con.Id);
        insert so;

        System.runAs(u) {

            Test.startTest();

            //TODO: Fix tests
            JP_EventTicketSelectionController.EventTickets priceMap = JP_EventTicketSelectionController.getUserTicketPrice(null, so.Id);
            System.assertEquals(null, priceMap);

            priceMap = JP_EventTicketSelectionController.getUserTicketPrice(item.AC_Event__c, null);
            System.assertEquals(null, priceMap);

            priceMap = JP_EventTicketSelectionController.getUserTicketPrice(item.AC_Event__c, so.Id);
            System.assertNotEquals(null, priceMap);

            OrderApi__Sales_Order_Line__c sol = TestDataFactory.buildSOLine(so.Id, item.Id, item.OrderApi__Item_Class__c);
            insert sol;

            priceMap = JP_EventTicketSelectionController.getUserTicketPrice(item.AC_Event__c, so.Id);
            System.assertNotEquals(null, priceMap);


            Test.stopTest();
        }
    }



    @isTest
    public static void test_getEventId(){
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Item__c item = [SELECT Id, OrderApi__Item_Class__c, AC_Event__c FROM OrderApi__Item__c WHERE Name = 'Test Event Ticket'];

        OrderApi__Sales_Order__c so = TestDataFactory.buildOpenSalesOrder(con.AccountId, con.Id);
        insert so;


        Test.startTest();


        String eventId = JP_EventTicketSelectionController.getEventId(so.Id);
        System.assertEquals(null, eventId);

        OrderApi__Sales_Order_Line__c sol = TestDataFactory.buildSOLine(so.Id, item.Id, item.OrderApi__Item_Class__c);
        insert sol;

        eventId = JP_EventTicketSelectionController.getEventId(so.Id);
        System.assertEquals(item.AC_Event__c, eventId);


        Test.stopTest();

    }

}