src/objects/AC_Event_User_Segment__c.object
<CustomObject>
    <description>This object relates the User Segment to the actual event.</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>AC Event User Segment</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>AC Event User Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AC Event User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AC_User_Segment__c.object
<CustomObject>
    <description>Actual user groups (ex. all members)</description>
    <label>AC User Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>BR Participations</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fon_Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>AC_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt__c.object
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <fields>
        <fullName>OrderApi__Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The Date the Receipt was processed. Default&apos;s to the Date the Entry was created.</description>
        <inlineHelpText>**Required** The Date the Receipt was processed. Default&apos;s to the Date the Entry was created.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Payment_Method_Description__c</fullName>
        <description>** System Calculated ** Derived from the source ePayment.</description>
        <formula>IF (OrderApi__EPayment__c != null,

IF (OrderApi__EPayment__r.OrderApi__Payment_Method_Type__c == &apos;credit_card&apos;,

UPPER(OrderApi__EPayment__r.OrderApi__Card_Type__c) &amp; &quot; **&quot; &amp; OrderApi__EPayment__r.OrderApi__Last_Four_Digits__c &amp; &quot; (&quot; &amp; TEXT(OrderApi__EPayment__r.OrderApi__Month__c) &amp; &quot;/&quot; &amp; TEXT(OrderApi__EPayment__r.OrderApi__Year__c) &amp; &quot;)&quot;,

OrderApi__EPayment__r.OrderApi__Bank_Name__c  &amp; &quot; &quot; &amp; OrderApi__EPayment__r.OrderApi__Bank_Account_Type__c &amp; &quot; &quot; &amp; OrderApi__EPayment__r.OrderApi__Bank_Account_Number__c


),&apos;N/A&apos;)</formula>
        <inlineHelpText>** System Calculated ** Derived from the source ePayment.</inlineHelpText>
        <label>Payment Method Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Caluclated** Lookup to the reciept for which you are refunding.</description>
        <inlineHelpText>**System Caluclated** Lookup to the reciept for which you are refunding.</inlineHelpText>
        <label>Receipt</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OrderApi__Receipt__c.OrderApi__Is_Payment__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__Receipt__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to related Sales Order.</description>
        <inlineHelpText>**System Calculated/Override** Link to related Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>**Conditionally Required** Receipt Total, required to post receipt to GL (Transactions).</description>
        <inlineHelpText>**Conditionally Required** Receipt Total, required to post receipt to GL (Transactions).</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt_Line__c.object
<CustomObject>
    <description>Receipt Lines apply cash related to either refunds or payments to Invoices or Items.</description>
    <fields>
        <fullName>OrderApi__Line_Description__c</fullName>
        <description>**System Calculated/Override** The line description by default populates with general information from either the linked Item or the linked Invoice.</description>
        <inlineHelpText>**System Calculated/Override** The line description by default populates with general information from either the linked Item or the linked Invoice.</inlineHelpText>
        <label>Line Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>**Required** Quantity of Items. Default 1.</description>
        <inlineHelpText>**Required** Quantity of Items. Default 1.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderApi__Receipt_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related parent Receipt Line.</description>
        <inlineHelpText>Link to related parent Receipt Line.</inlineHelpText>
        <label>Parent Receipt Line</label>
        <referenceTo>OrderApi__Receipt_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Receipt__c</fullName>
        <description>**Required** All Receipt details require a parent receipt that summarizes all receipt lines.</description>
        <inlineHelpText>**Required** All Receipt details require a parent receipt that summarizes all receipt lines.</inlineHelpText>
        <label>Receipt</label>
        <referenceTo>OrderApi__Receipt__c</referenceTo>
        <relationshipName>Receipt_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Sale_Price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>**System Calculated/Override** The Sale Price (per unit) for the related Item. Default 0.00.</description>
        <inlineHelpText>**System Calculated/Override** The Sale Price (per unit) for the related Item. Default 0.00.</inlineHelpText>
        <label>Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>**Required** Total amount for the Receipt Line. Default is 0.00.</description>
        <inlineHelpText>**Required** Total amount for the Receipt Line. Default is 0.00.</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Date__c</fullName>
        <description>The date the Sales Order was created. Default value is today&apos;s date.</description>
        <inlineHelpText>The date the Sales Order was created. Default value is today&apos;s date.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <description>**System Calculated**. Subtotal +</description>
        <formula>OrderApi__Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>**System Calculated** Subtotal +</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomReceiptController.cls
/**
 * Created by afaf.awad on 1/5/2021.
 */

public without sharing class CustomReceiptController {

    public String partId {get;set;}
    public BR_Participation__c participant {get;set;}
    public List<OrderApi__Receipt_Line__c> receiptLines {get;set;}
    public AC_Event_User_Segment__c userSegment {get;set;}

    public void getReceiptInfo() {

        partId = ApexPages.currentPage().getParameters().get('partId');

        participant = [SELECT Id, AC_User_Segment__r.Name, Fon_Sales_Order__c, BR_Event__c, Contact__r.FirstName, Contact__r.LastName FROM BR_Participation__c WHERE Id =: partId];

        receiptLines = [SELECT Id, OrderApi__Sale_Price__c, OrderApi__Total__c, OrderApi__Quantity__c, OrderApi__Line_Description__c, OrderApi__Receipt__r.OrderApi__Total__c,
                                OrderApi__Receipt__r.OrderApi__Date__c, OrderApi__Receipt__r.Name, OrderApi__Receipt__r.OrderApi__Payment_Method_Description__c
                        FROM OrderApi__Receipt_Line__c
                        WHERE OrderApi__Receipt__r.OrderApi__Sales_Order__c =: participant.Fon_Sales_Order__c];

        userSegment = [SELECT Id, Name,AC_User_Segment__r.Name, Price__c
                                                FROM AC_Event_User_Segment__c
                                                WHERE AC_Event__c =: participant.BR_Event__c AND AC_User_Segment__c =: participant.AC_User_Segment__c];

    }

    @AuraEnabled
    public static EmailResults emailReceipt(String participantId, String ccJSON, String msg){
        List<String> ccEmails = (List<String>)JSON.deserialize(ccJSON, List<String>.class);

        EmailResults result = new EmailResults();
        result.error = false;

        BR_Participation__c part = [SELECT BR_Event__r.End_Date__c, BR_Event__r.Name , BR_Event__c, Contact__c, Contact__r.Email, Contact__r.FirstName
        FROM BR_Participation__c WHERE Id=: participantId];

        PageReference pdf = Page.AACRCustomReceipt;
        pdf.getParameters().put('partId', participantId);

        // the contents of the attachment from the pdf
        Blob pdfbody;

        try {
            // returns the output of the page as a PDF
            pdfbody = pdf.getContent();

            // need to pass unit test -- current bug
        } catch (VisualforceException e) {
            pdfbody = Blob.valueOf('Something happened while creating your PDF.');
        }

        String orgWideEmailId = BrEventsHelper.getConfigValue('org wide email id');
        EmailTemplate emailTemplate = [SELECT Id, HtmlValue, Body FROM EmailTemplate WHERE Name = 'Custom Event Receipt'];

        String body = emailTemplate.HtmlValue;
        body = body.replace('{!BR_Event__c}', part.BR_Event__r.Name)
                .replace('{!First_Name}', part.Contact__r.FirstName)
                .replace('{!message}', msg!=null?msg:'');

        Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
        attach.setContentType('application/pdf');
        attach.setFileName(part.BR_Event__r.Name.replace(' ', '_') + '_Receipt.pdf');
        attach.setInline(false);
        attach.Body = pdfbody;

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        if(ccEmails!=null && !ccEmails.isEmpty()) {
            mail.setCcAddresses(ccEmails);
        }
        mail.setTargetObjectId(part.Contact__c);
        mail.setWhatId(part.BR_Event__c);
        mail.setOrgWideEmailAddressId(orgWideEmailId);
        mail.setTreatTargetObjectAsRecipient(true);
        mail.setUseSignature(false);
        mail.setSubject('Receipt for ' + part.BR_Event__r.Name);
        mail.setHtmlBody(body);
        mail.setFileAttachments(new Messaging.EmailFileAttachment[]{
                attach
        });

        try {
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                    mail
            });
            result.message = 'Receipt emailed!';
        }catch (EmailException e){
            new AACRCustomException(e.getMessage(), e.getStackTraceString(), 'Custom Event Receipt');
        }

        System.debug('Return Results');

        return result;

    }


    public class EmailResults{
        @AuraEnabled
        public Boolean error;

        @AuraEnabled
        public String message;
    }

}