src/objects/AC_Event_User_Segment__c.object
<CustomObject>
    <description>This object relates the User Segment to the actual event.</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>AC Event User Segment</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>AC Event User Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AC Event User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AC_User_Segment__c.object
<CustomObject>
    <description>Actual user groups (ex. all members)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is user segment active for use</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Available in segment manager</description>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>AC User Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>BR_Events_Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>BR_Events_Zone__c</referenceTo>
        <relationshipName>BR_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_Joint_Fields__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Joint Fields</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Pre_Post_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show pre/post doc fields on registration form</description>
        <label>Show Pre Post Doc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Workshop_Fields__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Workshop Fields</label>
        <type>Checkbox</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Events_Zone__c.object
<CustomObject>
    <label>AC Events Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>BR Participations</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Post_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre/Post Doc</label>
        <type>Checkbox</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Pre_Post_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre/Post Doc</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Nonmember</fullName>
        <active>true</active>
        <label>Nonmember</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JP_TicketTypesControllerTest.cls
/**
 * Created by lauren.lezberg on 2/21/2020.
 */
@isTest
private with sharing class JP_TicketTypesControllerTest {


    @testSetup public static void setup(){
        Account acc = LiveTestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = LiveTestDataFactory.buildContact(acc.Id);
        insert con;

        BR_Events_Zone__c zone = LiveTestDataFactory.buildZone('Test Zone', true);
        insert zone;

        BR_Event__c event = LiveTestDataFactory.buildEvent('Test Event', false, true);
        event.Show_Workshop_Fields__c = true;
        event.Show_Pre_Post_Doc__c = true;
        event.Show_Joint_Fields__c = true;
        event.BR_Events_Zone__c = zone.Id;
        insert event;

        AC_User_Segment__c defaultSeg = LiveTestDataFactory.buildUserSegment('Nonmember Individual');
        insert defaultSeg;

        AC_User_Segment__c prePostSeg = LiveTestDataFactory.buildUserSegment('Pre/Post Doc');
        prePostSeg.Query__c = 'SELECT Id FROM User WHERE ContactId IN (SELECT Id FROM Contact WHERE Pre_Post_Doc__c = true)';
        prePostSeg.Available__c = true;
        prePostSeg.Active__c = true;
        insert prePostSeg;

        AC_User_Segment__c us1 = LiveTestDataFactory.buildUserSegment('Students');
        insert us1;

        AC_User_Segment__c us2 = LiveTestDataFactory.buildUserSegment('Members');
        insert us2;


    }

    @isTest public static void test_getTicketTypes(){
        BR_Event__c evt = [SELECT Id FROM BR_Event__c WHERE Name='Test Event' LIMIT 1];

        Test.startTest();
        JP_TicketTypesController.TicketTypeInfo tti = JP_TicketTypesController.getTicketTypes(evt.Id);
        System.assertNotEquals(null, tti);
        System.assertEquals(3, tti.userSegments.size());
        Test.stopTest();
    }

    @isTest public static void test_saveTicketTypes(){
        BR_Event__c evt = [SELECT Id FROM BR_Event__c WHERE Name='Test Event' LIMIT 1];
        AC_User_Segment__c studentSegment = [SELECT Id, Name FROM AC_User_Segment__c WHERE Name='Students'];

        Map<String, String> fieldSets = FS_SelectorController.getFieldSets('BR_Participation__c');

        String fieldSetName = 'Test Field Set';

        JP_TicketTypesController.TicketType tt = new JP_TicketTypesController.TicketType(100.00, 1.0,'Student Tickets', studentSegment.Id, 50.00, Datetime.newInstance(System.now().year(), System.now().month()-1, System.now().day()),null, null, fieldSetName);
        List<Object> ticketTypes = new List<Object>{tt};

        Test.startTest();

        JP_TicketTypesController.saveEventUserSegments(evt.Id, ticketTypes);

        JP_TicketTypesController.TicketTypeInfo tti = JP_TicketTypesController.getTicketTypes(evt.Id);

        JP_TicketTypesController.saveEventUserSegments(evt.Id, ticketTypes);

        Test.stopTest();

        System.assertNotEquals(null, tti);
        System.assertEquals(4, tti.userSegments.size());
        System.assertEquals(4, tti.ticketTypes.size());

        Integer segmentCount = [SELECT COUNT() FROM AC_Event_User_Segment__c WHERE AC_Event__c=: evt.Id];
        System.assertEquals(1, segmentCount);
    }

}