src/objects/AC_Event_User_Segment__c.object
<CustomObject>
    <description>This object relates the User Segment to the actual event.</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AC User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>AC Event User Segments</relationshipLabel>
        <relationshipName>AC_Event_User_Segments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Early_Bird_Price_Deadline__c</fullName>
        <label>Early Bird Price Deadline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Early_Bird_Price__c</fullName>
        <label>Early Bird Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>On_Demand_Price__c</fullName>
        <label>On Demand Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>On_Demand_Start_Date__c</fullName>
        <label>On Demand Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority of ticket price if user belongs to multiple user segments. The lowest priority prevails.</description>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AC Event User Segment</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>AC Event User Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AC Event User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AC_User_Segment__c.object
<CustomObject>
    <description>Actual user groups (ex. all members)</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Portal_Help_Text__c</fullName>
        <description>explains to user what segment means</description>
        <label>Portal Help Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>AC User Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Ignore_Segment_Priority__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ignore priority of the matching segments and show chipest ticket.</description>
        <inlineHelpText>Priority will be ignored and the lowest price will prevail.</inlineHelpText>
        <label>Ignore Priority</label>
        <type>Checkbox</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>BR Participations</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>The status of the Sales Order.</description>
        <inlineHelpText>The status of the Sales Order.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>AC_User_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Segment</label>
        <referenceTo>AC_User_Segment__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</description>
        <inlineHelpText>Overrides the calculation of price based on the most appropriate price for the purchasing customer. Default is unchecked.</inlineHelpText>
        <label>Price Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/brEventParticipationManager.cls
/**
 * Created by mitfity on 15.07.2019.
 */

public without sharing class brEventParticipationManager {

    @AuraEnabled
    public static Boolean checkForTicketTypes(Id eventId){
        Integer segmentCount = [SELECT COUNT() FROM AC_Event_User_Segment__c WHERE AC_Event__c =: eventId];
        SYstem.debug('segmentCount: ' + segmentCount);
        if(segmentCount!=null && segmentCount>0){
            return true;
        }

        return false;
    }

    /**
     * Respond to event whether you are going or not.
     *
     * @param recordId
     * @param response
     * @param attendeesLimit
     *
     * @return
     */
    public static String respondToEvent(Id recordId, String response, Integer attendeesLimit) {
        if (String.isBlank(recordId) || String.isBlank(response)) {
            return 'error';
        }

        if (UserInfo.getUserType() == 'Guest') {
            return 'auth_required';
        }

        List<String> participationFieldsToUpdate = new List<String>();
        participationFieldsToUpdate.add('Participate__c');
        participationFieldsToUpdate.add('User__c');
        List<String> participationFieldsToCreate = new List<String>();
        participationFieldsToCreate.add('BR_Event__c');
        participationFieldsToCreate.add('Participate__c');
        participationFieldsToCreate.add('User__c');

        if (!BrEventsHelper.performAccessCheck('read', 'BR_Participation__c', null)
                || !BrEventsHelper.performAccessCheck('edit', 'BR_Participation__c', participationFieldsToUpdate)
                || !BrEventsHelper.performAccessCheck('create', 'BR_Participation__c', participationFieldsToCreate)) {
            return 'error';
        }

        String count_query = 'SELECT COUNT() FROM BR_Participation__c WHERE BR_Event__c = \'' + recordId +
                '\' AND Participate__c  = \'Yes\'';

        attendeesLimit = Integer.valueOf(attendeesLimit);

        if (attendeesLimit != 0 && response == 'Yes') {
            Integer attendeesCount = Database.countQuery(count_query);

            if (attendeesCount != 0 && attendeesCount >= attendeesLimit) {
                return 'limit_exceded';
            }

        }

        List<BR_Participation__c> participations = [
                SELECT Id
                FROM BR_Participation__c
                WHERE BR_Event__c = :recordId
                AND User__c = :UserInfo.getUserId()
                LIMIT 1
        ];

        BR_Participation__c p = new BR_Participation__c();

        if (participations.size() > 0) {
            p = participations[0];
            p.Participate__c = response;
        } else {
            p.BR_Event__c = recordId;
            p.Participate__c = response;
            p.User__c = UserInfo.getUserId();
        }

        try {
            upsert p;
            return String.valueOf(Database.countQuery(count_query));
        } catch (DmlException e) {
            System.debug(e.getMessage());
            new AACRCustomException(recordId, e.getMessage(), e.getStackTraceString(), 'Ticket Purchase');
            return 'error';
        }
    }

    /**
     * Calculates price of ticket for the event according to current user's segment.
     *
     * @param eventId
     *
     * @return
     */
//    public static Map<String,Double> getTicketPrice(Id eventId, Id currentUserId) {
//        SYstem.debug('getTicketPrice for user: ' + currentUserId + ' and eventId: ' + eventId);
//        List<BR_Event__c> eventRows = [SELECT Ignore_Segment_Priority__c FROM BR_Event__c WHERE Id = :eventId];
//
//        if (eventRows.isEmpty()) {
//            throw new AACRCustomException('Event does not exist', 'brEventParticipationManager.getTicketPrice', 'Ticket Purchase');
////            throw new brParticipationException('Event does not exists.');
//        }
//
////        Id currentUserId = UserInfo.getUserId();
//        List<AC_Event_User_Segment__c> eventUserSegments = [
//                SELECT AC_User_Segment__r.Query__c, AC_User_Segment__r.Name, Price__c, Priority__c,
//                        Early_Bird_Price__c, Early_Bird_Price_Deadline__c
//                FROM AC_Event_User_Segment__c WHERE AC_Event__c = :eventId
//        ];
//        List<AC_Event_User_Segment__c> currentUserSegments = new List<AC_Event_User_Segment__c>();
//
//        for (AC_Event_User_Segment__c eventUserSegment : eventUserSegments) {
//            SYstem.debug('userSEgment query: ' + eventUserSegment.AC_User_Segment__r.Query__c);
//
//            String segmentQuery = eventUserSegment.AC_User_Segment__r.Query__c + ' AND Id= \'' + currentUserId + '\'';
//            System.debug('segmentQuery with userId: ' + segmentQuery);
//            List<User> segmentUsers = Database.query(segmentQuery);
//
//            for (User segmentUser : segmentUsers) {
//                if (segmentUser.Id == currentUserId) {
//                    currentUserSegments.add(eventUserSegment);
//                    break;
//                }
//            }
//        }
//
//        if (currentUserSegments.isEmpty()) {
//            throw new AACRCustomException(eventId, 'User has no segments for this event.', 'brEventParticipationManager.getTicketPrice', 'Ticket Purchase');
////            throw new brParticipationException('User has no segments for this event.');
//        }
//
//        AC_Event_User_Segment__c topPrioritySegment;
//        BR_Event__c targetEvent = eventRows.get(0);
//        Map<String, Double> priceMap = new Map<STring, Double>();
//
//        for (AC_Event_User_Segment__c eventUserSegment : currentUserSegments) {
//            if (topPrioritySegment == null) {
//                topPrioritySegment = eventUserSegment;
//                continue;
//            }
//
//            if (targetEvent.Ignore_Segment_Priority__c) {
//                if (eventUserSegment.Price__c < topPrioritySegment.Price__c) {
//                    topPrioritySegment = eventUserSegment;
//                }
//            } else if (eventUserSegment.Priority__c < topPrioritySegment.Priority__c) {
//                topPrioritySegment = eventUserSegment;
//            }
//        }
//
//        if (topPrioritySegment.Early_Bird_Price__c != null
//                && Datetime.now() < topPrioritySegment.Early_Bird_Price_Deadline__c) {
//            priceMap.put(topPrioritySegment.AC_User_Segment__r.Name, topPrioritySegment.Early_Bird_Price__c);
//            return priceMap;
//        }
//
//
//        priceMap.put(topPrioritySegment.AC_User_Segment__r.Name, topPrioritySegment.Price__c);
//
//        return priceMap;
//    }
    public static Map<String,AC_Event_User_Segment__c> getTicketPrice(Id eventId, Id currentUserId) {
        SYstem.debug('getTicketPrice for user: ' + currentUserId + ' and eventId: ' + eventId);
        String contactId = [SELECT ContactId fROM User WHERE Id=:currentUserId].ContactId;

        List<BR_Event__c> eventRows = [SELECT Ignore_Segment_Priority__c FROM BR_Event__c WHERE Id = :eventId];

        if (eventRows.isEmpty()) {
            throw new AACRCustomException('Event does not exist', 'brEventParticipationManager.getTicketPrice', 'Ticket Purchase');
//            throw new brParticipationException('Event does not exists.');
        }

//        Id currentUserId = UserInfo.getUserId();
        List<AC_Event_User_Segment__c> eventUserSegments = [
                SELECT AC_User_Segment__r.Query__c, AC_User_Segment__r.Name, AC_User_Segment__r.Description__c, AC_User_Segment__r.Portal_Help_Text__c,Price__c, Priority__c,
                        Early_Bird_Price__c, Early_Bird_Price_Deadline__c, On_Demand_Price__c, On_Demand_Start_Date__c
                FROM AC_Event_User_Segment__c WHERE AC_Event__c = :eventId
        ];
        List<AC_Event_User_Segment__c> currentUserSegments = new List<AC_Event_User_Segment__c>();

        for (AC_Event_User_Segment__c eventUserSegment : eventUserSegments) {
            SYstem.debug('userSegment query: ' + eventUserSegment.AC_User_Segment__r.Query__c);

            String segmentQuery = eventUserSegment.AC_User_Segment__r.Query__c + ' AND Id= \'' + currentUserId + '\'';
            System.debug('segmentQuery with userId: ' + segmentQuery);
            List<User> segmentUsers = Database.query(segmentQuery);

            for (User segmentUser : segmentUsers) {
                if (segmentUser.Id == currentUserId) {
                    currentUserSegments.add(eventUserSegment);
                    break;
                }
            }
        }

        if (currentUserSegments.isEmpty()) {
            throw new AACRCustomException(eventId, 'User has no segments for this event.', 'brEventParticipationManager.getTicketPrice', 'Ticket Purchase');
//            throw new brParticipationException('User has no segments for this event.');
        }

        AC_Event_User_Segment__c topPrioritySegment;
        BR_Event__c targetEvent = eventRows.get(0);
        Map<String, AC_Event_User_Segment__c> priceMap = new Map<String, AC_Event_User_Segment__c>();

        for (AC_Event_User_Segment__c eventUserSegment : currentUserSegments) {
            if (topPrioritySegment == null) {
                topPrioritySegment = eventUserSegment;
                continue;
            }

            if (targetEvent.Ignore_Segment_Priority__c) {
                if (eventUserSegment.Price__c < topPrioritySegment.Price__c) {
                    topPrioritySegment = eventUserSegment;
                }
            } else if (eventUserSegment.Priority__c < topPrioritySegment.Priority__c) {
                topPrioritySegment = eventUserSegment;
            }
        }

        System.debug('topPrioritySegment: ' + topPrioritySegment);
        System.debug('dateTimeNow: ' + Datetime.now());
        System.debug('segment end date: ' + topPrioritySegment.Early_Bird_Price_Deadline__c);

        //EARLY BIRD PRICING
        if (topPrioritySegment.Early_Bird_Price__c != null
                && Datetime.now() < topPrioritySegment.Early_Bird_Price_Deadline__c) {
            System.debug('early bird...');
            priceMap.put(topPrioritySegment.AC_User_Segment__c, topPrioritySegment);
            return priceMap;
        }
        //ON DEMAND PRICING
        else if (topPrioritySegment.On_Demand_Price__c != null
                && Datetime.now() >= topPrioritySegment.On_Demand_Start_Date__c) {
            System.debug('on demand...');
            priceMap.put(topPrioritySegment.AC_User_Segment__c, topPrioritySegment);
            return priceMap;
        }


        else {
            priceMap.put(topPrioritySegment.AC_User_Segment__c, topPrioritySegment);
        }
        System.debug('priceMap: ' + priceMap);


        return priceMap;
    }


    /**
     * Calculates price of ticket for the event according to current user's segment.
     *
     * @param eventId
     *
     * @return
     */
    public static Double getTicketPrice(Id eventId) {
        List<BR_Event__c> eventRows = [SELECT Ignore_Segment_Priority__c FROM BR_Event__c WHERE Id = :eventId];

        if (eventRows.isEmpty()) {
            throw new AACRCustomException('Event does not exist', 'brEventParticipationManager.getTicketPrice', 'Ticket Purchase');
//            throw new brParticipationException('Event does not exists.');
        }

        Id currentUserId = UserInfo.getUserId();
        List<AC_Event_User_Segment__c> eventUserSegments = [
                SELECT AC_User_Segment__r.Query__c, Price__c, Priority__c,
                        Early_Bird_Price__c, Early_Bird_Price_Deadline__c
                FROM AC_Event_User_Segment__c WHERE AC_Event__c = :eventId
        ];
        List<AC_Event_User_Segment__c> currentUserSegments = new List<AC_Event_User_Segment__c>();

        for (AC_Event_User_Segment__c eventUserSegment : eventUserSegments) {
            List<User> segmentUsers = Database.query(eventUserSegment.AC_User_Segment__r.Query__c);

            for (User segmentUser : segmentUsers) {
                if (segmentUser.Id == currentUserId) {
                    currentUserSegments.add(eventUserSegment);
                    break;
                }
            }
        }

        if (currentUserSegments.isEmpty()) {
            throw new AACRCustomException(eventId, 'User has no segments for this event.', 'brEventParticipationManager.getTicketPrice()', 'Ticket Purchase');
//            throw new brParticipationException('User has no segments for this event.');
        }

        AC_Event_User_Segment__c topPrioritySegment;
        BR_Event__c targetEvent = eventRows.get(0);

        for (AC_Event_User_Segment__c eventUserSegment : currentUserSegments) {
            if (topPrioritySegment == null) {
                topPrioritySegment = eventUserSegment;
                continue;
            }

            if (targetEvent.Ignore_Segment_Priority__c) {
                if (eventUserSegment.Price__c < topPrioritySegment.Price__c) {
                    topPrioritySegment = eventUserSegment;
                }
            } else if (eventUserSegment.Priority__c < topPrioritySegment.Priority__c) {
                topPrioritySegment = eventUserSegment;
            }
        }

        if (topPrioritySegment.Early_Bird_Price__c != null
                && Datetime.now() < topPrioritySegment.Early_Bird_Price_Deadline__c) {
            return topPrioritySegment.Early_Bird_Price__c;
        }

        return topPrioritySegment.Price__c;
    }



    /**
     * Generates sales order with ticket for current user.
     *
     * @param ticketPrice
     *
     * @return
     */
    public static OrderApi__Sales_Order__c generateFonSalesOrderForTicket(AC_Event_User_Segment__c seg, Id eventId) {
        Savepoint savePoint = Database.setSavepoint();

        OrderApi__Sales_Order__c salesOrder;
        Id currentUserId = UserInfo.getUserId();

        try {
            User currentUser = [SELECT ContactId FROM User WHERE Id = :currentUserId LIMIT 1];

            salesOrder = new OrderApi__Sales_Order__c();
            salesOrder.OrderApi__Contact__c = currentUser.ContactId;
            salesOrder.OrderApi__Status__c = 'Open';

            insert salesOrder;



            OrderApi__Item__c item = [SELECT Id FROM OrderApi__Item__c WHERE OrderApi__Item_Class__r.Name='Live Event Tickets' AND AC_Event__c=: eventId ];


            OrderApi__Sales_Order_Line__c salesOrderLine = new OrderApi__Sales_Order_Line__c();
            salesOrderLine.OrderApi__Sales_Order__c = salesOrder.Id;
            salesOrderLine.OrderApi__Item__c = item.Id;
            salesOrderLine.OrderApi__Price_Override__c = true;
            if(seg.Early_Bird_Price__c != null
                    && Datetime.now() < seg.Early_Bird_Price_Deadline__c) {
                salesOrderLine.OrderApi__Sale_Price__c = seg.Early_Bird_Price__c;
            }
            else if(seg.On_Demand_Price__c != null
                    && Datetime.now() >= seg.On_Demand_Start_Date__c) {
                System.debug('on demand sales order line');
                salesOrderLine.OrderApi__Sale_Price__c = seg.On_Demand_Price__c;
            }
            else{
                salesOrderLine.OrderApi__Sale_Price__c = seg.Price__c;
            }
            salesOrderLine.AC_User_Segment__c = seg.AC_User_Segment__c;


            insert salesOrderLine;
        } catch (Exception e) {
            Database.rollback(savePoint);
            System.debug('exception: ' + e.getMessage());
             new AACRCustomException(eventId, e.getMessage(), e.getStackTraceString(), 'Ticket Purchase');
//            throw e;
        }

        return salesOrder;
    }

    public static List<brIFieldWrap> getEventPreferencesFormFields(Id eventId, Id currentUserId) {
        System.debug('getEventPreferencesFormFields with eventId : ' + eventId  + ' and currentUserId: ' + currentUserId);
//        Id currentUserId = UserInfo.getUserId();
        List<BR_Event__c> eventRows = [SELECT Ignore_Segment_Priority__c FROM BR_Event__c WHERE Id = :eventId];

        if (eventRows.isEmpty()) {
            throw new AACRCustomException('Event does not exist', 'brEventParticipationManager.getEventPreferencesFormFields', 'Ticket Purchase');
//            throw new brParticipationException('Event does not exists.');
        }

        List<AC_Event_User_Segment__c> eventUserSegments = [
                SELECT AC_User_Segment__r.Query__c, Priority__c
                FROM AC_Event_User_Segment__c WHERE AC_Event__c = :eventId
        ];
        System.debug('eventUserSegments: ' + eventUserSegments);
        List<AC_Event_User_Segment__c> currentUserSegments = new List<AC_Event_User_Segment__c>();
        for (AC_Event_User_Segment__c eventUserSegment : eventUserSegments) {
            List<User> segmentUsers = Database.query(eventUserSegment.AC_User_Segment__r.Query__c + ' AND Id=\'' + currentUserId + '\'');

            for (User segmentUser : segmentUsers) {
                if (segmentUser.Id == currentUserId) {
                    currentUserSegments.add(eventUserSegment);
                    break;
                }
            }
        }
        if (currentUserSegments.isEmpty()) {
            throw new AACRCustomException('User has no segments for this event.', 'brEventParticipationManager.getEventPreferencesFormFields', 'Ticket Purchase');
//            throw new brParticipationException('User has no segments for this event.');
        }
        System.debug('currentUserSegments: ' + currentUserSegments);

        AC_Event_User_Segment__c topPrioritySegment;
        BR_Event__c targetEvent = eventRows.get(0);

        for (AC_Event_User_Segment__c eventUserSegment : currentUserSegments) {
            if (topPrioritySegment == null) {
                System.debug('--- topPrioritySegment == null');
                topPrioritySegment = eventUserSegment;
                continue;
            }
            if (eventUserSegment.Priority__c < topPrioritySegment.Priority__c) {
                topPrioritySegment = eventUserSegment;
            }
        }

        List<AC_Event_User_Segment__c> eventResults = [
                SELECT Event_Preferences_Form_Fieldset__c, AC_User_Segment__r.Query__c, AC_User_Segment__c
                FROM AC_Event_User_Segment__c
                WHERE AC_Event__c = :eventId AND AC_User_Segment__c =: topPrioritySegment.AC_User_Segment__c
        ];

        System.debug('eventResults: ' + eventResults);
        if (eventResults.isEmpty()) {
            throw new AACRCustomException('Event does not exist', 'brEventParticipationManager.getEventPreferencesFormFields', 'Ticket Purchase');
//            throw new brParticipationException('Event does not exist.');
        }

        AC_Event_User_Segment__c event = eventResults.get(0);
        SYstem.debug('fieldSet name from event: ' + event.Event_Preferences_Form_Fieldset__c);
        Schema.DescribeSObjectResult objectDescribe = BR_Participation__c.SObjectType.getDescribe();
        Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();

        if (!fieldSetMap.containsKey(event.Event_Preferences_Form_Fieldset__c)) {
            return new List<brIFieldWrap>();
        }

        Schema.FieldSet fieldSet = fieldSetMap.get(event.Event_Preferences_Form_Fieldset__c);
        System.debug('fieldSet: ' + fieldSet);

        return brFieldSetMemberListFactory.construct(fieldSet, 'update');
    }

    /**
     * Retrieves event preferences form fields.
     *
     * @param eventId
     *
     * @return
     */
    public static List<brIFieldWrap> getEventPreferencesFormFields(Id eventId) {
        Id currentUserId = UserInfo.getUserId();
        List<BR_Event__c> eventRows = [SELECT Ignore_Segment_Priority__c FROM BR_Event__c WHERE Id = :eventId];

    if (eventRows.isEmpty()) {
        throw new AACRCustomException('Event does not exist', 'brEventParticipationManager.getEventPreferencesFormFields', 'Ticket Purchase');
//        throw new brParticipationException('Event does not exists.');
    }

    List<AC_Event_User_Segment__c> eventUserSegments = [
        SELECT AC_User_Segment__r.Query__c, Priority__c
        FROM AC_Event_User_Segment__c WHERE AC_Event__c = :eventId
    ];
        List<AC_Event_User_Segment__c> currentUserSegments = new List<AC_Event_User_Segment__c>();
        for (AC_Event_User_Segment__c eventUserSegment : eventUserSegments) {
            List<User> segmentUsers = Database.query(eventUserSegment.AC_User_Segment__r.Query__c);

            for (User segmentUser : segmentUsers) {
                if (segmentUser.Id == currentUserId) {
                    currentUserSegments.add(eventUserSegment);
                    break;
                }
            }
        }
        if (currentUserSegments.isEmpty()) {
            throw new AACRCustomException('User has no segments for this event.', 'brEventParticipationManager.getEventPreferencesFormFields', 'Ticket Purchase');
//            throw new brParticipationException('User has no segments for this event.');
        }

        AC_Event_User_Segment__c topPrioritySegment;
        BR_Event__c targetEvent = eventRows.get(0);

        for (AC_Event_User_Segment__c eventUserSegment : currentUserSegments) {
            if (topPrioritySegment == null) {
                System.debug('--- topPrioritySegment == null');    
                topPrioritySegment = eventUserSegment;
                continue;
            }
            if (eventUserSegment.Priority__c < topPrioritySegment.Priority__c) {
                topPrioritySegment = eventUserSegment;
            }
        }

        List<AC_Event_User_Segment__c> eventResults = [
                SELECT Event_Preferences_Form_Fieldset__c, AC_User_Segment__r.Query__c, AC_User_Segment__c
                FROM AC_Event_User_Segment__c
                WHERE AC_Event__c = :eventId AND AC_User_Segment__c =: topPrioritySegment.AC_User_Segment__c
        ];

        if (eventResults.isEmpty()) {
            throw new AACRCustomException('Event does not exist', 'brEventParticipationManager.getEventPreferencesFormFields', 'Ticket Purchase');
//            throw new brParticipationException('Event does not exist.');
        }

        AC_Event_User_Segment__c event = eventResults.get(0);
        Schema.DescribeSObjectResult objectDescribe = BR_Participation__c.SObjectType.getDescribe();
        Map<String, Schema.FieldSet> fieldSetMap = objectDescribe.fieldSets.getMap();

        if (!fieldSetMap.containsKey(event.Event_Preferences_Form_Fieldset__c)) {
            return new List<brIFieldWrap>();
        }

        Schema.FieldSet fieldSet = fieldSetMap.get(event.Event_Preferences_Form_Fieldset__c);

        return brFieldSetMemberListFactory.construct(fieldSet, 'update');
    }

    /** 
     * Saves event preferences for current user.
     *
     * @param eventId
     * @param preferencesJson
     */
//    public static void saveEventPreferences(Id eventId, Id userId, Id salesOrderId,  String preferencesJson) {
//        System.debug('saveEventPreferences...');
//        System.debug('eventId: ' + eventId);
//        System.debug('userId: ' + userId);
//        System.debug('preferences: ' + preferencesJson);
//
////        List<brIFieldWrap> eventPreferencesFields = getEventPreferencesFormFields(eventId, userId);
//
//        List<BR_Participation__c> participationResult = [
//                SELECT Id, Participate__c
//                FROM BR_Participation__c
//                WHERE BR_Event__c  = :eventId AND User__c = :userId
//        ];
//
//        SYstem.debug('participationResult: ' + participationResult);
//
//        BR_Participation__c participation;
//
////        if (participationResult.isEmpty()) {
////            participation = new BR_Participation__c();
////            participation.BR_Event__c = eventId;
////            participation.User__c = userId;
////            participation.Fon_Sales_Order__c = salesOrderId;
////        } else
//        if(!participationResult.isEmpty()){
//            participation = participationResult.get(0);
//        }
//
//        //dont need with record-edit-form
////        BR_Participation__c eventPreferences =
////                (BR_Participation__c) JSON.deserialize(preferencesJson, BR_Participation__c.class);
////
////        System.debug('eventPreferences: ' + eventPreferences);
////
////        for (brIFieldWrap fieldWrap : eventPreferencesFields) {
////            String fieldName = fieldWrap.getApiName();
////
////            if (fieldName == 'Participate__c') {
////                continue;
////            }
////
////            participation.put(fieldName, eventPreferences.get(fieldName));
////        }
//
//        try {
//
//            upsert participation;
//        } catch (Exception e) {
//            System.debug('Error :' + e.getMessage());
//            throw new AACRCustomException(e.getMessage(), e.getStackTraceString(), 'Ticket Purchase');
//        }
//    }


}