src/objects/AC_User_Segment__c.object
<CustomObject>
    <description>Actual user groups (ex. all members)</description>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>AC User Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC User Segments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>RT_ByName__c</fullName>
        <description>Get&apos;s Record Type by Name</description>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RT_ByName</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Nonmember</fullName>
        <active>true</active>
        <label>Nonmember</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User_Segment_Fields__mdt.object
<CustomObject>
    <description>List of fields available for selection in segment builder</description>
    <fields>
        <fullName>API_Name__c</fullName>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Segment Builder Field</label>
    <pluralLabel>Segment Builder Fields</pluralLabel>
</CustomObject>

src/classes/ObjectFieldSelectorControllerTest.cls
/**
 * Created by lauren.lezberg on 8/17/2020.
 */

@IsTest
private class ObjectFieldSelectorControllerTest {


    @IsTest
    static void test_getFields() {

        BR_Event__c evt = LiveTestDataFactory.buildEvent('Test Events', false, false);
        insert evt;

        List<User_Segment_Fields__mdt> segmentFields = new List<User_Segment_Fields__mdt>();
        User_Segment_Fields__mdt segField = new User_Segment_Fields__mdt(API_Name__c='RT_ByName__c', Object_Type__c='Contact');
        segmentFields.add(segField);

        AC_User_Segment__c segment = LiveTestDataFactory.buildUserSegment('Test Segment');
        segment.Query__c = 'SELECT Id FROM User WHERE ContactId IN (SELECT Id FROM Contact WHERE RT_ByName__c=\'Nonmember\')';
        insert segment;


        Test.startTest();

        UserSegmentHelper.segFields.addAll(segmentFields);
        List<List<UserSegmentHelper.FieldValuePair>> fields = ObjectFieldSelectorController.getFields('Contact', segment.Id);

        System.assert(!fields.isEmpty());
        
        Test.stopTest();
    }
}