src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>Institution Types</description>
        <inlineHelpText>Types of Institutions</inlineHelpText>
        <label>Institution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Institution_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Advocate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advocate</label>
        <type>Checkbox</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <description>Formula field reflecting either legacy iMIS ID or new Salesforce ID depending upon when record was created.</description>
        <formula>IF(ISBLANK( iMIS_ID__c ), Salesforce_ID__c, iMIS_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Advocate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this individual as a member of the Survivor and Patient Advocacy program.</description>
        <inlineHelpText>Eligible for discounted patient advocate rate</inlineHelpText>
        <label>Advocate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Current Education Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degrees_Held__c</fullName>
        <label>Degrees Held</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Degree</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AAS</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BAAS</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BDS</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>B Eng</fullName>
                </value>
                <value>
                    <fullName>BMBCh</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>B Pharm</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>BSN</fullName>
                </value>
                <value>
                    <fullName>DDS</fullName>
                </value>
                <value>
                    <fullName>DMD</fullName>
                </value>
                <value>
                    <fullName>DMSc</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>D Phil</fullName>
                </value>
                <value>
                    <fullName>DSc</fullName>
                </value>
                <value>
                    <fullName>DVM</fullName>
                </value>
                <value>
                    <fullName>Dr PH</fullName>
                </value>
                <value>
                    <fullName>Dr Rer Nat</fullName>
                </value>
                <value>
                    <fullName>Ed D</fullName>
                </value>
                <value>
                    <fullName>EdM</fullName>
                </value>
                <value>
                    <fullName>JD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the contact.</description>
        <inlineHelpText>Gender of the contact.</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                    <label>Prefer Not to Answer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>Historical reflection of iMIS data on the contact object. This field will be read only.</description>
        <label>Institution Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Focus__c</fullName>
        <description>Describes major focus of the contact.</description>
        <inlineHelpText>Describes major focus of the contact.</inlineHelpText>
        <label>Major Focus</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Basic Research</fullName>
                </value>
                <value>
                    <fullName>Basic Science</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Clinical Practice</fullName>
                </value>
                <value>
                    <fullName>Clinical Research</fullName>
                </value>
                <value>
                    <fullName>Population Science</fullName>
                </value>
                <value>
                    <fullName>Research Administration</fullName>
                </value>
                <value>
                    <fullName>Science Education</fullName>
                </value>
                <value>
                    <fullName>Translational Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Type__c</fullName>
        <description>Indicates what level of membership this individual possesses.</description>
        <inlineHelpText>Indicates what level of membership this individual possesses.</inlineHelpText>
        <label>Member Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organ_Sites__c</fullName>
        <description>Organ site research area(s)</description>
        <inlineHelpText>Organ site research area(s)</inlineHelpText>
        <label>Organ Sites</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Organ_Sites_Global_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paid_thru_date__c</fullName>
        <description>This field will track the date upto which the customer&apos;s subscription is paid</description>
        <inlineHelpText>***SYSTEM CALCULATED***This field tracks the paid thru date of the membership</inlineHelpText>
        <label>Paid Thru Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Research_Area_of_Expertise__c</fullName>
        <description>This field reflects the single primary research area for the AACR member.</description>
        <inlineHelpText>This field reflects the single primary research area for the AACR member.</inlineHelpText>
        <label>Research Area of Expertise</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Research_Areas_Global_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Race of the contact.</description>
        <inlineHelpText>Race of the contact.</inlineHelpText>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>African American/Black</fullName>
                </value>
                <value>
                    <fullName>Alaskan Native</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>Caucasian</fullName>
                </value>
                <value>
                    <fullName>Hispanic/Latino</fullName>
                </value>
                <value>
                    <fullName>Native American</fullName>
                </value>
                <value>
                    <fullName>Native Pacific Islander/Hawaiian</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                    <label>Prefer Not to Answer</label>
                </value>
                <value>
                    <fullName>Other | other</fullName>
                    <label>Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suffix_Text__c</fullName>
        <description>Text display of picklist value of the baseline Suffix field. This is to be leveraged for the custom created &quot;Donor Roll&quot; full name display field (JAR).</description>
        <formula>TEXT(DonorApi__Suffix__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Suffix Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survivor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this individual as a cancer survivor.</description>
        <inlineHelpText>Is this individual a cancer survivor?</inlineHelpText>
        <label>Survivor</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <formula>Contact.AACR_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AM21ParticipantWebService.cls
/**
 * Created by lauren.lezberg on 4/5/2021.
 */
@RestResource(urlMapping='/AM21Participant/*')
global with sharing class AM21ParticipantWebService {

    @HttpGet
    global static AM21Participation getParticipant() {
        RestRequest req = RestContext.request;

        String keyId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        String contactId;

        System.debug('keyId = ' + keyId.substring(0, 3));

        If ( keyId.substring(0, 3) == '005' ) {
            contactId = [SELECT ContactId FROM User WHERE Id = :keyId].ContactId;
        } else {
            contactId = keyId;
        }

        AM21Participation participant = new AM21Participation();


        try{
            Contact con = [
                    SELECT Salutation,
                            FirstName,
                            MiddleName,
                            LastName,
                            Suffix_Text__c,
                            Name,
                            Title,
                            Department,
                            AccountId,
                            Account.Name,
                            Account.Institution_Type__c,
                            MailingStreet,
                            MailingCity,
                            MailingState,
                            MailingPostalCode,
                            MailingCountry,
                            Email,
                            Phone,
                            Race__c,
                            Gender__c,
                            Birthdate,
                            Primary_Research_Area_of_Expertise__c,
                            Major_Focus__c,
                            AACR_ID__c,
                            Membership_Status__c,
                            Member_Type__c,
                            Paid_thru_date__c,
                            Degrees_Held__c,
                            Current_Education_Status__c,
                            Organ_Sites__c,
                            Advocate__c,
                            Survivor__c,
                            RecordType.Name,
                            Id
                    FROM Contact
                    WHERE AACR_ID__c = :contactId OR Id = :contactId];

            participant.contact = con;
            List<BR_Participation__c> participations = [SELECT Id FROM BR_Participation__c WHERE BR_Event__r.Name = 'AACR Annual Meeting 2021' AND Contact__c=:con.Id AND Participate__c = 'Yes'];

            if(!participations.isEmpty()){
                participant.isRegistered = true;
                participant.registrationId = participations[0].Id;
            }

        } catch(Exception e){

        }

        return participant;
    }

    global class AM21Participation{
        public Boolean isRegistered = false;
        public String registrationId = null;
        public Contact contact;
    }
}