src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>Institution Types</description>
        <inlineHelpText>Types of Institutions</inlineHelpText>
        <label>Institution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Institution_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>BR_Events_Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>BR_Events_Zone__c</referenceTo>
        <relationshipName>BR_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Events_Zone__c.object
<CustomObject>
    <label>AC Events Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>Historical reflection of iMIS data on the contact object. This field will be read only.</description>
        <label>Institution Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organ_Sites__c</fullName>
        <description>Organ site research area(s)</description>
        <inlineHelpText>Organ site research area(s)</inlineHelpText>
        <label>Organ Sites</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Organ_Sites_Global_Picklist</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/contact_last_accessed_step__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>contacts last accessed step</relationshipLabel>
        <relationshipName>contacts_last_accessed_step</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JoinId__c</fullName>
        <description>Id of join process</description>
        <label>JoinId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step_Order__c</fullName>
        <label>Step Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>contact last accessed step</label>
    <nameField>
        <displayFormat>SN-{0000}</displayFormat>
        <label>RN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>contacts last accessed step</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Email__c.object
<CustomObject>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Exhibitor Emails</relationshipLabel>
        <relationshipName>Exhibitor_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhibitor_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Setting</label>
        <referenceTo>EC_Exhibitor_Setting__c</referenceTo>
        <relationshipLabel>Exhibitor Emails</relationshipLabel>
        <relationshipName>Exhibitor_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exhibitor Email</label>
    <nameField>
        <displayFormat>EE-{0000}</displayFormat>
        <label>Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Event__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Exhibitor Connect Event to reference when making orders</description>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exhibitor Connect Event</label>
</CustomObject>

src/objects/EC_Exhibitor_Setting__c.object
<CustomObject>
    <label>Exhibitor Setting</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exhibitor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Order__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Type__c</fullName>
        <label>Attendee Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Members</fullName>
                </value>
                <value>
                    <fullName>Non-Members</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Countries__c</fullName>
        <label>Countries</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degrees__c</fullName>
        <label>Degrees</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Degrees_Held_Global_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exhibitor_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Setting</label>
        <referenceTo>EC_Exhibitor_Setting__c</referenceTo>
        <relationshipLabel>Exhibitor Orders</relationshipLabel>
        <relationshipName>Exhibitor_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <label>Institution Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Institution_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organ_Sites__c</fullName>
        <label>Organ Sites</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Organ_Sites_Global_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Research_Area_of_Expertise__c</fullName>
        <label>Research Area of Expertise</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Research_Areas_Global_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <label>Exhibitor Order</label>
    <nameField>
        <displayFormat>EO-{0000}</displayFormat>
        <label>EO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Schedule__c.object
<CustomObject>
    <label>Exhibitor Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibitor Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Join_Process__mdt.object
<CustomObject>
    <description>Types of membership join/renewal processes</description>
    <label>Join Process</label>
    <pluralLabel>Join Processes</pluralLabel>
</CustomObject>

src/objects/Join_Step__mdt.object
<CustomObject>
    <description>Individual steps available for join/renewal process</description>
    <label>Join Step</label>
    <pluralLabel>Join Steps</pluralLabel>
</CustomObject>

src/objects/Process_Steps__mdt.object
<CustomObject>
    <description>Steps related to an individual join process in order</description>
    <fields>
        <fullName>Join_Step__c</fullName>
        <description>Associate join step component</description>
        <label>Join Step</label>
        <referenceTo>Join_Step__mdt</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>Associated join process</description>
        <label>Process</label>
        <referenceTo>Join_Process__mdt</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Step_Order__c</fullName>
        <label>Step Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Step</label>
    <pluralLabel>Process Steps</pluralLabel>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>EC_Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Email</label>
        <referenceTo>EC_Email__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>EC_Schedule__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Slot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_OrderFormControllerTest.cls
/**
 * Created by afaf.awad on 3/24/2021.
 */
@IsTest
public with sharing class EC_OrderFormControllerTest {

    @TestSetup public static void setup() {
        Account account = LiveTestDataFactory.buildAccount('Test Account');
        insert account;

        Contact contact = LiveTestDataFactory.buildContact(account.Id);
        insert contact;

        User user = TestDataFactory.buildUser(contact.Id);
        insert user;

        EC_Exhibitor_Setting__c ecSetting = ExhibitorTestDataFactory.buildExhibitorSetting(account.Id);
        insert ecSetting;

        EC_Order__c order = ExhibitorTestDataFactory.buildECOrder(ecSetting.Id, contact);
        insert order;

        EC_Email__c email = ExhibitorTestDataFactory.buildECEmail(ecSetting.Id, order.Id);
        insert email;

        BR_Events_Zone__c zone = LiveTestDataFactory.buildZone('Default', true);
        insert zone;

        BR_Event__c event = LiveTestDataFactory.buildEvent('Exhibitor Test Event', false, false, zone.Id);
        insert event;

        EC_Schedule__c schedule = ExhibitorTestDataFactory.buildECSchedule(event.Id);
        insert schedule;

        Time_Slot__c timeSlot = ExhibitorTestDataFactory.buildTimeSlot(order.Id, email.Id, schedule.Id);
        insert timeSlot;

        insert new EC_Event__c(Event_Name__c = event.Name, Event_Id__c = event.Id);


    }

    @IsTest
    public static void test_getOrderInfo() {
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name = 'Test Account' LIMIT 1];
        User user = [SELECT Id, ContactId FROM User WHERE ContactId = :con.Id];
        EC_Email__c email = [SELECT Id, EC_Order__c, Exhibitor_Setting__c FROM EC_Email__c];

        List<Process_Steps__mdt> pSteps = [SELECT Id, Step_Order__c, Process__c FROM Process_Steps__mdt WHERE Process__r.DeveloperName = 'New_Exhibitor_Order' AND Join_Step__r.DeveloperName = 'EC_Order_Form'];

        contact_last_accessed_step__c las = new contact_last_accessed_step__c(Contact__c = con.Id, JoinId__c = pSteps[0].Process__c, Step_Order__c = pSteps[0].Step_Order__c - 1);
        insert las;

        System.runAs(user) {
            EC_OrderFormController.OrderInfo orderInfo = EC_OrderFormController.getOrderInfo(email.EC_Order__c, pSteps[0].Id);
            System.assertEquals(OrderInfo.order.Id, email.EC_Order__c);
            System.assertEquals(OrderInfo.countries.size(), 3);

        }
    }

    @IsTest
    public static void test_saveOrder() {
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name = 'Test Account' LIMIT 1];
        User user = [SELECT Id, ContactId FROM User WHERE ContactId = :con.Id];
        EC_Order__c order = [SELECT Id FROM EC_Order__c LIMIT 1];

        List<EC_OrderFormController.columnObject> countries = EC_OrderFormController.getColumnObject('Countries__c');
        List<EC_OrderFormController.columnObject> attendeeTypes = EC_OrderFormController.getColumnObject('Attendee_Type__c');
        List<EC_OrderFormController.columnObject> institutionTypes = EC_OrderFormController.getColumnObject('Institution_Type__c');
        List<EC_OrderFormController.columnObject> degrees = EC_OrderFormController.getColumnObject('Degrees__c');
        List<EC_OrderFormController.columnObject> organs = EC_OrderFormController.getColumnObject('Organ_Sites__c');
        List<EC_OrderFormController.columnObject> researchAreas = EC_OrderFormController.getColumnObject('Research_Area_of_Expertise__c');

        System.runAs(user) {
           EC_OrderFormController.saveOrder(order.Id, 'Test Order', JSON.serialize(countries), JSON.serialize(attendeeTypes)
                                                            ,JSON.serialize(degrees) , JSON.serialize(institutionTypes), JSON.serialize(organs), JSON.serialize(researchAreas));

        }

        EC_Order__c newOrder = [SELECT Id, Countries__c, Attendee_Type__c, Institution_Type__c, Degrees__c, Organ_Sites__c, Research_Area_of_Expertise__c FROM EC_Order__c];

        System.assertEquals(ColumnObjectToList(countries), newOrder.Countries__c);
        System.assertEquals(ColumnObjectToList(attendeeTypes), newOrder.Attendee_Type__c);
        System.assertEquals(ColumnObjectToList(degrees), newOrder.Degrees__c);

    }

    private static String ColumnObjectToList(List<EC_OrderFormController.columnObject> cObject){
        List<String> objectList = new List<String>();
        for(EC_OrderFormController.columnObject o : cObject){
            objectList.add(o.option);
        }
        return JSON.serialize(objectList).remove('"').remove('[').remove(']').replace(',',';');
    }

}