src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>Institution Types</description>
        <inlineHelpText>Types of Institutions</inlineHelpText>
        <label>Institution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Institution_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <description>Formula field reflecting either legacy iMIS ID or new Salesforce ID depending upon when record was created.</description>
        <formula>IF(ISBLANK( iMIS_ID__c ), Salesforce_ID__c, iMIS_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_Research_Areas__c</fullName>
        <description>This field reflects any additional research areas for the AACR member besides the primary area.</description>
        <inlineHelpText>This field reflects any additional research areas for the AACR member besides the primary area.</inlineHelpText>
        <label>Additional Research Areas</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Research_Areas_Global_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Advocate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this individual as a member of the Survivor and Patient Advocacy program.</description>
        <inlineHelpText>Eligible for discounted patient advocate rate</inlineHelpText>
        <label>Advocate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Current Education Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Segment__c</fullName>
        <label>Event Segment</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the contact.</description>
        <inlineHelpText>Gender of the contact.</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                    <label>Prefer Not to Answer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Highest_Degree__c</fullName>
        <label>Highest Degree</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Degrees_Held_Global_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Income_Level__c</fullName>
        <description>Income level based upon country of origin; reflects iMIS&apos; original Category field.</description>
        <inlineHelpText>The income level of contact based upon country.</inlineHelpText>
        <label>World Bank Income Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High Income</fullName>
                    <default>true</default>
                    <label>High Income</label>
                </value>
                <value>
                    <fullName>Upper Middle Income</fullName>
                </value>
                <value>
                    <fullName>Lower Middle Income</fullName>
                </value>
                <value>
                    <fullName>Low Income</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>Historical reflection of iMIS data on the contact object. This field will be read only.</description>
        <label>Institution Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Focus__c</fullName>
        <description>Describes major focus of the contact.</description>
        <inlineHelpText>Describes major focus of the contact.</inlineHelpText>
        <label>Major Focus</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Basic Research</fullName>
                </value>
                <value>
                    <fullName>Basic Science</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Clinical Practice</fullName>
                </value>
                <value>
                    <fullName>Clinical Research</fullName>
                </value>
                <value>
                    <fullName>Population Science</fullName>
                </value>
                <value>
                    <fullName>Research Administration</fullName>
                </value>
                <value>
                    <fullName>Science Education</fullName>
                </value>
                <value>
                    <fullName>Translational Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Type__c</fullName>
        <description>Indicates what level of membership this individual possesses.</description>
        <inlineHelpText>Indicates what level of membership this individual possesses.</inlineHelpText>
        <label>Member Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Preferred_Phone__c</fullName>
        <description>**System Calculated** The Preferred Phone for the Contact is calculated by mapping the Preferred Phone Type to it&apos;s corresponding field&apos;s value.</description>
        <formula>IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Mobile&quot;) &amp;&amp; NOT(OrderApi__Mobile_Do_Not_Call__c), MobilePhone,
IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Home&quot;) &amp;&amp; NOT(OrderApi__Home_Do_Not_Call__c), HomePhone,
IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Work&quot;) &amp;&amp; NOT(OrderApi__Work_Do_Not_Call__c),OrderApi__Work_Phone__c,
IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Other&quot;) &amp;&amp; NOT(OrderApi__Other_Do_Not_Call__c),OtherPhone,
IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Assistant&quot;) &amp;&amp; NOT(OrderApi__Assistant_Do_Not_Call__c),AssistantPhone,
&apos;&apos;)))))</formula>
        <inlineHelpText>**System Calculated** The Preferred Phone for the Contact is calculated by mapping the Preferred Phone Type to it&apos;s corresponding field&apos;s value.</inlineHelpText>
        <label>Preferred Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organ_Sites__c</fullName>
        <description>Organ site research area(s)</description>
        <inlineHelpText>Organ site research area(s)</inlineHelpText>
        <label>Organ Sites</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Organ_Sites_Global_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Post_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pre/Post Doc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Research_Area_of_Expertise__c</fullName>
        <description>This field reflects the single primary research area for the AACR member.</description>
        <inlineHelpText>This field reflects the single primary research area for the AACR member.</inlineHelpText>
        <label>Research Area of Expertise</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Research_Areas_Global_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <description>Race of the contact.</description>
        <inlineHelpText>Race of the contact.</inlineHelpText>
        <label>Race</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>African American/Black</fullName>
                </value>
                <value>
                    <fullName>Alaskan Native</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>Caucasian</fullName>
                </value>
                <value>
                    <fullName>Hispanic/Latino</fullName>
                </value>
                <value>
                    <fullName>Native American</fullName>
                </value>
                <value>
                    <fullName>Native Pacific Islander/Hawaiian</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                    <label>Prefer Not to Answer</label>
                </value>
                <value>
                    <fullName>Other | other</fullName>
                    <label>Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suffix_Text__c</fullName>
        <description>Text display of picklist value of the baseline Suffix field. This is to be leveraged for the custom created &quot;Donor Roll&quot; full name display field (JAR).</description>
        <formula>TEXT(DonorApi__Suffix__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Suffix Text</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <formula>Contact.AACR_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ParticipantWebService.cls
/**
 * Created by lauren.lezberg on 8/19/2020.
 */
@RestResource(urlMapping='/Participant/*')
global with sharing class ParticipantWebService {

    @Httpget
    global static CSI_Reg_Api.CSIObject getParticipant() {
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;

        String keyId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        String contactId;

        System.debug('keyId = ' + keyId.substring(0, 3));

        If (keyId.substring(0, 3) == '005') {
            contactId = [SELECT ContactId FROM User WHERE Id = :keyId].ContactId;
        } else if (keyId.contains('@')) {
            contactId = [SELECT ContactId FROM User WHERE Email = :keyId].ContactId;
        } else {
            contactId = keyId;
        }

        CSI_Reg_Api.CSIObject result = new CSI_Reg_Api.CSIObject();


        try {
            Contact con = [
                    SELECT Id,
                            Salutation,
                            FirstName,
                            MiddleName,
                            LastName,
                            Suffix_Text__c,
                            Name,
                            Title,
                            Account.Name,
                            MailingStreet,
                            MailingCity,
                            MailingState,
                            MailingPostalCode,
                            MailingCountry,
                            Email,
                            OrderApi__Preferred_Phone__c,
                            Race__c,
                            Gender__c,
                            Birthdate,
                            Highest_Degree__c,
                            Primary_Research_Area_of_Expertise__c,
                            Additional_Research_Areas__c,
                            Major_Focus__c,
                            AACR_ID__c,
                            Organ_Sites__c,
                            Member_Type__c,
                            RecordType.Name,
                            Account.Institution_Type__c,
                            Advocate__c,
                            Pre_Post_Doc__c,
                            Income_Level__c,
                            Event_Segment__c,
                            Department,
                            Current_Education_Status__c

                    FROM Contact
                    WHERE AACR_ID__c = :contactId OR Id = :contactId
            ];

            List<Degree_Translation__mdt> degreeTranslations = [SELECT Id, Label, CSI_Degree__c FROM Degree_Translation__mdt];

            Map<String,String> degreeMap = new Map<String,String>();
            for(Degree_Translation__mdt dt : degreeTranslations){
                degreeMap.put(dt.Label,dt.CSI_Degree__c);
            }

            result.Name = con.Name;
            result.ContactId = con.Id;
            result.Salutation = con.Salutation;
            result.First_Name = con.FirstName;
            result.Middle_Name = con.MiddleName;
            result.Last_Name = con.LastName;
            result.Suffix = con.Suffix_Text__c;
            result.Title = con.Title;
            result.Account_Name = (con.Account.Name.contains('Household') || con.Account.Name.contains('(Individual)')) ? null : con.Account.Name;
            result.Address = con.MailingStreet;
            result.City = con.MailingCity;
            result.State = con.MailingState;
            result.Zip = con.MailingPostalCode;
            result.Country = con.MailingCountry;
            result.Email = con.Email;
            result.Phone = con.OrderApi__Preferred_Phone__c;
            result.Race = con.Race__c;
            result.Gender = con.Gender__c;
            result.Birthdate = con.Birthdate;
            result.Primary_Research_Area_of_Expertise = con.Primary_Research_Area_of_Expertise__c + ';'+ con.Additional_Research_Areas__c;
            result.Major_Focus = con.Major_Focus__c;
            result.AACR_ID = con.AACR_ID__c;
            result.Organ_Sites = con.Organ_Sites__c;
            result.Segment = con.Event_Segment__c.replace('-', '_');
            result.Dues_Alert = con.RecordType.Name=='Prior Member'?true:false;
            result.Highest_Degree = degreeMap.get(con.Highest_Degree__c);
            result.Institution_Type = con.Account.Institution_Type__c;
            result.Department = con.Department;
            result.Current_Education_Status = con.Current_Education_Status__c == 'N/A' ? null : con.Current_Education_Status__c;

        } catch (DmlException e) {
            System.debug('Id ' + contactId + ' returned no result');
        }

        return result;
    }



}