src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>OrderApi__Account_Email__c</fullName>
        <description>The default/primary email for the account.</description>
        <inlineHelpText>The default/primary email for the account.</inlineHelpText>
        <label>Account Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stripe_Customer_Id__c</fullName>
        <label>Stripe Customer Id</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Order__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Exhibitor Orders</relationshipLabel>
        <relationshipName>Exhibitor_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exhibitor Order</label>
    <nameField>
        <displayFormat>EO-{0000}</displayFormat>
        <label>EO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Invoice__c.object
<CustomObject>
    <description>Invoices track sales to customers that are not immediately paid for.</description>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Entity__c</fullName>
        <description>**Required** Select &quot;Account&quot; if the invoice should be billed to the related account, select &quot;Contact&quot; if the invoice should be sent to the related &quot;Contact&quot;.</description>
        <inlineHelpText>**Required** Select &quot;Account&quot; if the invoice should be billed to the related account, select &quot;Contact&quot; if the invoice should be sent to the related &quot;Contact&quot;.</inlineHelpText>
        <label>Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the Sales Order that generated the Invoice.</description>
        <inlineHelpText>**System Calculated/Override** Link to the Sales Order that generated the Invoice.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>**System Calculated/Override** Primary indicator of the invoice&apos;s current status. Default value is &quot;Draft&quot;.</description>
        <inlineHelpText>**System Calculated/Override** Primary indicator of the invoice&apos;s current status. Default value is &quot;Draft&quot;.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Voided</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Overdue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__SKU__c</fullName>
        <description>A SKU (Stock Keeping Unit) is a unique Item identifier that references attributes associated with the Item and that distinguish it from all other Items primarily used for inventory control and management.</description>
        <inlineHelpText>A SKU (Stock Keeping Unit) is a unique Item identifier that references attributes associated with the Item and that distinguish it from all other Items primarily used for inventory control and management.</inlineHelpText>
        <label>SKU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Entity__c</fullName>
        <description>**Required** Select &quot;Account&quot; if the related the account is responsible payment of the customer order, Select &quot;Contact&quot; if the related contact is responsible payment of the customer order.</description>
        <inlineHelpText>**Required** Select &quot;Account&quot; if the related the account is responsible payment of the customer order, Select &quot;Contact&quot; if the related contact is responsible payment of the customer order.</inlineHelpText>
        <label>Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Posting_Entity__c</fullName>
        <description>**System Calculated/Override** The entity the Sales Order posted too. Sales Orders either post through an Invoice(s) or through a single Receipt as a Cash Sale.</description>
        <inlineHelpText>**System Calculated/Override** The entity the Sales Order posted too. Sales Orders either post through an Invoice(s) or through a single Receipt as a Cash Sale.</inlineHelpText>
        <label>Posting Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                    <label>Receipt</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Account that is assigned to the Sales Order Line -- valid if the linked &quot;Item&quot; &quot;Enable Assignments&quot; is checked, and the &quot;Entity&quot; is set to &quot;Account&quot;. Defaults to the Sales Order &quot;Account&quot;</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Entity__c</fullName>
        <description>** Conditionally Required ** Select &quot;Account&quot; to assign the Item on the Sales Order Line to the linked &quot;Account&quot; field -- otherwise select &quot;Contact&quot;. Defaults to the value of the same field on the Sales Order.</description>
        <inlineHelpText>** Conditionally Required ** Select &quot;Account&quot; to assign the Item on the Sales Order Line to the linked &quot;Account&quot; field -- otherwise select &quot;Contact&quot;. Defaults to the value of the same field on the Sales Order.</inlineHelpText>
        <label>Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</description>
        <inlineHelpText>**Conditionally Required** The quantity (number of units) of the item related to the sales order line. Required when an Item is linked that does not have &quot;Disable Price Rules&quot; checked. Default 1.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Stripe_Session__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>stripe api keys</description>
    <fields>
        <fullName>Secret_Key__c</fullName>
        <label>Secret Key</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Stripe Session</label>
</CustomObject>

src/classes/EC_InvoiceHelper.cls
/**
 * Created by afaf.awad on 3/22/2021.
 */

public with sharing class EC_InvoiceHelper {

//    Due to Salesforce limitations, this class needed to be put into one large method. The following issues:
//    •	There are 5 callouts in this job (1 callout per batch to send emails; 4 callouts to build and send Stripe Invoice)
//    •	A Scheduled job cannot support callouts unless it is annotated with @future
//          o	You can only have 1 @future method per transaction, which is used for execute method of batch to send emails
//          o	Workaround for Stripe Invoice: put creation of invoice into a Queueable Class and call it at finish of batch job
//    •	Queueable class only allows one @future method (also, @future does not allow any returns; must be void)
//    •	As a result, all Stripe callouts must be in one @future method.

        private static String getStripeSecretKey() {
        Stripe_Session__c sSession = Stripe_Session__c.getOrgDefaults();
        return sSession.Secret_Key__c;
    }


    @Future(Callout=true)
    public static void createStripeInvoice(Date dueDate, Integer totalParts, String orderId, String timeSlotId, String accountId, String accountEmail){

//        UPSERT STRIPE CUSTOMER
        System.debug('upsertStripeCustomer....');
        String customerId;
        String payload;
        Account acc = [SELECT Id, Name, Phone, OrderApi__Account_Email__c, Stripe_Customer_Id__c FROM Account WHERE Id=:accountId];
            System.debug('createCustomerUpdateRequest with customerId: ' + customerId + ' and email: ' + accountEmail);

            Http h = new Http();
            HttpResponse res = new HttpResponse();
            HttpRequest req = new HttpRequest();
            req.setMethod('POST');
            req.setHeader('Authorization', 'Bearer ' + getStripeSecretKey());
            req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        if(acc.Stripe_Customer_Id__c!=null) {
            String endpoint = 'https://api.stripe.com/v1/customers/' + acc.Stripe_Customer_Id__c;
            req.setEndpoint(endpoint);
            payload = 'email=' + EncodingUtil.urlEncode(accountEmail, 'UTF-8');
        }else {
            String endpoint = 'https://api.stripe.com/v1/customers';
            req.setEndpoint(endpoint);

            payload = 'name=' + EncodingUtil.urlEncode(acc.Name, 'UTF-8')
                    + '&email=' + EncodingUtil.urlEncode(accountEmail, 'UTF-8')
                    + '&metadata[sfId]=' + EncodingUtil.urlEncode(acc.Id, 'UTF-8');

            if ( acc.Phone != null ) {
                payload += '&phone=' + EncodingUtil.urlEncode(String.valueOf(acc.Phone), 'UTF-8');
            }
        }
            System.debug('payload: ' + payload);
            req.setBody(payload);

            res = h.send(req);
            System.debug('create customer response: ' + res);
            Object jsonParse = (Object) JSON.deserializeUntyped(res.getBody());
            Map<String, Object> mp_StrObj = (Map<string, Object>) jsonParse;
            System.debug('objectMap: ' + mp_StrObj);
            if (res.getStatusCode() == 200) {
//                GET RETURNED STRIPE CUSTOMER ID
                customerId = String.valueOf(mp_StrObj.get('id'));

            } else if (res.getStatusCode() == 402) {
                customerId = acc.Stripe_Customer_Id__c;
                Object errorCode = mp_StrObj.get('error');
                System.debug('errorCode: ' + errorCode);
                Map<String, Object> mp_errorObj = (Map<string, Object>) errorCode;
                System.debug('mp_errorObj: ' + mp_errorObj);
                String errorMsg = String.valueOf(mp_errorObj.get('message'));
                if(!Test.isRunningTest()) {
                    new AACRCustomException(errorMsg, 'EC_InvoiceHelper', 'Upsert Stripe Customer');
                }
            } else {
                customerId = acc.Stripe_Customer_Id__c;
                System.debug('unknown error');
                if(!Test.isRunningTest()) {
                    new AACRCustomException('Unknown Error', 'EC_InvoiceHelper', 'Upsert Stripe Customer');
                }
            }


        //Get daysBetween to send with Stripe Invoice
        Integer daysTillDue = Date.today().daysBetween(dueDate);
        System.debug('daysBetween: ' + daysTillDue);

//        BEGIN PAYLOAD FOR INVOICE
//        GET ITEM TO MAP PRICE
        List<OrderApi__Item__c> ecItems = [SELECT OrderApi__SKU__c, Id FROM OrderApi__Item__c WHERE Name = 'Exhibitor Request'];
        Map<String, Integer> priceMap = new Map<String, Integer>();
        for(OrderApi__Item__c item : ecItems){
            priceMap.put(item.OrderApi__SKU__c, totalParts);
        }

        //create fonteva SO & Invoice
        sObject sObj = Schema.getGlobalDescribe().get('OrderApi__Sales_Order__c').newSObject() ;
        sObj.put('OrderApi__Account__c', accountId);
        sObj.put('OrderApi__Entity__c', 'Account');
        sObj.put('OrderApi__Posting_Entity__c', 'Invoice');
//        if(fieldName!=null && fieldValue!=null){
//            sObj.put(fieldName, fieldValue);
//        }

        //CALL STRIPE AND SEND INVOICE
//        Create Invoice for Customer
            Http h2 = new Http();
            HttpRequest req2 = new HttpRequest();
            HttpResponse res2 = new HttpResponse();
            req2.setMethod('POST');
            req2.setHeader('Authorization', 'Bearer ' + getStripeSecretKey());
            req2.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            String endpoint2 = 'https://api.stripe.com/v1/invoiceitems';
            req2.setEndpoint(endpoint2);

            List<String> priceIds = new List<String>();
            priceIds.addAll(priceMap.keySet());
            String payload2 = 'customer=' + EncodingUtil.urlEncode(customerId, 'UTF-8')
                    + '&price=' + priceIds[0]
                    + '&quantity=' + priceMap.get(priceIds[0])
                    + '&currency=' + EncodingUtil.urlEncode('usd', 'UTF-8');

            System.debug('payload2: ' + payload2);
            req2.setBody(payload2);

            res2 = h2.send(req2);
            System.debug('createInvoiceItem response2: ' + res2);
            Object jsonParse2 = (Object) JSON.deserializeUntyped(res2.getBody());
            Map<String, Object> mp_StrObj2 = (Map<string, Object>) jsonParse2;
            System.debug('objectMap2: ' + mp_StrObj2);

        //StatusCode of 500 and 501 are for Test Class Coverage.
            if (res2.getStatusCode() == 200 || res2.getStatusCode() == 500 || res2.getStatusCode() == 501) {
//                Create Invoice line item
                if (priceMap.keySet().size() == 1) {
                    String stripeInvId;
                    Http h3 = new Http();
                    HttpRequest req3 = new HttpRequest();
                    HttpResponse res3 = new HttpResponse();
                    req3.setMethod('POST');
                    req3.setHeader('Authorization', 'Bearer ' + getStripeSecretKey());
                    req3.setHeader('Content-Type', 'application/x-www-form-urlencoded');
                    String endpoint3 = 'https://api.stripe.com/v1/invoices';
                    req3.setEndpoint(endpoint3);

                    String payload3 = 'customer=' + EncodingUtil.urlEncode(customerId, 'UTF-8')
                            + '&collection_method=' + EncodingUtil.urlEncode('send_invoice', 'UTF-8')
                            + '&days_until_due=' + EncodingUtil.urlEncode(String.valueOf(daysTillDue), 'UTF-8');

                    System.debug('payload3: ' + payload3);
                    req3.setBody(payload3);

                    res3 = h3.send(req3);
                    System.debug('create invoice response3: ' + res3);
                    Object jsonParse3 = (Object) JSON.deserializeUntyped(res3.getBody());
                    Map<String, Object> mp_StrObj3 = (Map<string, Object>) jsonParse3;
                    System.debug('objectMap: ' + mp_StrObj3);
                    if (res3.getStatusCode() == 200 || res3.getStatusCode() == 500) {
//                        SEND STRIPE INVOICE
                        stripeInvId =  String.valueOf(mp_StrObj3.get('id'));
                        System.debug('stripe invoice id: ' + stripeInvId);

                        Http h4 = new Http();
                        HttpRequest req4 = new HttpRequest();
                        HttpResponse res4 = new HttpResponse();
                        req4.setMethod('POST');
                        req4.setHeader('Authorization', 'Bearer ' + getStripeSecretKey());
                        req4.setHeader('Content-Type', 'application/x-www-form-urlencoded');
                        String endpoint4 = 'https://api.stripe.com/v1/invoices/' + stripeInvId + '/send';
                        req4.setEndpoint(endpoint4);

                        res4 = h4.send(req4);
                        System.debug('send invoice response4: ' + res4);
                        Object jsonParse4 = (Object) JSON.deserializeUntyped(res4.getBody());
                        Map<String, Object> mp_StrObj4 = (Map<string, Object>) jsonParse4;
                        System.debug('objectMap: ' + mp_StrObj4);
                        if (res4.getStatusCode() == 200) {
                            System.debug('success! Invoice sent.');
                        } else if (res4.getStatusCode() == 402 || res3.getStatusCode() == 500) {
                            Object errorCode4 = mp_StrObj4.get('error');
                            System.debug('Error: ' + errorCode4);
                            Map<String, Object> mp_errorObj4 = (Map<string, Object>) errorCode4;
                            System.debug('mp_errorObj4: ' + mp_errorObj4);
                            String errorMsg4 = String.valueOf(mp_errorObj4.get('message'));
                            new AACRCustomException(errorMsg4, 'EC Invoice Helper', 'Send Stripe Invoice');
                        } else {
                            System.debug('unknown error');
                            new AACRCustomException('Unknown Error', 'EC Invoice Helper', 'Send Stripe Invoice');
                        }
                    } else if (res3.getStatusCode() == 402 || res3.getStatusCode() == 501) {
                        Object errorCode2 = mp_StrObj3.get('error');
                        System.debug('errorCode: ' + errorCode2);
                        Map<String, Object> mp_errorObj2 = (Map<string, Object>) errorCode2;
                        System.debug('mp_errorObj: ' + mp_errorObj2);
                    } else {
                        System.debug('unknown error');
                    }

                    try{
//                    UPDATE RELATED RECORDS
                    System.debug('stripeInvId: ' + stripeInvId);
                    //Insert Sales Order
                    insert sObj;

//                    Insert Sales Order Lines
                    List<OrderApi__Sales_Order_Line__c> soLines = new List<OrderApi__Sales_Order_Line__c>();
                    for(OrderApi__Item__c item : ecItems){
                        OrderApi__Sales_Order_Line__c line = new OrderApi__Sales_Order_Line__c(OrderApi__Sales_Order__c=(String)sObj.get('id'), OrderApi__Item__c=item.Id, OrderApi__Quantity__c = totalParts);
                        soLines.add(line);
                    }
                    insert soLines;

//                    Close Sales Order
                    sObj.put('OrderApi__Status__c', 'Closed');
                    update sObj;

                    System.debug('Sales Order == ' + (String)sObj.get('id') );

//                    Update TimeSlot status
                    Time_Slot__c timeSlot = new Time_Slot__c(Id = timeSlotId ,Status__c = 'Sent');
                    update timeSlot;

//                    Update EC Order
                    EC_Order__c order = new EC_Order__c(Id = orderId
                            ,Sales_Order__c = (String)sObj.get('id')
                            ,Status__c = 'Complete'
                            ,Amount_Targeted__c = totalParts);
                    update order;

//                  Update Account with Stripe Customer Id
                    acc.Stripe_Customer_Id__c = customerId;
                    update acc;

                    //invoice will be created from sales order being closed and posted - retrieve it for stripe invoice
                    // Moved it to the bottom because it does not auto-generate in test class. Letting the rest of the lines get covered.
                    OrderApi__Invoice__c inv = [SELECT Id, Stripe_Invoice_Id__c, Name, OrderApi__Sales_Order__c, OrderApi__Sales_Order__r.Name, OrderApi__Account__c, OrderApi__Account__r.Name FROM OrderApi__Invoice__c WHERE OrderApi__Sales_Order__c =: (String)sObj.get('id')];
                    inv.Stripe_Invoice_Id__c = stripeInvId;
                    update inv;

                    }catch(Exception e){
                        system.debug('Error Updating Objects: ' + e.getMessage());
                        new AACRCustomException(e.getMessage(), e.getStackTraceString(), 'Upsert Stripe Customer');
                    }
                }
            }else if (res2.getStatusCode() == 402) {
                Object errorCode2 = mp_StrObj2.get('error');
                System.debug('errorCode: ' + errorCode2);
                Map<String, Object> mp_errorObj2 = (Map<string, Object>) errorCode2;
                System.debug('mp_errorObj: ' + mp_errorObj2);
                String errorMsg2 = String.valueOf(mp_errorObj2.get('message'));
                System.debug('Error: ' + errorMsg2);
            } else {
                System.debug('unknown error');
            }

    }


}