src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Appeal_Code__c.object
<CustomObject>
    <description>Stores all appeal codes used by AACR Foundation staff</description>
    <label>Appeal Code</label>
    <nameField>
        <label>Appeal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appeal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>npsp__Primary_Contact__c</fullName>
        <description>Automatically checked if the Contact is the Primary Contact on their Account.</description>
        <formula>Account.npe01__One2OneContact__c = Id</formula>
        <inlineHelpText>This is is checked if the user is the Primary Contact on their Account.  The Primary Contact can be edited on the Account.</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Waitlist_Entry__c.object
<CustomObject>
    <description>Waitlist Entry store the Contact Information for people who want to be notified when any available ticket/registrations become open either for a Event or a Schedule Item at an Event.</description>
    <fields>
        <fullName>LTE__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Linked the to related Sales Order.</description>
        <inlineHelpText>Linked the to related Sales Order.</inlineHelpText>
        <label>SYSTEM</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Waitlist Entry</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Waitlist Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OrderApi__GL_Account__c.Distribution_Code__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__GL_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c4g_Appeal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Denotes the appeal code that relates to the specific opportunity</description>
        <label>Appeal Code</label>
        <referenceTo>Appeal_Code__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c4g_Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>Wire</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>c4g_Pledge_Type__c</fullName>
        <description>Denotes whether the pledge is made by an organization or an individual. Fonteva will transform the pledge data based on the value in this field. Organization pledges are reflected in GL immediately while individual pledges are not reflected until payment is received.</description>
        <inlineHelpText>Is this pledge from an individual or an organization?</inlineHelpText>
        <label>Pledge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Organization</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npsp__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</description>
        <inlineHelpText>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderApi__GL_Account__c.object
<CustomObject>
    <description>GL Accounting codes used for linking debits and credits with the appropriate codes.</description>
    <fields>
        <fullName>Distribution_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a Distribution code?</description>
        <inlineHelpText>Is this a Distribution code?</inlineHelpText>
        <label>Distribution Code</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateSalesOrderTest.cls
/**
 * Created by afaf.awad on 1/9/2019.
 */

@IsTest (seeAllData = true)
public class CreateSalesOrderTest {

    @IsTest public static void CreateClosedWonOpportunityTest() {

        Account acc = [Select Id from Account where Name = 'AACR Test Accounts' Limit 1];
        Contact cont = [Select Id from Contact where Accountid =:acc.id Limit 1];
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('DD Donations').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];

        Opportunity opptest = new Opportunity();
        opptest.Recordtypeid = OppRecId;
        opptest.Name = 'Test Opportunity';
        opptest.AccountId = acc.id;
        opptest.npsp__Primary_Contact__c = cont.id;
        opptest.CloseDate = date.today();
        opptest.stageName ='Closed Won';
        opptest.c4g_Appeal_Code__c = appCode.id;
        opptest.GL_Account__c = GLCode.id;
        opptest.Amount = 100;
        opptest.c4g_Payment_Method__c='CC';

        insert opptest;

        GLCode = [Select Id From OrderApi__GL_Account__c where Name = 'DIRECT_MAIL' LImit 1];
        opptest.GL_Account__c = GLCode.id;

        Update opptest;

        Opportunity opp = [SELECT Id, (SELECT Id FROM Sales_Orders__r) FROM Opportunity WHERE Id =: opptest.Id];

        System.assertEquals(1, opp.Sales_Orders__r.size());


    }

    @IsTest public static void CreatePledgedOpportunityTest() {

        Account acc = [Select Id from Account where Name = 'AACR Test Accounts' Limit 1];
        Contact cont = [Select Id from Contact where Accountid =:acc.id Limit 1];
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];

        Test.startTest();
        Opportunity opptest = new Opportunity();
        opptest.Recordtypeid = OppRecId;
        opptest.Name = 'Test Opportunity';
        opptest.AccountId = acc.id;
        opptest.npsp__Primary_Contact__c = cont.id;
        opptest.CloseDate = date.today();
        opptest.stageName ='Prospecting';
        opptest.c4g_Pledge_Type__c = 'Organization';
        opptest.c4g_Appeal_Code__c = appCode.id;
        opptest.GL_Account__c = GLCode.id;
        opptest.Amount = 1000;
        opptest.stageName = 'Pledged';

        insert opptest;

        Test.stopTest();

        Opportunity opp = [SELECT Id, (SELECT Id FROM Sales_Orders__r) FROM Opportunity WHERE Id =: opptest.Id];

        System.assertEquals(1, opp.Sales_Orders__r.size());

    }
}