src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ddrive__DonorDrive_ID__c</fullName>
        <externalId>true</externalId>
        <label>DonorDrive ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Appeal_Code__c.object
<CustomObject>
    <description>Stores all appeal codes used by AACR Foundation staff</description>
    <label>Appeal Code</label>
    <nameField>
        <label>Appeal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appeal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ddrive__DonorDrive_ID__c</fullName>
        <externalId>true</externalId>
        <label>DonorDrive ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ddrive__Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npsp__Primary_Contact__c</fullName>
        <description>Automatically checked if the Contact is the Primary Contact on their Account.</description>
        <formula>Account.npe01__One2OneContact__c = Id</formula>
        <inlineHelpText>This is is checked if the user is the Primary Contact on their Account.  The Primary Contact can be edited on the Account.</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OrderApi__GL_Account__c.Distribution_Code__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__GL_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c4g_Appeal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Denotes the appeal code that relates to the specific opportunity</description>
        <label>Appeal Code</label>
        <referenceTo>Appeal_Code__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c4g_Expected_Amount__c</fullName>
        <description>When informed of a future planned gift, the amount expected, if known</description>
        <label>Expected Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>c4g_Pledge_Type__c</fullName>
        <description>Denotes whether the pledge is made by an organization or an individual. Fonteva will transform the pledge data based on the value in this field. Organization pledges are reflected in GL immediately while individual pledges are not reflected until payment is received.</description>
        <inlineHelpText>Is this pledge from an individual or an organization?</inlineHelpText>
        <label>Pledge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Organization</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ddrive__Donation_Is_Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Part of DonorDrive integration</description>
        <label>Donation Is Recurring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ddrive__Donation_Recurring_Cancel_Date__c</fullName>
        <description>Part of DonorDrive integration</description>
        <label>Donation Recurring Cancel Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ddrive__DonorDrive_ID__c</fullName>
        <externalId>true</externalId>
        <label>DonorDrive ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ddrive__Donor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Donor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Donor)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ddrive__Level__c</fullName>
        <label>Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>npsp__Acknowledgment_Date__c</fullName>
        <description>Used to track date opportunity was acknowledged</description>
        <inlineHelpText>Date of acknowledgment</inlineHelpText>
        <label>Acknowledgment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>npsp__Acknowledgment_Status__c</fullName>
        <description>Status of Acknowledgment of this gift.</description>
        <inlineHelpText>Status of Acknowledgment of this gift.</inlineHelpText>
        <label>Acknowledgment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>To Be Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Do Not Acknowledge</fullName>
                </value>
                <value>
                    <fullName>Email Acknowledgment Now</fullName>
                </value>
                <value>
                    <fullName>Email Acknowledgment Not Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npsp__Ask_Date__c</fullName>
        <description>The date when the donor was specifically asked for the donation, as opposed to the Opportunity Close Date that the organization may set to either when the Opportunity was first created, or when the Opportunity was won.</description>
        <inlineHelpText>The date when the donor was specifically asked for the donation, as opposed to the Opportunity Close Date that the organization may set to either when the Opportunity was first created, or when the Opportunity was won.</inlineHelpText>
        <label>Ask Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>npsp__In_Kind_Type__c</fullName>
        <description>The type of In-Kind gift.</description>
        <inlineHelpText>The type of In-Kind gift.</inlineHelpText>
        <label>In-Kind Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Goods</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npsp__Matching_Gift_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account of the company who will match this gift.</description>
        <inlineHelpText>The account of the company who will match this gift.</inlineHelpText>
        <label>Matching Gift Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Matched Gifts</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npsp__Matching_Gift_Employer__c</fullName>
        <description>The name of the company who will match this gift.</description>
        <inlineHelpText>The name of the company who will match this gift.</inlineHelpText>
        <label>Matching Gift Employer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>npsp__Matching_Gift_Status__c</fullName>
        <description>The status of this gift being matched.</description>
        <inlineHelpText>The status of this gift being matched.</inlineHelpText>
        <label>Matching Gift Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Potential</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npsp__Matching_Gift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The employer&apos;s matching gift for this employee&apos;s gift.</description>
        <inlineHelpText>The employer&apos;s matching gift for this employee&apos;s gift.</inlineHelpText>
        <label>Matching Gift</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Matched Gifts</relationshipLabel>
        <relationshipName>MatchedGifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npsp__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</description>
        <inlineHelpText>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npsp__Requested_Amount__c</fullName>
        <description>The amount you are requesting. This number might be different from the final award amount.</description>
        <inlineHelpText>The amount you are requesting. This number might be different from the final award amount.</inlineHelpText>
        <label>Requested Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>npsp__Tribute_Type__c</fullName>
        <description>Indicates whether the gift is in honor or memory of an individual.</description>
        <inlineHelpText>Indicates whether the gift is in honor or memory of an individual.</inlineHelpText>
        <label>Tribute Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Honor</fullName>
                </value>
                <value>
                    <fullName>Memorial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Matching_Gift</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Matching Donation from an Donor&apos;s Employer or other Organization</description>
        <label>Matching Gift</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Dimension_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Dim_Tag_Id__c</fullName>
        <label>Dim Tag Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tags</relationshipLabel>
        <relationshipName>Opportunity_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Tag</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Opportunity Tag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__GL_Account__c.object
<CustomObject>
    <description>GL Accounting codes used for linking debits and credits with the appropriate codes.</description>
    <fields>
        <fullName>Distribution_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a Distribution code?</description>
        <inlineHelpText>Is this a Distribution code?</inlineHelpText>
        <label>Distribution Code</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExportHelper_Opportunity.cls
/**
 * Created by afaf.awad on 6/14/2021.
 */

public with sharing class ExportHelper_Opportunity {

    public static final List<String> opportunityHeaders = new List<String>{'Id',
                                                                            'Opportunity_Name',
                                                                            'Account_Id',
                                                                            'Account_Name',
                                                                            'Primary_Contact',
                                                                            'Amount',
                                                                            'Expected_Amount',
                                                                            'Requested_Amount',
                                                                            'Record_Type',
                                                                            'Type',
                                                                            'Pledge_Type',
                                                                            'Stage',
                                                                            'Ask_Date',
                                                                            'Close_Date',
                                                                            'Acknowledgment_Date',
                                                                            'Acknowledgment_Status',
                                                                            'Donation_Is_Recurring',
                                                                            'Donation_Recurring_Cancel_Date',
                                                                            'Donor_ContactId',
                                                                            'DonorDrive_ID',
                                                                            'Level',
                                                                            'Appeal_Code',
                                                                            'Distribution_Code',
                                                                            'Lead_Source',
                                                                            'InKind_Type',
                                                                            'Matching_Gift',
                                                                            'Matching_Gift_Account',
                                                                            'Matching_Gift_Employer',
                                                                            'Matching_Gift_Status',
                                                                            'Tribute_Type',
                                                                            'Probability'};

    public static OpportunityExport queryOpportunities(String dimTagId){
        
        List<Opportunity> Opportunities = [SELECT Account.Id, Account.Name, Account.ddrive__DonorDrive_ID__c, c4g_Appeal_Code__r.Name, GL_Account__r.Distribution_Code__c,
                GL_Account__r.Name, npsp__Primary_Contact__r.Name, RecordType.Name, Id, Amount, CloseDate, Description, LeadSource, Name, Probability,
                StageName, Type, c4g_Expected_Amount__c, c4g_Pledge_Type__c, ddrive__Donation_Is_Recurring__c, ddrive__Donation_Recurring_Cancel_Date__c,
                ddrive__Donor__c, ddrive__Level__c, npsp__Acknowledgment_Date__c, npsp__Acknowledgment_Status__c, npsp__Ask_Date__c, npsp__In_Kind_Type__c,
                npsp__Matching_Gift_Account__r.Name, npsp__Matching_Gift_Employer__c, npsp__Matching_Gift_Status__c, npsp__Matching_Gift__r.Name, npsp__Primary_Contact__c,
                npsp__Requested_Amount__c, npsp__Tribute_Type__c, ddrive__DonorDrive_ID__c
                FROM Opportunity WHERE Id IN (SELECT Object_Lookup__c
                                                FROM Opportunity_Dimension_Tag__c
                                                WHERE Dim_Tag_Id__c =: dimTagId)];

        System.debug('Opportunities == ' + Opportunities);

        List<OpportunityList> oppList = new List<OpportunityList>();
        for(Opportunity opp : Opportunities){
        OpportunityList ol = new OpportunityList();
            ol.Id = opp.Id;
            ol.Opportunity_Name = opp.Name;
            ol.Account_Id = opp.Account.Id;
            ol.Account_Name = opp.Account.Name;
            ol.Primary_Contact = opp.npsp__Primary_Contact__r.Name;
            ol.Amount = opp.Amount;
            ol.Expected_Amount = opp.c4g_Expected_Amount__c ;
            ol.Requested_Amount = opp.npsp__Requested_Amount__c;
            ol.Record_Type = opp.RecordType.Name;
            ol.Type = opp.Type;
            ol.Pledge_Type = opp.c4g_Pledge_Type__c;
            ol.Stage = opp.StageName;
            ol.Ask_Date = opp.npsp__Ask_Date__c;
            ol.Close_Date = opp.CloseDate;
            ol.Acknowledgment_Date = opp.npsp__Acknowledgment_Date__c;
            ol.Acknowledgment_Status = opp.npsp__Acknowledgment_Status__c;
            ol.Donation_Is_Recurring = opp.ddrive__Donation_Is_Recurring__c;
            ol.Donation_Recurring_Cancel_Date = opp.ddrive__Donation_Recurring_Cancel_Date__c == null ? null : Date.newInstance(opp.ddrive__Donation_Recurring_Cancel_Date__c.year(),opp.ddrive__Donation_Recurring_Cancel_Date__c.month(),opp.ddrive__Donation_Recurring_Cancel_Date__c.day());
            ol.Donor_ContactId = opp.ddrive__Donor__c;
            ol.DonorDrive_ID = opp.ddrive__DonorDrive_ID__c;
            ol.Level = opp.ddrive__Level__c;
            ol.Appeal_Code = opp.c4g_Appeal_Code__r.Name;
            ol.Distribution_Code = opp.GL_Account__r.Name;
            ol.Lead_Source = opp.LeadSource;
            ol.InKind_Type = opp.npsp__In_Kind_Type__c;
            ol.Matching_Gift = opp.npsp__Matching_Gift__r.Name;
            ol.Matching_Gift_Account = opp.npsp__Matching_Gift_Account__r.Name;
            ol.Matching_Gift_Employer = opp.npsp__Matching_Gift_Employer__c;
            ol.Matching_Gift_Status = opp.npsp__Matching_Gift_Status__c;
            ol.Tribute_Type = opp.npsp__Tribute_Type__c;
            ol.Probability = opp.Probability;

            oppList.add(ol);
        }

        System.debug('oppList == ' + oppList);
        return new OpportunityExport(oppList);
    }

    public class OpportunityExport{
        @AuraEnabled
        public List<Object> Opportunities;
        @AuraEnabled
        public List<String> headers;

        public OpportunityExport(List<OpportunityList> OpportunityLists){
            this.Opportunities = OpportunityLists;
            this.headers  = opportunityHeaders;
        }

    }

    public class OpportunityList{
        @AuraEnabled public String Id;
        @AuraEnabled public String Opportunity_Name;
        @AuraEnabled public String Account_Id;
        @AuraEnabled public String Account_Name;
        @AuraEnabled public String Primary_Contact;
        @AuraEnabled public Double Amount;
        @AuraEnabled public Double Expected_Amount;
        @AuraEnabled public Double Requested_Amount;
        @AuraEnabled public String Record_Type;
        @AuraEnabled public String Type;
        @AuraEnabled public String Pledge_Type;
        @AuraEnabled public String Stage;
        @AuraEnabled public Date Ask_Date;
        @AuraEnabled public Date Close_Date;
        @AuraEnabled public Date Acknowledgment_Date;
        @AuraEnabled public String Acknowledgment_Status;
        @AuraEnabled public Boolean Donation_Is_Recurring;
        @AuraEnabled public Date Donation_Recurring_Cancel_Date;
        @AuraEnabled public String Donor_ContactId;
        @AuraEnabled public String DonorDrive_ID;
        @AuraEnabled public String Level;
        @AuraEnabled public String Appeal_Code;
        @AuraEnabled public String Distribution_Code;
        @AuraEnabled public String Lead_Source;
        @AuraEnabled public String InKind_Type;
        @AuraEnabled public String Matching_Gift;
        @AuraEnabled public String Matching_Gift_Account;
        @AuraEnabled public String Matching_Gift_Employer;
        @AuraEnabled public String Matching_Gift_Status;
        @AuraEnabled public String Tribute_Type;
        @AuraEnabled public Double Probability;
    }

}