src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DonorApi__Do_Not_Solicit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Do not solicit this organization for donations/grants.</description>
        <inlineHelpText>Do not solicit this organization for donations/grants.</inlineHelpText>
        <label>Do Not Solicit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DonorApi__Funding_Cycle__c</fullName>
        <description>Indicates how often a philanthropic entity accepts LOIs/Proposals.</description>
        <inlineHelpText>Indicates how often a philanthropic entity accepts LOIs/Proposals.</inlineHelpText>
        <label>Funding Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Biannual</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DonorApi__Gifts_Received__c</fullName>
        <description>**System Calculated Field** Summarizes the total amount of all related gifts with a status of &quot;Collected&quot;.</description>
        <inlineHelpText>**System Calculated Field** Summarizes the total amount of all related gifts with a status of &quot;Collected&quot;.</inlineHelpText>
        <label>Gifts Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DonorApi__Last_Gift_Amount__c</fullName>
        <description>**System Calculated Field** Calculates the amount of the last gift from the account&apos;s related gifts list.</description>
        <inlineHelpText>**System Calculated Field** Calculates the amount of the last gift from the account&apos;s related gifts list.</inlineHelpText>
        <label>Last Gift Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DonorApi__Last_Gift_Date__c</fullName>
        <label>Last Gift Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>Institution Types</description>
        <inlineHelpText>Types of Institutions</inlineHelpText>
        <label>Institution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Institution_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MSI_type__c</fullName>
        <label>MSI type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Selection</fullName>
                    <default>true</default>
                    <label>No Selection</label>
                </value>
                <value>
                    <fullName>HBCU</fullName>
                </value>
                <value>
                    <fullName>HSI</fullName>
                </value>
                <value>
                    <fullName>TCU</fullName>
                </value>
                <value>
                    <fullName>ITCCU</fullName>
                </value>
                <value>
                    <fullName>Nat-Hawaii</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minority_Institution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Minority Institution as identified by the Higher Education Act (HEA)</description>
        <inlineHelpText>Minority Institution as identified by the Higher Education Act (HEA)</inlineHelpText>
        <label>Minority Serving Institution</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Primary Contact for the Account will auto-populate on all Account Transactions, Payments, etc... by default.</description>
        <inlineHelpText>The Primary Contact for the Account will auto-populate on all Account Transactions, Payments, etc... by default.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Primary Contact Accounts</relationshipLabel>
        <relationshipName>Primary_Contact_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cfg_Actively_Prospecting_Corporate_Gift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to denote an Org Account has a prospective corporate gift opportunity. 7/16/18 meeting requirement W-000065</description>
        <label>Actively Prospecting Corporate Gift</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ddrive__Date_Entered__c</fullName>
        <label>Date Entered</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>npo02__TotalOppAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Do not manually update. Updated by automatic processes. See excluded Record Types in Household Settings.</description>
        <inlineHelpText>The sum of amounts of all won Opportunities related to this Account.</inlineHelpText>
        <label>Total Gifts</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Dimension_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Dim_Tag_Id__c</fullName>
        <label>Dim Tag Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Tags</relationshipLabel>
        <relationshipName>Account_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Tag</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Account Tag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExportHelper_Account.cls
/**
 * Created by afaf.awad on 6/14/2021.
 */

public with sharing class ExportHelper_Account {

    public static final List<String> accountHeaders = new List<String>{'Id',
                                                                'Account_Name',
                                                                'Primary_Contact',
                                                                'Record_Type',
                                                                'Date_Entered',
                                                                'Industry',
                                                                'Institution_Type',
                                                                'Minority_Serving_Institution',
                                                                'MSI_type',
                                                                'Do_Not_Solicit',
                                                                'Employees',
                                                                'Annual_Revenue',
                                                                'Actively_Prospecting_Corporate_Gift',
                                                                'Funding_Cycle',
                                                                'Gifts_Received',
                                                                'Last_Gift_Amount',
                                                                'Last_Gift_Date',
                                                                'Total_Gifts',
                                                                'SIC_Code',
                                                                'SIC_Description'};


    
    public static AccountExport queryAccounts(String dimTagId){
        List<Account> accounts = [SELECT RecordType.Name, Id, AnnualRevenue, DonorApi__Do_Not_Solicit__c, DonorApi__Funding_Cycle__c, DonorApi__Gifts_Received__c,
                DonorApi__Last_Gift_Amount__c, DonorApi__Last_Gift_Date__c, Industry, Institution_Type__c, MSI_type__c, Minority_Institution__c, Name,
                NumberOfEmployees, OrderApi__Primary_Contact__c, Sic, SicDesc, cfg_Actively_Prospecting_Corporate_Gift__c, ddrive__Date_Entered__c,
                npo02__TotalOppAmount__c FROM Account WHERE Id IN (SELECT Object_Lookup__c
                                                                    FROM Account_Dimension_Tag__c
                                                                    WHERE Dim_Tag_Id__c =: dimTagId)];

        System.debug('accounts == ' + accounts);

        List<AccountList> accList = new List<AccountList>();
        for(Account acc : accounts){
            AccountList al = new AccountList();
            al.Id = acc.Id;
            al.Primary_Contact = acc.OrderApi__Primary_Contact__c;
            al.Record_Type = acc.RecordType.Name;
            al.Date_Entered = acc.ddrive__Date_Entered__c == null ? null : date.newinstance(acc.ddrive__Date_Entered__c.year(), acc.ddrive__Date_Entered__c.month(), acc.ddrive__Date_Entered__c.day());
            al.Industry = acc.Industry;
            al.Institution_Type = acc.Institution_Type__c;
            al.Minority_Serving_Institution = acc.Minority_Institution__c;
            al.MSI_type = acc.MSI_type__c;
            al.Do_Not_Solicit = acc.DonorApi__Do_Not_Solicit__c;
            al.Employees = acc.NumberOfEmployees;
            al.Annual_Revenue = acc.AnnualRevenue;
            al.Actively_Prospecting_Corporate_Gift = acc.cfg_Actively_Prospecting_Corporate_Gift__c;
            al.Funding_Cycle = acc.DonorApi__Funding_Cycle__c;
            al.Gifts_Received = acc.DonorApi__Gifts_Received__c;
            al.Last_Gift_Amount = acc.DonorApi__Last_Gift_Amount__c;
            al.Last_Gift_Date = acc.DonorApi__Last_Gift_Date__c;
            al.Total_Gifts = acc.npo02__TotalOppAmount__c;
            al.SIC_Code = acc.Sic;
            al.Account_Name = acc.Name;
            al.SIC_Description = acc.SicDesc;

            accList.add(al);
        }

        System.debug('accList == ' + accList);
        return new AccountExport(accList);
    }

    public class AccountExport{
        @AuraEnabled
        public List<Object> Accounts;
        @AuraEnabled
        public List<String> headers;

        public AccountExport(List<AccountList> accountLists){
            this.Accounts = accountLists;
            this.headers  = accountHeaders;
        }

    }

    public class AccountList{
        @AuraEnabled public String Id;
        @AuraEnabled public String Account_Name;
        @AuraEnabled public String Primary_Contact;
        @AuraEnabled public String Record_Type;
        @AuraEnabled public Date Date_Entered;
        @AuraEnabled public String Industry;
        @AuraEnabled public String Institution_Type;
        @AuraEnabled public Boolean Minority_Serving_Institution;
        @AuraEnabled public String MSI_type;
        @AuraEnabled public Boolean Do_Not_Solicit;
        @AuraEnabled public Integer Employees;
        @AuraEnabled public Double Annual_Revenue;
        @AuraEnabled public String Actively_Prospecting_Corporate_Gift;
        @AuraEnabled public String Funding_Cycle;
        @AuraEnabled public Double Gifts_Received;
        @AuraEnabled public Double Last_Gift_Amount;
        @AuraEnabled public Date Last_Gift_Date;
        @AuraEnabled public Double Total_Gifts;
        @AuraEnabled public String SIC_Code;
        @AuraEnabled public String SIC_Description;
    }

}