src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DNBoptimizer__DnBCompanyRecord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Upon a successful match, Optimizer populates this field that links the Account record to a specific D-U-N-S Number for display of the correct custom object with D&amp;B data.</description>
        <inlineHelpText>Upon a successful match, Optimizer populates this field that links the Account record to a specific D-U-N-S Number for display of the correct custom object with D&amp;B data.</inlineHelpText>
        <label>AccountToDnB</label>
        <referenceTo>DNBoptimizer__DnBCompanyRecord__c</referenceTo>
        <relationshipLabel>AccountToDnB</relationshipLabel>
        <relationshipName>AccountToDnB</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>Institution Types</description>
        <inlineHelpText>Types of Institutions</inlineHelpText>
        <label>Institution Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Institution_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minority_Institution__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Minority Institution as identified by the Higher Education Act (HEA)</description>
        <inlineHelpText>Minority Institution as identified by the Higher Education Act (HEA)</inlineHelpText>
        <label>Minority Serving Institution</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DNBoptimizer__DnBCompanyRecord__c.object
<CustomObject>
    <fields>
        <fullName>DNBoptimizer__DUNSNumber__c</fullName>
        <description>The Dun &amp; Bradstreet D-U-N-S® Number is an identification number assigned by Dun &amp; Bradstreet that uniquely identifies the entity in accordance with the Data Universal Numbering System (D-U-N-S).</description>
        <inlineHelpText>The Dun &amp; Bradstreet D-U-N-S® Number is an identification number assigned by Dun &amp; Bradstreet that uniquely identifies the entity in accordance with the Data Universal Numbering System (D-U-N-S).</inlineHelpText>
        <label>D-U-N-S Number</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DNBoptimizer__MinorityOwnedIndicator__c</fullName>
        <description>When &apos;true&apos; indicates that this organization is certified as a business that is greater than 50% owned by and whose management and daily business operations are controlled by one or more minority group members.</description>
        <inlineHelpText>When &apos;true&apos; indicates that this organization is certified as a business that is greater than 50% owned by and whose management and daily business operations are controlled by one or more minority group members.</inlineHelpText>
        <label>Minority Owned Indicator</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNBoptimizer__SIC4Code1__c</fullName>
        <description>The primary Standard Industrial Classification (SIC) four digit code for the business.</description>
        <inlineHelpText>The primary Standard Industrial Classification (SIC) four digit code for the business.</inlineHelpText>
        <label>SIC4 Code 1</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>D&amp;B Company Record</label>
    <nameField>
        <label>Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>D&amp;B Company Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SIC_Code__mdt.object
<CustomObject>
    <fields>
        <fullName>Industry_Group__c</fullName>
        <description>Level 2 Sic Code</description>
        <label>Industry Group</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Group__c</fullName>
        <description>Level 1 SIC Codes</description>
        <label>Major Group</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specific_Code__c</fullName>
        <description>Level 3 SIC Code</description>
        <label>Specific Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>SIC Code</label>
    <pluralLabel>SIC Codes</pluralLabel>
</CustomObject>

src/classes/DnBTriggerHandler.cls
/**
 * Created by afaf.awad on 6/10/2021.
 */

public without sharing class DnBTriggerHandler {

    public static void updateInstitutionType(List<Account> accounts){

        List<String> dnbIds = new List<String>();
        for(Account acc : accounts){
            dnbIds.add(acc.DNBoptimizer__DnBCompanyRecord__c);
        }

        List<DNBoptimizer__DnBCompanyRecord__c> dnBCompanyRecords = [SELECT Id, Name,  DNBoptimizer__MinorityOwnedIndicator__c, DNBoptimizer__SIC4Code1__c, DNBoptimizer__DUNSNumber__c
                                                                        FROM DNBoptimizer__DnBCompanyRecord__c
                                                                        WHERE Id IN: dnbIds];

        System.debug('accountToDnb = ' + dnBCompanyRecords);

        List<SIC_Code__mdt> sicCodesMtd = [SELECT Id, Label, Industry_Group__c, Major_Group__c, Specific_Code__c FROM SIC_Code__mdt];
        Map<String,String> majorGroup = new Map<String,String>();
        Map<String,String> industryGroup = new Map<String,String>();
        Map<String,String> specificGroup = new Map<String,String>();
        List<Account> accounts2Update = new List<Account>();

        for(SIC_Code__mdt code: sicCodesMtd){
            majorGroup.put(code.Major_Group__c, code.Label);
            industryGroup.put(code.Industry_Group__c, code.Label);
            specificGroup.put(code.Specific_Code__c, code.Label);
        }

        for(Account acc : accounts) {
            for (DNBoptimizer__DnBCompanyRecord__c dnb : dnBCompanyRecords) {
                if(acc.DNBoptimizer__DnBCompanyRecord__c == dnb.Name) {
                    String sicCode = dnb.DNBoptimizer__SIC4Code1__c;
                    System.debug('sicCode == ' + sicCode);
                    if(String.isNotBlank(sicCode)) {
                        if (getListOfSicCodeMatches(sicCode.left(2), majorGroup) != null) {
                            acc.Institution_Type__c = getListOfSicCodeMatches(sicCode.left(2), majorGroup);
                        } else if (getListOfSicCodeMatches(sicCode.left(3), industryGroup) != null) {
                            acc.Institution_Type__c = getListOfSicCodeMatches(sicCode.left(3), industryGroup);
                        } else if (getListOfSicCodeMatches(sicCode.left(4), specificGroup) != null){
                            acc.Institution_Type__c = getListOfSicCodeMatches(sicCode.left(4), specificGroup);
                        }else{
                            acc.Institution_Type__c = 'Other';
                        }
                    }else{
                        acc.Institution_Type__c = 'Other';
                    }
                    acc.Minority_Institution__c = dnb.DNBoptimizer__MinorityOwnedIndicator__c == 'true' ? true : false;
                    accounts2Update.add(acc);
                }
            }
        }

        try{
            if(!accounts2Update.isEmpty()) {
                update accounts2Update;
            }
        }catch(Exception e){
            System.debug('Error updating Institution types from DNB: ' + e.getMessage());
        }
    }

    public static String getListOfSicCodeMatches(String sicCode, Map<String, String> groupMap) {

        List<String> groupList = new List<String>();
        for (String key : groupMap.keySet()) {
            if ( groupMap.containsKey(sicCode) ) {
                groupList.add(groupMap.get(sicCode));
            }
        }

        if ( groupList.size() > 1 ) {
            System.debug('groupMap == ' + groupMap.get(sicCode));
            return groupMap.get(sicCode);
        } else {
            return null;
        }
    }

}