src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Appeal_Code__c.object
<CustomObject>
    <description>Stores all appeal codes used by AACR Foundation staff</description>
    <label>Appeal Code</label>
    <nameField>
        <label>Appeal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appeal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>npsp__Primary_Contact__c</fullName>
        <description>Automatically checked if the Contact is the Primary Contact on their Account.</description>
        <formula>Account.npe01__One2OneContact__c = Id</formula>
        <inlineHelpText>This is is checked if the user is the Primary Contact on their Account.  The Primary Contact can be edited on the Account.</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OrderApi__GL_Account__c.Distribution_Code__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__GL_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c4g_Appeal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Denotes the appeal code that relates to the specific opportunity</description>
        <label>Appeal Code</label>
        <referenceTo>Appeal_Code__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c4g_Check_Number__c</fullName>
        <label>Check Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>c4g_Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>Wire</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>c4g_Pledge_Type__c</fullName>
        <description>Denotes whether the pledge is made by an organization or an individual. Fonteva will transform the pledge data based on the value in this field. Organization pledges are reflected in GL immediately while individual pledges are not reflected until payment is received.</description>
        <inlineHelpText>Is this pledge from an individual or an organization?</inlineHelpText>
        <label>Pledge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Organization</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ddrive__Donation_Payment_Status_Text__c</fullName>
        <label>Donation Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ddrive__Donation_Refund_Date__c</fullName>
        <label>Donation Refund Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ddrive__Refund_Amount__c</fullName>
        <label>Refund Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>npsp__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</description>
        <inlineHelpText>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donation Received</description>
        <label>Donation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderApi__GL_Account__c.object
<CustomObject>
    <description>GL Accounting codes used for linking debits and credits with the appropriate codes.</description>
    <fields>
        <fullName>Distribution_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a Distribution code?</description>
        <inlineHelpText>Is this a Distribution code?</inlineHelpText>
        <label>Distribution Code</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/test_OpptoSOandRefund.cls
@isTest (seealldata=true)
public class test_OpptoSOandRefund {
	
    public static testMethod void testOpportunityCash(){
        try{
        Id AccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.RecordTypeId = AccRecId;
        insert acc;
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];
        Opportunity Opp = new Opportunity();
        Opp.Name = 'Donation Test';
        Opp.AccountId = acc.Id;
        Opp.CloseDate = date.today();
        Opp.StageName = 'Posted';
        Opp.RecordTypeId = OppRecId;
        Opp.Amount = 100;
        Opp.c4g_Appeal_Code__c = appCode.Id;
            Opp.GL_Account__c = GLCode.Id;
        Opp.c4g_Payment_Method__c = 'Cash';
        insert Opp;
        } catch(Exception ex){
            system.debug(ex.getStackTraceString() + ex.getMessage());
        }
    }
    
    public static testMethod void testOpportunity(){
        try{
        Id AccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.RecordTypeId = AccRecId;
        insert acc;
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];
        Opportunity Opp = new Opportunity();
        Opp.Name = 'Donation Test1';
        Opp.AccountId = acc.Id;
        Opp.CloseDate = date.today();
        Opp.StageName = 'Posted';
        Opp.RecordTypeId = OppRecId;
        Opp.Amount = 100;
        Opp.c4g_Appeal_Code__c = appCode.Id;
            Opp.GL_Account__c = GLCode.Id;
        insert Opp;
        } catch(Exception ex){
            system.debug(ex.getStackTraceString() + ex.getMessage());
        }
    }
    
    public static testMethod void testOpportunityWire(){
        try{
        Id AccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.RecordTypeId = AccRecId;
        insert acc;
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];
        Opportunity Opp = new Opportunity();
        Opp.Name = 'Donation Test1';
        Opp.AccountId = acc.Id;
        Opp.CloseDate = date.today();
        Opp.StageName = 'Posted';
        Opp.RecordTypeId = OppRecId;
        Opp.Amount = 100;
        Opp.c4g_Appeal_Code__c = appCode.Id;
            Opp.GL_Account__c = GLCode.Id;
        Opp.c4g_Payment_Method__c = 'Wire';
        insert Opp;
        } catch(Exception ex){
            system.debug(ex.getStackTraceString() + ex.getMessage());
        }
    }
    
    public static testMethod void testOpportunityCC(){
        try{
        Id AccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.RecordTypeId = AccRecId;
        insert acc;
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];
        Opportunity Opp = new Opportunity();
        Opp.Name = 'Donation Test1';
        Opp.AccountId = acc.Id;
        Opp.CloseDate = date.today();
        Opp.StageName = 'Posted';
        Opp.RecordTypeId = OppRecId;
        Opp.Amount = 100;
        Opp.c4g_Appeal_Code__c = appCode.Id;
            Opp.GL_Account__c = GLCode.Id;
        Opp.c4g_Payment_Method__c = 'CC';
        insert Opp;
        } catch(Exception ex){
            system.debug(ex.getStackTraceString() + ex.getMessage());
        }
    }
    
    public static testMethod void testOpportunityCheck(){
        try{
        Id AccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.RecordTypeId = AccRecId;
        insert acc;
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];
        Opportunity Opp = new Opportunity();
        Opp.Name = 'Donation Test1';
        Opp.AccountId = acc.Id;
        Opp.CloseDate = date.today();
        Opp.StageName = 'Posted';
        Opp.RecordTypeId = OppRecId;
        Opp.Amount = 100;
        Opp.c4g_Appeal_Code__c = appCode.Id;
            Opp.GL_Account__c = GLCode.Id;
        Opp.c4g_Payment_Method__c = 'Check';
            Opp.c4g_Check_Number__c = '123';
        insert Opp;
        } catch(Exception ex){
            system.debug(ex.getStackTraceString() + ex.getMessage());
        }
    }
    
    public static testMethod void testOpportunity1(){
        Id AccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.RecordTypeId = AccRecId;
        insert acc;
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];
        Opportunity Opp = new Opportunity();
        Opp.AccountId = acc.Id;
        Opp.Name = 'Donation Test';
        Opp.CloseDate = date.today();
        Opp.StageName = 'Closed Won';
        Opp.RecordTypeId = OppRecId;
        Opp.Amount = 100;
        Opp.c4g_Appeal_Code__c = appCode.Id;
            Opp.GL_Account__c = GLCode.Id;
        insert Opp;
        Opp.ddrive__Donation_Payment_Status_Text__c = 'Refunded';
        Opp.ddrive__Refund_Amount__c = 100;
        Opp.ddrive__Donation_Refund_Date__c = date.today();
        Update Opp;
        
    }
    
    public static testMethod void testOpportunityRefund(){
        Id AccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.RecordTypeId = AccRecId;
        insert acc;
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];
        Opportunity Opp = new Opportunity();
        Opp.AccountId = acc.Id;
        Opp.Name = 'Donation Test';
        Opp.CloseDate = date.today();
        Opp.StageName = 'Closed Won';
        Opp.RecordTypeId = OppRecId;
        Opp.Amount = 100;
        Opp.c4g_Appeal_Code__c = appCode.Id;
            Opp.GL_Account__c = GLCode.Id;
        Opp.ddrive__Donation_Payment_Status_Text__c = 'Refunded';
        Opp.ddrive__Refund_Amount__c = 100;
        Opp.ddrive__Donation_Refund_Date__c = date.today();
        Insert Opp;
        
    }
    
    public static testMethod void testOpportunity2(){
        Id AccRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.RecordTypeId = AccRecId;
        insert acc;
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Lastname';
        con.AccountId = acc.Id;
        con.Email = 'test+1@mail.com';
        insert con;
        Id OppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Pledge').getRecordTypeId();
        Appeal_Code__c appCode = [Select Id From Appeal_Code__c Limit 1];
        OrderApi__GL_Account__c GLCode = [Select Id From OrderApi__GL_Account__c where Distribution_Code__c=true LImit 1];
        Opportunity Opp = new Opportunity();
        Opp.AccountId = acc.Id;
        Opp.Name = 'Donation Test';
        Opp.npsp__Primary_Contact__c = con.Id;
        Opp.CloseDate = date.today();
        Opp.StageName = 'Pledged';
        Opp.RecordTypeId = OppRecId;
        Opp.c4g_Pledge_Type__c = 'Organization';
        Opp.Amount = 100;
        Opp.c4g_Appeal_Code__c = appCode.Id;
            Opp.GL_Account__c = GLCode.Id;
        Opp.c4g_Payment_Method__c = 'Cash';
        insert Opp;
    }
    
    public static testmethod void customExceptionTest(){
        CustomException ex= new CustomException('Refund Date and Refund Amount are required!');
    }
}