src/objects/Appeal_Code__c.object
<CustomObject>
    <description>Stores all appeal codes used by AACR Foundation staff</description>
    <label>Appeal Code</label>
    <nameField>
        <label>Appeal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appeal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <description>Formula field reflecting either legacy iMIS ID or new Salesforce ID depending upon when record was created.</description>
        <formula>IF(ISBLANK( iMIS_ID__c ), Salesforce_ID__c, iMIS_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dimension_Tags__mdt.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>BR_Event__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                    <default>true</default>
                    <label>Public</label>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dimension Tag</label>
    <pluralLabel>Dimension Tags</pluralLabel>
</CustomObject>

src/objects/OrderApi__GL_Account__c.object
<CustomObject>
    <description>GL Accounting codes used for linking debits and credits with the appropriate codes.</description>
    <fields>
        <fullName>Distribution_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a Distribution code?</description>
        <inlineHelpText>Is this a Distribution code?</inlineHelpText>
        <label>Distribution Code</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DimensionTagBulkImportControllerTest.cls
/**
 * Created by afaf.awad on 7/7/2021.
 */

@IsTest
private class DimensionTagBulkImportControllerTest {
    @TestSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        List<Contact> contacts = new List<Contact>();
        for(Integer i=0; i <5; i++) {
            Contact con = TestDataFactory.buildContact(acc.Id);
            con.LastName = con.LastName+i;
            con.Email = 'testemail' + i + '@yopmail.com';
            contacts.add(con);
        }
        insert contacts;

        Appeal_Code__c appealCode = new Appeal_Code__c(Name = 'Test Appeal Code');
        insert appealCode;

        OrderApi__GL_Account__c glAccount = TestDataFactory.buildGLAccount();
        glAccount.Distribution_Code__c = true;
        insert glAccount;

        Opportunity opp = TestDataFactory.buildOpportunity(acc.Id, contacts[0].Id, appealCode.Id, glAccount.Id);
        insert opp;

    }

    @IsTest
    public static void test_validateData(){
        List<Contact> contacts = [Select Id, AACR_ID__c FROM Contact];

        String sampleFile = 'Id, AACRID';
        for(Contact contact: contacts) {
            sampleFile += '\n' + contact.Id + ',' + contact.AACR_ID__c ;
        }

        List<String> fields = new List<String>();
        fields.add('Id');
        fields.add('AACRID');

        DimensionTagBulkImportController.fileData fileData = DimensionTagBulkImportController.validateData(sampleFile, fields,'Id');
        System.assertEquals(true, fileData.validated);

        sampleFile += '\n  , 123456';
        DimensionTagBulkImportController.fileData fileDataBlank = DimensionTagBulkImportController.validateData(sampleFile, fields,'Id');
        System.assertEquals(false, fileDataBlank.validated);

        sampleFile += '\n NOT AN ID , 123456';
        DimensionTagBulkImportController.fileData fileDataFalseId = DimensionTagBulkImportController.validateData(sampleFile, fields,'Id');
        System.assertEquals(false, fileDataFalseId.validated);

    }

    @IsTest
    public static void test_createTagRecords(){

        Dimension_Tags__mdt dimTag = [SELECT Id FROM Dimension_Tags__mdt WHERE Object__c = 'Contact' AND Visibility__c = 'Public' LIMIT 1];
        List<Contact> contacts = [SELECT Id FROM Contact];

        List<String> idString = new List<String>();
        for(Contact con: contacts){
            idString.add(con.Id);
        }

        DimensionTagBulkImportController.TagImportResults results = DimensionTagBulkImportController.createTagRecords(JSON.serialize(idString), dimTag.Id);
        System.assertEquals(5, results.importResults.size());
    }


//    @IsTest
//    public static void test_createTagRecords_Error(){
//
//        Dimension_Tags__mdt dimTag = [SELECT Id FROM Dimension_Tags__mdt WHERE Object__c = 'Contact' AND Visibility__c = 'Public' LIMIT 1];
//        List<Appeal_Code__c> appealCodes = [SELECT Id FROM Appeal_Code__c];
//
//        List<String> idString = new List<String>();
//        for(Appeal_Code__c ac: appealCodes){
//            idString.add(ac.Id);
//        }
//
//        DimensionTagBulkImportController.TagImportResults results = DimensionTagBulkImportController.createTagRecords(JSON.serialize(idString), dimTag.Id);
//        System.assertEquals(false, results.success);
//    }
}