src/objects/Appeal_Code__c.object
<CustomObject>
    <description>Stores all appeal codes used by AACR Foundation staff</description>
    <label>Appeal Code</label>
    <nameField>
        <label>Appeal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appeal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dimension_Tags__mdt.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>BR_Event__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                    <default>true</default>
                    <label>Public</label>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dimension Tag</label>
    <pluralLabel>Dimension Tags</pluralLabel>
</CustomObject>

src/objects/Opportunity_Dimension_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Dim_Tag_Id__c</fullName>
        <label>Dim Tag Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Visibility</valueSetName>
        </valueSet>
    </fields>
    <label>Opportunity Tag</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Opportunity Tag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__GL_Account__c.object
<CustomObject>
    <description>GL Accounting codes used for linking debits and credits with the appropriate codes.</description>
    <fields>
        <fullName>Distribution_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a Distribution code?</description>
        <inlineHelpText>Is this a Distribution code?</inlineHelpText>
        <label>Distribution Code</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExportHelper_OpportunityTest.cls
/**
 * Created by afaf.awad on 7/7/2021.
 */

@IsTest
private class ExportHelper_OpportunityTest {

    @TestSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        Appeal_Code__c appealCode = new Appeal_Code__c(Name = 'Test Appeal Code');
        insert appealCode;

        OrderApi__GL_Account__c glAccount = TestDataFactory.buildGLAccount();
        glAccount.Distribution_Code__c = true;
        insert glAccount;

        Opportunity opp = TestDataFactory.buildOpportunity(acc.Id, con.Id, appealCode.Id, glAccount.Id);
        insert opp;

        Dimension_Tags__mdt dmt = [SELECT Id FROM Dimension_Tags__mdt WHERE Object__c = 'Contact' AND Visibility__c = 'Public' LIMIT 1];
        SObject publicObj = DimensionTagHelper.createTagRecord(dmt.Id,  opp.Id);
        insert publicObj;

    }

    @IsTest
    public static void test_exportTagsOpportunity() {

        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Opportunity_Dimension_Tag__c odt = [SELECT Id, Dim_Tag_Id__c FROM Opportunity_Dimension_Tag__c LIMIT 1];

        ExportHelper_Opportunity.OpportunityExport oe = ExportHelper_Opportunity.queryOpportunities(odt.Dim_Tag_Id__c);
        System.assertEquals(1, oe.Opportunities.size());
    }
}