src/objects/Appeal_Code__c.object
<CustomObject>
    <description>Stores all appeal codes used by AACR Foundation staff</description>
    <fields>
        <fullName>c4g_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Appeal Code</label>
    <nameField>
        <label>Appeal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appeal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Do_Not_Create_Sales_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Prevent auto-creation of Sales Order</description>
        <inlineHelpText>Prevent auto-creation of Sales Order</inlineHelpText>
        <label>Do Not Create Sales Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OrderApi__GL_Account__c.Distribution_Code__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__GL_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c4g_Appeal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Denotes the appeal code that relates to the specific opportunity</description>
        <label>Appeal Code</label>
        <referenceTo>Appeal_Code__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>c4g_Check_Number__c</fullName>
        <label>Check Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>c4g_Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>Wire</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>c4g_Pledge_Type__c</fullName>
        <description>Denotes whether the pledge is made by an organization or an individual. Fonteva will transform the pledge data based on the value in this field. Organization pledges are reflected in GL immediately while individual pledges are not reflected until payment is received.</description>
        <inlineHelpText>Is this pledge from an individual or an organization?</inlineHelpText>
        <label>Pledge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Organization</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npsp__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</description>
        <inlineHelpText>The primary contact for this opportunity. The primary contact role is kept in sync with this field. For individual donations, this denotes attribution for this opportunity.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donation Received</description>
        <label>Donation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderApi__Business_Group__c.object
<CustomObject>
    <description>Separate groups or business entities to facilitate clear reporting on business lines and/or entities.</description>
    <fields>
        <fullName>OrderApi__Description__c</fullName>
        <description>Briefly describe the ledger as you would like to see it on a report. (72 Chars. or less)</description>
        <inlineHelpText>Briefly describe the ledger as you would like to see it on a report. (72 Chars. or less)</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderApi__GL_Account__c.object
<CustomObject>
    <description>GL Accounting codes used for linking debits and credits with the appropriate codes.</description>
    <fields>
        <fullName>Distribution_GL_Mapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The GL Code that this distribution maps to</description>
        <inlineHelpText>The GL Code that this distribution maps to</inlineHelpText>
        <label>Distribution GL Mapping</label>
        <referenceTo>OrderApi__GL_Account__c</referenceTo>
        <relationshipLabel>GL Accounts</relationshipLabel>
        <relationshipName>GL_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Business_Group__c</fullName>
        <description>**Required** Master-Detail Relationship to Business Group.</description>
        <inlineHelpText>**Required** Master-Detail Relationship to Business Group.</inlineHelpText>
        <label>Business Group</label>
        <referenceTo>OrderApi__Business_Group__c</referenceTo>
        <relationshipLabel>Chart of Accounts</relationshipLabel>
        <relationshipName>GL_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Business_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</description>
        <inlineHelpText>Items can be related to Business Groups to separate business lines and/or legal entities on transactional (sales) and financial reports.</inlineHelpText>
        <label>Business Group</label>
        <referenceTo>OrderApi__Business_Group__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Description__c</fullName>
        <description>Product description.</description>
        <inlineHelpText>Product description.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>OrderApi__Business_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Group</label>
        <referenceTo>OrderApi__Business_Group__c</referenceTo>
        <relationshipLabel>Item Classes</relationshipLabel>
        <relationshipName>Item_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt__c.object
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <fields>
        <fullName>OrderApi__Business_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override/Required** Link to the related Business Group auto-populates if not specified on record creation based upon the user&apos;s &quot;Default Business Group&quot; setting on the custom settings object.</description>
        <inlineHelpText>**System Calculated/Override/Required** Link to the related Business Group auto-populates if not specified on record creation based upon the user&apos;s &quot;Default Business Group&quot; setting on the custom settings object.</inlineHelpText>
        <label>Business Group</label>
        <referenceTo>OrderApi__Business_Group__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt_Line__c.object
<CustomObject>
    <description>Receipt Lines apply cash related to either refunds or payments to Invoices or Items.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**Required** Link to related Item.</description>
        <inlineHelpText>**Required** Link to related Item.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Description__c</fullName>
        <description>Internal facing descriptions will not appear and should not be included in customer-facing communications.</description>
        <inlineHelpText>Internal facing descriptions will not appear and should not be included in customer-facing communications.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateSalesOrderHandler.cls
/**
 * Created by afaf.awad on 1/7/2019.
 */

public with sharing class CreateSalesOrderHandler {

    public static Boolean isFirstTime = true;

    public static void CreateSalesOrder(Opportunity opportunity) {

        System.debug('Starting SalesOrderHandler...');
        //Requery Opportunity Record to grab Lookup Values for GL and Appeal Code.
        Opportunity opp = [SELECT Id, AccountId, npsp__Primary_Contact__c, CloseDate, StageName, c4g_Pledge_Type__c, GL_Account__c,
                            Amount, c4g_Payment_Method__c, c4g_Check_Number__c,GL_Account__r.Distribution_GL_Mapping__c, c4g_Appeal_Code__c,
                            Do_Not_Create_Sales_Order__c,c4g_Appeal_Code__r.c4g_Description__c
                            FROM Opportunity WHERE Id =: opportunity.Id];

        List<OrderApi__Item__c> donationItem = [Select Id, Name, OrderApi__Item_Class__c, OrderApi__Description__c, OrderApi__Business_Group__c From OrderApi__Item__c WHERE Name = '*General Donation'];
        String businessGroup = donationItem[0].OrderApi__Business_Group__c;

        //Create New open Sales Order
        OrderApi__Sales_Order__c newSO = new OrderApi__Sales_Order__c();
        newSO.OrderApi__Account__c = opp.AccountId;
        newSO.OrderApi__Contact__c = opp.npsp__Primary_Contact__c;
        newSO.OrderApi__Date__c = opp.CloseDate;
        newSO.OrderApi__Status__c = 'Open';
        newSO.OrderApi__Business_Group__c = businessGroup;
        newSO.Opportunity__c = opp.Id;
        //Posting entity is receipt or invoice
        if ( opp.stageName == 'Closed Won' || opp.stageName == 'Awarded' || opp.stageName == 'Posted' ) {
            newSO.OrderApi__Posting_Entity__c = 'Receipt';
        } else if ( opp.stageName == 'Pledged' && opp.c4g_Pledge_Type__c == 'Organization' ) {
            newSO.OrderApi__Posting_Entity__c = 'Invoice';
        }

        try {
            insert newSO;
        } catch (Exception e) {
            System.debug('Cannot insert Sales Order:: ' + e.getMessage());
        }

//        Create Sales Order Line
        OrderApi__Sales_Order_Line__c newSOL = new OrderApi__Sales_Order_Line__c();
        newSOL.OrderApi__Sales_Order__c = newSO.Id;
        newSOL.OrderApi__Line_Description__c = opp.c4g_Appeal_Code__r.c4g_Description__c;
        newSOL.OrderApi__Quantity__c = 1;
        newSOL.OrderApi__Sale_Price__c = opp.Amount;
        newSOL.OrderApi__Account__c = opp.AccountId;
        newSOL.OrderApi__Contact__c = opp.npsp__Primary_Contact__c;
        newSOL.OrderApi__GL_Account__c = opp.GL_Account__r.Distribution_GL_Mapping__c;
        newSOL.OrderApi__Item__c = donationItem[0].Id;
        newSOL.OrderApi__Item_Class__c = donationItem[0].OrderApi__Item_Class__c;
        newSOL.OrderApi__Business_Group__c = businessGroup;
        newSOL.OrderApi__Price_Override__c = true;
        newSOL.Opportunity__c = opp.Id;

        try {
            System.debug('SalesOrderLine: ' + newSOL);
            insert newSOL;
        } catch (Exception e) {
            System.debug('Cannot insert Sales Order Line:: ' + e.getMessage());
        }

        System.debug('SalesOrderLine AFTER insert: ' + newSOL);
        //Update SalesOrder to "Closed" after SalesOrderLines are Created
        newSO.OrderApi__Status__c = 'Closed';
        try {
            update newSO;
        } catch (Exception e) {
            System.debug('Cannot Close Sales Order:: ' + e.getMessage());
        }

        //Update SalesOrder to "Posted" for Pledged Stages to trigger creation of an invoice.
        if(opp.stageName=='Pledged') {
            newSO.OrderApi__Posting_Status__c ='Posted';
        }
        update newSO;

        System.debug('SalesOrderLine AFTER SO Update: ' + newSOL);


        //For closed Opportunities, create Receipt and ReceiptLines for closed SalesOrder
        if ( opp.stageName == 'Closed Won' || opp.stageName == 'Awarded' || opp.stageName == 'Posted' ) {

            //Create Receipt
            OrderApi__Receipt__c receipt = new OrderApi__Receipt__c();
            receipt.OrderApi__Account__c = opp.AccountId;
            receipt.OrderApi__Contact__c = opp.npsp__Primary_Contact__c;
            receipt.OrderApi__Date__c = opp.CloseDate;
            receipt.OrderApi__Sales_Order__c = newSO.Id;
            receipt.OrderApi__Business_Group__c = businessGroup;
            receipt.OrderApi__Total__c = newSO.OrderApi__Total__c;
            receipt.OrderApi__Type__c = 'Payment';
            receipt.Is_Contribution__c = true;
            if ( opp.c4g_Payment_Method__c == null || opp.c4g_Payment_Method__c == 'CC' ) {
                receipt.OrderApi__Payment_Type__c = 'Credit Card';
            }
            receipt.OrderApi__Payment_Type__c = opp.c4g_Payment_Method__c;
            if ( opp.c4g_Payment_Method__c == 'Check' ) {
                receipt.OrderApi__Reference_Number__c = opp.c4g_Check_Number__c;
            }
            if ( opp.c4g_Payment_Method__c == 'Wire' ) {
                receipt.OrderApi__Payment_Type__c = 'EFT';
            }
            insert receipt;

            //Create ReceiptLines
            OrderApi__Receipt_Line__c rline = new OrderApi__Receipt_Line__c();
            rline.OrderApi__Receipt__c = receipt.Id;
            rline.OrderApi__Quantity__c = newsol.OrderApi__Quantity__c;
            rline.OrderApi__Sale_Price__c = newsol.OrderApi__Sale_Price__c;
            rline.OrderApi__Line_Description__c = newsol.OrderApi__Line_Description__c;
            rline.OrderApi__Contact__c = newsol.OrderApi__Contact__c;
            rline.OrderApi__Business_Group__c = newsol.OrderApi__Business_Group__c;
            rline.OrderApi__Item__c = newsol.OrderApi__Item__c;
            rline.OrderApi__GL_Account__c = newsol.OrderApi__GL_Account__c;
            rline.OrderApi__Total__c = newsol.OrderApi__Quantity__c * newsol.OrderApi__Sale_Price__c;

            //Update Receipt to "Posted" after ReceiptLines are created
            insert rline;
            receipt.OrderApi__Is_Posted__c = true;
            receipt.OrderApi__Posted_Date__c = opp.CloseDate;
            receipt.OrderApi__Total__c = opp.Amount;
            update receipt;
        }

        //UPDATING OPPORTUNITY TO PREVENT RE-TRIGGER
        opp.Do_Not_Create_Sales_Order__c = true;
        try {
            update opp;
        }catch(Exception e){
            System.debug('Cannot update Opportunity after creation of Sales Order: ' + e.getMessage());
        }

    }
}