src/objects/Bad_Address_Audit__c.object
<CustomObject>
    <description>Tracks marked addresses from Bad Address</description>
    <fields>
        <fullName>Return_Sender_Reason__c</fullName>
        <label>Return to Sender Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Address Unknown</fullName>
                </value>
                <value>
                    <fullName>Attempted Not Known (or Unknown)</fullName>
                </value>
                <value>
                    <fullName>Insufficient Address</fullName>
                </value>
                <value>
                    <fullName>Moved Left No Address</fullName>
                </value>
                <value>
                    <fullName>No Longer At Address</fullName>
                </value>
                <value>
                    <fullName>No Mail Receptacle</fullName>
                </value>
                <value>
                    <fullName>No Receptacle</fullName>
                </value>
                <value>
                    <fullName>No Such Number</fullName>
                </value>
                <value>
                    <fullName>No Such Street</fullName>
                </value>
                <value>
                    <fullName>Not At This Address</fullName>
                </value>
                <value>
                    <fullName>Not Deliverable as Addressed</fullName>
                </value>
                <value>
                    <fullName>Not In Directory Unable To Forward</fullName>
                </value>
                <value>
                    <fullName>Not Known</fullName>
                </value>
                <value>
                    <fullName>Refused</fullName>
                </value>
                <value>
                    <fullName>Return To Sender</fullName>
                </value>
                <value>
                    <fullName>Unable To Forward</fullName>
                </value>
                <value>
                    <fullName>Unclaimed</fullName>
                </value>
                <value>
                    <fullName>Undeliverable</fullName>
                </value>
                <value>
                    <fullName>Undeliverable as Addressed</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Unusable</fullName>
                </value>
                <value>
                    <fullName>Vacant</fullName>
                </value>
                <value>
                    <fullName>Other (please enter into Other Return)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Returned Address Audit</label>
    <nameField>
        <displayFormat>CCA-{0000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returned Address Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Known_Address__c.object
<CustomObject>
    <description>Known Addresses allows Contacts and Accounts to have multiple related address records.</description>
    <fields>
        <fullName>Bad_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Returned Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__City__c</fullName>
        <description>Address City</description>
        <inlineHelpText>Address City</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the known address to a contact.</description>
        <inlineHelpText>Relates the known address to a contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Known Addresses</relationshipLabel>
        <relationshipName>Known_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Country__c</fullName>
        <description>Address Country</description>
        <inlineHelpText>Address Country</inlineHelpText>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Postal_Code__c</fullName>
        <description>Address Zip/Postal Code</description>
        <inlineHelpText>Address Zip/Postal Code</inlineHelpText>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Province__c</fullName>
        <description>Address State</description>
        <inlineHelpText>Address State</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Street__c</fullName>
        <description>Address Street</description>
        <inlineHelpText>Address Street</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Known Address</label>
    <nameField>
        <displayFormat>KA-{000000000}</displayFormat>
        <label>Known Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BadAddressController.cls
/**
 * Created by afaf.awad on 10/27/2020.
 */

public without sharing class BadAddressController {


    @AuraEnabled
    public static ContactWrapper getContactInfo(String contactId) {

        List<Contact> contacts = [SELECT Id, Name, FirstName, LastName FROM Contact WHERE Id = :contactId];

        ContactWrapper conWrap = new ContactWrapper();
        conWrap.duplicate = false;
        conWrap.contact = contacts[0];
        conWrap.reasonList = ECRMUtils.getPicklistValues('Bad_Address_Audit__c','Return_Sender_Reason__c');
        conWrap.knownAddresses = [SELECT OrderApi__Street__c, OrderApi__City__c, OrderApi__Province__c, OrderApi__Country__c, OrderApi__Postal_Code__c,
                                            Type__c, Bad_Address__c, Id
                                    FROM OrderApi__Known_Address__c WHERE OrderApi__Contact__c =: contacts[0].Id];

        List<Datacloud.FindDuplicatesResult> results = Datacloud.FindDuplicates.findDuplicates(contacts);

        for (Datacloud.FindDuplicatesResult dupeResult : results) {
            for (Datacloud.DuplicateResult dupeRes : dupeResult.getDuplicateResults()) {
                for (Datacloud.MatchResult matchRes : dupeRes.getMatchResults()) {
                    for (Datacloud.MatchRecord matchRec : matchRes.getMatchRecords()) {
                        System.debug('matchRecord: ' + (string) matchRec.getRecord().get('id'));
                        conWrap.duplicate = true;
                    }
                }
            }
        }
        return conWrap;
    }

    @AuraEnabled
    public static Boolean saveBadAddress(String[] auditString, String kaIdString) {
        List<Bad_Address_Audit__c> auditList = new List<Bad_Address_Audit__c>();
            for (String audit : auditString) {
                Bad_Address_Audit__c a = (Bad_Address_Audit__c) JSON.deserialize(audit, Bad_Address_Audit__c.class);
                auditList.add(a);
            }

            //insert bad address audit
            Database.DMLOptions dmlAudit = new Database.DMLOptions();
            List<Database.SaveResult> insertResults = Database.insert(auditList, dmlAudit);
            for (Database.SaveResult sr : insertResults) {
                if ( !sr.isSuccess() ) {
                    for (Database.Error error : sr.getErrors()) {
                        System.debug('Error saving Bad Addresses:: ' + error.message);
                        return false;
                    }
                }
            }
        
        try {
            //update known addresses
            List<String> kaIds = (List<String>) JSON.deserialize(kaIdString, List<String>.class);
            List<OrderApi__Known_Address__c> knownAddresses = new List<OrderApi__Known_Address__c>();
            for(String kaId: kaIds){
                OrderApi__Known_Address__c ka = new OrderApi__Known_Address__c(Id = kaId, Bad_Address__c = true);
                knownAddresses.add(ka);
            }

            System.debug('Known Addresses to Update : ' + knownAddresses);

                update knownAddresses;
                return true;
            }catch(Exception e){
                System.debug('Cannot update Known Address: ' + e.getMessage());
                return false;
            }
    }

    public class ContactWrapper{
        @AuraEnabled
        public Contact contact;
        @AuraEnabled
        public Boolean duplicate;
        @AuraEnabled
        public List<String> reasonList;
        @AuraEnabled
        public List<OrderApi__Known_Address__c> knownAddresses;
    }
}