src/objects/Badge_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Badge Setting</label>
    <nameField>
        <displayFormat>Badge-{0000000}</displayFormat>
        <label>Badge Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactBadgeControllerTest.cls
@isTest 
public class ContactBadgeControllerTest {
    static ContactBadgeController ext;
    static Contact a;
    static Contact aa;
    private static void init(){
    
	PageReference pageRef = Page.ContactBadges;
	Test.setCurrentPage(pageRef); 
        a = new Contact();
        a.LastName = 'Test';
        a.HasOptedOutOfEmail = TRUE;
        insert a;
        
        aa = new Contact();
        aa.LastName = 'Test2';
        insert aa;
        
        Badge_Setting__c b = new Badge_Setting__c();
        b.Object__c = 'Contact';
        b.Criteria__c = 'HasOptedOutOfEmail = TRUE';
        b.Active__c = TRUE;
        b.Sort_Order__c = 1;
        insert b;

	pageRef.getParameters().put('id', a.id);
        ApexPages.StandardController act = new ApexPages.StandardController(a);
        ext = new ContactBadgeController(act);
    }
    static testMethod void testBadges(){
        init();
        Test.startTest();
        ext.con = a;
        ext.getBadges();
		ext.con = aa;
        ext.getBadges();
        Test.stopTest();
    }
}