src/objects/Badge_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>This will appear when a user hovers their mouse over the badge.</inlineHelpText>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <inlineHelpText>Use static resource</inlineHelpText>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Badge Setting</label>
    <nameField>
        <displayFormat>Badge-{0000000}</displayFormat>
        <label>Badge Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactBadgeController.cls
public class ContactBadgeController {
   //set up the extension
    public Contact con;
    public ContactBadgeController(ApexPages.StandardController stdController) {
        this.con = (Contact)stdController.getRecord();
    }
    
    //get list of active badges for contacts
    public List<Badge_Setting__c> getBadges() {
         Badge_Setting__c[] conbadges = [SELECT Id, Object__c, Criteria__c, Sort_Order__c, Image__c, Description__c
                                     FROM Badge_Setting__c
                                     WHERE Active__c = TRUE AND Object__c = 'Contact' ORDER BY Sort_Order__c ASC ];
    
    //set up list for badges for this contact
    List<Badge_Setting__c> activebadges = new List<Badge_Setting__c>();    
    
    //loop through badges list to query contacts that meet criteria and assign them to a list
    for(Badge_Setting__c b : conbadges) {
        string contactid = con.id;
        string query = 'SELECT Id FROM Contact WHERE Id = :contactid AND ' + b.Criteria__c;
        System.debug('>>>>>>>>> Query: ' + query);
        List<sObject> conlist = Database.query(query);
        
    //check if current contact is included in list of contacts meeting the criteria for badge     
        for(sObject thiscontact : conlist) {
            if(thiscontact.id == con.id){
                activebadges.add(b);
            } 
        }   

            }
    return activebadges;
    }
}