src/objects/Badge_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Badge Setting</label>
    <nameField>
        <displayFormat>Badge-{0000000}</displayFormat>
        <label>Badge Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountBadgeControllerTest.cls
@isTest 
public class AccountBadgeControllerTest {
    static AccountBadgeController ext;
    static Account a;
    static Account aa;
    private static void init(){
    
	PageReference pageRef = Page.Badges;
	Test.setCurrentPage(pageRef); 
        a = new Account();
        a.Name = 'Test';
        a.AnnualRevenue = 100;
        insert a;
        
        aa = new Account();
        aa.Name = 'Test2';
        insert aa;
        
        Badge_Setting__c b = new Badge_Setting__c();
        b.Object__c = 'Account';
        b.Criteria__c = 'AnnualRevenue > 5';
        b.Active__c = TRUE;
        b.Sort_Order__c = 1;
        insert b;

	pageRef.getParameters().put('id', a.id);
        ApexPages.StandardController act = new ApexPages.StandardController(a);
        ext = new AccountBadgeController(act);
    }
    static testMethod void testBadges(){
        init();
        Test.startTest();
        ext.acct = a;
        ext.getBadges();
		ext.acct = aa;
        ext.getBadges();
        Test.stopTest();
    }
}