src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Main_Image_Filename__c</fullName>
        <label>Main Image Filename</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__GL_Account__c.object
<CustomObject>
    <description>GL Accounting codes used for linking debits and credits with the appropriate codes.</description>
    <fields>
        <fullName>Distribution_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a Distribution code?</description>
        <inlineHelpText>Is this a Distribution code?</inlineHelpText>
        <label>Distribution Code</label>
        <type>Checkbox</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price__c</fullName>
        <description>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</description>
        <inlineHelpText>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</inlineHelpText>
        <label>Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt__c.object
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</description>
        <inlineHelpText>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Default unchecked. When checked, the receipt will create a new cash transaction (journal entry) and the posted date will populate with the value of today&apos;s date.</description>
        <inlineHelpText>Default unchecked. When checked, the receipts will create a new cash transaction (journal entry) and the posted date will populate with the value of today&apos;s date.</inlineHelpText>
        <label>Is Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to related Sales Order.</description>
        <inlineHelpText>**System Calculated/Override** Link to related Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>**System Calculated/Override** Checked when the Sales Order is closed. Sales Orders close automatically when paid in full by the customer, when a contract expires, or when a contract/recurring Sales Order is cancelled.</description>
        <inlineHelpText>**System Calculated/Override** Checked when the Sales Order is closed. Sales Orders close automatically when paid in full by the customer, when a contract expires, or when a contract/recurring Sales Order is cancelled.</inlineHelpText>
        <label>Is Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked all Invoices related to the Sales Order will post an receivable transaction to the GL.</description>
        <inlineHelpText>When checked all Invoices related to the Sales Order will post an receivable transaction to the GL.</inlineHelpText>
        <label>Is Posted</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Required/Override** Link to the related GL Account.</description>
        <inlineHelpText>**System Calculated/Required/Override** Link to the related GL Account.</inlineHelpText>
        <label>GL Account</label>
        <referenceTo>OrderApi__GL_Account__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Posted__c</fullName>
        <description>When checked all Invoices related to the Sales Order will post an receivable transaction to the GL.</description>
        <formula>OrderApi__Sales_Order__r.OrderApi__Is_Posted__c</formula>
        <inlineHelpText>When checked all Invoices related to the Sales Order will post an receivable transaction to the GL.</inlineHelpText>
        <label>Is Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Virtual_Event_Details__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Virtual Event Details</relationshipLabel>
        <relationshipName>Virtual_Event_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Virtual Event Details</label>
    <nameField>
        <label>Virtual Event Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LiveTicketConfirmationControllerTest.cls
/**
 * Created by lauren.lezberg on 10/6/2020.
 */

@IsTest
private class LiveTicketConfirmationControllerTest {
    @TestSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        BR_Event__c evt = LiveTestDataFactory.buildEvent('Test Event', false, false);
        insert evt;

        String fileId = CustomFileUploadController.saveChunk(evt.Id,'Test File', 'THIS IS THE BODY', null,'', 'Main Image');
        System.assertNotEquals(null, fileId);
        ContentVersion cv = [SELECT ContentDocumentId FROM ContentVersion WHERE Id=:fileId];
        JP_EventOptionsController.setImageToPublic(cv.ContentDocumentId, evt.Id, 'Main');

        evt.Main_Image_Filename__c = 'Test File';
        update evt;

        OrderApi__Item_Class__c itemClass = TestDataFactory.buildItemClass('Live Event Tickets');
        insert itemClass;

        OrderApi__Item__c ticketItem = TestDataFactory.buildItem(itemClass.Id, 'Test Event Ticket');
        ticketItem.AC_Event__c = evt.Id;
        ticketItem.OrderApi__Price__c = 0.0;
        insert ticketItem;


        //Appeal codes for Opportunity
        Appeal_Code__c appealCode = new Appeal_Code__c(Name = 'Test Appeal Code');
        insert appealCode;

        OrderApi__GL_Account__c glAccount = TestDataFactory.buildGLAccount();
        glAccount.Distribution_Code__c = true;
        insert glAccount;

    }


    @IsTest
    static void testConstructor() {
        Account acc = [SELECT Id FROM ACcount WHERE Name='Test Account'];
        Contact con = [SELECT Id FROM Contact WHERE AccountId=:acc.Id];

        OrderApi__Item_Class__c itemClass = [SELECT Id FROM OrderApi__Item_Class__c WHERE Name='Live Event Tickets'];
        OrderApi__Item__c ticketItem = [SELECT Id FROM OrderApi__Item__c WHERE Name='Test Event Ticket'];

//        OrderApi__Sales_Order__c so = [SELECT Id, OrderApi__Contact__c FROM OrderApi__Sales_Order__c];

        OrderApi__Sales_Order__c SO = TestDataFactory.buildOpenSalesOrder(acc.Id, con.Id);
        insert SO;

        OrderApi__Sales_Order_Line__c line = TestDataFactory.buildSOLine(SO.Id, ticketItem.Id, itemClass.Id);
        insert line;

        so.OrderApi__Is_Closed__c=true;
        so.OrderApi__Is_Posted__c = true;
        update so;

        OrderApi__Receipt__c rec = new OrderApi__Receipt__c(
                OrderApi__Contact__c = so.OrderApi__Contact__c,
                OrderApi__Entity__c = 'Contact',
                OrderApi__Is_Posted__c = true,
                OrderApi__Sales_Order__c = so.Id
        );
        insert rec;


        BR_Event__c evt = [SELECT Id FROM BR_Event__c WHERE Name='Test Event'];


        PageReference pageRef = Page.LiveTicketConfirmation;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('salesOrder',so.id);
        ApexPages.currentPage().getParameters().put('receipt',rec.Id);

        Test.startTest();

        LiveTicketConfirmationController ctrl = new LiveTicketConfirmationController();
        System.assertEquals(ctrl.receiptId, rec.Id);
        System.assertEquals(ctrl.evt.Id, evt.Id);

        Test.stopTest();

    }

    @IsTest
    static void testConstructor2() {
        Account acc = [SELECT Id FROM ACcount WHERE Name='Test Account'];
        Contact con = [SELECT Id FROM Contact WHERE AccountId=:acc.Id];

        OrderApi__Item_Class__c iClass = [SELECT Id FROM OrderApi__Item_Class__c WHERE Name='Live Event Tickets'];

        BR_Event__c evt = [SELECT Id FROM BR_Event__c WHERE Name='Test Event'];

        OrderApi__Item__c ticketItem = [SELECT Id FROM OrderApi__Item__c WHERE Name='Test Event Ticket'];

        BR_Event__c childEvt = LiveTestDataFactory.buildEvent('Child Event', false, true);
        childEvt.Parent_Event__c = evt.Id;
        insert childEvt;

        OrderApi__Item__c childticketItem = TestDataFactory.buildItem(iClass.Id, 'Child Event Ticket');
        childticketItem.AC_Event__c = childEvt.Id;
        childticketItem.OrderApi__Price__c = 0.0;
        insert childticketItem;

        OrderApi__Sales_Order__c SO = TestDataFactory.buildOpenSalesOrder(acc.Id, con.Id);
        insert SO;

        OrderApi__Sales_Order_Line__c line = TestDataFactory.buildSOLine(SO.Id, ticketItem.Id, iClass.Id);
        insert line;

        OrderApi__Sales_Order_Line__c line2 = TestDataFactory.buildSOLine(SO.Id, childTicketItem.Id, iClass.Id);
        insert line2;

        so.OrderApi__Is_Closed__c=true;
        so.OrderApi__Is_Posted__c = true;
        update so;

//        List<OrderApi__Sales_Order_Line__c> lines = [SELECT Id FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c=:so.Id AND  OrderApi__Item_Class__r.Name = 'Live Event Tickets'];
//        System.assertEquals(2, lines.size());

        OrderApi__Receipt__c rec = new OrderApi__Receipt__c(
                OrderApi__Contact__c = so.OrderApi__Contact__c,
                OrderApi__Entity__c = 'Contact',
                OrderApi__Is_Posted__c = true,
                OrderApi__Sales_Order__c = so.Id
        );
        insert rec;

        PageReference pageRef = Page.LiveTicketConfirmation;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('salesOrder',so.id);
//        ApexPages.currentPage().getParameters().put('receipt',rec.Id);

        Test.startTest();

        LiveTicketConfirmationController ctrl = new LiveTicketConfirmationController();
//        System.assertEquals(ctrl.receiptId, rec.Id);
        System.assertEquals(ctrl.evt.Id, evt.Id);

        Test.stopTest();

    }

    @IsTest
    public static void test_checkExhibitStatus(){

        Venue__c virtualVen = LiveTestDataFactory.buildVenue('Test Virtual Venue');
        virtualVen.Integration_Controller__c = 'CallableTest';
        insert virtualVen;

        BR_Event__c evt = [SELECT Id FROM BR_Event__c WHERE Name='Test Event'];
        evt.Virtual_Venue__c = virtualVen.Id;
        update evt;

        Virtual_Event_Details__c ved = new Virtual_Event_Details__c(Exhibit_Open__c=true, Event__c=evt.Id, External_Event_Id__c='1234');
        insert ved;

        Account acc = [SELECT Id FROM ACcount WHERE Name='Test Account'];
        Contact con = [SELECT Id FROM Contact WHERE AccountId=:acc.Id];

        OrderApi__Item_Class__c itemClass = [SELECT Id FROM OrderApi__Item_Class__c WHERE Name='Live Event Tickets'];
        OrderApi__Item__c ticketItem = [SELECT Id FROM OrderApi__Item__c WHERE Name='Test Event Ticket'];

        OrderApi__Sales_Order__c SO = TestDataFactory.buildOpenSalesOrder(acc.Id, con.Id);
        insert SO;

        OrderApi__Sales_Order_Line__c line = TestDataFactory.buildSOLine(SO.Id, ticketItem.Id, itemClass.Id);
        insert line;

        so.OrderApi__Is_Closed__c=true;
        so.OrderApi__Is_Posted__c = true;
        update so;

        OrderApi__Receipt__c rec = new OrderApi__Receipt__c(
                OrderApi__Contact__c = so.OrderApi__Contact__c,
                OrderApi__Entity__c = 'Contact',
                OrderApi__Is_Posted__c = true,
                OrderApi__Sales_Order__c = so.Id
        );
        insert rec;

        PageReference pageRef = Page.LiveTicketConfirmation;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('salesOrder',so.id);

        Test.startTest();
        LiveTicketConfirmationController ctrl = new LiveTicketConfirmationController();
        PageReference newPageRef = ctrl.checkExhibitStatus();
        System.assertNotEquals(null, newPageRef);

        Test.stopTest();

    }

}