src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>BR_Events_Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>BR_Events_Zone__c</referenceTo>
        <relationshipName>BR_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Confirmation_Message__c</fullName>
        <inlineHelpText>Used for registration confirmation email.</inlineHelpText>
        <label>Registration Confirmation Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GDPR_Certification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GDPR Certification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BrEvents_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Label__c</fullName>
        <description>Settings variable label</description>
        <inlineHelpText>Settings variable label</inlineHelpText>
        <label>Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BrEvents Settings</label>
</CustomObject>

src/objects/EC_Email__c.object
<CustomObject>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Exhibitor Emails</relationshipLabel>
        <relationshipName>Exhibitor_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exhibitor Email</label>
    <nameField>
        <displayFormat>EE-{0000}</displayFormat>
        <label>Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Event__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Exhibitor Connect Event to reference when making orders</description>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <label>Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exhibitor Connect Event</label>
</CustomObject>

src/objects/EC_Exhibitor_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Max_Budget__c</fullName>
        <label>Max Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Send_Invoice_To__c</fullName>
        <label>Send Invoice To</label>
        <type>Email</type>
    </fields>
    <label>Exhibitor Setting</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exhibitor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Order__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Type__c</fullName>
        <label>Attendee Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Members</fullName>
                </value>
                <value>
                    <fullName>Non-Members</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Over Budget</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Exhibitor Order</label>
    <nameField>
        <displayFormat>EO-{0000}</displayFormat>
        <label>EO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Email_Activity__c.object
<CustomObject>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Email Activities</relationshipLabel>
        <relationshipName>Email_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Email Activity</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Email Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Send_Grid__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Send Grid API Values</description>
    <fields>
        <fullName>API_key__c</fullName>
        <label>API key</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <label>url</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Send Grid</label>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EC_Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Email</label>
        <referenceTo>EC_Email__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Schedule</label>
        <referenceTo>EC_Schedule__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Review</fullName>
                    <default>true</default>
                    <label>In Review</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Over Budget</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Slot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendGridActivityControllerTest.cls
/**
 * Created by afaf.awad on 5/11/2021.
 */
@IsTest
public with sharing class SendGridActivityControllerTest {

    @TestSetup public static void setup() {
        Account account = LiveTestDataFactory.buildAccount('Test Account');
        insert account;

        Contact contact = LiveTestDataFactory.buildContact(account.Id);
        insert contact;

        User user = TestDataFactory.buildUser(contact.Id);
        insert user;

        //Participant Contacts
        Account partAccount = LiveTestDataFactory.buildAccount('Test Participant Account');
        insert partAccount;

        List<Contact> partContacts = new List<Contact>();
        for (Integer i = 0; i < 50; i++) {
            Contact con = LiveTestDataFactory.buildContact(partAccount.Id);
            con.LastName = con.LastName + i;
            con.Email = 'testEmail' + i + '@yopmail.com';
            partContacts.add(con);
        }
        insert partContacts;

        List<User> partUsers = new List<User>();
        for (Integer k = 0; k < partContacts.size(); k++){
            // Create users record
            User u = TestDataFactory.buildUser(partContacts[k].Id);
            u.LastName = 'Test User' + k;
            u.Email = 'test' + k + '@testorg.com';
            partUsers.add(u);
        }

        EC_Exhibitor_Setting__c ecSetting = ExhibitorTestDataFactory.buildExhibitorSetting(account.Id);
        ecSetting.Max_Budget__c = 10.00;
        ecSetting.Send_Invoice_To__c = 'testInvoice@testEmail.com';
        insert ecSetting;

        EC_Order__c order = ExhibitorTestDataFactory.buildECOrder(ecSetting.Id, contact);
        order.Attendee_Type__c = 'Non-Members';
        insert order;

        EC_Email__c email = ExhibitorTestDataFactory.buildECEmail(ecSetting.Id, order.Id);
        insert email;

        BR_Events_Zone__c zone = LiveTestDataFactory.buildZone('Default', true);
        insert zone;

        BR_Event__c event = LiveTestDataFactory.buildEvent('Exhibitor Test Event', false, false, zone.Id);
        event.Registration_Confirmation_Message__c = 'You are registered!';
        insert event;

        List<OrgWideEmailAddress> owas = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];

        insert new Send_Grid__c(url__c = 'https://api.sendgrid.com/v3/mail/send', API_key__c = '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');

        insert new BrEvents_Settings__c(Name='org wide email id', Label__c = 'org wide email id', Value__c = owas[0].Id);

        List<BR_Participation__c> participations = new List<BR_Participation__c>();
        for(Integer j = 5;j<partContacts.size();j++){
            participations.add(new BR_Participation__c(Contact__c=partContacts[j].Id
                    , BR_Event__c=event.Id
                    , Participate__c='Yes'
                    , Bypass_Confirmation__c= true
                    , GDPR_Certification__c = true));
        }
        insert participations;

        OrderApi__Item_Class__c itemClass = TestDataFactory.buildItemClass('Exhibitor Connect');
        insert itemClass;

        OrderApi__Item__c item = TestDataFactory.buildItem(itemClass.Id, 'Exhibitor Request');
        insert item;

        EC_Schedule__c schedule = ExhibitorTestDataFactory.buildECSchedule(event.Id);
        insert schedule;

        Time_Slot__c timeSlot = ExhibitorTestDataFactory.buildTimeSlot(order.Id, email.Id, schedule.Id);
        timeSlot.Delivery_Date__c = System.today().addDays(-1) ;
        timeSlot.Status__c = 'Sent';
        insert timeSlot;

        insert new EC_Event__c(Event_Name__c = event.Name, Event_Id__c = event.Id);

    }

    @isTest
    public static void test_Schedule_EC_EmailActivity() {
        String CRON_EXP = '0 0 0 ? * * *';

        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest',
                CRON_EXP,
                new Schedule_EC_EmailActivity());
        Test.stopTest();

    }

    @IsTest
    public static void test_downloadEmailActivity(){

        Time_Slot__c ts = [SELECT Id, Start_Time__c, Delivery_Date__c, EC_Email__r.Subject__c, EC_Order__c FROM Time_Slot__c];

        Test.setMock(HttpCalloutMock.class, new CreateMockHTTPResponseGenerator());

        Test.startTest();
        SendGridActivityController.downloadEmailActivity(ts.Delivery_Date__c, ts.Start_Time__c, ts.EC_Email__r.Subject__c, ts.EC_Order__c);
        Test.stopTest();

        List<Email_Activity__c> ea = [SELECT Id FROM Email_Activity__c];
        System.assertEquals(true, ea.size() > 0);
    }


    @IsTest
    public static void test_FAILdownloadEmailActivity(){

        Time_Slot__c ts = [SELECT Id, Start_Time__c, Delivery_Date__c, EC_Email__r.Subject__c, EC_Order__c FROM Time_Slot__c];

        Test.setMock(HttpCalloutMock.class, new FailureMockHTTPResponseGenerator());

        Test.startTest();
        SendGridActivityController.downloadEmailActivity(ts.Delivery_Date__c, ts.Start_Time__c, ts.EC_Email__r.Subject__c, ts.EC_Order__c);
        Test.stopTest();

    }

    public class CreateMockHTTPResponseGenerator implements HttpCalloutMock{
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            res.setBody('{"messages":[{"from_email":"testEmail@yopmail.com","msg_id":"TBKPAedYRmGscdFMlWZALw.filterdrecv-6b4886b6-th98w-1-609AD438-B5.180","subject":"Email Activity","to_email":"testEmail1@yopmail.com","status":"delivered","opens_count":1,"clicks_count":0,"last_event_time":"2021-05-11T23:22:27Z"}]}');
            res.setStatusCode(200);
            return res;
        }
    }


    public class FailureMockHTTPResponseGenerator implements HttpCalloutMock{
        public HTTPResponse respond(HTTPRequest req) {
            //This is will fail because setBody is missing closing brackets.
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            res.setBody('{"messages":[{"from_email":"testEmail@yopmail.com","msg_id":"TBKPAedYRmGscdFMlWZALw.filterdrecv-6b4886b6-th98w-1-609AD438-B5.180","subject":"Email Activity","to_email":"testEmail1@yopmail.com","status":"delivered","opens_count":1,"clicks_count":0,"last_event_time":"2021-05-11T23:22:27Z"}');
            res.setStatusCode(200);
            return res;
        }
    }

}