src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>BR_Events_Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>BR_Events_Zone__c</referenceTo>
        <relationshipName>BR_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Draft_Program__c</fullName>
        <label>Draft Program</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Event is not published.</inlineHelpText>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Stage__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
                <value>
                    <fullName>On Demand</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                    <isActive>false</isActive>
                    <label>Live</label>
                </value>
                <value>
                    <fullName>Mock Live</fullName>
                    <isActive>false</isActive>
                    <label>Mock Live</label>
                </value>
                <value>
                    <fullName>Prerecorded</fullName>
                    <isActive>false</isActive>
                    <label>Prerecorded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Publicly_available__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Event is available for users to purchase tickets.</inlineHelpText>
        <label>Publicly available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Registration_Confirmation_Message__c</fullName>
        <inlineHelpText>Used for registration confirmation email.</inlineHelpText>
        <label>Registration Confirmation Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Venue at which the event will take place</description>
        <label>Physical Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>AC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>Virtual_ACEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Events_Zone__c.object
<CustomObject>
    <label>AC Events Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BrEvents_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Label__c</fullName>
        <description>Settings variable label</description>
        <inlineHelpText>Settings variable label</inlineHelpText>
        <label>Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BrEvents Settings</label>
</CustomObject>

src/objects/Send_Grid__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Send Grid API Values</description>
    <fields>
        <fullName>API_key__c</fullName>
        <label>API key</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <label>url</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Send Grid</label>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Live! Event venues</description>
    <fields>
        <fullName>Virtual_Instructions__c</fullName>
        <label>Virtual Instructions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_SendEventRemindersTest.cls
/**
 * Created by afaf.awad on 10/23/2020.
 */

@IsTest
private class Batch_SendEventRemindersTest {

    @testsetup
    public static void setup(){

        Account acc = LiveTestDataFactory.buildAccount('Test Account');
        insert acc;

        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i < 10; i++) {
            Contact con = LiveTestDataFactory.buildContact(acc.Id);
            con.LastName = con.LastName + i;
            con.Email = 'testEmail' + i + '@yopmail.com';
            contacts.add(con);
        }
        insert contacts;

        List<OrgWideEmailAddress> owas = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];

        insert new Send_Grid__c(url__c = 'https://api.sendgrid.com/v3/mail/send', API_key__c = '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');

        insert new BrEvents_Settings__c(Name='org wide email id', Label__c = 'org wide email id', Value__c = owas[0].Id);

        BR_Events_Zone__c zone = LiveTestDataFactory.buildZone('Test Zone', true);
        insert zone;

        Venue__c ven = LiveTestDataFactory.buildVenue('Test Venue');
        ven.Virtual_Instructions__c = 'Testing Instructions.';
        insert ven;

        BR_Event__c physicalEvt = LiveTestDataFactory.buildEvent('Test Event',false,false);
        physicalEvt.Draft_Program__c = 'Test Draft Program';
        physicalEvt.Venue__c = ven.Id;
        physicalEvt.Publicly_available__c = TRUE;
        physicalEvt.Draft__c = FALSE;
        physicalEvt.Registration_Confirmation_Message__c = 'You Registered!';
        physicalEvt.Event_Stage__c='In Person';
        physicalEvt.Start_Date__c = Date.today();
        insert physicalEvt;

        BR_Event__c virtualEvt = LiveTestDataFactory.buildEvent('Test Event',false,false);
        virtualEvt.Draft_Program__c = 'Test Draft Program';
        virtualEvt.Venue__c = ven.Id;
        virtualEvt.Virtual_Venue__c = ven.Id;
        virtualEvt.Publicly_available__c = TRUE;
        virtualEvt.Draft__c = FALSE;
        virtualEvt.Registration_Confirmation_Message__c = 'You Registered!';
        virtualEvt.Event_Stage__c='Virtual';
        virtualEvt.Start_Date__c = date.today().addDays(1);
        insert virtualEvt;

        List<BR_Participation__c> participations = new List<BR_Participation__c>();
        for(Integer i = 0;i<5;i++){
            participations.add(new BR_Participation__c(Contact__c=contacts[i].Id, BR_Event__c=physicalEvt.Id, Participate__c='Yes'));
        }

        for(Integer j = 5;j<contacts.size();j++){
            participations.add(new BR_Participation__c(Contact__c=contacts[j].Id, BR_Event__c=virtualEvt.Id, Participate__c='Yes'));
        }

        insert new BrEvents_Settings__c(Name='org wide email id', Label__c = 'org wide email id', Value__c = owas[0].Id);

        system.debug('Insert Participants.size = ' + participations.size());
        insert participations;
    }

    @isTest
    public static void test_schedule() {
        String CRON_EXP = '0 0 0 15 3 ? 2022';

        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest',
                CRON_EXP,
                new Batch_SendEventRemindersScheduler());
        Test.stopTest();

    }

    @isTest
    public static void test_sendEmailReminders() {

        Date today = Date.today();

        List<BR_Participation__c> parts = [SELECT Id FROM BR_Participation__c
                WHERE BR_Event__r.Publicly_available__c = TRUE
                AND BR_Event__r.Draft__c = FALSE
                AND BR_Event__r.Start_Date__c >=: today];

        System.debug('Participants size == : ' + parts.size());

        Test.startTest();

        database.executeBatch(new Batch_SendEventReminders());
        Test.stopTest();

    }
}