src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Draft_Program__c</fullName>
        <label>Draft Program</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Invite_Image_Id__c</fullName>
        <label>Invite Image Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Event_Link__c</fullName>
        <formula>&apos;uat-aacr.cs195.force.com/LiveEventsList?ac__id=&apos; + Id</formula>
        <label>Portal Event Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Confirmation_Message__c</fullName>
        <inlineHelpText>Used for registration confirmation email.</inlineHelpText>
        <label>Registration Confirmation Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Venue at which the event will take place</description>
        <label>Physical Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>AC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>Virtual_ACEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Live! Event venues</description>
    <fields>
        <fullName>Virtual_Instructions__c</fullName>
        <label>Virtual Instructions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddToCalendarController.cls
/**
 * Created by afaf.awad on 10/8/2020.
 */

public without sharing class AddToCalendarController {

    public BR_Event__c event {get;set;}
    public String location {get;set;}
    public String eventUrl {get;set;}
    public String longStartDate {get;set;}
    public String longEndDate {get;set;}
    public String StartDate {get;set;}
    public String EndDate {get;set;}
    public String StartDateAM21 {get;set;}
    public String EndDateAM21 {get;set;}

    public void getEvent() {

        String eventId = ApexPages.currentPage().getParameters().get('Id');

        event = [SELECT Id, Name, Start_Date__c, End_Date__c, Venue__c, Virtual_Venue__c, Description__c,
                            Portal_Event_Link__c, Registration_Confirmation_Message__c, Invite_Image_Id__c,
                            Virtual_Venue__r.Virtual_Instructions__c, Venue__r.Name, Draft_Program__c
                    FROM BR_Event__c
        WHERE Id =: eventId];

        if(event.Name == 'AACR Annual Meeting 2021'){
            StartDate = Datetime.newInstance(2021,4,10,8,0,0).format();
            EndDate = Datetime.newInstance(2021, 4, 15,18,30,0).format();

            StartDateAM21 = Datetime.newInstance(2021, 5, 17,8,0,0).format();
            EndDateAM21 = Datetime.newInstance(2021, 5, 21,18,30,0).format();

        }else {
            //Create short datetime format in guest timezone for AddToCalendar cmp
            StartDate = event.Start_Date__c.format();
            EndDate = event.End_Date__c.format();
        }

        //Create long datetime format
        longStartDate = event.Start_Date__c.format('MMMM d,  yyyy h:mm a z');
        longEndDate = event.End_Date__c.format('MMMM d,  yyyy h:mm a z');
        

        if(event.Virtual_Venue__c == null){
            location = event.Venue__r.Name;
        }else{
            location = 'https://' + event.Portal_Event_Link__c;
        }

        eventUrl = 'https://' + event.Portal_Event_Link__c;


    }


}