src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Draft_Program__c</fullName>
        <label>Draft Program</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Invite_Image_Id__c</fullName>
        <label>Invite Image Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Confirmation_Message__c</fullName>
        <inlineHelpText>Used for registration confirmation email.</inlineHelpText>
        <label>Registration Confirmation Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Venue at which the event will take place</description>
        <label>Physical Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>AC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>Virtual_ACEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Live! Event venues</description>
    <fields>
        <fullName>Virtual_Instructions__c</fullName>
        <label>Virtual Instructions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddToCalendarControllerTest.cls
/**
 * Created by afaf.awad on 11/12/2020.
 */

@IsTest
private class AddToCalendarControllerTest {
    @testSetup
    public static void setup(){
        Account acc = LiveTestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = LiveTestDataFactory.buildContact(acc.Id);
        insert con;

        Venue__c ven = LiveTestDataFactory.buildVenue('Test Venue');
        ven.Virtual_Instructions__c = 'These instructions are fake.';
        insert ven;

        BR_Event__c event = LiveTestDataFactory.buildEvent('Test Event', false, false);
        event.Description__c = 'Test Event';
        event.Registration_Confirmation_Message__c = 'You are Registered!';
        event.Venue__c = ven.Id;
        event.Virtual_Venue__c = null;
        event.Invite_Image_Id__c = '';
        event.Draft_Program__c = 'www.google.com';
        insert event;

        BR_Event__c am21Event = LiveTestDataFactory.buildEvent('AACR Annual Meeting 2021', false, false);
        am21Event.Description__c = 'Test Event';
        am21Event.Registration_Confirmation_Message__c = 'You are Registered!';
        am21Event.Venue__c = ven.Id;
        am21Event.Virtual_Venue__c = null;
        am21Event.Invite_Image_Id__c = '';
        am21Event.Draft_Program__c = 'www.google.com';
        insert am21Event;

        BR_Participation__c part = new BR_Participation__c(BR_Event__c = event.Id,
                Contact__c = con.Id);
        insert part;

    }

    @IsTest
    static void test_getPhysicalEvent() {

        BR_Event__c event = [SELECT Id FROM BR_Event__c LIMIT 1];

        Test.startTest();
        PageReference addCalPage = Page.LetterOfParticipation;
        Test.setCurrentPage(addCalPage);
        addCalPage.getParameters().put('Id',event.Id);

        AddToCalendarController addCal = new AddToCalendarController();
        addCal.getEvent();

        System.assertEquals(event.Id, addCal.event.Id);
        Test.stopTest();
    }

    @IsTest
    static void test_getVirtualEvent() {

        Venue__c ven = [SELECT Id FROM Venue__c LIMIT 1];

        BR_Event__c event = [SELECT Id FROM BR_Event__c LIMIT 1];
        event.Virtual_Venue__c = ven.Id;
        update event;

        Test.startTest();
        Pagereference addCalPage = Page.LetterOfParticipation;
        Test.setCurrentPage(addCalPage);
        addCalPage.getParameters().put('Id',event.Id);

        AddToCalendarController addCal = new AddToCalendarController();
        addCal.getEvent();

        System.assertEquals(event.Id, addCal.event.Id);
        Test.stopTest();
    }

    @IsTest
    static void test_getAM21Event() {
        BR_Event__c am21Event = [SELECT Id FROM BR_Event__c WHERE Name = 'AACR Annual Meeting 2021'];

        Test.startTest();
        PageReference addCalPage = Page.LetterOfParticipation;
        Test.setCurrentPage(addCalPage);
        addCalPage.getParameters().put('Id',am21Event.Id);

        AddToCalendarController addCal = new AddToCalendarController();
        addCal.getEvent();

        System.assertEquals(am21Event.Id, addCal.event.Id);
        Test.stopTest();
    }
}