src/objects/BR_Event__c.object
<CustomObject>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Meeting_Links__mdt.object
<CustomObject>
    <description>links for virtual meetings</description>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Event_Id__c</fullName>
        <label>Live Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Virtual Meeting Links</label>
    <pluralLabel>Virtual Meetings Links</pluralLabel>
</CustomObject>

src/classes/AttendeeToParticipantTriggerTest.cls
/**
 * Created by lauren.lezberg on 9/1/2020.
 */

@IsTest
private class AttendeeToParticipantTriggerTest {

    @TestSetup
    public static void setup(){
        EventApi__Event__c evt = TestDataFactory.buildEvent();
        insert evt;

        BR_Event__c liveEVT = LiveTestDataFactory.buildEvent('Test Event', true, false);
        insert liveEVT;

        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;
    }


    @IsTest
    static void testParticipantCreation() {
        BR_Event__c liveevt = [SELECT Id FROM BR_Event__c LIMIT 1];

        EventApi__Event__c evt = [SELECT Id FROM EventApi__Event__c LIMIT 1];

        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];

        Virtual_Meeting_Links__mdt vml = new Virtual_Meeting_Links__mdt(
                DeveloperName='Test',
                Event_Id__c=evt.Id,
                Live_Event_Id__c = liveevt.Id
        );

        AttendeeToParticipantTriggerHandler.links = new List<Virtual_Meeting_Links__mdt>{vml};

        Test.startTest();

        EventApi__Attendee__c att = new EventApi__Attendee__c(EventApi__Contact__c=con.Id, EventApi__Event__c=evt.Id);
        insert att;

        Test.stopTest();


        Integer pCount = [SELECT COUNT() FROM BR_Participation__c WHERE Contact__c=:con.Id];
        System.assertEquals(1, pCount);
    }
}