src/objects/BR_Event__c.object
<CustomObject>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Attendee_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Attendee Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_ProcessCareerFairParticipants.cls
/**
 * Created by lauren.lezberg on 3/4/2021.
 */

global class Batch_ProcessCareerFairParticipants implements Database.Batchable<sObject>, Database.AllowsCallouts{
    public string eventId;

    public Batch_ProcessCareerFairParticipants(String eventId){
        this.eventId = eventId;
    }

    global Database.Querylocator start(Database.BatchableContext bc){
        System.debug('start....');
        String query = 'SELECT Id, External_Attendee_Id__c FROM BR_Participation__c WHERE External_Attendee_Id__c=null AND Participate__c= \'Yes\' AND BR_Event__c=: eventId';

        System.debug('query: ' + query);
        System.debug('result: ' + Database.query(query));
        return Database.getQuerylocator(query);
    }

    global void execute(Database.BatchableContext bc, List<BR_Participation__c> scope){
        List<BR_Participation__c> toUpdate = new List<BR_Participation__c>();

        for(BR_Participation__c p : scope){
            if(p.External_Attendee_Id__c==null) {
                System.debug('p: ' + p);
                String attId = vFairsHelper.synchronousInsertAttendee(p.Id);
                vFairsHelper.uploadResume(p.Id, attId);
                p.External_Attendee_Id__c = attId;
                toUpdate.add(p);
            }
        }

        update toUpdate;

    }

    global void finish(Database.BatchableContext BC){

        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                TotalJobItems, CreatedBy.Email
        FROM AsyncApexJob WHERE Id =
                :BC.getJobId()];
        System.debug('job summary: ' + a);
    }
}