src/objects/BR_Event__c.object
<CustomObject>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Attendee_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Attendee Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Current Education Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Highest_Degree__c</fullName>
        <label>Highest Degree</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Degrees_Held_Global_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Major_Focus__c</fullName>
        <description>Describes major focus of the contact.</description>
        <inlineHelpText>Describes major focus of the contact.</inlineHelpText>
        <label>Major Focus</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Basic Research</fullName>
                </value>
                <value>
                    <fullName>Basic Science</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Clinical Practice</fullName>
                </value>
                <value>
                    <fullName>Clinical Research</fullName>
                </value>
                <value>
                    <fullName>Population Science</fullName>
                </value>
                <value>
                    <fullName>Research Administration</fullName>
                </value>
                <value>
                    <fullName>Science Education</fullName>
                </value>
                <value>
                    <fullName>Translational Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Preferred_Email__c</fullName>
        <description>**System Calculated** The Preferred Email for the Contact is calculated by mapping the Preferred Email Type to it&apos;s corresponding field&apos;s value.</description>
        <formula>IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Personal&quot;) &amp;&amp; NOT(OrderApi__Personal_Email_Opt_Out__c), OrderApi__Personal_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Work&quot;) &amp;&amp; NOT(OrderApi__Work_Email_Opt_Out__c), OrderApi__Work_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Other&quot;) &amp;&amp; NOT(OrderApi__Other_Email_Opt_Out__c),OrderApi__Other_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Assistant&quot;) &amp;&amp; NOT(OrderApi__Assistant_Email_Opt_Out__c),OrderApi__Assistant_Email__c, &apos;&apos;))))</formula>
        <inlineHelpText>**System Calculated** The Preferred Email for the Contact is calculated by mapping the Preferred Email Type to it&apos;s corresponding field&apos;s value.</inlineHelpText>
        <label>Preferred Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Work_Phone__c</fullName>
        <description>The Work Phone for the Contact.</description>
        <inlineHelpText>The Work Phone for the Contact.</inlineHelpText>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Research_Area_of_Expertise__c</fullName>
        <description>This field reflects the single primary research area for the AACR member.</description>
        <inlineHelpText>This field reflects the single primary research area for the AACR member.</inlineHelpText>
        <label>Research Area of Expertise</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Research_Areas_Global_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/vFairs_Session__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>vFairs api keys</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>vFairs Session</label>
</CustomObject>

src/classes/vFairsHelper.cls
/**
 * Created by lauren.lezberg on 3/4/2021.
 */

public with sharing class vFairsHelper {



    /**
         * @purpose Retrieve vFairs API key from custom setting
         * @return vFairs API key
         */
    private static String get_vFairsKey() {
        vFairs_Session__c vSession = vFairs_Session__c.getOrgDefaults();
        return vSession.API_Key__c;
    }

    public class vFairsAttendee{
        public String email;
        public String first_name;
        public String middle_name;
        public String last_name;
        public String user_type_id = '8';
        public String title;
        public String work_phone;
        public String mobile_phone;
        public String highest_degree;
        public String research_area_of_expertise;
        public String major_focus;
        public String current_education_status;
        public String resume;
    }

    public class vFairsAttendeeUpdate{
        public String first_name;
        public String middle_name;
        public String last_name;
        public String user_type_id = '8';
        public String title;
        public String work_phone;
        public String mobile_phone;
        public String highest_degree;
        public String research_area_of_expertise;
        public String major_focus;
        public String current_education_status;
    }


    public static void updateAttendee(String participantId) {
        BR_Participation__c participant = [
                SELECT Id, External_Attendee_Id__c, User__r.Email, Contact__r.FirstName, Contact__r.Title,
                        Contact__r.OrderApi__Work_Phone__c, Contact__r.MobilePhone, Contact__r.Highest_Degree__c,
                        Contact__r.Primary_Research_Area_of_Expertise__c, Contact__r.Major_Focus__c,
                        Contact__r.Current_Education_Status__c,Contact__r.LastName, Contact__r.MiddleName,
                        Contact__r.OrderApi__Preferred_Email__c
                FROM BR_Participation__c
                WHERE Id = :participantId AND Participate__c = 'Yes' ORDER BY CreatedDate DESC LIMIT 1
        ];

        Http h = new Http();
        HttpResponse res = new HttpResponse();
        HttpRequest req = new HttpRequest();
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        String endpoint = 'https://api.vfairs.com/v12/users?access_key=' + get_vFairsKey() + '&user_id=' + participant.External_Attendee_Id__c;
        req.setEndpoint(endpoint);

        vFairsAttendeeUpdate attData = new vFairsAttendeeUpdate();
        attData.first_name = participant.Contact__r.FirstName;
        attData.last_name = participant.Contact__r.LastName;
        attData.middle_name = participant.Contact__r.MiddleName!=null?participant.Contact__r.MiddleName:null;
        attData.title = participant.Contact__r.Title!=null?participant.Contact__r.Title:null;
        attData.work_phone = participant.Contact__r.OrderApi__Work_Phone__c!=null?participant.Contact__r.OrderApi__Work_Phone__c:null;
        attData.mobile_phone = participant.Contact__r.MobilePhone!=null?participant.Contact__r.MobilePhone:null;
        attData.highest_degree = participant.Contact__r.Highest_Degree__c!=null?participant.Contact__r.Highest_Degree__c:null;
        attData.research_area_of_expertise = participant.Contact__r.Primary_Research_Area_of_Expertise__c!=null?participant.Contact__r.Primary_Research_Area_of_Expertise__c:null;
        attData.major_focus = participant.Contact__r.Major_Focus__c!=null?participant.Contact__r.Major_Focus__c:null;
        attData.current_education_status = participant.Contact__r.Current_Education_Status__c!=null?participant.Contact__r.Current_Education_Status__c:null;


        String payload = JSON.serialize(attData);

        System.debug('payload: ' + payload);
        req.setBody(payload);

        res = h.send(req);
        System.debug('create attendee response: ' + res);
        Object jsonParse = (Object) JSON.deserializeUntyped(res.getBody());
        Map<String, Object> mp_StrObj = (Map<string, Object>) jsonParse;
        System.debug('objectMap: ' + mp_StrObj);
        if (res.getStatusCode() != 200) {
//            errorMsg = 'Unknown Error';
            System.debug('unknown error');
            new AACRCustomException(participantId, 'Callout Error', String.valueOf(mp_StrObj.get('error')), 'vFairs Update Attendee');
        }


    }




    @Future(callout=true)
    public static void insertAttendee(String participantId) {
        System.debug('insert vFairs attendee');
        BR_Participation__c participant = [
                SELECT Id, External_Attendee_Id__c, User__r.Email, Contact__r.FirstName, Contact__r.Title,
                        Contact__r.OrderApi__Work_Phone__c, Contact__r.MobilePhone, Contact__r.Highest_Degree__c,
                        Contact__r.Primary_Research_Area_of_Expertise__c, Contact__r.Major_Focus__c,
                        Contact__r.Current_Education_Status__c,Contact__r.LastName, Contact__r.MiddleName,
                        Contact__r.OrderApi__Preferred_Email__c
                FROM BR_Participation__c
                WHERE Id = :participantId
        ];



        List<ContentDocumentLink> contactFiles = [SELECT ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.Title, LinkedEntityId
        FROM ContentDocumentLink WHERE LinkedEntityId =: participant.Contact__c ANd ContentDocument.Title LIKE '%Resume%' ORDER BY SystemModstamp DESC];

        List<ContentDistribution> distributions = [Select Id, DistributionPublicUrl from ContentDistribution WHERE ContentVersionId =: contactFiles[0].ContentDocument.LatestPublishedVersionId];

        Http h = new Http();
        HttpResponse res = new HttpResponse();
        HttpRequest req = new HttpRequest();
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        String endpoint = 'https://api.vfairs.com/v12/users?access_key=' + get_vFairsKey();
        req.setEndpoint(endpoint);

        vFairsAttendee attData = new vFairsAttendee();
        attData.email = participant.User__r.Email;
        attData.first_name = participant.Contact__r.FirstName;
        attData.last_name = participant.Contact__r.LastName;
        attData.middle_name = participant.Contact__r.MiddleName!=null?participant.Contact__r.MiddleName:null;
        attData.title = participant.Contact__r.Title!=null?participant.Contact__r.Title:null;
        attData.work_phone = participant.Contact__r.OrderApi__Work_Phone__c!=null?participant.Contact__r.OrderApi__Work_Phone__c:null;
        attData.mobile_phone = participant.Contact__r.MobilePhone!=null?participant.Contact__r.MobilePhone:null;
        attData.highest_degree = participant.Contact__r.Highest_Degree__c!=null?participant.Contact__r.Highest_Degree__c:null;
        attData.research_area_of_expertise = participant.Contact__r.Primary_Research_Area_of_Expertise__c!=null?participant.Contact__r.Primary_Research_Area_of_Expertise__c:null;
        attData.major_focus = participant.Contact__r.Major_Focus__c!=null?participant.Contact__r.Major_Focus__c:null;
        attData.current_education_status = participant.Contact__r.Current_Education_Status__c!=null?participant.Contact__r.Current_Education_Status__c:null;
        attData.resume = distributions.isEmpty()?'':distributions[0].DistributionPublicUrl;


        String payload = JSON.serialize(attData);

        System.debug('payload: ' + payload);
        req.setBody(payload);

        res = h.send(req);
        System.debug('create attendee response: ' + res);
        Object jsonParse = (Object) JSON.deserializeUntyped(res.getBody());
        Map<String, Object> mp_StrObj = (Map<string, Object>) jsonParse;
        System.debug('objectMap: ' + mp_StrObj);
        if (res.getStatusCode() == 200) {
            String attId =String.valueOf(mp_StrObj.get('id'));
//            uploadResume(participantId, attId);
            try {
                participant.External_Attendee_Id__c = attId;
                update participant;
            } catch(Exception e){
                new AACRCustomException(participantId, e.getMessage(), e.getStackTraceString(), 'vFairs Insert Attendee');
            }
        } else {
//            errorMsg = 'Unknown Error';
            System.debug('unknown error');
            new AACRCustomException(participantId, 'Callout Error', String.valueOf(mp_StrObj.get('error')), 'vFairs Insert Attendee');
        }


    }


    public static String synchronousInsertAttendee(String participantId) {
        BR_Participation__c participant = [
                SELECT Id, External_Attendee_Id__c, User__r.Email, Contact__r.FirstName, Contact__r.Title,
                        Contact__r.OrderApi__Work_Phone__c, Contact__r.MobilePhone, Contact__r.Highest_Degree__c,
                        Contact__r.Primary_Research_Area_of_Expertise__c, Contact__r.Major_Focus__c,
                        Contact__r.Current_Education_Status__c,Contact__r.LastName, Contact__r.MiddleName,
                        Contact__r.OrderApi__Preferred_Email__c
                FROM BR_Participation__c
                WHERE Id = :participantId
        ];

        List<ContentDocumentLink> contactFiles = [SELECT ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.Title, LinkedEntityId
        FROM ContentDocumentLink WHERE LinkedEntityId =: participant.Contact__c ANd ContentDocument.Title LIKE '%Resume%' ORDER BY SystemModstamp DESC];

        List<ContentDistribution> distributions = [Select Id, DistributionPublicUrl from ContentDistribution WHERE ContentVersionId =: contactFiles[0].ContentDocument.LatestPublishedVersionId];

        Http h = new Http();
        HttpResponse res = new HttpResponse();
        HttpRequest req = new HttpRequest();
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        String endpoint = 'https://api.vfairs.com/v12/users?access_key=' + get_vFairsKey();
        req.setEndpoint(endpoint);

        vFairsAttendee attData = new vFairsAttendee();
        attData.email = participant.User__r.Email;
        attData.first_name = participant.Contact__r.FirstName;
        attData.last_name = participant.Contact__r.LastName;
        attData.middle_name = participant.Contact__r.MiddleName!=null?participant.Contact__r.MiddleName:null;
        attData.title = participant.Contact__r.Title!=null?participant.Contact__r.Title:null;
        attData.work_phone = participant.Contact__r.OrderApi__Work_Phone__c!=null?participant.Contact__r.OrderApi__Work_Phone__c:null;
        attData.mobile_phone = participant.Contact__r.MobilePhone!=null?participant.Contact__r.MobilePhone:null;
        attData.highest_degree = participant.Contact__r.Highest_Degree__c!=null?participant.Contact__r.Highest_Degree__c:null;
        attData.research_area_of_expertise = participant.Contact__r.Primary_Research_Area_of_Expertise__c!=null?participant.Contact__r.Primary_Research_Area_of_Expertise__c:null;
        attData.major_focus = participant.Contact__r.Major_Focus__c!=null?participant.Contact__r.Major_Focus__c:null;
        attData.current_education_status = participant.Contact__r.Current_Education_Status__c!=null?participant.Contact__r.Current_Education_Status__c:null;
        attData.resume = distributions.isEmpty()?'':distributions[0].DistributionPublicUrl;

        String payload = JSON.serialize(attData);

        System.debug('payload: ' + payload);
        req.setBody(payload);

        res = h.send(req);
        System.debug('create attendee response: ' + res);
        Object jsonParse = (Object) JSON.deserializeUntyped(res.getBody());
        Map<String, Object> mp_StrObj = (Map<string, Object>) jsonParse;
        System.debug('objectMap: ' + mp_StrObj);
        if (res.getStatusCode() == 200) {
            return String.valueOf(mp_StrObj.get('id'));

        } else {
//            errorMsg = 'Unknown Error';
            System.debug('unknown error');
            new AACRCustomException(participantId, 'Callout Error', String.valueOf(mp_StrObj.get('error')), 'vFairs Insert Attendee');
        }

        return null;

    }

    public static String getAttendeeLoginURL(String contactId, String SFEventId){
        BR_Participation__c participant = [
                SELECT Id, External_Attendee_Id__c, User__r.Email, Contact__r.FirstName, Contact__r.Title,
                        Contact__r.OrderApi__Work_Phone__c, Contact__r.MobilePhone, Contact__r.Highest_Degree__c,
                        Contact__r.Primary_Research_Area_of_Expertise__c, Contact__r.Major_Focus__c,
                        Contact__r.Current_Education_Status__c,Contact__r.LastName, Contact__r.MiddleName,
                        Contact__r.OrderApi__Preferred_Email__c
                FROM BR_Participation__c
                WHERE Contact__c=:contactId AND BR_Event__c=:SFEventId
        ];


        Http h = new Http();
        HttpResponse res = new HttpResponse();
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setHeader('Content-Type', 'application/json');
        String endpoint = 'https://api.vfairs.com/v12/users?access_key=' + get_vFairsKey() + '&user_id=' + participant.External_Attendee_Id__c;
        req.setEndpoint(endpoint);


        res = h.send(req);
        System.debug('get attendee response: ' + res);
        List<Object> jsonParse = (List<Object>) JSON.deserializeUntyped(res.getBody());
        Map<String, Object> mp_StrObj = (Map<string, Object>) jsonParse[0];
        System.debug('objectMap: ' + mp_StrObj);
        if (res.getStatusCode() == 200) {
            return String.valueOf(mp_StrObj.get('autologin_url'));

        } else {
//            errorMsg = 'Unknown Error';
            System.debug('unknown error');
            new AACRCustomException(contactId, 'Callout Error', String.valueOf(mp_StrObj.get('error')), 'vFairs - Login URL');
        }

        return null;
    }

//    public class ResumeData{
//        public String resume_file_name;
//        public String resume_file_contents;
//    }
//
//    public static void uploadResume(String participantId, String vUser_id){
//        BR_Participation__c participant = [
//                SELECT Id, External_Attendee_Id__c, Contact__c
//                FROM BR_Participation__c
//                WHERE Id = :participantId
//        ];
//
//        List<ContentDocumentLink> contactFiles = [SELECT ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.Title, LinkedEntityId
//        FROM ContentDocumentLink WHERE LinkedEntityId =: participant.Contact__c ORDER BY SystemModstamp DESC];
//        System.debug('contact Files: ' + contactFiles);
//
//        if(!contactFiles.isEmpty()) {
//            ContentVersion resume;
//            for (ContentDocumentLink file : contactFiles) {
//                if (file.ContentDocument.Title.contains('Resume') && resume == null) {
//                    resume = [SELECT Id, VersionData, Title FROM ContentVersion WHERE ContentDocumentId = :file.ContentDocumentId AND IsLatest = true];
//                }
//            }
//
//            System.debug('resume: ' + resume);
//
//            Http h = new Http();
//            HttpResponse res = new HttpResponse();
//            HttpRequest req = new HttpRequest();
//            req.setMethod('POST');
//            req.setHeader('Content-Type', 'application/json');
//            String endpoint = 'https://api.vfairs.com/v12/users?access_key=' + get_vFairsKey() + '&user_id=' + vUser_id;
//            req.setEndpoint(endpoint);
//
//            ResumeData rData = new ResumeData();
//            rData.resume_file_name = resume.Title;
//            rData.resume_file_contents = EncodingUtil.base64Encode(resume.VersionData);
//
//            String payload = JSON.serialize(rData);
//
//            System.debug('payload: ' + payload);
//            req.setBody(payload);
//
//            res = h.send(req);
//            System.debug('upload resume response: ' + res);
//            Object jsonParse = (Object) JSON.deserializeUntyped(res.getBody());
//            Map<String, Object> mp_StrObj = (Map<string, Object>) jsonParse;
//            System.debug('objectMap: ' + mp_StrObj);
//            if (res.getStatusCode() == 200) {
//                System.debug('resumeURL: ' + mp_StrObj.get('resume'));
//            } else {
////            errorMsg = 'Unknown Error';
//                System.debug('unknown error');
//                new AACRCustomException(participantId, 'Callout Error', String.valueOf(mp_StrObj.get('error')), 'vFairs Upload Resume');
//            }
//        }
//
//    }

}