src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Stage__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
                <value>
                    <fullName>On Demand</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                    <isActive>false</isActive>
                    <label>Live</label>
                </value>
                <value>
                    <fullName>Mock Live</fullName>
                    <isActive>false</isActive>
                    <label>Mock Live</label>
                </value>
                <value>
                    <fullName>Prerecorded</fullName>
                    <isActive>false</isActive>
                    <label>Prerecorded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Event_Details__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Virtual Event Details</relationshipLabel>
        <relationshipName>Virtual_Event_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhibit_Open__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the virtual exhibit open for users to visit?</inlineHelpText>
        <label>Exhibit Open</label>
        <type>Checkbox</type>
    </fields>
    <label>Virtual Event Details</label>
    <nameField>
        <label>Virtual Event Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrEventAutoOpenExibitTest.cls
/**
 * Created by afaf.awad on 10/23/2020.
 */

@IsTest
private class BrEventAutoOpenExibitTest {
    
    @IsTest
    public static void test_OpenExibit() {

        BR_Event__c testEvent = LiveTestDataFactory.buildEvent('Test Event', false , false);
        testEvent.Start_Date__c = System.now().addMinutes(15);
        testEvent.Event_Stage__c = 'Virtual';
        insert testEvent;

        Virtual_Event_Details__c ved = new Virtual_Event_Details__c(
                Name = 'Test Virtual Details',
                Event__c = testEvent.Id,
                Exhibit_Open__c = false
        );
        insert ved;


        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest',
                '0 0 0 15 3 ? 2022',
                new BrEventAutoOpenExibitScheduler());
        Test.stopTest();

        Virtual_Event_Details__c ved_post = [SELECT Exhibit_Open__c FROM Virtual_Event_Details__c LIMIT 1];
        System.assertEquals(true, ved_post.Exhibit_Open__c);

    }


}