src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Virtual_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>Virtual_ACEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Live! Event venues</description>
    <fields>
        <fullName>Base_URL__c</fullName>
        <label>Base URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Event_Details__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Virtual Event Details</relationshipLabel>
        <relationshipName>Virtual_Event_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Event_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Event Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Virtual Event Details</label>
    <nameField>
        <label>Virtual Event Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/V_PathLMSIntegration.cls
/**
 * Created by lauren.lezberg on 9/25/2020.
 */

public without sharing class V_PathLMSIntegration implements Callable, VirtualEventIntegration{

    public Object call(String action, Map<String, Object> args){
        switch on action {
            when 'sendAttendee' {
                return this.sendAttendee((String)args.get('contactId'), (String)args.get('externalEventId'), (Boolean)args.get('flag'));
            }
            when 'asyncSendAttendee' {
                V_PathLMSIntegration.asyncSendAttendee((String)args.get('contactId'), (String)args.get('externalEventId'), (Boolean)args.get('flag'));
                return null;
            }
            when 'updateAttendee' {
                V_PathLMSIntegration.updateAttendee((String)args.get('participantId'));
                return null;
            }
            when 'deleteAttendee' {
                V_PathLMSIntegration.deleteAttendee((String)args.get('fuzionAttendeeId'), (String)args.get('fuzionEventId'));
                return null;
            }
            when 'goToVenue' {
                return this.goToVenue((String)args.get('contactId'), (String)args.get('SFEventId'));
            }
            when else {
                throw new AACRCustomException('Failure to execute action: ' + action, 'PathLMSIntegration.call()', 'PathLMSIntegration');
            }
        }
    }

    public static void deleteAttendee(String fuzionAttendeeId, String fuzionEventId){

    }

    public static void updateAttendee(String participantId){

    }

    public String sendAttendee(String contactId, String externalEventId, Boolean flag){

        return null;
    }

    @Future(callout=true)
    public static void asyncSendAttendee(String contactId, String externalEventId, Boolean flag){

    }

    public String goToVenue(String contactId, String SFEventId){
        String redirectURL = '';

        BR_Event__c evt = [SELECT Id, Virtual_Venue__r.Base_URL__c FROM BR_Event__c WHERE Id=: SFEventId];

        Virtual_Event_Details__c ved = [SELECT External_Event_Id__c FROM Virtual_Event_Details__c WHERE Event__c=: SFEventId];

        redirectURL = evt.Virtual_Venue__r.Base_URL__c + ved.External_Event_Id__c + '?force_authorization=true';

        return redirectURL;
    }

}