src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Stage__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
                <value>
                    <fullName>On Demand</fullName>
                </value>
                <value>
                    <fullName>Hybrid</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                    <isActive>false</isActive>
                    <label>Live</label>
                </value>
                <value>
                    <fullName>Mock Live</fullName>
                    <isActive>false</isActive>
                    <label>Mock Live</label>
                </value>
                <value>
                    <fullName>Prerecorded</fullName>
                    <isActive>false</isActive>
                    <label>Prerecorded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hide_Date_Time__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Date/Time</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_Image_Filename__c</fullName>
        <label>List Image Filename</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone to show to public</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>(GMT+14:00) Line Is. Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:45) Chatham Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:00) Phoenix Is. Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:00) Tonga Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:00) New Zealand Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:45) Chatham Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) Petropavlovsk-Kamchatski Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) New Zealand Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) Fiji Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Solomon Is. Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Norfolk Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Lord Howe Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Australian Eastern Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:30) Lord Howe Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:30) Australian Central Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:00) Australian Eastern Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:30) Australian Central Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:00) Korea Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:00) Japan Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Hong Kong Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Malaysia Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Philippines Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) China Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Singapore Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Australian Western Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+07:00) Indochina Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+07:00) West Indonesia Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+06:30) Myanmar Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+06:00) Bangladesh Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+05:45) Nepal Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AdvocateAppConfirmationController.cls
/**
 * Created by lauren.lezberg on 7/14/2021.
 */

public without sharing class AdvocateAppConfirmationController {

    public class EventInfo{
        @AuraEnabled
        public String imgUrl;

        @AuraEnabled
        public BR_Event__c evt;

        @AuraEnabled
        public String eventDates;

        public EventInfo(String url, BR_Event__c event, String dates){
            this.imgUrl = url;
            this.evt = event;
            this.eventDates = dates;
        }
    }


    @AuraEnabled
    public static EventInfo getEventInfo(String eventId){
        BR_Event__c item = [SELECT Id, Timezone__c, Event_Stage__c, Hide_Date_Time__c, List_Image_Filename__c, Name, Start_Date__c, End_Date__c FROM BR_Event__c WHERE Id=:eventId];
        Id currentContactId = ECRMUtils.getCurrentLoginUserContactId();

        List<BR_Participation__c> tickets = [SELECT Id, Participate__c FROM BR_Participation__c WHERE Contact__c=:currentContactId AND BR_Event__c=:eventId AND Participate__c = 'Incomplete'];
        if(tickets.size()>0) {
            tickets[0].Participate__c = 'Pending Approval';
            update tickets[0];
        }

        Set<Id> items_ids = new Set<Id>{eventId};
        Map<Id, Map<String, String>> itemsAttachments = BrEventsHelper.getAttachmentsForItems(items_ids);
        String imgURL;
        for (Id item_id : itemsAttachments.keySet()) {
            Map<String, String> itemAttachments = itemsAttachments.get(item_id);
            for (String att : itemAttachments.keySet()) {
                if (item.List_Image_Filename__c == att) {
                    imgURL= itemAttachments.get(att);
                }
            }
        }

        String eventDates;
        Integer diffMinutes = 0;
        String eventTimezone = item.Timezone__c;
//        if(eventTimezone == null){
//            eventTimezone = '';
//        }
        String userTimezone = UserInfo.getTimeZone().toString();

        if (eventTimezone != null) {
            diffMinutes = BrEventsHelper.getDiffMinutesBetweenTimezones(eventTimezone, userTimezone);
        }

        Datetime startDate = item.Start_Date__c.addMinutes(diffMinutes);
        Datetime endDate = item.End_Date__c;

        eventDates = startDate.format('MMMM') + ' ' + startDate.day() + ', ' + startDate.year() + ', ' + startDate.format('h:mm a') + ' to ' + endDate.format('h:mm a');

        Date startDay = Date.newInstance(startDate.year(), startDate.month(), startDate.day());
        Date endDay = Date.newInstance(endDate.year(), endDate.month(), endDate.day());

        if (endDate!=null) {
            if (diffMinutes != 0) {
                endDate = item.End_Date__c.addMinutes(diffMinutes);
            }

            if (endDate > startDate && endDay!=startDay) {
                eventDates = startDate.format('MMMM') + ' ' + startDate.day() + '-' + endDate.day() + ', ' + endDate.year() + ', ' + startDate.format('h:mm a') + ' to ' + endDate.format('h:mm a');
            }
        }

        eventDates = eventDates.replaceAll('AM', 'a.m.').replaceAll('PM', 'p.m.');
        if(eventDates.contains('12:00 a.m.')){
            eventDates = eventDates.replace('12:00 a.m.', 'Midnight');
        } else if(eventDates.contains('12:00 p.m.')) {
            eventDates = eventDates.replace('12:00 p.m.', 'Noon');
        }
        eventDates = eventDates.replaceAll(':00', '');

        return new EventInfo(imgURL, item, eventDates);
    }
}