src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Virtual_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>Virtual_ACEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Live! Event venues</description>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Event_Details__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Virtual Event Details</relationshipLabel>
        <relationshipName>Virtual_Event_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Password__c</fullName>
        <label>Meeting Password</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zoom_Type__c</fullName>
        <label>Zoom Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zoom_User_Id__c</fullName>
        <label>Zoom User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Virtual Event Details</label>
    <nameField>
        <label>Virtual Event Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VirtualEventDetailsTriggerHandler.cls
/**
 * Created by lauren.lezberg on 10/27/2020.
 */

public with sharing class VirtualEventDetailsTriggerHandler {

    @Future(Callout=true)
    public static void createZoomMeeting(String vedID){
//        String userId = '6pwXvs6bQ2-bwZFL_xmYkA';
        Virtual_Event_Details__c ved = [SELECT Zoom_Type__c, Meeting_Password__c, Zoom_User_Id__c, Event__c,Event__r.Virtual_Venue__r.Name, Event__r.Virtual_Venue__c FROM Virtual_Event_Details__c WHERE Id=:vedID];

        if(ved.Event__r.Virtual_Venue__c!=null && ved.Event__r.Virtual_Venue__r.Name.contains('Zoom')) {
            V_ZoomIntegration.createZoomMeeting(ved.Event__c, ved.Zoom_User_Id__c, ved.Meeting_Password__c, ved.Zoom_Type__c == 'Webinar');
        }
    }

    @Future(Callout=true)
    public static void updateZoomMeeting(String vedID){
//        String userId = '6pwXvs6bQ2-bwZFL_xmYkA';
        Virtual_Event_Details__c ved = [SELECT Meeting_Password__c, Zoom_User_Id__c, Event__c,Event__r.Virtual_Venue__r.Name, Event__r.Virtual_Venue__c FROM Virtual_Event_Details__c WHERE Id=:vedID];

        if(ved.Event__r.Virtual_Venue__c!=null && ved.Event__r.Virtual_Venue__r.Name.contains('Zoom')) {
            V_ZoomIntegration.updateZoomMeeting(ved.Event__c, ved.Zoom_User_Id__c, ved.Meeting_Password__c);
        }
    }

}