src/objects/BR_Event__c.object
<CustomObject>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>EventApi__Full_Name__c</fullName>
        <description>** System Calculated Override ** The full name of the attendee as it should display on Event badges. Derives automatically from the First and Last Name fields on the linked Contact record.</description>
        <inlineHelpText>** System Calculated Override ** The full name of the attendee as it should display on Event badges. Derives automatically from the First and Last Name fields on the linked Contact record.</inlineHelpText>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_EmailEvent.cls
/**
 * Created by afaf.awad on 9/2/2020.
 */

global class Batch_EmailEvent implements Database.Batchable<sObject>, Database.Stateful{

    String eventId;
//    String templateName;

    global Batch_EmailEvent(String event ){
        this.eventId = event;
//        this.templateName = template;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        String queryString = 'SELECT Id, BR_Event__c, Contact__r.Name, Contact__r.Email, Contact__c FROM BR_Participation__c WHERE Contact__r.IsEmailBounced = FALSE AND Participate__c = \'Yes\' AND BR_Event__c =: eventId';
        System.debug('queryString: ' + queryString);
        return Database.getQueryLocator(queryString);
    }


    global void execute(Database.BatchableContext BC, List<BR_Participation__c> scope){
        System.debug('executing Batch_EmailEvent with ' + scope.size() + ' records.');
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        EmailTemplate emailTemplate = [SELECT Id, HtmlValue, Body  FROM EmailTemplate WHERE Name = 'AM21 ATC Email'];

        for(BR_Participation__c part : scope){

            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

            String body = emailTemplate.HtmlValue;
            body = emailTemplate.HtmlValue.replace('{!Contact.Name}', part.Contact__r.Name)
                    .replace('{!BR_Event__c.Id}',part.BR_Event__c);

//            body = emailTemplate.HtmlValue.replace('{!EventApi__Attendee__c.EventApi__Event__c}', attendee.EventApi__Event__r.Name)
//                    .replace('{!Contact.Email}',attendee.EventApi__Contact__r.Email)
//                    .replace('{!EventApi__Attendee__c.EventApi__Full_Name__c}', attendee.EventApi__Full_Name__c);

            email.setHtmlBody(body);
            email.setSubject('Calendar Item Now Available');
            email.setTargetObjectId(part.Contact__c);
            email.setTemplateId(emailTemplate.Id);
            email.setWhatId(part.Id);
            email.setSaveAsActivity(false);
            email.setSenderDisplayName('American Association For Cancer Research');
            email.setToAddresses(new List<String>{part.Contact__r.Email});
            emails.add(email);
        }

        System.debug('emails to send: ' + emails.size());

        if (!emails.isEmpty()) {
            try {
                Messaging.sendEmail(emails);
            } catch (EmailException ex) {
                System.debug(ex.getMessage());
                throw new AACRCustomException(ex.getMessage(), ex.getStackTraceString(), 'Email: Calendar Item Now Available');
            }
        }
    }


    global void finish(Database.BatchableContext BC){
        System.debug('finishing Batch_EmailEvent...');

    }

}