src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>BR_Events_Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>BR_Events_Zone__c</referenceTo>
        <relationshipName>BR_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Unlisted_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Unlisted events will not appear in the portal for general purchase but will still be open for ticket sales.</inlineHelpText>
        <label>Unlisted Event</label>
        <type>Checkbox</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <recordTypes>
        <fullName>Cancelled</fullName>
        <active>true</active>
        <description>Event has been cancelled</description>
        <label>Cancelled</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Events_Zone__c.object
<CustomObject>
    <label>AC Events Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Event__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Exhibitor Connect Event to reference when making orders</description>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Exhibitor Connect Event</label>
</CustomObject>

src/objects/EC_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Exhibitor Schedules</relationshipLabel>
        <relationshipName>Exhibitor_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Exhibitor Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exhibitor Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_DatePickerController.cls
/**
 * Created by afaf.awad on 2/22/2021.
 */

public without sharing class EC_DatePickerController {

        @AuraEnabled
        public static List<EC_Schedule__c> getEventsForMonth(String zoneId, Integer year, Integer month, String eventId) {

            System.debug('eventId = ' + eventId);
//            BR_Event__c event;
            EC_Event__c globalEvent = EC_Event__c.getOrgDefaults();
//            If(Test.isRunningTest()){
//                event = [SELECT Id FROM BR_Event__c WHERE Name = 'Text Exhibitor Event'];
//            }else{
//                event = [SELECT Id FROM BR_Event__c WHERE Name = 'Tumor Heterogeneity: From Single Cells to Clinical Impact'];
//            }

            List<EC_Schedule__c> itemsList = [SELECT Id, Name, Start_Date__c, End_Date__c FROM EC_Schedule__c WHERE Event__c =: globalEvent.Event_Id__c];
//            List<EC_Schedule__c> itemListFormatted = new List<EC_Schedule__c>();
//
//            for (EC_Schedule__c item : itemsList) {
//                item.Start_Date__c = DateTime.newInstanceGmt(item.Start_Date__c.date(), item.Start_Date__c.time());
//                itemListFormatted.add(item);
//            }

            System.debug('itemsList:: ' + itemsList);

            return itemsList;

//            if(!BrEventsHelper.performAccessCheck('read', 'BR_Event__c', null)
//                    || !BrEventsHelper.performAccessCheck('read', 'BR_Participation__c', null))
//                return itemsList;

//            year = Integer.valueOf(year);
//            month = Integer.valueOf(month);
//            String currentTimeGMT = DateTime.now().formatGmt('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'');
//            Integer numberOfDays = Date.daysInMonth(year, month);
//            DateTime monthDateStartGMT = DateTime.newInstanceGMT(year, month, 1);
//            DateTime monthDateEndGMT = DateTime.newInstanceGMT(year, month, numberOfDays, 23, 59, 0);

//            String query = 'SELECT Id, Name, Start_Date__c, End_Date__c FROM EC_Schedule__c WHERE Event__c =: eventId';
//            String query = 'SELECT Start_Date__c, (SELECT Participate__c FROM BR_Participations__r' +
//                    ' WHERE User__c = \'' + UserInfo.getUserId() +'\' AND Participate__c = \'Yes\')' +
//                    ' FROM BR_Event__c WHERE BR_Events_Zone__c = \'' + zoneId + '\' AND Start_Date__c > YESTERDAY' +
//                    ' AND Start_Date__c > ' + monthDateStartGMT.formatGmt('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'') + ' AND Start_Date__c < '
//                    + monthDateEndGMT.formatGmt('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'') + ' AND RecordType.Name!=\'Cancelled\'';

//            List<BR_Participation__c> participations = [
//                    SELECT BR_Event__c
//                    FROM BR_Participation__c
//                    WHERE User__c = :UserInfo.getUserId() AND Participate__c = 'Yes'
//            ];
//            List<Id> eventsUserIsParticipating = new List<Id>();
//
//            for (BR_Participation__c participation : participations) {
//                eventsUserIsParticipating.add(participation.BR_Event__c);
//            }
//
//            if (eventsUserIsParticipating.isEmpty()) {
//                query += ' AND Unlisted_Event__c = FALSE';
//            } else {
//                query += ' AND (Unlisted_Event__c = FALSE OR Id IN (\'' + String.join(eventsUserIsParticipating, '\', \'') + '\') )';
//            }

//            itemsList = Database.query(query);
//
//            List<EC_Schedule__c> itemListFormatted = new List<EC_Schedule__c>();
//
//            for (EC_Schedule__c item : itemsList) {
//                item.Start_Date__c = DateTime.newInstanceGmt(item.Start_Date__c.date(), item.Start_Date__c.time());
//                itemListFormatted.add(item);
//            }
//
//            System.debug('itemsList:: ' + itemsList);
//
//            return itemsList;

        }

}