src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Display_on_Confirmation_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display on Confirmation Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Draft_Program__c</fullName>
        <label>Draft Program</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Main_Image_Filename__c</fullName>
        <label>Main Image Filename</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Coupled Events</relationshipLabel>
        <relationshipName>Child_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portal_Event_Link__c</fullName>
        <formula>&apos;uat-aacr.cs195.force.com/LiveEventsList?ac__id=&apos; + Id</formula>
        <label>Portal Event Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Confirmation_Page_Logos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Confirmation Page Logos</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ticket_Purchase_Confirmation_Message__c</fullName>
        <description>Custom messaging for ticket purchase confirmation page.</description>
        <inlineHelpText>Custom messaging for ticket purchase confirmation page.</inlineHelpText>
        <label>Ticket Purchase Confirmation Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Venue at which the event will take place</description>
        <label>Physical Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>AC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>View_Confirmation_Page_Horizontally__c</fullName>
        <defaultValue>false</defaultValue>
        <label>View Confirmation Page Horizontally</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Virtual_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>Virtual_ACEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt__c.object
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</description>
        <inlineHelpText>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Caluclated** Lookup to the reciept for which you are refunding.</description>
        <inlineHelpText>**System Caluclated** Lookup to the reciept for which you are refunding.</inlineHelpText>
        <label>Receipt</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OrderApi__Receipt__c.OrderApi__Is_Payment__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__Receipt__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to related Sales Order.</description>
        <inlineHelpText>**System Calculated/Override** Link to related Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Live! Event venues</description>
    <fields>
        <fullName>Integration_Controller__c</fullName>
        <label>Integration Controller</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Event_Details__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Virtual Event Details</relationshipLabel>
        <relationshipName>Virtual_Event_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhibit_Open__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the virtual exhibit open for users to visit?</inlineHelpText>
        <label>Exhibit Open</label>
        <type>Checkbox</type>
    </fields>
    <label>Virtual Event Details</label>
    <nameField>
        <label>Virtual Event Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LiveTicketConfirmationController.cls
/**
 * Created by lauren.lezberg on 10/5/2020.
 */

public without sharing class LiveTicketConfirmationController {
    public BR_Event__c evt { get; set; }
    public String receiptId { get; set; }
    public String location {get;set;}
    public String StartDate {get;set;}
    public String EndDate {get;set;}

    public LiveTicketConfirmationController() {
        String salesOrderId = ApexPages.currentPage().getParameters().get('salesOrder');
        receiptId = ApexPages.currentPage().getParameters().get('receipt');
        if(receiptId==null){
            List<OrderApi__Receipt__c> recs = [SELECT Id FROM OrderApi__Receipt__c WHERE OrderApi__Sales_Order__c=:salesOrderId];
            receiptId = recs[0].Id;
        }
        List<OrderApi__Sales_Order_Line__c> ticketLines = [SELECT Id, OrderApi__Item__r.AC_Event__c, OrderApi__Item__r.AC_Event__r.Parent_Event__c FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c = :salesOrderId AND OrderApi__Item_Class__r.Name = 'Live Event Tickets'];

        if (ticketLines.size() == 1) {
            evt = [SELECT Name, Id, Virtual_Venue__c, Portal_Event_Link__c, Display_on_Confirmation_Page__c , Show_Confirmation_Page_Logos__c, View_Confirmation_Page_Horizontally__c,
                            Ticket_Purchase_Confirmation_Message__c, Main_Image_Filename__c, Start_Date__c, End_Date__c, Description__c, Venue__c,
                            Venue__r.Name, Draft_Program__c
                    FROM BR_Event__c
                    WHERE Parent_Event__c=null
                    AND Id = :ticketLines[0].OrderApi__Item__r.AC_Event__c];
            //Create short datetime format in guest timezone for AddToCalendar cmp
            StartDate = evt.Start_Date__c.format();
            EndDate  = evt.End_Date__c.format();



//            TimeZone targetTimezone = TimeZone.getTimeZone('America/New_York');
//            Integer offsetSeconds = targetTimezone.getOffset(evt.Start_Date__c) / 1000;
//            Datetime targetDatetime = evt.Start_Date__c.addSeconds(offsetSeconds);
//            evt.Start_Date__c = targetDatetime;
//
//            offsetSeconds = targetTimezone.getOffset(evt.End_Date__c) / 1000;
//            targetDatetime = evt.End_Date__c.addSeconds(offsetSeconds);
//            evt.End_Date__c = targetDatetime;

            if(evt.Virtual_Venue__c == null){
                location = evt.Venue__r.Name;
            }else{
                location = 'https://' + evt.Portal_Event_Link__c;
            }
        } else {
            OrderApi__Sales_Order_Line__c ticketLine;
            for(OrderApi__Sales_Order_Line__c line : ticketLines){
                if(line.OrderApi__Item__r.AC_Event__r.Parent_Event__c == null){
                    ticketLine = line;
                }
            }
            evt = [SELECT Name, Id, Virtual_Venue__c, Portal_Event_Link__c, Display_on_Confirmation_Page__c , Show_Confirmation_Page_Logos__c, View_Confirmation_Page_Horizontally__c,Ticket_Purchase_Confirmation_Message__c, Main_Image_Filename__c, Start_Date__c, End_Date__c, Description__c, Venue__c, Venue__r.Name, Draft_Program__c FROM BR_Event__c WHERE Parent_Event__c=null AND Id = :ticketLine.OrderApi__Item__r.AC_Event__c];
            StartDate = evt.Start_Date__c.format();
            EndDate  = evt.End_Date__c.format();
            if(evt.Virtual_Venue__c == null){
                location = evt.Venue__r.Name;
            }else{
                location = 'https://' + evt.Portal_Event_Link__c;
            }
        }
    }

    public PageReference checkExhibitStatus(){
        String salesOrderId = ApexPages.currentPage().getParameters().get('salesOrder');
        List<OrderApi__Sales_Order_Line__c> ticketLines = [SELECT Id, OrderApi__Sales_Order__r.OrderApi__Contact__c, OrderApi__Item__r.AC_Event__c, OrderApi__Item__r.AC_Event__r.Parent_Event__c FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c = :salesOrderId AND OrderApi__Item_Class__r.Name = 'Live Event Tickets'];
        OrderApi__Sales_Order_Line__c ticketLine;
        for(OrderApi__Sales_Order_Line__c line : ticketLines){
            if(line.OrderApi__Item__r.AC_Event__r.Parent_Event__c == null){
                ticketLine = line;
            }
        }
        evt = [SELECT Name, Id, Display_on_Confirmation_Page__c, Show_Confirmation_Page_Logos__c, View_Confirmation_Page_Horizontally__c, Virtual_Venue__c, Virtual_Venue__r.Name, Virtual_Venue__r.Integration_Controller__c, Portal_Event_Link__c, Ticket_Purchase_Confirmation_Message__c, Main_Image_Filename__c, Start_Date__c, End_Date__c, Description__c, Venue__c, Venue__r.Name, Draft_Program__c FROM BR_Event__c WHERE Parent_Event__c=null AND Id = :ticketLines[0].OrderApi__Item__r.AC_Event__c];
        if(evt.Virtual_Venue__c!=null) { //if virtual event

            List<Virtual_Event_Details__c> veds = [SELECT Exhibit_Open__c
                                            FROM Virtual_Event_Details__c
                                            WHERE Event__c = :ticketLines[0].OrderApi__Item__r.AC_Event__c];
            if(veds.size()==1){
                if(veds[0].Exhibit_Open__c){//if exhibit open, send user to event
                    Callable extension = (Callable) Type.forName(evt.Virtual_Venue__r.Integration_Controller__c).newInstance();
                    String evtURL = (String) extension.call('goToVenue', new Map<String, Object>{
                            'contactId' => (String) ticketLine.OrderApi__Sales_Order__r.OrderApi__Contact__c, 'SFEventId' => evt.Id
                    });
                    System.debug('evtURL: ' + evtURL);
                    if(evt.Virtual_Venue__r.Name == 'Freeman'){
                        return new PageReference('/FreemanRedirect?venueURL=' + evtURL);
                    } else {
                        return new PageReference(evtURL);
                    }
                }
            }

        }

        return null;
    }

}