src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BrEvents_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Label__c</fullName>
        <description>Settings variable label</description>
        <inlineHelpText>Settings variable label</inlineHelpText>
        <label>Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BrEvents Settings</label>
</CustomObject>

src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BackOfficeLOPControllerTest.cls
/**
 * Created by afaf.awad on 10/15/2020.
 */

@IsTest
private class BackOfficeLOPControllerTest {

    @testSetup
    public static void setup(){
        Account acc = LiveTestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = LiveTestDataFactory.buildContact(acc.Id);
        con.FirstName = 'Zono';
        insert con;

//      ***LIVE EVENT OBJECTS***
        BR_Event__c event = LiveTestDataFactory.buildEvent('Test Event', false, false);
        insert event;

        BR_Participation__c part = new BR_Participation__c(BR_Event__c = event.Id,Contact__c = con.Id);
        insert part;

        BR_Participation__c partNull = new BR_Participation__c(BR_Event__c = event.Id);
        insert partNull;

        List<OrgWideEmailAddress> owas = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        System.assertEquals(owas.size(), 1);
        insert new BrEvents_Settings__c(Name='org wide email id', Label__c = 'org wide email id', Value__c = owas[0].Id);

//        ***FONTEVA EVENT OBJECTS***

        EventApi__Event__c fonEvent = TestDataFactory.buildEvent();
        insert fonEvent;

        EventApi__Attendee__c att = new EventApi__Attendee__c(EventApi__Contact__c=con.Id, EventApi__Event__c=fonEvent.Id);
        insert att;

    }

    @IsTest
    static void test_getLOP() {
        String participant = [SELECT Id FROM BR_Participation__c LIMIT 1].Id;
        Test.startTest();
        Boolean disabled = BackOfficeLOPController.getLOP(participant);

        BR_Event__c event = [SELECT End_Date__c FROM BR_Event__c LIMIT 1];
        event.Start_Date__c = System.now() -2;
        event.End_Date__c = System.now()-1;
        update event;

        Boolean enable = BackOfficeLOPController.getLOP(participant);
        Test.stopTest();
        System.assertEquals(true,enable);
        System.assertEquals(false,disabled);


    }

    @IsTest
    static void test_getDomain(){
        Test.startTest();
        String domain = BackOfficeLOPController.getDomain();
        Test.stopTest();
        System.assertEquals('Test domain', domain);
    }


    @IsTest
    static void test_sendPDF() {
        List<BR_Participation__c> participant = [SELECT Id, Contact__c FROM BR_Participation__c];

        String body = 'Testing Email Messaging with merge fields : {!BR_Event__c} and {!First_Name}';

//        EmailTemplate e = new EmailTemplate (developerName = 'Test_Email'
//                                            , FolderId = userInfo.getUserId()
//                                            , TemplateType= 'Text'
//                                            , Name = 'Letter of Participation'
//                                            , HtmlValue = body);
//
//        insert e;

        Test.startTest();
        BackOfficeLOPController.EmailResults withContact;

        for(BR_Participation__c p : participant) {
            if(p.Contact__c != null) {
               withContact = BackOfficeLOPController.sendPDF(p.Id);
            }else {
                BackOfficeLOPController.sendPDF(p.Id);
            }
        }
        System.assertEquals('Letter emailed!',withContact.message);
        Test.stopTest();
    }


    @IsTest
    static void test_sendPDF_Fon() {
        List<EventApi__Attendee__c> att = [SELECT Id, EventApi__Contact__c FROM EventApi__Attendee__c];

        String body = 'Testing Email Messaging with merge fields : {!BR_Event__c} and {!First_Name}';

        Test.startTest();
        BackOfficeLOPController.EmailResults results;

        for(EventApi__Attendee__c a : att) {
                results = BackOfficeLOPController.sendPDF_Fon(a.Id);
        }
        System.assertEquals('Letter emailed!',results.message);
        Test.stopTest();
    }
}