src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Registration_Confirmation_Message__c</fullName>
        <inlineHelpText>Used for registration confirmation email.</inlineHelpText>
        <label>Registration Confirmation Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reminder_Hours__c</fullName>
        <defaultValue>&quot;1;24;168;&quot;</defaultValue>
        <label>Reminder Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Message1__c</fullName>
        <description>Used for mail merge reminder email</description>
        <inlineHelpText>Used for mail merge reminder email</inlineHelpText>
        <label>First reminder message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reminder_Message2__c</fullName>
        <label>Second reminder message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reminder_Message3__c</fullName>
        <label>Third reminder message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Send_reminders__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send reminders</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone to show to public</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>(GMT+14:00) Line Is. Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:45) Chatham Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:00) Phoenix Is. Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:00) Tonga Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:00) New Zealand Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:45) Chatham Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) Petropavlovsk-Kamchatski Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) New Zealand Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) Fiji Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Solomon Is. Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Norfolk Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Lord Howe Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Australian Eastern Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:30) Lord Howe Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:30) Australian Central Daylight Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:00) Australian Eastern Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:30) Australian Central Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:00) Korea Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:00) Japan Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Hong Kong Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Malaysia Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Philippines Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) China Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Singapore Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Australian Western Standard Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+07:00) Indochina Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+07:00) West Indonesia Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+06:30) Myanmar Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+06:00) Bangladesh Time</fullName>
                </value>
                <value>
                    <fullName>(GMT+05:45) Nepal Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue_Address__c</fullName>
        <label>Venue Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrSendRemindersForEvents.cls
global without sharing class BrSendRemindersForEvents implements Schedulable {

    global void execute(SchedulableContext sc) {
        sendEventReminders();
    }

    public void sendEventReminders() {
        Datetime currentDateTime = Datetime.now();
        Set<Id> eventsId = new Set<Id>();
        List<Integer> reminderNum = new List<Integer>();

        for (BR_Event__c event : [
                SELECT Id, Name, Reminder_Hours__c, Start_Date__c
                FROM BR_Event__c
                WHERE Send_reminders__c = TRUE AND
                Start_Date__c > :currentDateTime])  //AND (End_Date__c = NULL OR End_Date__c > :currentDateTime)
        {

            System.debug('----event: ' + event.Name);

            if (event.Reminder_Hours__c != null) {
                List<String> reminderHours = new List<String>();
                String reminderHoursData = event.Reminder_Hours__c;

                if (reminderHoursData.contains(';')) {
                    reminderHours = reminderHoursData.split(';');
                } else if (reminderHoursData.contains(',')) {
                    reminderHours = reminderHoursData.split(',');
                }
                System.debug('----reminderHours: ' + reminderHours);
                System.debug('----reminderHours.size()-1: ' + reminderHours.size());
                if (!reminderHours.isEmpty()) {

                    for (Integer rem = 0; rem <=  reminderHours.size()-1; rem ++) {

                        Datetime reminderDateTime = currentDateTime.addHours(Integer.valueOf(reminderHours[rem]));
                        System.debug('----reminderDateTime: ' + reminderDateTime);
                        System.debug('----reminderHours[rem]: ' + reminderHours[rem]);

                        Datetime startDatetime = event.Start_Date__c;
                        System.debug('----startDatetime: ' + startDatetime);

                        Integer diffMinutes = reminderDateTime.minute() - startDatetime.minute();
                        System.debug('----diffMinutes: ' + diffMinutes);

                        if (startDatetime.date() == reminderDateTime.date() &&
                                startDatetime.hour() == reminderDateTime.hour() &&
                                diffMinutes >= 0 && diffMinutes < 30) {
                            System.debug('----GOTCHA rem: ' + rem);
                            System.debug('----add event: ' + event.name);
                            System.debug('----final rem: ' + rem);

                            reminderNum.add(rem);
                            eventsId.add(event.Id);
                            System.debug('----final reminderNum: ' + reminderNum);
                        }
                    }
                }
            }
        }

        if (!eventsId.isEmpty()) {
            System.debug('----BrSendRemindersForEvents.createEmails( eventsId: ' + eventsId + ', currentDateTime: ' + currentDateTime + ', reminderNum:' + reminderNum.get(0)+ ')');
//            List<Messaging.SingleEmailMessage> emails = BrSendRemindersForEvents.createEmails(eventsId, currentDateTime, reminderNum.get(0));
            List<Messaging.SingleEmailMessage> emails = BrSendRemindersForEvents.createEmails(eventsId, currentDateTime, reminderNum);

            if (!emails.isEmpty()) {
                try {
                    Messaging.sendEmail(emails);
                } catch (EmailException ex) {
                    System.debug(ex.getMessage());
                }
            }
        }
    }

    public static List<Messaging.SingleEmailMessage> createEmails(Set<Id> eventsId, Datetime currentDateTime, List<Integer> reminderNums) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        EmailTemplate emailTemplate = new emailTemplate();
        System.debug('---- I`m in createEmails ---- ');
        System.debug('----reminderNums (0-2) : ' + reminderNums);



        String orgName = UserInfo.getOrganizationName();
        String emailSetting = '';
        String orgWideEmailId = BrEventsHelper.getConfigValue('org wide email id');
        List<OrgWideEmailAddress> emailAddresses = [
                SELECT Id, Address
                FROM OrgWideEmailAddress
                WHERE Id = :orgWideEmailId
        ];


        for (BR_Participation__c participation : [
                SELECT Id, User__c, User__r.Name, Contact__c, Contact__r.Name, BR_Event__r.Timezone__c,
                        BR_Event__r.Name, BR_Event__r.Start_Date__c, Lead__c, Lead__r.Name,
                        BR_Event__r.Venue_Address__c, BR_Event__r.Reminder_Message1__c, BR_Event__r.Reminder_Message2__c,
                        BR_Event__r.Reminder_Message3__c, BR_Event__r.Registration_Confirmation_Message__c
                FROM BR_Participation__c
                WHERE BR_Event__c IN :eventsId
                AND Participate__c = 'Yes'
        ]) {

            Integer idx = 0;
            Integer i = 0;
            for(Id eventId : eventsId){
                if(eventId == participation.BR_Event__c){
                    idx = i;
                }
                i++; 
            }

            if (reminderNums[idx] == 0){
                emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'brEventReminders_1' LIMIT 1];
            } else if (reminderNums[idx] == 1) {
                emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'brEventReminders_2' LIMIT 1];
            } else if (reminderNums[idx] == 2) {
                emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'brEventReminders_3' LIMIT 1];
            } else {
                emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'brEventReminders_1' LIMIT 1];
                System.debug('reminderNum out of range (0-2) and selected 0 by default');
            }

            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            Id targetId = null;
            Id userId = participation.User__c;
            Id contactId = participation.Contact__c;
            Id leadId = participation.Lead__c;

            if (userId != null) {
                targetId = userId;
            } else if (contactId != null) {
                targetId = contactId;
            } else if (leadId != null) {
                targetId = leadId;
            }

            if (targetId != null) {
                String body = emailTemplate.HtmlValue;

                String userName = participation.User__r.Name;
                userName = (userName == null) ? participation.Contact__r.Name : userName;
                userName = (userName == null) ? participation.Lead__r.Name : userName;

                String eventName = participation.BR_Event__r.Name;

                String reminderMsg1 = participation.BR_Event__r.Reminder_Message1__c;
                String reminderMsg2 = participation.BR_Event__r.Reminder_Message2__c;
                String reminderMsg3 = participation.BR_Event__r.Reminder_Message3__c;

                Integer diffMinutes = 0;
                String eventTimezone = participation.BR_Event__r.Timezone__c;
                String userTimezone = UserInfo.getTimeZone().toString();

                if (eventTimezone != null) {
                    diffMinutes = BrEventsReminderHelper.getDiffMinutesBetweenTimezones(eventTimezone, userTimezone);
                } else {
                    eventTimezone = '';
                }

                Datetime startDate = participation.BR_Event__r.Start_Date__c.addMinutes(diffMinutes);

                String address = participation.BR_Event__r.Venue_Address__c;
                String conformationMessage = participation.BR_Event__r.Registration_Confirmation_Message__c;
                address = (address == null) ? '' : address;
                String addressURL =  (address == null) ? '' :'https://www.google.com/maps/place/' + address;

                body = emailTemplate.HtmlValue.replace('{!userName}', userName)
                        .replace('{!reminderMsg1}', reminderMsg1)
                        .replace('{!reminderMsg2}', reminderMsg2)
                        .replace('{!reminderMsg3}', reminderMsg3)
                        .replace('{!eventName}', eventName)
                        .replace('{!startDate}', startDate.format())
                        .replace('{!gmt}', eventTimezone)
                        .replace('{!location}', address)
                        .replace('{!confirmationMessage}',conformationMessage)
                        .replace('{!locationURL}', addressURL);

                String subject = Label.br_lbleventreminder + ': ' + + eventName;

                email.setHtmlBody(body);
                if (emailAddresses.isEmpty()) {
                    email.setSenderDisplayName(orgName);
                } else {
                    email.setOrgWideEmailAddressId(emailAddresses[0].Id);
                }
                email.setTargetObjectId(targetId);
                email.setTemplateId(emailTemplate.Id);
                email.setSubject(subject);
                email.setWhatId(participation.Id);
                email.setSaveAsActivity(false);
                emails.add(email);

            }
        }
        return emails;
    }

//    public static List<Messaging.SingleEmailMessage> createEmails(Set<Id> eventsId, Datetime currentDateTime, Integer reminderNum) {
//        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
//        EmailTemplate emailTemplate = new emailTemplate();
//        System.debug('---- I`m in createEmails ---- ');
//        System.debug('----reminderNum (0-2) : ' + reminderNum);
//
//        if (reminderNum == 0){
//            emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'brEventReminders_1' LIMIT 1];
//        } else if (reminderNum == 1) {
//            emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'brEventReminders_2' LIMIT 1];
//        } else if (reminderNum == 2) {
//            emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'brEventReminders_3' LIMIT 1];
//        } else {
//            emailTemplate = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'brEventReminders_1' LIMIT 1];
//            System.debug('reminderNum out of range (0-2) and selected 0 by default');
//        }
//
//        String orgName = UserInfo.getOrganizationName();
//        String emailSetting = '';
//        String orgWideEmailId = BrEventsHelper.getConfigValue('org wide email id');
//        List<OrgWideEmailAddress> emailAddresses = [
//                SELECT Id, Address
//                FROM OrgWideEmailAddress
//                WHERE Id = :orgWideEmailId
//        ];
//
//        for (BR_Participation__c participation : [
//                SELECT Id, User__c, User__r.Name, Contact__c, Contact__r.Name, BR_Event__r.Timezone__c,
//                        BR_Event__r.Name, BR_Event__r.Start_Date__c, Lead__c, Lead__r.Name,
//                        BR_Event__r.Venue_Address__c, BR_Event__r.Reminder_Message1__c, BR_Event__r.Reminder_Message2__c,
//                        BR_Event__r.Reminder_Message3__c, BR_Event__r.Registration_Confirmation_Message__c
//                FROM BR_Participation__c
//                WHERE BR_Event__c IN :eventsId
//                AND Participate__c = 'Yes'
//        ]) {
//
//            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
//            Id targetId = null;
//            Id userId = participation.User__c;
//            Id contactId = participation.Contact__c;
//            Id leadId = participation.Lead__c;
//
//            if (userId != null) {
//                targetId = userId;
//            } else if (contactId != null) {
//                targetId = contactId;
//            } else if (leadId != null) {
//                targetId = leadId;
//            }
//
//            if (targetId != null) {
//                String body = emailTemplate.HtmlValue;
//
//                String userName = participation.User__r.Name;
//                userName = (userName == null) ? participation.Contact__r.Name : userName;
//                userName = (userName == null) ? participation.Lead__r.Name : userName;
//
//                String eventName = participation.BR_Event__r.Name;
//
//                String reminderMsg1 = participation.BR_Event__r.Reminder_Message1__c;
//                String reminderMsg2 = participation.BR_Event__r.Reminder_Message2__c;
//                String reminderMsg3 = participation.BR_Event__r.Reminder_Message3__c;
//
//                Integer diffMinutes = 0;
//                String eventTimezone = participation.BR_Event__r.Timezone__c;
//                String userTimezone = UserInfo.getTimeZone().toString();
//
//                if (eventTimezone != null) {
//                    diffMinutes = BrEventsReminderHelper.getDiffMinutesBetweenTimezones(eventTimezone, userTimezone);
//                } else {
//                    eventTimezone = '';
//                }
//
//                Datetime startDate = participation.BR_Event__r.Start_Date__c.addMinutes(diffMinutes);
//
//                String address = participation.BR_Event__r.Venue_Address__c;
//                String conformationMessage = participation.BR_Event__r.Registration_Confirmation_Message__c;
//                address = (address == null) ? '' : address;
//                String addressURL =  (address == null) ? '' :'https://www.google.com/maps/place/' + address;
//
//                body = emailTemplate.HtmlValue.replace('{!userName}', userName)
//                        .replace('{!reminderMsg1}', reminderMsg1)
//                        .replace('{!reminderMsg2}', reminderMsg2)
//                        .replace('{!reminderMsg3}', reminderMsg3)
//                        .replace('{!eventName}', eventName)
//                        .replace('{!startDate}', startDate.format())
//                        .replace('{!gmt}', eventTimezone)
//                        .replace('{!location}', address)
//                        .replace('{!confirmationMessage}',conformationMessage)
//                        .replace('{!locationURL}', addressURL);
//
//                String subject = Label.br_lbleventreminder + ': ' + + eventName;
//
//                email.setHtmlBody(body);
//                if (emailAddresses.isEmpty()) {
//                    email.setSenderDisplayName(orgName);
//                } else {
//                    email.setOrgWideEmailAddressId(emailAddresses[0].Id);
//                }
//                email.setTargetObjectId(targetId);
//                email.setTemplateId(emailTemplate.Id);
//                email.setSubject(subject);
//                email.setWhatId(participation.Id);
//                email.setSaveAsActivity(false);
//                emails.add(email);
//
//            }
//        }
//        return emails;
//    }
}