src/objects/BR_Event__c.object
<CustomObject>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Attendee_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Attendee Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BrEvents_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Label__c</fullName>
        <description>Settings variable label</description>
        <inlineHelpText>Settings variable label</inlineHelpText>
        <label>Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BrEvents Settings</label>
</CustomObject>

src/objects/vFairs_Session__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>vFairs api keys</description>
    <fields>
        <fullName>API_Key__c</fullName>
        <label>API Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>vFairs Session</label>
</CustomObject>

src/classes/Batch_UpdateCareerFairParticipantsTest.cls
/**
 * Created by lauren.lezberg on 3/17/2021.
 */

@IsTest
private class Batch_UpdateCareerFairParticipantsTest {
    @TestSetup
    public static void setup(){
        List<OrgWideEmailAddress> owas = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        System.assertEquals(owas.size(), 1);

        insert new BrEvents_Settings__c(Name='org wide email id', Label__c = 'org wide email id', Value__c = owas[0].Id);

        insert new vFairs_Session__c(API_Key__c = '92348u34');

        BR_Event__c event = LiveTestDataFactory.buildEvent('Test Event', false, false);
        insert event;

        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;


        List<ContentVersion> cvs = new List<ContentVersion>();
        List<ContentDocumentLink> cdls = new List<ContentDocumentLink>();


        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(System.Label.Contact_Non_Member_Record_Type).getRecordTypeId();
        List<Contact> contacts = new List<Contact>();
        String yourFilesContent = 'TEST FILE';
        Map<String, String> fileMap = new Map<String, String>();
        for(Integer i = 0 ; i< 5;i++){
            Contact con = new Contact(LastName = 'Test contact' + i,
                    AccountId = acc.Id,
                    RecordTypeId = recordTypeId,
                    Phone ='9878986789',
                    Fax = 'fax',
                    Email = 'testEmail' + i + '@yopmail.com');
            contacts.add(con);

            ContentVersion cv = new ContentVersion(
                    ContentLocation = 'S', // to use S specify this document is in Salesforce, to use E for external files
                    PathOnClient = 'Resume.txt',// The files name, extension is very important here which will help the file in preview.
                    Title = 'Resume.txt',// Display name of the files
                    VersionData = EncodingUtil.base64Decode(yourFilesContent + String.valueOf(i)));
            cvs.add(cv);

        }

        insert contacts;

        insert cvs;
        cvs = [SELECT ContentDocumentId FROM ContentVersion WHERE Id IN: cvs];
        contacts = [SELECT Id FROM Contact];

        for(Integer i =0 ; i<contacts.size();i++){
            cdls.add(New ContentDocumentLink(
                    LinkedEntityId = contacts[i].Id, // Specify RECORD ID here i.e Any Object ID (Standard Object/Custom Object)
                    ContentDocumentId = cvs[0].ContentDocumentId,  //ContentDocumentId Id from ContentVersion
                    shareType = 'V'));
        }

        insert cdls;

        List<BR_Participation__c> participants = new List<BR_Participation__c>();
        Integer counter = 0;
        for(Contact con: contacts){
            participants.add(new BR_Participation__c(
                    Participate__c = 'Yes',
                    External_Attendee_Id__c = '123' + counter,
                    Contact__c=con.Id,
                    BR_Event__c=event.Id,
                    Bypass_Confirmation__c = true)
            );
            counter++;
        }
        insert participants;



    }

    @IsTest
    static void testBatch() {
        BR_Event__c evt = [SELECT Id FROM BR_Event__c];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CreateMockHttpResponseGenerator());

        Batch_UpdateCareerFairParticipants btch = new Batch_UpdateCareerFairParticipants(evt.Id);
        database.executeBatch(btch);

        Test.stopTest();
    }

    public class CreateMockHTTPResponseGenerator implements HttpCalloutMock{
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"id": "83459843758947594"}');
            res.setStatusCode(200);
            return res;
        }
    }
}