src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>BR_Events_Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>BR_Events_Zone__c</referenceTo>
        <relationshipName>BR_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Preferences_Form_Fieldset__c</fullName>
        <label>Event Preferences Form Fieldset</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Confirmation_Message__c</fullName>
        <inlineHelpText>Used for registration confirmation email.</inlineHelpText>
        <label>Registration Confirmation Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Registration_Form_Fieldset__c</fullName>
        <label>Registration Form Fieldset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Venue at which the event will take place</description>
        <label>Physical Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>AC_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Virtual_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipName>Virtual_ACEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Events_Zone__c.object
<CustomObject>
    <label>AC Events Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BrEvents_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Label__c</fullName>
        <description>Settings variable label</description>
        <inlineHelpText>Settings variable label</inlineHelpText>
        <label>Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BrEvents Settings</label>
</CustomObject>

src/objects/Venue__c.object
<CustomObject>
    <description>Live! Event venues</description>
    <fields>
        <fullName>Base_URL__c</fullName>
        <label>Base URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Controller__c</fullName>
        <label>Integration Controller</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <recordTypes>
        <fullName>Virtual</fullName>
        <active>true</active>
        <label>Virtual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Event_Details__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Virtual Event Details</relationshipLabel>
        <relationshipName>Virtual_Event_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Event_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Event Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zoom_Type__c</fullName>
        <label>Zoom Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zoom_User_Id__c</fullName>
        <label>Zoom User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Virtual Event Details</label>
    <nameField>
        <label>Virtual Event Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zoom_Session__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <label>Client Secret</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Zoom Session</label>
</CustomObject>

src/classes/LiveEventTriggerTest.cls
/**
 * Created by lauren.lezberg on 11/5/2020.
 */

@IsTest
private class LiveEventTriggerTest {


    @IsTest
    static void testUpdate() {
        List<OrgWideEmailAddress> owas = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        System.assertEquals(owas.size(), 1);

        insert new BrEvents_Settings__c(Name='org wide email id', Label__c = 'org wide email id', Value__c = owas[0].Id);

        insert new Zoom_Session__c(Client_Id__c = '92348u34', Client_Secret__c='4580568406856');

        BR_Events_Zone__c zone = LiveTestDataFactory.buildZone('Test Zone', true);
        insert zone;

        Id virtualRecordTypeId = Schema.SObjectType.Venue__c.getRecordTypeInfosByName().get('Virtual').getRecordTypeId();
        Venue__c ven = new Venue__c(Name='Zoom', RecordTypeId=virtualRecordTypeId, Integration_Controller__c='V_ZoomIntegration', Base_URL__c = 'https://aacr.zoom.us/j/');
        insert ven;
        Venue__c ven2 = new Venue__c(Name='PathLMS', RecordTypeId=virtualRecordTypeId, Integration_Controller__c='V_PathLMSIntegration', Base_URL__c = 'https://www.pathlms.com/aacr/courses/');
        insert ven2;

        BR_Event__c testEvent = new BR_Event__c(
                Name = 'Test event0',
                Virtual_Venue__c = ven.Id,
                Start_Date__c = Datetime.newInstance(2016, 10, 15, 12, 30, 0),
                End_Date__c = Datetime.newInstance(2016, 10, 15, 17, 30, 0),
                Event_Preferences_Form_Fieldset__c = 'test',
                Registration_Form_Fieldset__c = 'Registration_Basic',
                Registration_Confirmation_Message__c = 'TEST MESSAGE'
        );
        insert testEvent;

        Virtual_Event_Details__c ved = new Virtual_Event_Details__c(Event__c=testEvent.Id, External_Event_Id__c='1234', Zoom_Type__c='Meeting', Zoom_User_Id__c='5555');
        insert ved;

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        testEvent.End_Date__c = Datetime.newInstance(2016, 10, 16, 17, 30, 0);
        update testEvent;

        testEvent.Virtual_Venue__c = ven2.Id;
        update testEvent;

        testEvent.Virtual_Venue__c = ven.Id;
        update testEvent;

        Test.stopTest();
    }

    @IsTest
    static void testDelete() {
        List<OrgWideEmailAddress> owas = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        System.assertEquals(owas.size(), 1);

        insert new BrEvents_Settings__c(Name='org wide email id', Label__c = 'org wide email id', Value__c = owas[0].Id);

        insert new Zoom_Session__c(Client_Id__c = '92348u34', Client_Secret__c='4580568406856');

        BR_Events_Zone__c zone = LiveTestDataFactory.buildZone('Test Zone', true);
        insert zone;

        Id virtualRecordTypeId = Schema.SObjectType.Venue__c.getRecordTypeInfosByName().get('Virtual').getRecordTypeId();
        Venue__c ven = new Venue__c(Name='Zoom', RecordTypeId=virtualRecordTypeId, Integration_Controller__c='V_ZoomIntegration', Base_URL__c = 'https://aacr.zoom.us/j/');
        insert ven;

        BR_Event__c testEvent = new BR_Event__c(
                Name = 'Test event0',
                Virtual_Venue__c = ven.Id,
                Start_Date__c = Datetime.newInstance(2016, 10, 15, 12, 30, 0),
                End_Date__c = Datetime.newInstance(2016, 10, 15, 17, 30, 0),
                Event_Preferences_Form_Fieldset__c = 'test',
                Registration_Form_Fieldset__c = 'Registration_Basic',
                Registration_Confirmation_Message__c = 'TEST MESSAGE'
        );
        insert testEvent;

        Virtual_Event_Details__c ved = new Virtual_Event_Details__c(Event__c=testEvent.Id, External_Event_Id__c='1234', Zoom_Type__c='Meeting', Zoom_User_Id__c='5555');
        insert ved;

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        delete testEvent;

        Test.stopTest();
    }

    public class MockHTTPResponseGenerator implements HttpCalloutMock{
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            return res;
        }
    }


}