src/objects/BR_Event__c.object
<CustomObject>
    <fields>
        <fullName>BR_Events_Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>BR_Events_Zone__c</referenceTo>
        <relationshipName>BR_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Event is not published.</inlineHelpText>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publicly_available__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Event is available for users to purchase tickets.</inlineHelpText>
        <label>Publicly available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Unlisted_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Unlisted events will not appear in the portal for general purchase but will still be open for ticket sales.</inlineHelpText>
        <label>Unlisted Event</label>
        <type>Checkbox</type>
    </fields>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <recordTypes>
        <fullName>Cancelled</fullName>
        <active>true</active>
        <description>Event has been cancelled</description>
        <label>Cancelled</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Events_Zone__c.object
<CustomObject>
    <label>AC Events Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrDatePickerController.cls
public without sharing class BrDatePickerController {

    @AuraEnabled
    public static List<BR_Event__c> getEventsForMonth(String zoneId, Integer year, Integer month) {

        List<BR_Event__c> itemsList = new List<BR_Event__c>();

        if(!BrEventsHelper.performAccessCheck('read', 'BR_Event__c', null)
                || !BrEventsHelper.performAccessCheck('read', 'BR_Participation__c', null))
            return itemsList;

        year = Integer.valueOf(year);
        month = Integer.valueOf(month);
        String currentTimeGMT = DateTime.now().formatGmt('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'');
        Integer numberOfDays = Date.daysInMonth(year, month);
        DateTime monthDateStartGMT = DateTime.newInstanceGMT(year, month, 1);
        DateTime monthDateEndGMT = DateTime.newInstanceGMT(year, month, numberOfDays, 23, 59, 0);

        String query = 'SELECT Start_Date__c, (SELECT Participate__c FROM BR_Participations__r' +
                ' WHERE User__c = \'' + UserInfo.getUserId() +'\' AND Participate__c = \'Yes\')' +
                ' FROM BR_Event__c WHERE BR_Events_Zone__c = \'' + zoneId + '\' AND Start_Date__c > YESTERDAY' +
                ' AND Start_Date__c > ' + monthDateStartGMT.formatGmt('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'') + ' AND Start_Date__c < '
                + monthDateEndGMT.formatGmt('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'') + ' AND RecordType.Name!=\'Cancelled\'';

        query += (UserInfo.getUserType() == 'Guest') ? ' AND Publicly_available__c = true' : '';
        query += ' AND Draft__c = FALSE';
        List<BR_Participation__c> participations = [
                SELECT BR_Event__c
                FROM BR_Participation__c
                WHERE User__c = :UserInfo.getUserId() AND Participate__c = 'Yes'
        ];
        List<Id> eventsUserIsParticipating = new List<Id>();

        for (BR_Participation__c participation : participations) {
            eventsUserIsParticipating.add(participation.BR_Event__c);
        }

        if (eventsUserIsParticipating.isEmpty()) {
            query += ' AND Unlisted_Event__c = FALSE';
        } else {
            query += ' AND (Unlisted_Event__c = FALSE OR Id IN (\'' + String.join(eventsUserIsParticipating, '\', \'') + '\') )';
        }

        itemsList = Database.query(query);

        List<BR_Event__c> itemListFormatted = new List<BR_Event__c>();

        for (BR_Event__c item : itemsList) {
            item.Start_Date__c = DateTime.newInstanceGmt(item.Start_Date__c.date(), item.Start_Date__c.time());
            itemListFormatted.add(item);
        }

        return itemsList;
    }
}