src/objects/BR_Event__c.object
<CustomObject>
    <label>Live Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Live Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>BR_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bypass_Confirmation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Confirmation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Meeting_Links__mdt.object
<CustomObject>
    <description>links for virtual meetings</description>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Event_Id__c</fullName>
        <label>Live Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Virtual Meeting Links</label>
    <pluralLabel>Virtual Meetings Links</pluralLabel>
</CustomObject>

src/classes/AttendeeToParticipantTriggerHandler.cls
/**
 * Created by lauren.lezberg on 9/1/2020.
 */

public with sharing class AttendeeToParticipantTriggerHandler {
    public static List<Virtual_Meeting_Links__mdt> links {get;set;}



    public static void createMatchingParticipants(List<EventApi__Attendee__c> attendees){

        Map<Id, Id> eventIdMap = new Map<Id, Id>();
        List<Virtual_Meeting_Links__mdt> mtdMeetings = new List<Virtual_Meeting_Links__mdt>();
        if(Test.isRunningTest()){
            mtdMeetings = links;
        } else {
            mtdMeetings = [SELECT Id, Live_Event_Id__c,Event_Id__c FROM Virtual_Meeting_Links__mdt WHERE Live_Event_Id__c !=NULL AND Event_Id__c!=NULL];
        }
        for(Virtual_Meeting_Links__mdt m : mtdMeetings){
            eventIdMap.put(m.Event_Id__c, m.Live_Event_Id__c);
        }


        //get all attendee records that have an evt mtd record with a matching live event
        List<EventApi__Attendee__c> validAttendees = [SELECT EventApi__Contact__c, EventApi__Event__c FROM EventApi__Attendee__c WHERE Id IN: attendees AND EventApi__Event__c IN: eventIdMap.keySet()];
        if(!validAttendees.isEmpty()) {
            Set<Id> contactIds = new Set<Id>();
            for (EventApi__Attendee__c att : validAttendees) {
                contactIds.add(att.EventApi__Contact__c);
            }

            //get contact user map
            List<User> users = [SELECT ContactId, Id FROM User WHERE ContactId IN:contactIds];
            Map<Id, Id> contactUserMap = new Map<Id, Id>();
            for (User u : users) {
                contactUserMap.put(u.ContactId, u.Id);
            }

            List<BR_Participation__c> participations = new List<BR_Participation__c>();
            for (EventApi__Attendee__c att : validAttendees) {
                BR_Participation__c p = new BR_Participation__c();
                p.Contact__c = att.EventApi__Contact__c;
                p.Participate__c = 'Yes';
                p.Bypass_Confirmation__c = true;
                p.BR_Event__c = eventIdMap.get(att.EventApi__Event__c);
                p.User__c = contactUserMap.get(att.EventApi__Contact__c);
                participations.add(p);
            }

            try {
                insert participations;

            } catch (Exception e) {
                new AACRCustomException(e.getMessage(), e.getStackTraceString(), 'Attendee/Participation Conversion');
            }
        }
    }

}