src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhibitor_ID__c</fullName>
        <formula>IF( Is_Booth_Staff__c ,  Contact__r.AccountId , null)</formula>
        <label>Exhibitor ID</label>
        <type>Text</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountWebService.cls
/**
 * Created by afaf.awad on 3/10/2021.
 */

@RestResource(urlMapping='/Account/*')
global with sharing class AccountWebService {
    @HttpGet
    global static List<Account> getRecords(){
        List<BR_Participation__c> participations = [Select Contact__r.Account.Name, Contact__r.AccountId from BR_Participation__c where Exhibitor_ID__c != NULL];

        Set<Account> accSet = new Set<Account>();

        for(BR_Participation__c p : participations){
            Account a = new Account(Id = p.Contact__r.AccountId, Name = p.Contact__r.Account.Name);
            accSet.add(a);
        }

        List<Account> accounts = new List<Account>();

        accounts.addAll(accSet);

        return accounts;
    }
}