src/objects/BR_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Live! Events</relationshipLabel>
        <relationshipName>Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BR Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Participations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Email__c.object
<CustomObject>
    <fields>
        <fullName>Exhibitor_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Setting</label>
        <referenceTo>EC_Exhibitor_Setting__c</referenceTo>
        <relationshipLabel>Exhibitor Emails</relationshipLabel>
        <relationshipName>Exhibitor_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exhibitor Email</label>
    <nameField>
        <displayFormat>EE-{0000}</displayFormat>
        <label>Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Exhibitor_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exhibitor Settings</relationshipLabel>
        <relationshipName>Exhibitor_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reply_To__c</fullName>
        <label>Reply To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Name__c</fullName>
        <label>Sender Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verified_Email__c</fullName>
        <formula>If(NOT(ISBLANK(Verified_Domain__c)),LEFT(Exhibitor_Email__c , FIND(&quot;@&quot;, Exhibitor_Email__c )) + Verified_Domain__c, &apos;&apos;)</formula>
        <label>Verified Email</label>
        <type>Text</type>
    </fields>
    <label>Exhibitor Setting</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exhibitor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>EC_Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Email</label>
        <referenceTo>EC_Email__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Slot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_EC_SendEmails.cls
/**
 * Created by afaf.awad on 3/4/2021.
 */

public class Batch_EC_SendEmails implements Database.Batchable<sObject>, Database.AllowsCallouts{

    List<Id> partIds {get;set;}
    EC_Email__c email {get;set;}
    String emailBody {get;set;}
    Time_Slot__c timeSlot {get;set;}
    

        public Batch_EC_SendEmails(List<Id> participantIds, EC_Email__c ecEmail, String body, Time_Slot__c ts){
            partIds = participantIds;
            email = ecEmail;
            emailBody= body;
            timeSlot = ts;
        }

        public Database.QueryLocator start(Database.BatchableContext BC){
            String query = 'SELECT Contact__r.Email, Contact__r.FirstName, Contact__r.LastName FROM BR_Participation__c WHERE Id IN: partIds';
            System.debug('Query: ' + query);
            return Database.getQueryLocator(query);
        }

        public void execute(Database.BatchableContext BC, List<BR_Participation__c> scope){

            try {
                Map<String, String> emailMap = new Map<String, String>();
                for (BR_Participation__c part : scope) {
                    emailMap.put(part.Contact__r.Email, part.Contact__r.FirstName + ' ' + part.Contact__r.LastName);
                }

                PlatformEmailService.callSendGridAPI(emailMap
                        , email.Subject__c
                        , email.Exhibitor_Setting__r.Verified_Email__c
                        , email.Exhibitor_Setting__r.Sender_Name__c != null ? email.Exhibitor_Setting__r.Sender_Name__c : email.Exhibitor_Setting__r.Company__r.Name
                        , email.Exhibitor_Setting__r.Reply_To__c != null ? email.Exhibitor_Setting__r.Reply_To__c : email.Exhibitor_Setting__r.Verified_Email__c
                        , emailbody);

            }catch(Exception e) {
                System.debug('Error on Batch_EC_SendEmails Line number ====> '+ e.getLineNumber() + '--- Exception Message =====> ' + e.getMessage());
                throw new AACRCustomException(e.getMessage(), e.getStackTraceString(), 'Batch_EC_SendEmails');
            }

        }

        public void finish(Database.BatchableContext BC){
            System.debug('finishing Batch_SendEventReminders...');

            System.enqueueJob(new EC_QueueableStripeInvoice(partIds.size(), timeSlot));

        }

    }