src/objects/Community_Permission__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Community Permissions</relationshipLabel>
        <relationshipName>Community_Permissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Permission</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>CP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunityPermissionsCtrl.cls
/**
 * Created by afaf.awad on 3/25/2021.
 */

public with sharing class CommunityPermissionsCtrl {

    public String contactId {get;set;}
    public Boolean ecAccess {get;set;}

    public CommunityPermissionsCtrl(){
        contactId = ECRMUtils.getCurrentLoginUserContactId();
        checkPermissions();
    }

    public void checkPermissions(){
        System.debug('contactId = ' + contactId);
        List<Community_Permission__c> cp = [SELECT Id FROM Community_Permission__c WHERE Contact__c =: contactId];
        System.debug('commPerm = ' + cp);
        if(!cp.isEmpty()) {
            ecAccess = true;
        }else{
            ecAccess = false;
        }
        System.debug('ec access = ' + ecAccess);

    }

}