src/objects/Committee__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual Meeting</fullName>
                </value>
                <value>
                    <fullName>Constituency Group</fullName>
                </value>
                <value>
                    <fullName>Scientific Achievement Award</fullName>
                </value>
                <value>
                    <fullName>Scientific Grant Review</fullName>
                </value>
                <value>
                    <fullName>Standing</fullName>
                </value>
                <value>
                    <fullName>Specialty Group</fullName>
                </value>
                <value>
                    <fullName>Scientific Working Group</fullName>
                </value>
                <value>
                    <fullName>Scientific Task Force</fullName>
                </value>
                <value>
                    <fullName>Journal Editorial Board</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Committee</label>
    <nameField>
        <label>Committee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Committee_Member__c.object
<CustomObject>
    <fields>
        <fullName>Committee_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Committee Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Committees</relationshipLabel>
        <relationshipName>Committee_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Committee_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Committee Name</label>
        <referenceTo>Committee__c</referenceTo>
        <relationshipLabel>Committee Members</relationshipLabel>
        <relationshipName>Committee_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Committee_Type__c</fullName>
        <label>Committee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annual Meeting</fullName>
                </value>
                <value>
                    <fullName>Constituency Group</fullName>
                </value>
                <value>
                    <fullName>Journal Editorial Board</fullName>
                </value>
                <value>
                    <fullName>Scientific Achievement Award</fullName>
                </value>
                <value>
                    <fullName>Scientific Grant Review</fullName>
                </value>
                <value>
                    <fullName>Scientific Task Force</fullName>
                </value>
                <value>
                    <fullName>Scientific Working Group</fullName>
                </value>
                <value>
                    <fullName>Specialty Group</fullName>
                </value>
                <value>
                    <fullName>Standing</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Role__c</fullName>
        <label>Member Role</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advisory Editors</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Associate Editor</fullName>
                </value>
                <value>
                    <fullName>Biostatistical Editor</fullName>
                </value>
                <value>
                    <fullName>Breaking Insights Editor</fullName>
                </value>
                <value>
                    <fullName>Cancer Survivor</fullName>
                </value>
                <value>
                    <fullName>Chair</fullName>
                </value>
                <value>
                    <fullName>Chair-Elect</fullName>
                </value>
                <value>
                    <fullName>Chief Executive Officer</fullName>
                </value>
                <value>
                    <fullName>Co-Chair</fullName>
                </value>
                <value>
                    <fullName>Deputy Editor</fullName>
                </value>
                <value>
                    <fullName>Deputy Editor for Breaking Insights</fullName>
                </value>
                <value>
                    <fullName>Deputy Editor for Controversy and Consensus</fullName>
                </value>
                <value>
                    <fullName>Deputy Editor for Reviews</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Editor for Controvery and Consensus</fullName>
                </value>
                <value>
                    <fullName>Editorial Board Member</fullName>
                </value>
                <value>
                    <fullName>Editor-in-Chief</fullName>
                </value>
                <value>
                    <fullName>Executive Editor</fullName>
                </value>
                <value>
                    <fullName>Ex-Officio</fullName>
                </value>
                <value>
                    <fullName>Fellow</fullName>
                </value>
                <value>
                    <fullName>Founding Chairman of the Board</fullName>
                </value>
                <value>
                    <fullName>Founding Chairman of the Board and President Emeritus</fullName>
                </value>
                <value>
                    <fullName>Immediate Past President</fullName>
                </value>
                <value>
                    <fullName>Journal Board Member</fullName>
                </value>
                <value>
                    <fullName>Liaison</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Member at Large</fullName>
                </value>
                <value>
                    <fullName>Past Chair</fullName>
                </value>
                <value>
                    <fullName>Past President</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Committee Member</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Committee Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Committee Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommitteeCreationTriggerHandler.cls
/**
 * Created by lauren.lezberg on 7/22/2019.
 */

public without sharing class CommitteeCreationTriggerHandler {

    public static void createCommittees(Id salesOrderId, Id contactId){
        System.debug('createCommittees just called with salesOrderId: ' + salesOrderId + ' and contactId: ' + contactId);

        List<OrderApi__Sales_Order_Line__c> lines = [
                SELECT Id, OrderApi__Sales_Order__r.OrderApi__Contact__c, OrderApi__Sales_Order__c, OrderApi__Item_Class__r.Name, OrderApi__Item__r.Name
                FROM OrderApi__Sales_Order_Line__c
                WHERE OrderApi__Sales_Order__c = :salesOrderId AND OrderApi__Item_Class__r.Name = 'Working Groups'
                ORDER BY OrderApi__Sales_Order__c
        ];

        if(lines.size()>0) {

            //get all committee records for contact
            List<Committee_Member__c> committeeMembers = [SELECT Id, End_Date__c, Committee_Name__r.Name FROM Committee_Member__c WHERE Committee_Member__c = :contactId AND (End_Date__c = null OR End_Date__c > TODAY)];
            System.debug('committee member records: ' + committeeMembers);
            if (committeeMembers.size() > 0) {

                Set<String> oldCommitteeNames = new Set<String>();
                for (Committee_Member__c com : committeeMembers) {
                    oldCommitteeNames.add(com.Committee_Name__r.Name);
                }
                System.debug('oldCommmitteeNames: ' + oldCommitteeNames);

                List<String> committeesToAdd = new List<String>();
                for(OrderApi__Sales_Order_Line__c line : lines){
                    if(!oldCommitteeNames.contains(line.OrderApi__Item__r.Name)){
                        committeesToAdd.add(line.OrderApi__Item__r.Name);
                    }
                }
                System.debug('committeesToAdd: ' + committeesToAdd);

            //if there are committee records to add
            List<Committee_Member__c> membershipsToAdd = new List<Committee_Member__c>();
                if(committeesToAdd.size()>0) {
                    List<Committee__c> committees = [SELECT Id, Type__c FROM Committee__c WHERE Name IN:committeesToAdd];
                    System.debug('found committees: ' + committees);

                    if (committees.size() > 0) {
                        for (Committee__c committee : committees) {
                            Committee_Member__c member = new Committee_Member__c();
                            member.Committee_Name__c = committee.Id;
                            member.Committee_Type__c = committee.Type__c;
                            member.Committee_Member__c = contactId;
                            member.Member_Role__c = 'Member';
                            member.Start_Date__c = Date.today();
                            membershipsToAdd.add(member);
                        }
                    }
                }
                System.debug('membershipsToAdd: ' + membershipsToAdd);

                //deselected committee member record update
                Set<String> newCommitteeNames = new Set<String>();
                for (OrderApi__Sales_Order_Line__c line : lines) {
                    newCommitteeNames.add(line.OrderApi__Item__r.Name);
                }
                System.debug('newCommitteeNames: ' + newCommitteeNames);

            List<Committee_Member__c> recordsToUpdate = new List<Committee_Member__c>();
                if(newCommitteeNames.size()>0) {
                    for (Committee_Member__c mem : committeeMembers) {
                        if (!newCommitteeNames.contains(mem.Committee_Name__r.Name)) {
                            //update end date of committee member record
                            mem.End_Date__c = Date.today();
                            recordsToUpdate.add(mem);
                        }
                    }
                }
                System.debug('recordsToUpdate: ' + recordsToUpdate);

                insert membershipsToAdd;
                update recordsToUpdate;

            } else {
                System.debug('no committee member records found...adding committee member records...');
                List<String> committeesToAdd = new List<String>();
                for(OrderApi__Sales_Order_Line__c line : lines){
                    committeesToAdd.add(line.OrderApi__Item__r.Name);
                }

                List<Committee_Member__c> membershipsToAdd = new List<Committee_Member__c>();
                if(committeesToAdd.size()>0) {
                    List<Committee__c> committees = [SELECT Id, Type__c FROM Committee__c WHERE Name IN:committeesToAdd];
                    System.debug('found committees: ' + committees);

                    if (committees.size() > 0) {
                        for (Committee__c committee : committees) {
                            Committee_Member__c member = new Committee_Member__c();
                            member.Committee_Name__c = committee.Id;
                            member.Committee_Type__c = committee.Type__c;
                            member.Committee_Member__c = contactId;
                            member.Member_Role__c = 'Member';
                            member.Start_Date__c = Date.today();
                            membershipsToAdd.add(member);
                        }
                    }
                }

                System.debug('membershipsToAdd: ' + membershipsToAdd);
                insert membershipsToAdd;
            }
        }
    }

}