src/objects/Community_Permission__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Community Permissions</relationshipLabel>
        <relationshipName>Community_Permissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Community Permission</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>CP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Permissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <description>Identifies contacts that will receive special consideration as related to a specific AACR campaign.</description>
        <inlineHelpText>Identifies contacts that will receive special consideration as related to a specific AACR campaign.</inlineHelpText>
        <label>Campaign Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/contact_last_accessed_step__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>contacts last accessed step</relationshipLabel>
        <relationshipName>contacts_last_accessed_step</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>contact last accessed step</label>
    <nameField>
        <displayFormat>SN-{0000}</displayFormat>
        <label>RN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>contacts last accessed step</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Join_Process__mdt.object
<CustomObject>
    <description>Types of membership join/renewal processes</description>
    <fields>
        <fullName>Is_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If process is for initial join or renewing of membership</description>
        <label>Is Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>List of items that can be processed for a particular join process</description>
        <label>Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Join Process</label>
    <pluralLabel>Join Processes</pluralLabel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>Is_Reinstatement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Transfer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Transfer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>The status of the Sales Order.</description>
        <inlineHelpText>The status of the Sales Order.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Subscription that is being upgraded or renewed.</description>
        <inlineHelpText>Link to the Subscription that is being upgraded or renewed.</inlineHelpText>
        <label>Subscription (Upgrade/Renew)</label>
        <referenceTo>OrderApi__Subscription__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** The source Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated ** The source Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Sales Order Line (Source)</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>** System Calculated Required ** The status of the Subscription.</description>
        <inlineHelpText>** System Calculated Required ** The status of the Subscription.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MemberProfileController.cls
/**
 * Created by lauren.lezberg on 2/14/2019.
 */

public with sharing class MemberProfileController {
    public String contactId {get;set;}
    public Boolean ecAccess {get;set;}

    public MemberProfileController(){
        contactId = ECRMUtils.getCurrentLoginUserContactId();
        checkPermissions();
    }


    public void checkPermissions(){
        System.debug('contactId = ' + contactId);
        List<Community_Permission__c> cp = [SELECT Id FROM Community_Permission__c WHERE Contact__c =: contactId];
        System.debug('commPerm = ' + cp);
        if(!cp.isEmpty()) {
            ecAccess = true;
        }else{
            ecAccess = false;
        }
        System.debug('ec access = ' + ecAccess);

    }

    @AuraEnabled
    public static String getInvoicePaymentURL(String contactId){
        if(contactId!=null){
            OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c
                                            WHERE OrderApi__Contact__c=:contactId
                                            AND OrderApi__Status__c='Open'
                                            AND (Is_Transfer__c = true OR Is_Reinstatement__c = true)
                                            ORDER BY CreatedDate DESC
                                            LIMIT 1];
            return '/AACRPayment?salesOrder=' + so.Id;
        }

        return null;
    }
 
    @AuraEnabled
    public static MembershipData getMembershipData(){
        Contact currentContact = ECRMUtils.getCurrentLoginContact();

        //search for duplicates
        ECRMUtils.createDuplicateAlert(currentContact); 

        OrderApi__Subscription__c memSub;
        List<OrderApi__Subscription__c> memSubs = RenewalUtils.getIndividualMembershipSubscription(currentContact.Id);
        if(!memSubs.isEmpty()){
            memSub = memSubs[0];
        }

        return new MembershipData(currentContact, memSub);
    }

    @AuraEnabled
    public static String cancelApplication(){
        Contact currentContact = ECRMUtils.getCurrentLoginContact();
        OrderApi__Sales_Order__c recentSO = JP_Helper.getMostRecentSO(currentContact.Id);
        if(recentSO!=null) {
            if (recentSO.OrderApi__Status__c == 'Open') {
                //find contact last access step
                List<OrderApi__Sales_Order_Line__c> lines = [SELECT Id, OrderApi__Item__c, OrderApi__Item__r.Name FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c = :recentSO.Id AND OrderApi__Item_Class__r.Name = 'Individual Memberships'];
                Join_Process__mdt jp = [SELECT Id FROM Join_Process__mdt WHERE Item__c LIKE:'%' + lines[0].OrderApi__Item__r.Name + '%' AND Is_Renewal__c = false AND Campaign_Code__c = null LIMIT 1 ];
                contact_last_accessed_step__c las = [SELECT Step_Order__c, Join_Process__c FROM contact_last_accessed_step__c WHERE Contact__c = :currentContact.Id AND JoinId__c = :jp.Id];
                try {
                    currentContact.Application_Status__c = null;
                    update currentContact;
                    delete recentSO;
                    delete las;
                } catch (Exception e) {
                    System.debug('Error canceling application: ' + e.getMessage());
                    return null;
                }
            }
        }
        return '/apex/MembershipCategories';
    }

    public class MembershipData{

        @AuraEnabled
        public OrderApi__Subscription__c membership;

        @AuraEnabled
        public String membershipType;

        @AuraEnabled
        public String joinURL;

        @AuraEnabled
        public Id contactId;


        public MembershipData(Contact currentContact, OrderApi__Subscription__c membership){
            this.contactId = currentContact.Id;
            if(membership!=null) {
                this.membership = membership;
                this.membershipType = membership.OrderApi__Item__r.Name;
            } else {
                OrderApi__Sales_Order__c recentSO = JP_Helper.getMostRecentSO(currentContact.Id);
                if(recentSO!=null){
                    if (recentSO.OrderApi__Status__c == 'Open') {
                        List<OrderApi__Sales_Order_Line__c> membershipLines = [SELECT Id, OrderApi__Item__r.Name FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c = :recentSO.Id AND OrderApi__Item_Class__r.Name = 'Individual Memberships'];
                        if (membershipLines.size() == 1) {
                            this.membershipType = membershipLines[0].OrderApi__Item__r.Name;
                            Join_Process__mdt jp = [SELECT Id FROM Join_Process__mdt WHERE Item__c LIKE: '%' + this.membershipType + '%' AND Is_Renewal__c = false AND Campaign_Code__c = null];
                            List<contact_last_accessed_step__c> las = [SELECT Step_Order__c, Join_Process__c, JoinId__c FROM contact_last_accessed_step__c WHERE Contact__c = :currentContact.Id AND JoinId__c =: jp.Id ];
                            if(!las.isEmpty()) {
                                this.joinURL = '/apex/JP_Container?id=' + las[0].JoinId__c + '&salesOrder=' + recentSO.Id;
                            } else {
                                this.joinURL = '/apex/MembershipCategories';
                            }
                        }
                    }
                }
            }
        }
    }

//    @AuraEnabled
//    public static RenewalData catchUpToCurrent(){
//        Contact UserContactData = ECRMUtils.getCurrentLoginContact();
//        DW_ECRMDTO.Response response = RenewalUtils.renewSubscriptions(UserContactData,false);
//
//        System.debug('response: ' + response);
//        if(response.isSuccess) {
//            DW_ECRMDTO.RenewDTO renewDTO = (DW_ECRMDTO.RenewDTO) JSON.deserialize(JSON.serialize(response.data), DW_ECRMDTO.RenewDTO.class);
//            return new RenewalData(renewDTO, response.message, response.isSuccess);
//        }
//        return new RenewalData(null, response.message, response.isSuccess);
//    }
//
//    @AuraEnabled
//    public static RenewalData renewSubscriptions(){
//        System.debug('renewSubscription was just called');
//        Contact UserContactData = ECRMUtils.getCurrentLoginContact();
//        //check for campaign code on contact record & get join id
//        String campaignId = UserContactData.Campaign_Code__c;
//
//        if(campaignId!=null){
//            DW_ECRMDTO.RenewDTO renewDTO = new DW_ECRMDTO.RenewDTO();
//            renewDTO.contactId = UserContactData.Id;
//            renewDTO.joinProcessURL = '/apex/BAMpaignRedirect?campaignId=' + campaignId;
//            return new RenewalData(renewDTO, null, true);
//        }
//
//
//        Renewal_Settings__c renewalProcess = Renewal_Settings__c.getInstance();
//        DW_ECRMDTO.Response response = RenewalUtils.renewSubscriptions(UserContactData, renewalProcess.Is_Active__c);
//
//        System.debug('response: ' + response);
//        if(response.isSuccess) {
//            DW_ECRMDTO.RenewDTO renewDTO = (DW_ECRMDTO.RenewDTO) JSON.deserialize(JSON.serialize(response.data), DW_ECRMDTO.RenewDTO.class);
//            //modify sales order if campaign id is not null
//            return new RenewalData(renewDTO, response.message, response.isSuccess);
////            JP_Helper.setCartCookies(ApexPages.currentPage(), renewDTO.salesOrderId);
////            String joinURL = renewDTO.joinProcessURL;
//        }
//        return new RenewalData(null, response.message, response.isSuccess);
//    }


//    public class RenewalData{
//        @AuraEnabled
//        public String joinURL;
//
//        @AuraEnabled
//        public String cookieName;
//
//        @AuraEnabled
//        public String userId;
//
//        @AuraEnabled
//        public String salesOrderId;
//
//        @AuraEnabled
//        public String message;
//
//        @AuraEnabled
//        public Boolean isSuccess;
//
//        public RenewalData(DW_ECRMDTO.RenewDTO renewDTO, String message, Boolean isSuccess){
//            if(renewDTO!=null) {
//                this.joinURL = renewDTO.joinProcessURL;
//                this.salesOrderId = renewDTO.salesOrderId;
//            }
//            this.message = message;
//            this.isSuccess = isSuccess;
//
//            this.userId = UserInfo.getUserId();
//            this.cookieName = UserInfo.getOrganizationId() + '-fonteva-shopping-cart';
//        }
//
//    }



}