src/objects/Committees__c.object
<CustomObject>
    <description>[OLD] AACR committees that are invitation only or members are elected to.</description>
    <fields>
        <fullName>Committee_Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Item in the eStore this committee is related to.</description>
        <label>Committee Related To</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Related Committee Item</relationshipLabel>
        <relationshipName>Committees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Committees__c</fullName>
        <label>Committees</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Committees</relationshipLabel>
        <relationshipName>Committees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_From__c</fullName>
        <description>Date a given member joined the committee</description>
        <inlineHelpText>Date a given member joined the committee</inlineHelpText>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Through__c</fullName>
        <description>Date a given member exited the committee</description>
        <inlineHelpText>Date a given member exited the committee</inlineHelpText>
        <label>Date Through</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dropped__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Departure of committee member from a group</description>
        <label>Dropped</label>
        <type>Checkbox</type>
    </fields>
    <label>Committees</label>
    <nameField>
        <label>Committee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Eligible_Nominator_Membership__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible Nominator Membership</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fon_Association_Journal_Type__c</fullName>
        <description>Classify association journals in Online only or Print</description>
        <label>Association Journals Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Online Only</fullName>
                </value>
                <value>
                    <fullName>Print &amp; Online</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Active_Membership_Type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active Membership Type?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price__c</fullName>
        <description>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</description>
        <inlineHelpText>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</inlineHelpText>
        <label>Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>Is_Membership__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Defines membership item class for Membership Status updates</inlineHelpText>
        <label>Is Membership</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</description>
        <inlineHelpText>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__End_Date__c</fullName>
        <description>The date when the subscription ends. This date will always be the current term end date or the subscription cancelled date where appropriate.</description>
        <inlineHelpText>The date when the subscription ends. This date will always be the current term end date or the subscription cancelled date where appropriate.</inlineHelpText>
        <label>Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>**System Calculated/Override** Checked when a recurring order or contract is active.</description>
        <inlineHelpText>**System Calculated/Override** Checked when a recurring order or contract is active.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Activation_Date__c</fullName>
        <description>** System Calculated Override Conditionally Required ** The date the Subscription will be activated is calculated based on conditions set on the related Subscription Plan and can be manually over-ridden if &quot;Auto Calculate Activation Date&quot; is unchecked.</description>
        <inlineHelpText>** System Calculated Override Conditionally Required ** The date the Subscription will be activated is calculated based on conditions set on the related Subscription Plan and can be manually over-ridden if &quot;Auto Calculate Activation Date&quot; is unchecked.</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__End_Date__c</fullName>
        <description>** System Calculated Override Conditionally Required ** The date the Subscription will be ended is calculated based on conditions set on the related Subscription Plan and Activation Date.</description>
        <inlineHelpText>** System Calculated Override Conditionally Required ** The date the Subscription will be ended is calculated based on conditions set on the related Subscription Plan and Activation Date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DW_CommitteeAutomationTriggerTest.cls
/**
 *@Purpose       : Test class for DW_CommitteeAutomationTrigger 
 *@Created Date  : 30-08-2018
 *@Modified Date : 
 */
@isTest
public class DW_CommitteeAutomationTriggerTest {
 
    @testSetup
    private static void buildTestData(){
        // build Account record
        Account account = buildAccount('Test Account1');
        insert account;
        
        // Build Contact record
        Contact contact= buildContact(account.Id);
        insert contact;
        
        // Build User recod
        User user = buildUser(contact.Id);
        insert user;
        
        OrderApi__Item_Class__c workingGroupClass = buildItemClass('Working Groups');
        insert workingGroupClass;
        
        OrderApi__Sales_Order__c salesOrder = buildSalesOrder(contact.Id);
        insert salesOrder;
        
        OrderApi__Item_Class__c indMemClass = buildItemClass('Individual Memberships');
        insert indMemClass;
    }
    
    /**
     *@purpose   : build Account record
     *@param     : -
     *@return    : Account record
     */
    static Account buildAccount(String accountName){
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        
        return new Account(RecordTypeId = recordTypeId,
                           Name = accountName);
    }
    
    /**
     *@purpose   : Build Contact record
     *@param     : accountId
     *@return    : Contact record
     */
    static Contact buildContact(Id accountId){
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get( Label.Contact_Non_Member_Record_Type ).getRecordTypeId();
        
        // Creating Contact record
        return new Contact(LastName = 'Test contact',
                           AccountId = accountId,
                           RecordTypeId = recordTypeId,
                           Phone ='9878986789',
                           Fax = 'fax');
    }
    
    /**
     *@purpose   : Build User record
     *@param     : contactId
     *@return    : -
     */
    static User buildUser(Id contactId){
        // Fetching profile record
        Profile profileRecord = [SELECT Id
                                 FROM Profile 
                                 WHERE Name =: 'Fonteva Customer Community Login User'
								 LIMIT 1];
        
        // Create users record
        User userRecord = new User(alias = 'test',
                                   ContactId = contactId,
                                  // AccountId = contactRecord1.AccountId,
                                   ProfileId = profileRecord.Id, 
                                   email = 'test@testorg.com', 
                                   emailencodingkey = 'UTF-8', 
                                   lastname = 'Test User2', 
                                   CommunityNickname = 'test user2',
                                   languagelocalekey = 'en_US', 
                                   localesidkey = 'en_US', 
                                   timezonesidkey = 'America/Los_Angeles', 
                                   username = System.now().millisecond() + 'test@testorg2.com');
        return userRecord;
    }
    
    /**
     *@purpose   : Build Item class record 
     *@parameter : -
     *@return    : Itesm class record
     */
    private static OrderApi__Item_Class__c buildItemClass(String itemClassName){
        return new OrderApi__Item_Class__c(Name = itemClassName,
                                           Is_Membership__c =  false);
    }
    
    /**
     *@purpose   : Build Item record
     *@parameter : -
     *@return    : Item record
     */
    static OrderApi__Item__c buildItem(Id itemClassId, String itemName){
        return new OrderApi__Item__c(Name = itemName,
                                     OrderApi__Item_Class__c = itemClassId,
                                     OrderApi__Is_Active__c = true,
                                     Is_Active_Membership_Type__c =true,
                                     OrderApi__Price__c = 50,
                                     Fon_Association_Journal_Type__c = 'Online Only',
                                     Eligible_Nominator_Membership__c = true);
    }
    
    /**
     *@Purpose : Build sales order
     *@Param   : contactId
     *@return  :
     */
    static OrderApi__Sales_Order__c buildSalesOrder(Id contactId){
        return new OrderApi__Sales_Order__c(OrderApi__Contact__c = contactId);
    }
    
    /**
     *@purpose : to test single sales order line item Insertion
     */
    static testMethod void testSingleLIInsertDelete(){
        Test.startTest();
        
        User user = [SELECT Id, ContactId 
                     FROM User 
                     WHERE lastname =: 'Test User2'];
        
        System.runAs(user){
            OrderApi__Item_Class__c WorkingGroupClass = [SELECT Id, Name FROM OrderApi__Item_Class__c WHERE Name =: 'Working Groups'];
            OrderApi__Item_Class__c activeMemClass = [SELECT Id, Name FROM OrderApi__Item_Class__c WHERE Name =: 'Individual Memberships'];
            
            
            OrderApi__Item__c workingGroupitem1 = buildItem(WorkingGroupClass.Id, 'Behavioral Science in Cancer Research (BSCR)');
            insert workingGroupitem1;
            
            OrderApi__Item__c workingGroupitem2 = buildItem(WorkingGroupClass.Id, 'Chemistry in Cancer Research (CICR)');
            insert workingGroupitem2;
            
            OrderApi__Item__c indMemitem = buildItem(WorkingGroupClass.Id, 'Behavioral Science in Cancer Research (BSCR)');
            insert indMemitem;
            
            OrderApi__Sales_Order__c salesOrder = [SELECT Id FROM OrderApi__Sales_Order__c];
            List<OrderApi__Sales_Order_Line__c> sol = new List<OrderApi__Sales_Order_Line__c>();
            // Test sales order Line item insertion
            OrderApi__Sales_Order_Line__c salesOrderLI1 = new OrderApi__Sales_Order_Line__c(OrderApi__Item__c = indMemitem.Id,
                                                                                           OrderApi__Sales_Order__c = salesOrder.Id,
                                                                                           OrderApi__Item_Class__c = activeMemClass.Id,
                                                                                           OrderApi__Activation_Date__c = System.today(),
                                                                                           OrderApi__End_Date__c = System.today()+2);
            insert salesOrderLI1;
            
            // Test sales order Line item insertion
            OrderApi__Sales_Order_Line__c salesOrderLI2 = new OrderApi__Sales_Order_Line__c(OrderApi__Item__c = workingGroupitem1.Id,
                                                                                            OrderApi__Sales_Order__c = salesOrder.Id,
                                                                                            OrderApi__Item_Class__c = WorkingGroupClass.Id);
            insert salesOrderLI2;
            sol.add(salesOrderLI1);
            sol.add(salesOrderLI2);
              DW_CommitteeAutomationTriggerHandler.getCommiteesToUpdate(sol);
            DW_CommitteeAutomationTriggerHandler.updateCommiteeAfterLIDelete(sol);
            
            
        }
        Test.stopTest();
    }
    
    /**
     *@purpose : to test bulk sales order line item Insertion
     */
    static testMethod void testBulkLIInsertDel(){
        Test.startTest();
        
        User user = [SELECT Id, ContactId 
                     FROM User 
                     WHERE lastname =: 'Test User2'];
        
        System.runAs(user){
            OrderApi__Item_Class__c WorkingGroupClass = [SELECT Id, Name FROM OrderApi__Item_Class__c WHERE Name =: 'Working Groups'];
            OrderApi__Item_Class__c activeMemClass = [SELECT Id, Name FROM OrderApi__Item_Class__c WHERE Name =: 'Individual Memberships'];
            
            OrderApi__Item__c indMemitem = buildItem(WorkingGroupClass.Id, 'Behavioral Science in Cancer Research (BSCR)');
            insert indMemitem;
            
            OrderApi__Sales_Order__c salesOrder = [SELECT Id FROM OrderApi__Sales_Order__c];
            
            // Test sales order Line item insertion
            OrderApi__Sales_Order_Line__c salesOrderLI1 = new OrderApi__Sales_Order_Line__c(OrderApi__Item__c = indMemitem.Id,
                                                                                            OrderApi__Sales_Order__c = salesOrder.Id,
                                                                                            OrderApi__Item_Class__c = activeMemClass.Id,
                                                                                            OrderApi__Activation_Date__c = System.today(),
                                                                                            OrderApi__End_Date__c = System.today()+2);
            insert salesOrderLI1;
            
            // insert class items
            List<OrderApi__Item__c> itemList = new List<OrderApi__Item__c>();
            for(Integer index = 0; index < 5; index ++){
                itemList.add(buildItem(WorkingGroupClass.Id, 
                                       'Behavioral Science in Cancer Research (BSCR)'+index));
            }
            insert itemList;
            
            // test insert sales order LI records
            List<OrderApi__Sales_Order_Line__c> salesOredrLIList = new List<OrderApi__Sales_Order_Line__c>();
            for(Integer index = 0; index < 5; index ++){
                salesOredrLIList.add(new OrderApi__Sales_Order_Line__c(OrderApi__Item__c = itemList[index].Id,
                                                                       OrderApi__Sales_Order__c = salesOrder.Id,
                                                                       OrderApi__Item_Class__c = WorkingGroupClass.Id));
            }
            insert salesOredrLIList;
            
            List<Committees__c> committeeList = [SELECT Id, Name, Committee_Related_To__c,Committees__c, Date_From__c, Date_Through__c, Dropped__c 
                                                 FROM Committees__c
                                                 WHERE Committee_Related_To__c IN : itemList];
            
            // test deletion of sales order LI record
            delete salesOredrLIList;
            
            committeeList = [SELECT Id, Name, Committee_Related_To__c,Committees__c, Date_From__c, Date_Through__c, Dropped__c 
                             FROM Committees__c
                             WHERE Id IN : committeeList];
            
            
        }
        Test.stopTest();
    }
}