src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_Announcements__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>AACR Announcements</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AACR_Foundation__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>AACR Foundation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Annual_Meeting__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Annual Meeting</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Awards_Grants__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Awards &amp; Grants</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CEO_Preference__c</fullName>
        <label>CEO Preference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancer_Immunology_Group__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Cancer Immunology Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancer_Policy_Advocacy__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Cancer Policy &amp; Advocacy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cancer_Today_Magazine__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Cancer Today Magazine</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Chemistry_in_Cancer_Research__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Chemistry in Cancer Research</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Conferences_Workshops__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Conferences &amp; Workshops</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Display_in_Directory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field as criteria in directory to not display contact record.  Does not automatically remove contact unless configured in directory.</description>
        <inlineHelpText>Use this field as criteria in directory to not display contact record.  Does not automatically remove contact unless configured in directory.</inlineHelpText>
        <label>Do Not Display in Directory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Formerly_Known_As__c</fullName>
        <label>Formerly Known As</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Foundation_Do_Not_Solicit__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Has this individual donated to the AACR?</inlineHelpText>
        <label>Foundation - Do Not Solicit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maiden_Name__c</fullName>
        <label>Maiden Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Information__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Membership Information</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minorities_in_Cancer_Research__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Minorities in Cancer Research</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Molecular_Epidemiology__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Molecular Epidemiology</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <description>Nickname of the contact.</description>
        <inlineHelpText>Nickname of the contact.</inlineHelpText>
        <label>Nickname</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Home_Do_Not_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Do Not Call the Contact&apos;s Home Phone.</description>
        <inlineHelpText>Do Not Call the Contact&apos;s Home Phone.</inlineHelpText>
        <label>Home Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Mobile_Do_Not_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Do Not Call the Contact&apos;s Mobile Phone.</description>
        <inlineHelpText>Do Not Call the Contact&apos;s Mobile Phone.</inlineHelpText>
        <label>Mobile Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Preferred_Email_Type__c</fullName>
        <description>**Defaults to Personal Email** Select the Preferred Email Type for the Contact. The value of the corresponding email field will update the standard Contact Email field.</description>
        <inlineHelpText>**Defaults to Work Email** Select the Preferred Email Type for the Contact. The value of the corresponding email field will update the standard Contact Email field.</inlineHelpText>
        <label>Preferred Email Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                    <default>true</default>
                    <label>Work</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Preferred_Phone_Type__c</fullName>
        <description>**Defaults to Personal Email** Select the Preferred Phone Type for the Contact. The value of the corresponding phone field will update the standard Contact Phone field.</description>
        <inlineHelpText>**Defaults to Work Phone** Select the Preferred Phone Type for the Contact. The value of the corresponding phone field will update the standard Contact Phone field.</inlineHelpText>
        <label>Preferred Phone Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                    <default>true</default>
                    <label>Work</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Preferred_Phone__c</fullName>
        <description>**System Calculated** The Preferred Phone for the Contact is calculated by mapping the Preferred Phone Type to it&apos;s corresponding field&apos;s value.</description>
        <formula>IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Mobile&quot;) &amp;&amp; NOT(OrderApi__Mobile_Do_Not_Call__c), MobilePhone,
IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Home&quot;) &amp;&amp; NOT(OrderApi__Home_Do_Not_Call__c), HomePhone,
IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Work&quot;) &amp;&amp; NOT(OrderApi__Work_Do_Not_Call__c),OrderApi__Work_Phone__c,
IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Other&quot;) &amp;&amp; NOT(OrderApi__Other_Do_Not_Call__c),OtherPhone,
IF(ISPICKVAL(OrderApi__Preferred_Phone_Type__c,&quot;Assistant&quot;) &amp;&amp; NOT(OrderApi__Assistant_Do_Not_Call__c),AssistantPhone,
&apos;&apos;)))))</formula>
        <inlineHelpText>**System Calculated** The Preferred Phone for the Contact is calculated by mapping the Preferred Phone Type to it&apos;s corresponding field&apos;s value.</inlineHelpText>
        <label>Preferred Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Work_Do_Not_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Do Not Call the Contact&apos;s Work Phone.</description>
        <inlineHelpText>Do Not Call the Contact&apos;s Work Phone.</inlineHelpText>
        <label>Work Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Address__c</fullName>
        <description>What is the preferred mailing address for this member?</description>
        <inlineHelpText>What is the preferred mailing address for this member?</inlineHelpText>
        <label>Preferred Address</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                    <default>true</default>
                    <label>Business</label>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stand_Up_2_Cancer__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Stand Up 2 Cancer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survivor_Advocacy__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Survivor Advocacy</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tumor_Microenvironment__c</fullName>
        <description>Marketing Preferences indicator</description>
        <label>Tumor Microenvironment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Women_in_Cancer_Research__c</fullName>
        <description>Marketing Preference indicator</description>
        <label>Women in Cancer Research</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DW_ContactServiceHelper.cls
/**
 *@Purpose      : Getting community contact's Marketing Preferences or Communication preference and Display on VF page and saved updated values
 *@Created Date : 20/08/18
 *@Modified Date: 
 */
public class DW_ContactServiceHelper {
    
    /**
     *@purpose : Getting current login user contact Id
     *@param   : -
     *@return  : Contact Id
     **/
    public static Id getcurrentLoginContactId(){
        // Getting current login user id
        Id userId = UserInfo.getUserId();
        
        User user = [SELECT Id, ContactId 
                     FROM User 
                     WHERE Id = : userId];
        return user.ContactId;
    }
    
    /**
     *@Purpose : Getting contact with Marketing Preferences fields
     *@Param   : contactId
     *@return  : Contact record
     */
    public static Contact getMarketingPrefContact(Id contactId){
        
        List<String> marketingPrefFieldsList = new List<String>{'AACR_Announcements__c','Conferences_Workshops__c','AACR_Foundation__c','Membership_Information__c',
                                                                'Annual_Meeting__c','Minorities_in_Cancer_Research__c','Awards_Grants__c','Molecular_Epidemiology__c',
                                                                'Cancer_Immunology_Group__c','Stand_Up_2_Cancer__c','Cancer_Policy_Advocacy__c','Survivor_Advocacy__c',
                                                                'Cancer_Today_Magazine__c','Tumor_Microenvironment__c','Chemistry_in_Cancer_Research__c',
                                                                'Women_in_Cancer_Research__c'};
        // Getting contact with fields in  marketingPrefFieldsList   
        Contact contact = getContact(contactId, marketingPrefFieldsList);
        return contact;
    }
    
    /**
     *@Purpose : Getting contact with Communication Preferences fields
     *@Param   : contactId
     *@return  : Contact record
     */
    public static Contact getcommunicationPrefContact(Id contactId){
        
        List<String> communiactionPrefFieldsList = new List<String>{'Nickname__c', 'OrderApi__Work_Do_Not_Call__c', 'OrderApi__Home_Do_Not_Call__c', 'OrderApi__Mobile_Do_Not_Call__c',
                                                                    'Maiden_Name__c', 'Formerly_Known_As__c', 'CEO_Preference__c', 'Preferred_Address__c',
            													    'OrderApi__Preferred_Phone_Type__c','OrderApi__Preferred_Email_Type__c', 'Email', 
                                                                    'Do_Not_Display_in_Directory__c','Foundation_Do_Not_Solicit__c', 'OrderApi__Preferred_Phone__c',
                                                                    'OrderApi__Preferred_Email__c','Journal_Street__c','Journal_City__c', 'OrderApi__Work_Phone__c', 'HomePhone',
                                                                    'Journal_State_Province__c','Journal_Zip_Postal_Code__c','Journal_Country__c', 'MobilePhone',
                                                                    'Do_Not_Mail__c', 'DoNotCall','Do_Not_Email__c', 'OrderApi__Work_Email__c', 'OrderApi__Personal_Email__c',
                                                                    'Do_Not_Trade_Externally__c', 'Birthdate'};
       // Getting contact with fields in  communiactionPrefFieldsList 
       Contact contact = getContact(contactId, communiactionPrefFieldsList);
       return contact;
    }
    
    /**
     *@Purpose : Getting contact with particular fields
     *@Param   : contactId, contactFieldsList
     *@return  : Contact record
     */
    public static Contact getContact(Id contactId, List<String> contactFieldsList){
        Contact contact;
        
        if(contactId != NULL && ! contactFieldsList.isEmpty()){
            try{
                
                String contactQuery = 'SELECT Id,';
                contactQuery += String.join(contactFieldsList,','); 
                contactQuery += ' FROM Contact WHERE Id = \'' + contactId +'\'';
                
                //Getting contacts List
                contact  = Database.query(contactQuery);
                
            }catch(Exception exp){
                System.debug('Exception occured ::'+exp.getMessage());
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,Exp.getMessage()));
            }
        }
        return contact;
    }
}