src/objects/Contact_Dimension_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Dim_Tag_Id__c</fullName>
        <label>Dim Tag Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Visibility</valueSetName>
        </valueSet>
    </fields>
    <label>Contact Tag</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Contact Tag Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dimension_Tags__mdt.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>BR_Event__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                    <default>true</default>
                    <label>Public</label>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dimension Tag</label>
    <pluralLabel>Dimension Tags</pluralLabel>
</CustomObject>

src/objects/OrderApi__Badge__c.object
<CustomObject>
    <description>Badges are assigned to Contacts either automatically (Badge Workflow) or manually. Badges can enable Contacts for special Price Rules - as well as permission to read, update, or delete certain content types.</description>
    <fields>
        <fullName>OrderApi__Badge_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge Type</label>
        <referenceTo>OrderApi__Badge_Type__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Badge ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Badge_Type__c.object
<CustomObject>
    <description>Configure Badge Types to assign to Contacts to allow greater control and flexibility around pricing and content accessibility.</description>
    <label>Badge Type</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExportHelper_ContactTest.cls
/**
 * Created by afaf.awad on 7/7/2021.
 */

@IsTest
private class ExportHelper_ContactTest {

    @TestSetup
    public static void setup() {
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        OrderApi__Badge_Type__c badgeType = TestDataFactory.buildBadgeType('WICR - Women in Cancer Research');
        insert badgeType;

        OrderApi__Badge__c badge = TestDataFactory.buildBadge(badgeType.Id, con.Id);
        insert badge;

        Dimension_Tags__mdt dmt = [SELECT Id FROM Dimension_Tags__mdt WHERE Object__c = 'Contact' AND Visibility__c = 'Public' LIMIT 1];
        SObject publicObj = DimensionTagHelper.createTagRecord(dmt.Id,  con.Id);
        insert publicObj;

    }

    @IsTest
    public static void test_queryContacts_full() {

        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Contact_Dimension_Tag__c cdt = [SELECT Id, Dim_Tag_Id__c FROM Contact_Dimension_Tag__c LIMIT 1];

        ExportHelper_Contact.ContactExport ce = ExportHelper_Contact.queryContacts_full(cdt.Dim_Tag_Id__c);

        System.assertEquals(1, ce.Contacts.size());
    }

    @IsTest
    public static void queryContacts_market() {
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Contact_Dimension_Tag__c cdt = [SELECT Id, Dim_Tag_Id__c FROM Contact_Dimension_Tag__c LIMIT 1];

        ExportHelper_Contact.ContactExport ce = ExportHelper_Contact.queryContacts_market(cdt.Dim_Tag_Id__c);

        System.assertEquals(1, ce.Contacts.size());
    }
}