src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <description>Formula field reflecting either legacy iMIS ID or new Salesforce ID depending upon when record was created.</description>
        <formula>IF(ISBLANK( iMIS_ID__c ), Salesforce_ID__c, iMIS_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_StudentNominatorName__c</fullName>
        <label>Nominator Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_StudentNominatorTitle__c</fullName>
        <label>Nominator Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_StudentNominatorType__c</fullName>
        <label>Nominator Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advisor</fullName>
                </value>
                <value>
                    <fullName>AACR member</fullName>
                </value>
                <value>
                    <fullName>Dean</fullName>
                </value>
                <value>
                    <fullName>Mentor</fullName>
                </value>
                <value>
                    <fullName>Principal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Membership_Id__c</fullName>
        <inlineHelpText>This field in JP to get the membership type that user has selected. In hidden form field we will map membership type to this field and after custom nomination page remove data from this field.</inlineHelpText>
        <label>Membership Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Other_Email__c</fullName>
        <description>Other/Additional Email for the Contact.</description>
        <inlineHelpText>Other/Additional Email for the Contact.</inlineHelpText>
        <label>Other Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OrderApi__Personal_Email__c</fullName>
        <description>Personal/Home Email address for the Contact.</description>
        <inlineHelpText>Personal/Home Email address for the Contact.</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OrderApi__Work_Email__c</fullName>
        <description>Work/Business Email for the Contact.</description>
        <inlineHelpText>Work/Business Email for the Contact.</inlineHelpText>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>npe4__Contact__c</fullName>
        <description>Related Contact is this Contact&apos;s ______.</description>
        <inlineHelpText>Related Contact is this Contact&apos;s ______.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe4__RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe4__Status__c</fullName>
        <description>Status of the Relationship.</description>
        <inlineHelpText>Status of the Relationship.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe4__Type__c</fullName>
        <description>Field that describes how the Related Contact is connected to the Contact.</description>
        <inlineHelpText>Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Nominator</fullName>
                </value>
                <value>
                    <fullName>Nominee</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Significant Other</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Grandchild</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Eligible_Nominator_Membership__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible Nominator Membership</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active_Membership_Type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active Membership Type?</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** The source Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated ** The source Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Sales Order Line (Source)</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Upgraded_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Override ** Defines the related upgraded subscription.</description>
        <inlineHelpText>** System Calculated Override ** Defines the related upgraded subscription.</inlineHelpText>
        <label>Upgraded Subscription</label>
        <referenceTo>OrderApi__Subscription__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <formula>Contact.AACR_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DW_JPMembershipControllerCloneHelper.cls
/*
 * @Purpose     : Controller for DW_JPMembership1 visualforce page
 * @Author      : Rabaab (Dreamwares)
 * @Date        : 14-August-2018
 */
public class DW_JPMembershipControllerCloneHelper {
    
    /*
     * @Purpose : Init metjod for JPMEmbership page
     */
    public static Response doInit( String stepId, String salesOrderId ){
        Id userId = UserInfo.getUserId();
        Integer totalAttachmentCount = 0;
        Integer totalNominatorsCount = 0;
        String membershipType = '';
        //Querying user to get contact Id of logged in community user
        User user = [SELECT ContactId, Contact.Membership_Id__c FROM User WHERE ID = :userId ];
        Contact currentContact = [ Select Id, Contact_StudentNominatorType__c, Contact_StudentNominatorName__c, 
                                  Contact_StudentNominatorTitle__c FROM Contact WHERE Id =: user.ContactId ];
        Map<String, String> contactStudentNomInfo = new Map<String, String> {
                                    'name' => currentContact.Contact_StudentNominatorName__c, 
                                    'title' => currentContact.Contact_StudentNominatorTitle__c, 
                                    'type' => currentContact.Contact_StudentNominatorType__c
                                };
                                    
        // Getting sales order LI list
        List<OrderApi__Sales_Order_Line__c> membershipSalesOrderLIs =  DW_ECRMUtils.getSpecificSalesOrderIndMemLIs(salesOrderId);
        // pdate total Attachments Count
        if( membershipSalesOrderLIs.size() > 0 ) {
            OrderApi__Sales_Order_Line__c membershipSalesOrederLI = membershipSalesOrderLIs[ 0 ];
            membershipType = membershipSalesOrederLI.OrderApi__Item__r.Name;
            if(membershipSalesOrederLI.OrderApi__Item__r.Name.contains('Active') ||
               membershipSalesOrederLI.OrderApi__Item__r.Name.contains('Associate')){
                totalAttachmentCount = 1;
                System.debug('Active==>'+totalAttachmentCount);
                if( membershipSalesOrederLI.OrderApi__Item__r.Name.contains('Active') ) {
                    totalNominatorsCount = 2;
                } else { //Associate
                    totalNominatorsCount = 1;
                }
            } else if(membershipSalesOrederLI.OrderApi__Item__r.Name.contains('Student')){
                totalAttachmentCount = 2;
                System.debug('Student==>'+totalAttachmentCount); 
                totalNominatorsCount = 1;
            }
            else if(membershipSalesOrederLI.OrderApi__Item__r.Name.contains('Affiliate')){
                totalAttachmentCount = 3;
                System.debug('Affiliate==>'+totalAttachmentCount);
                totalNominatorsCount = 1;
            }
            
            try{
                //Orderapi__Item__c item = getItem(user.ContactId);
                
                Boolean isItemNull;
                isItemNull = ( membershipSalesOrderLIs.size() > 0 ) ? false : true;
                //Getting nominator information
                NominatorInfo[] nominatorsInfo = getNominatorsInfo(user.ContactId);
               
                //Getting attachments
                DW_JPMembershipControllerClone.Attachment_x[] attachments = new List<DW_JPMembershipControllerClone.Attachment_x>();
                //Integer numberOfAttachments =  item != null && item.Is_Active_Membership_Type__c ? 2 : 1;
                for(Attachment attachment : [SELECT Id, Name FROM Attachment WHERE ParentId = :user.ContactId LIMIT :totalAttachmentCount]){
                    attachments.add(new DW_JPMembershipControllerClone.Attachment_x(attachment.Id, attachment.Name));
                }

                //Getting url for nextstep
                String nextStepUrl = getNextStepURL( stepId );
                //get picklist values for student membership type field
                Map<String, String> nominatorTypeMap = DW_ECRMUtils.getPicklistEntries('Contact', 'Contact_StudentNominatorType__c');
                return new Response(true, '', new Map<String, 
                                    Object>{
                                            'ContactId' => user.ContactId, 
                                            'ItemIsNull' => isItemNull, 
                                            'nextStepUrl' => nextStepUrl, 
                                            'nominatorsInfo' => nominatorsInfo,
                                            'attachments' => attachments,
                                            'totalAttachmentCount' => totalAttachmentCount,
                                            'totalNominatorsCount' => totalNominatorsCount,
                                            'membershipType' => membershipType,
                                            'nominatorTypeMap' => nominatorTypeMap,
                                            'contactStudentNomInfo' => contactStudentNomInfo,
                                            'previousStepUrl' => getPreviousStepURL( stepId ),
                                            'cancelStepUrl' => getCancelStepURL( stepId )
                                            });
            }catch(Exception e){
                System.debug(e.getMessage() + ' ' + e.getStackTraceString());
                return new Response(false, '', null);
            }
        } else {
            return new Response(false, 'No membership item found', null);
        }
    }
   
    /*
     * @Purpose : Init metjod for JPMEmbership page
     */
    public static Response verifyNominators(String contactId, String memberNo , String email, List<String> existingNominatorIds ){
        if(String.isBlank(contactId)){
            return new Response(false, 'Please provide contact id', null);
        }
        
        Contact[] contacts = new List<Contact>();
        String message;
        
        try{
            /*Orderapi__Item__c item = getItem(contactId);
            if(item == null){
                return new Response(false, Label.DW_Item_Not_Found, null);
            }*/
            
            Response buildStringQueryResponse = buildStringQuery(contactId, memberNo, email);
            if(!buildStringQueryResponse.isSuccess){
                return buildStringQueryResponse;
            }
            
            //Firing query
            contacts = Database.query(buildStringQueryResponse.message);
        }catch(Exception e){
            System.debug(e.getMessage() + '\n' + e.getStackTraceString());
            return new Response(false, 'Something went wrong', null);
        }
        
        System.debug('Contacts: ' + contacts);

        //Check if contacts list is empty
        if(contacts.isEmpty()){
            message = Label.Nominator_Not_Found;
            return new Response(false, message, null);
        }
        
        //Check for duplicate nominator
        /*if(String.isNotBlank(nominatorOneId) && contacts[0].Id == nominatorOneId){
            return new Response(false, Label.DW_Duplicate_Nominator, null);
        }*/
        if( existingNominatorIds.size() > 0 && existingNominatorIds.contains( contacts[0].Id ) ) {
            return new Response(false, Label.DW_Duplicate_Nominator, null);
        }
        System.debug('subscription size()==>'+contacts[0].OrderApi__Subscriptions__r.size());
        //Check if nominator is valid
        Map<String, Object> returnMap = new Map<String, Object>();
        if(contacts[0].Membership_Status__c == 'Current' && contacts[0].OrderApi__Subscriptions__r.size() > 0){
            //Initializing map to be returned
            //Map<String, Object> returnMap = new Map<String, Object>();
            
            //message = Label.Nominator_Name_Verified.replace('NominatorName', contacts[0].Name);
            //returnMap.put('NominatorID', contacts[0].Id);
            String statusText = contacts[0].Name+' has been verified';
            NominatorInfo nom = new NominatorInfo( contacts[0].Id, contacts[0].AACR_ID__c, contacts[0].Email,
                                                 contacts[0].Name, statusText, true );
            returnMap.put( 'nominator', nom );
            return new Response( true, statusText, returnMap );
        }else{
            message = Label.Nominator_Cannot_Be_Used.replace('NominatorName', contacts[0].Name);
            NominatorInfo nom = new NominatorInfo( contacts[0].Id, contacts[0].AACR_ID__c, contacts[0].Email,
                                                 contacts[0].Name, message, false );
            returnMap.put( 'nominator', nom );
            return new Response(false, message, returnMap);
        }       
    }
    
    /*
     * @Purpose     : nextStep processing
     * @Parameter   : String contactId, String stepId, DW_JPMembershipControllerClone.Attachment_x[] attachments, String[] nominatorIDs
     * @Returns     : Response
     */
    public static Response nextStep( String contactId, String stepId, DW_JPMembershipControllerClone.Attachment_x[] attachments, 
        String[] nominatorIDs , String[] oldAttachmentIds, Boolean isStudentMembership, Map<String, String> studentNominator ){
        // Updating user contact Last accessed Step
        DW_ECRMUtils.upsertContLastAccessedStep(stepId);
        
        //Intializing record lists to be inserted
        Attachment[] insertAttachments = new List<Attachment>();
        npe4__Relationship__c[] relationships =new List<npe4__Relationship__c>();
        
        //Getting contactId if contactId is null or blank
        if(String.isBlank(contactId)){
            Id userId = UserInfo.getUserId();
            User user = [SELECT ContactId FROM User WHERE ID = :userId ];
            contactId = user.ContactId;
        }
        
        try{
            //Adding attachment records to attachment list
            for( DW_JPMembershipControllerClone.Attachment_x attachment : attachments ){
                insertAttachments.add(new Attachment(ParentId=contactId, Body=EncodingUtil.base64Decode(attachment.body), Name = attachment.name, Description = 'JoinProcess'));
            }
            if(!insertAttachments.isEmpty()){
                //Deleting old attachments
                delete [SELECT Id FROM Attachment WHERE ParentId = :contactId AND Description LIKE '%JoinProcess%' AND Id NOT IN :oldAttachmentIds ];
            }
            
            //Inserting attachments
            insert insertAttachments;
            if( !isStudentMembership ) { //if not student membership then only create and delete relationship records
                for( String nominatorId : nominatorIDs ){
                    //Adding relationship records
                    relationships.add( new npe4__Relationship__c( npe4__Contact__c = contactId,
                                                                npe4__RelatedContact__c = nominatorId,
                                                                npe4__Status__c = 'Current',
                                                                npe4__Type__c = 'Nominator'
                                                               ) );
                }

                //Deleting old relationship records
                npe4__Relationship__c[] oldRelationships = [SELECT Id, npe4__RelatedContact__c
                                                            FROM npe4__Relationship__c
                                                            WHERE npe4__Contact__c = :contactId LIMIT 2 ];
                delete oldRelationships;
                
                //Inserting relationship records for nominies
                insert relationships;
            } else {
                Contact contactObj = new Contact();
                contactObj.Id = contactId;
                contactObj.Contact_StudentNominatorType__c = studentNominator.get('type');
                contactObj.Contact_StudentNominatorName__c = studentNominator.get('name');
                contactObj.Contact_StudentNominatorTitle__c = studentNominator.get('title');
                upsert contactObj;
            }
            //Changes in code
            joinApi.JoinUtils joinUtil = new joinApi.JoinUtils(stepId);
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('stepId', stepId);
            String redirectURL = joinUtil.navStepsMap.get('Next');
            system.debug('===redirectURL '+redirectURL);
            gen.writeStringField('redirectURL', redirectURL);
            gen.writeEndObject();
            system.debug('gen='+gen);
            
            try{if(gen.getAsString()!=null)
                joinUtil.setRedirectURLCookie(gen.getAsString());
               }
            catch(Exception e){system.debug('===='+e);}
            
            return new Response(true, '', null);
            
            
            //return new Response(true, ''+item, null);
        }catch(Exception e){
            System.debug(e.getMessage() + '\t' + e.getStackTraceString());
            return new Response(false, e.getMessage() + '\t' + e.getStackTraceString(), null);
        }
    }
    
    /*
     * @Purpose     : Method to fetch Item record for the given contact
     * @Parameter   : Contact Id (String)
     * @Returns     : Item record
     */
   /* private static Orderapi__Item__c getItem(String contactId){
        Contact contact = [SELECT Membership_Id__c FROM Contact WHERE Id = :contactId];
        system.debug( 'SELECT Membership_Id__c FROM Contact WHERE Id = '+contactId );
        system.debug( 'contact: ' + contact );
        Orderapi__Item__c item;
        if(contact.Membership_Id__c != null){
            item = (Orderapi__Item__c) new Framework.Selector(Orderapi__Item__c.SObjectType).selectById(contact.Membership_Id__c);
            System.debug('@@@item:' + item);
        }
        return item;
    }*/
    
    /*
     * @Purpose     : Method to fetch URL of next step
     * @Parameter   : Current Step Id (String)
     * @Returns     : URL (String)
     */
    public static String getNextStepURL(String currentStepId) {
        return new joinApi.JoinUtils( currentStepId ).navStepsMap.get('Next');
    }
    
    public static String getPreviousStepURL(String currentStepId) {
    	return new joinApi.JoinUtils(currentStepId).navStepsMap.get('Previous');
    }
    
    public static String getCancelStepURL(String currentStepId) {
        return new joinApi.JoinUtils(currentStepId).navStepsMap.get('First');
    }
    
    /*
     * @Purpose     : Builds soql string to be fired to verify nominator
     * @Parameter   : Current Step Id (String)
     * @Returns     : Response
     */
    private static Response buildStringQuery(String contactId, String memberNo , String email){
        if(String.isBlank(memberNo) && String.isBlank(email)){
            return new Response(false, 'Please enter member# or email', null);
        }
        
        //Building sql query string
        String soqlString = 'SELECT Id, Name, Lastname, Email, AACR_ID__c, OrderApi__Personal_Email__c, OrderApi__Other_Email__c, OrderApi__Work_Email__c, Membership_Status__c,'
            + ' (SELECT Id, OrderApi__Item__r.Eligible_Nominator_Membership__c FROM OrderApi__Subscriptions__r WHERE OrderApi__Item__r.Eligible_Nominator_Membership__c = true)'
            + ' FROM ' + Schema.SobjectType.Contact.Name
            + ' WHERE ';
        
        //Adding where clause to the query
        soqlString += String.isNotBlank(memberNo) ? 'AACR_ID__c =\'' + memberNo + '\' ' : '';
        soqlString += String.isNotBlank(memberNo) && String.isNotBlank(email) ? ' OR ' : '';
        soqlString += String.isNotBlank(email) ? 'Email =\'' + email + '\' ' : '';
        
        System.debug('soqlString: ' + soqlString);
        
        return new Response(true, soqlString);
    }
    /*
     * @Purpose     : Fetch all details about nominators related to the given contact
     * @Parameter   : Contact Id (String)
     * @Returns     : List of nominators with their details
     */
    private static NominatorInfo[] getNominatorsInfo(String contactId){
        //Getting nominator information
        NominatorInfo[] nominatorsInfo = new List<NominatorInfo>();
        for(npe4__Relationship__c nominator : [SELECT Id, npe4__RelatedContact__c, npe4__RelatedContact__r.AACR_ID__c, npe4__RelatedContact__r.Email, 
                                               npe4__RelatedContact__r.Name
                                               FROM npe4__Relationship__c
                                               WHERE npe4__Contact__c = :contactId LIMIT 2 ]){
            String statusText = nominator.npe4__RelatedContact__r.Name + ' has been verified';
            nominatorsInfo.add(new NominatorInfo(nominator.npe4__RelatedContact__c, nominator.npe4__RelatedContact__r.AACR_ID__c, nominator.npe4__RelatedContact__r.Email,
                                                 nominator.npe4__RelatedContact__r.Name, statusText, true));
        }
        return nominatorsInfo;
    }
    
    /*
     * @Purpose     : Wrapper to store each nominators details
     */
    public class NominatorInfo{
        String nominatorId;
        String memberNo;
        String email;
        String name;
        String status;
        Boolean isVerified;
        
        public NominatorInfo(){}
        
        public NominatorInfo(String nominatorId, String memberNo, String email, String name, String status, Boolean isVerified){
            this.nominatorId = nominatorId;
            this.memberNo = memberNo;
            this.email = email;
            this.name = name;
            this.status = status;
            this.isVerified = isVerified;
        }
    }

    public static Response deleteAttachment( String contactId, String attachmentId ) {
        if( String.isNotBlank( contactId ) && String.isNotBlank( attachmentId ) ){
            Attachment attach = new Attachment();
            try {
                attach = [ SELECT Id FROM Attachment WHERE Id =: attachmentId ];
                delete attach; 
                return new Response( true, 'Attachment deleted successfully', null );   
            } catch( Exception e ) {
                system.debug( 'Exception while attachment delete: '+e.getMessage() + ' ' + e.getStackTraceString() );
                return new Response( false, 'Error occured while deleting attachment', null );
            }            
        } else {
            return new Response( false, 'Bad data', null );
        }
    }
}