src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Major_Focus__c</fullName>
        <description>Describes major focus of the contact.</description>
        <inlineHelpText>Describes major focus of the contact.</inlineHelpText>
        <label>Major Focus</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
                <value>
                    <fullName>Basic Research</fullName>
                </value>
                <value>
                    <fullName>Basic Science</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Clinical Practice</fullName>
                </value>
                <value>
                    <fullName>Clinical Research</fullName>
                </value>
                <value>
                    <fullName>Population Science</fullName>
                </value>
                <value>
                    <fullName>Research Administration</fullName>
                </value>
                <value>
                    <fullName>Science Education</fullName>
                </value>
                <value>
                    <fullName>Translational Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Join_Process__mdt.object
<CustomObject>
    <description>Types of membership join/renewal processes</description>
    <fields>
        <fullName>Is_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If process is for initial join or renewing of membership</description>
        <label>Is Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <description>List of items that can be processed for a particular join process</description>
        <label>Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Join Process</label>
    <pluralLabel>Join Processes</pluralLabel>
</CustomObject>

src/objects/Join_Step__mdt.object
<CustomObject>
    <description>Individual steps available for join/renewal process</description>
    <label>Join Step</label>
    <pluralLabel>Join Steps</pluralLabel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Steps__mdt.object
<CustomObject>
    <description>Steps related to an individual join process in order</description>
    <fields>
        <fullName>Join_Step__c</fullName>
        <description>Associate join step component</description>
        <label>Join Step</label>
        <referenceTo>Join_Step__mdt</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <description>Associated join process</description>
        <label>Process</label>
        <referenceTo>Join_Process__mdt</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Step_Order__c</fullName>
        <label>Step Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Process Step</label>
    <pluralLabel>Process Steps</pluralLabel>
</CustomObject>

src/classes/JP_ScientificInterestsControllerTest.cls
/**
 * Created by lauren.lezberg on 2/4/2019.
 */
@isTest 
private with sharing class JP_ScientificInterestsControllerTest {


    @testSetup static void setup() {
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;
        Contact testContact = TestDataFactory.buildContactMemberCurrent(acc.Id);
        insert testContact;
        User u = TestDataFactory.buildUser(testContact.Id);
        insert u;
        OrderApi__Item_Class__c itemClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert itemClass;
        OrderApi__Item__c item = TestDataFactory.buildItem(itemClass.Id, 'Active Membership');
        insert item;

    }

    @isTest
    public static void testInitialize(){

        Test.startTest();
        JP_ScientificInterestsController controller = new JP_ScientificInterestsController();
        Test.stopTest();

        System.assertNotEquals(controller, null);

    }

    @isTest
    public static void testGetScientificInterestData(){
        Join_Process__mdt jp = [SELECT Id FROM Join_Process__mdt WHERE Item__c LIKE: '%Active Membership%' AND Is_Renewal__c = false];
        Process_Steps__mdt step = [SELECT Id, Step_Order__c FROM Process_Steps__mdt WHERE Process__c =: jp.Id AND Join_Step__r.DeveloperName ='Scientific_Interest'];

        Test.startTest();
        JP_ScientificInterestsController.scientificInterestData scientificInterestData = JP_ScientificInterestsController.getScientificInterestData(step.Id);
        Test.stopTest();

        System.assertNotEquals(null, scientificInterestData);
    }


    @isTest
    public static void testUpsertContact(){
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Join_Process__mdt jp = [SELECT Id FROM Join_Process__mdt WHERE Item__c LIKE: '%Active Membership%' AND Is_Renewal__c = false];
        Process_Steps__mdt step = [SELECT Id, Step_Order__c FROM Process_Steps__mdt WHERE Process__c =: jp.Id AND Join_Step__r.DeveloperName ='Scientific_Interest'];

        User u = [SELECT Id FROM User WHERE ContactId =: testContact.Id];

        Test.startTest();
        System.runAs(u){
            testContact.Major_Focus__c = 'Basic Research';
            Boolean updateComplete = JP_ScientificInterestsController.updateContactRecord(testContact);

            Contact updatedCon = [SELECT Major_Focus__c FROM Contact WHERE Id=: testContact.Id];

            System.assertEquals(updateComplete, true);
            System.assertEquals(updatedCon.Major_Focus__c, 'Basic Research');
        }
        Test.stopTest();
    }
}