src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Member_Type__c</fullName>
        <description>Indicates what level of membership this individual possesses.</description>
        <inlineHelpText>Indicates what level of membership this individual possesses.</inlineHelpText>
        <label>Member Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Badge__c.object
<CustomObject>
    <description>Badges are assigned to Contacts either automatically (Badge Workflow) or manually. Badges can enable Contacts for special Price Rules - as well as permission to read, update, or delete certain content types.</description>
    <fields>
        <fullName>OrderApi__Badge_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge Type</label>
        <referenceTo>OrderApi__Badge_Type__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the assigned Contact.</description>
        <inlineHelpText>Link to the assigned Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked, the Badge is considered &quot;Awarded&quot; and &quot;Active&quot; and will be considered when calculating any permission or pricing configurations related to the linked Badge Type. Defaults checked.</description>
        <inlineHelpText>When checked, the Badge is considered &quot;Awarded&quot; and &quot;Active&quot; and will be considered when calculating any permission or pricing configurations related to the linked Badge Type. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Badge ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Badge_Type__c.object
<CustomObject>
    <description>Configure Badge Types to assign to Contacts to allow greater control and flexibility around pricing and content accessibility.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked the Badge Type is active and available for assignment to a Contact</description>
        <inlineHelpText>When checked the Badge Type is active and available for assignment to a Contact</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Badge Type</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactFellowAccessControllerTest.cls
/**
 * Created by afaf.awad on 1/21/2021.
 */

@isTest
private with sharing class ContactFellowAccessControllerTest {
        @testSetup
        public static void setup(){
            Account acc = TestDataFactory.buildAccount('Test Account');
            insert acc;

            Contact con = TestDataFactory.buildContact(acc.Id);
            con.Member_Type__c = 'Active Member';
            insert con;

            User u = TestDataFactory.buildUser(con.Id);
            insert u;

            OrderApi__Badge_Type__c badgeType = TestDataFactory.buildBadgeType('AACR Fellow');
            insert badgeType;

            OrderApi__Badge__c badge = TestDataFactory.buildBadge(badgeType.Id, con.Id);
            insert badge;

        }

        @isTest
        public static void testGetFellowAccessBadgeAccess(){
            Contact con = [SELECT Id FROM Contact LIMIT 1];

            Test.startTest();
            ContactFellowAccessController.FellowBadgeInfo badgeInfo = ContactFellowAccessController.getFellowAccessBadge(con.Id);
            System.assertNotEquals(null, badgeInfo);
            System.assertNotEquals(null, badgeInfo.dirBadge);
            System.assertEquals(true, badgeInfo.canEdit);
            Test.stopTest();
        }

        @isTest
        public static void testGetFellowAccessBadgeNoAccess(){
            Contact con = [SELECT Id, Member_Type__c FROM Contact LIMIT 1];
            con.Member_Type__c = 'Student Member';
            update con;

            Test.startTest();
            ContactFellowAccessController.FellowBadgeInfo badgeInfo = ContactFellowAccessController.getFellowAccessBadge(con.Id);
            System.assertNotEquals(null, badgeInfo);
            System.assertNotEquals(null, badgeInfo.dirBadge);
            System.assertEquals(false, badgeInfo.canEdit);
            Test.stopTest();
        }

        @isTest
        public static void testEnableAndDisableFellowBadge(){
            Contact con = [SELECT Id FROM Contact LIMIT 1];

            Test.startTest();
            Boolean success = ContactFellowAccessController.revokeFellowForContact(con.Id);
            System.assertEquals(true, success);
            OrderApi__Badge__c dirBadge = [SELECT OrderApi__Is_Active__c FROM OrderApi__Badge__c WHERE OrderApi__Contact__c=:con.Id AND OrderApi__Badge_Type__r.Name='AACR Fellow'];
            System.assertEquals(false, dirBadge.OrderApi__Is_Active__c);

            success = ContactFellowAccessController.enableFellowForContact(con.Id);
            System.assertEquals(true, success);
            dirBadge = [SELECT OrderApi__Is_Active__c FROM OrderApi__Badge__c WHERE OrderApi__Contact__c=:con.Id AND OrderApi__Badge_Type__r.Name='AACR Fellow'];
            System.assertEquals(true, dirBadge.OrderApi__Is_Active__c);

            Test.stopTest();
        }
    }