src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Paid_thru_date__c</fullName>
        <description>This field will track the date upto which the customer&apos;s subscription is paid</description>
        <inlineHelpText>***SYSTEM CALCULATED***This field tracks the paid thru date of the membership</inlineHelpText>
        <label>Paid Thru Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Fon_Association_Journal_Type__c</fullName>
        <description>Classify association journals in Online only or Print</description>
        <label>Association Journals Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Online Only</fullName>
                </value>
                <value>
                    <fullName>Print &amp; Online</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</description>
        <inlineHelpText>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s account record. Auto-populates with the related contact&apos;s parent account if not defined prior to entry.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>**System Calculated/Override** Checked when a recurring order or contract is active.</description>
        <inlineHelpText>**System Calculated/Override** Checked when a recurring order or contract is active.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>Days_Left__c</fullName>
        <formula>OrderApi__Grace_Period_End_Date__c - TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Join_Date__c</fullName>
        <defaultValue>DATE(1900,1,01)</defaultValue>
        <description>Used to pull month and date of 1/1 into Process Builder.</description>
        <label>Join Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Account. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Account&quot;. Defaults to the same Account assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Account. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Account&quot;. Defaults to the same Account assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Current_Term_End_Date__c</fullName>
        <description>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</inlineHelpText>
        <label>Current Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Current_Term_Start_Date__c</fullName>
        <description>** System Calculated Required Override ** The start date for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The start date for the current subscription term.</inlineHelpText>
        <label>Current Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Days_To_Lapse__c</fullName>
        <description>** System Calculated ** The number of days until the Subscription will expire.</description>
        <inlineHelpText>** System Calculated ** The number of days until the Subscription will expire.</inlineHelpText>
        <label>Days to Lapse</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderApi__Grace_Period_End_Date__c</fullName>
        <description>This date is calculated by the Paid Through Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</description>
        <inlineHelpText>This date is calculated by the Paid Through Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</inlineHelpText>
        <label>Grace Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
        <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when the Subscription has expired.</description>
        <inlineHelpText>Checked when the Subscription has expired.</inlineHelpText>
        <label>Is Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Paid_Through_Date__c</fullName>
        <description>Defines the last active date of the subscription including all subscription renewals.</description>
        <inlineHelpText>Defines the last active date of the subscription including all subscription renewals.</inlineHelpText>
        <label>Paid Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</description>
        <inlineHelpText>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransferMemberController.cls
/**
 * Created by lauren.lezberg on 11/15/2019.
 */

public with sharing class TransferMemberController {

    /**
      * @purpose Determines whether to show the transfer button
      * Criteria: Does current user have custom permission & does contact have current PTD
      *
      * @param contactId
      *
      * @return True or False
      */
    @AuraEnabled
    public static Boolean showTransferButton(String contactId){
        Boolean toReturn = false;
        if(FeatureManagement.checkPermission('Transfers')) {
            Contact con = [SELECT Id, Paid_thru_date__c FROM Contact WHERE Id=: contactId];
            if(con.Paid_thru_date__c!=null) {
                if (con.Paid_thru_date__c.year() == System.now().year()) {
                    toReturn = true;
                } else if(con.Paid_thru_date__c.year() == System.now().year() + 1){ //if paid through next year
                    //get most recent membership subscription
                    List<OrderApi__Subscription__c> memSubs = [
                            SELECT Id,OrderApi__Paid_Through_Date__c, OrderApi__Subscription_Plan__c, OrderApi__Contact__c, OrderApi__Current_Term_End_Date__c, OrderApi__Days_To_Lapse__c,
                                    OrderApi__Item__c, OrderApi__Item__r.Name, OrderApi__Item__r.Fon_Association_Journal_Type__c, OrderApi__Grace_Period_End_Date__c,
                                    OrderApi__Item_Class__r.Name, Join_Date__c, OrderApi__Account__c,OrderApi__Is_Active__c, OrderApi__Is_Expired__c, OrderApi__Current_Term_Start_Date__c, Days_Left__c,
                                    OrderApi__Business_Group__c, OrderApi__Entity__c, OrderApi__Enable_Auto_Renew__c,Delinquency__c, OrderApi__Item__r.OrderApi__Image_Path__c, OrderApi__Item__r.Managed__c
                            FROM OrderApi__Subscription__c
                            WHERE OrderApi__Contact__c = :contactId AND
                            OrderApi__Item_Class__r.Name= 'Individual Memberships'
                            ORDER BY OrderApi__Paid_Through_Date__c DESC, CreatedDate DESC
                    ];
                    if(!memSubs.isEmpty()){
                        if(memSubs[0].OrderApi__Item__r.Managed__c) {
                            OrderApi__Subscription_Plan__c subPlan = [SELECT OrderApi__Advanced_Calendar_Days__c FROM OrderApi__Subscription_Plan__c WHERE Id = :memSubs[0].OrderApi__Subscription_Plan__c];
                            //check that sub plan is 2YR
                            if (subPlan.OrderApi__Advanced_Calendar_Days__c == 365) {
                                toReturn = true;
                            }
                        } else {
                            toReturn = true; 
                        }
                    }
                }
            }
        }
        return toReturn;
    }

    /**
     * @purpose Creates an empty sales order for back order processing and find correct join process for transfer
     *
     * @param contactId
     *
     * @return Instance of TransferInfo class
     */
    @AuraEnabled
    public static TransferInfo createEmptySO(Id contactId){
        OrderApi__Sales_Order__c SO = new OrderApi__Sales_Order__c(OrderApi__Contact__c=contactId);
        try {

            insert SO;
            List<Join_Process__mdt> joinProcesses = [SELECT Id FROM Join_Process__mdt WHERE DeveloperName = 'Back_Office_Transfer' LIMIT 1];
            return new TransferInfo(SO.Id, joinProcesses[0].Id);
        } catch(Exception e){
            System.debug('Could not create sales order: ' + e.getMessage());
        }
        return null;
    }

    public class TransferInfo{
        @AuraEnabled
        public String salesOrderId;

        @AuraEnabled
        public String joinId;


        public TransferInfo(String soId, String jId){
            this.salesOrderId = soId;
            this.joinId = jId;
        }

    }
}