src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Journal_City__c</fullName>
        <label>Journal City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_Country__c</fullName>
        <label>Journal Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_State_Province__c</fullName>
        <label>Journal State/Province</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_Street__c</fullName>
        <description>Address where member would prefer their printed journals to be sent.</description>
        <inlineHelpText>Address where member would prefer their printed journals to be sent.</inlineHelpText>
        <label>Journal Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Journal_Zip_Postal_Code__c</fullName>
        <label>Journal Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Known_Address__c.object
<CustomObject>
    <description>Known Addresses allows Contacts and Accounts to have multiple related address records.</description>
    <fields>
        <fullName>Bad_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Returned Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__City__c</fullName>
        <description>Address City</description>
        <inlineHelpText>Address City</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the known address to a contact.</description>
        <inlineHelpText>Relates the known address to a contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Known Addresses</relationshipLabel>
        <relationshipName>Known_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Country__c</fullName>
        <description>Address Country</description>
        <inlineHelpText>Address Country</inlineHelpText>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this will be the pre-populated address when a user is checking out. Only one address
            can be checked for a contact at any given time.</description>
        <inlineHelpText>When checked, this will be the pre-populated address when a user is checking out. Only one
            address can be checked for a contact at any given time.</inlineHelpText>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Name__c</fullName>
        <description>Name used as reference for this address.</description>
        <inlineHelpText>Name used as reference for this address.</inlineHelpText>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Postal_Code__c</fullName>
        <description>Address Zip/Postal Code</description>
        <inlineHelpText>Address Zip/Postal Code</inlineHelpText>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Province__c</fullName>
        <description>Address State</description>
        <inlineHelpText>Address State</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Street__c</fullName>
        <description>Address Street</description>
        <inlineHelpText>Address Street</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Known Address</label>
    <nameField>
        <displayFormat>KA-{000000000}</displayFormat>
        <label>Known Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateContactMailingAddressTriggerTest.cls
/**
 * Created by lauren.lezberg on 9/17/2020.
 */
@IsTest
private with sharing class UpdateContactMailingAddressTriggerTest {


    @TestSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

    }

    @IsTest
    public static void test_updateBillingAddress(){
        Contact con = [SELECT Id, MailingStreet, MailingState, MailingCountry, MailingCity, MailingPostalCode FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Known_Address__c ka = new OrderApi__Known_Address__c(
                OrderApi__Name__c = 'TEST',
                Type__c= 'Business',
                OrderApi__Is_Default__c = true,
                OrderApi__Contact__c = con.Id,
                OrderApi__Street__c = '123 Main St',
                OrderApi__City__c = 'Test',
                OrderApi__Country__c = 'United States',
                OrderApi__Province__c = 'California',
                OrderApi__Postal_Code__c = '12345'
        );

        Test.startTest();

        insert ka;

        Test.stopTest();

        ka = [SELECT OrderApi__Name__c, Type__c FROM OrderApi__Known_Address__c WHERE Id=:ka.Id];

        System.assertEquals('Other', ka.Type__c);
        System.assertEquals('Billing Address', ka.OrderApi__Name__c);
    }

    @IsTest
    public static void test_nonDefaultKnownAddress(){
        Contact con = [SELECT Id, MailingStreet, MailingState, MailingCountry, MailingCity, MailingPostalCode FROM Contact WHERE Account.Name = 'Test Account'];
        List<OrderApi__Known_Address__c> kas = new List<OrderApi__Known_Address__c>();
        Test.startTest();

        OrderApi__Known_Address__c ka = new OrderApi__Known_Address__c(
                Type__c= 'Business',
                OrderApi__Is_Default__c = true,
                OrderApi__Contact__c = con.Id,
                OrderApi__Street__c = '123 Main St',
                OrderApi__City__c = 'Test',
                OrderApi__Country__c = 'United States',
                OrderApi__Province__c = 'California',
                OrderApi__Postal_Code__c = '12345'
        );
        kas.add(ka);

        OrderApi__Known_Address__c ka2 = new OrderApi__Known_Address__c(
                Type__c= 'Personal',
                OrderApi__Is_Default__c = false,
                OrderApi__Contact__c = con.Id,
                OrderApi__Street__c = '456 Main St',
                OrderApi__City__c = 'Test2',
                OrderApi__Country__c = 'Canada',
                OrderApi__Province__c = 'Quebec',
                OrderApi__Postal_Code__c = '67890'
        );
        kas.add(ka2);

        insert kas;

        Test.stopTest();

        con = [SELECT Id, MailingStreet, MailingState, MailingCountry, MailingCity, MailingPostalCode FROM Contact WHERE Id=:con.Id];

        System.assertEquals(ka.OrderApi__Street__c, con.MailingStreet);
        System.assertEquals(ka.OrderApi__City__c, con.MailingCity);
        System.assertEquals(ka.OrderApi__Province__c, con.MailingState);
        System.assertEquals(ka.OrderApi__Country__c, con.MailingCountry);
        System.assertEquals(ka.OrderApi__Postal_Code__c, con.MailingPostalCode);

        System.assertNotEquals(ka2.OrderApi__Street__c, con.MailingStreet);
        System.assertNotEquals(ka2.OrderApi__City__c, con.MailingCity);
        System.assertNotEquals(ka2.OrderApi__Province__c, con.MailingState);
        System.assertNotEquals(ka2.OrderApi__Country__c, con.MailingCountry);
        System.assertNotEquals(ka2.OrderApi__Postal_Code__c, con.MailingPostalCode);

    }

    @IsTest
    public static void test_newKnownAddress(){
        Contact con = [SELECT Id, MailingStreet, MailingState, MailingCountry, MailingCity, MailingPostalCode FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Known_Address__c ka = new OrderApi__Known_Address__c(
                Type__c= 'Business',
                OrderApi__Is_Default__c = true,
                OrderApi__Contact__c = con.Id,
                OrderApi__Street__c = '123 Main St',
                OrderApi__City__c = 'Test',
                OrderApi__Country__c = 'United States',
                OrderApi__Province__c = 'California',
                OrderApi__Postal_Code__c = '12345'
        );

        Test.startTest();

        insert ka;

        Test.stopTest();

        con = [SELECT Id, MailingStreet, MailingState, MailingCountry, MailingCity, MailingPostalCode FROM Contact WHERE Id=:con.Id];

        System.assertEquals(ka.OrderApi__Street__c, con.MailingStreet);
        System.assertEquals(ka.OrderApi__City__c, con.MailingCity);
        System.assertEquals(ka.OrderApi__Province__c, con.MailingState);
        System.assertEquals(ka.OrderApi__Country__c, con.MailingCountry);
        System.assertEquals(ka.OrderApi__Postal_Code__c, con.MailingPostalCode);

    }

    @IsTest
    public static void test_newJournalAddress(){
        Contact con = [SELECT Id, Journal_Street__c, Journal_City__c, Journal_State_Province__c, Journal_Country__c, Journal_Zip_Postal_Code__c FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Known_Address__c ka = new OrderApi__Known_Address__c(
                Type__c= 'Journal',
                OrderApi__Is_Default__c = false,
                OrderApi__Contact__c = con.Id,
                OrderApi__Street__c = '123 Main St',
                OrderApi__City__c = 'Test',
                OrderApi__Country__c = 'United States',
                OrderApi__Province__c = 'California',
                OrderApi__Postal_Code__c = '12345'
        );

        Test.startTest();

        insert ka;

        Test.stopTest();

        con = [SELECT Id, Journal_Street__c, Journal_City__c, Journal_State_Province__c, Journal_Country__c, Journal_Zip_Postal_Code__c FROM Contact WHERE Id=:con.Id];

        System.assertEquals(ka.OrderApi__Street__c, con.Journal_Street__c);
        System.assertEquals(ka.OrderApi__City__c, con.Journal_City__c);
        System.assertEquals(ka.OrderApi__Province__c, con.Journal_State_Province__c);
        System.assertEquals(ka.OrderApi__Country__c, con.Journal_Country__c);
        System.assertEquals(ka.OrderApi__Postal_Code__c, con.Journal_Zip_Postal_Code__c);

    }

    @IsTest
    public static void test_updateReturnedAddress(){
        Contact con = [SELECT Id, MailingStreet, MailingState, MailingCountry, MailingCity, MailingPostalCode FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Known_Address__c ka = new OrderApi__Known_Address__c(
                OrderApi__Name__c = 'TEST',
                Type__c= 'Business',
                OrderApi__Is_Default__c = true,
                OrderApi__Contact__c = con.Id,
                OrderApi__Street__c = '123 Main St',
                OrderApi__City__c = 'Test',
                OrderApi__Country__c = 'United States',
                OrderApi__Province__c = 'California',
                OrderApi__Postal_Code__c = '12345',
                Bad_Address__c = True
        );
        insert ka;
        Test.startTest();

        ka.OrderApi__Street__c = '456 New Main Street';
        update ka;

        Test.stopTest();

        ka = [SELECT OrderApi__Name__c, Bad_Address__c FROM OrderApi__Known_Address__c WHERE Id=:ka.Id];

        System.assertEquals(false, ka.Bad_Address__c);
    }

}