src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paid_thru_date__c</fullName>
        <description>This field will track the date upto which the customer&apos;s subscription is paid</description>
        <inlineHelpText>***SYSTEM CALCULATED***This field tracks the paid thru date of the membership</inlineHelpText>
        <label>Paid Thru Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ROEContactUpdateHandlerTest.cls
/**
 * Created by lauren.lezberg on 12/13/2018.
 */

@IsTest
private class ROEContactUpdateHandlerTest {

    @IsTest
    static void test_Prior_updateContactToMember() {
        TestDataFactory testData = new TestDataFactory();

        List<RecordType> rTypes = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact' AND Name='Prior Member' ];
        testData.testContact.RecordTypeId = rTypes[0].Id;
        testData.testContact.Paid_Thru_Date__c = Date.newInstance(2017, 12,31);
        testData.testContact.Membership_Status__c = '1-YR Suspended';
        update testData.testContact;

        Test.startTest();
        ROEContactUpdateHandler.updateContactToMember(testData.testContact.Id, null);
        Test.stopTest();

        Contact c = [SELECT Membership_Status__c, Paid_thru_date__c FROM Contact WHERE Id=:testData.testContact.Id LIMIT 1];

        System.assert(c.Membership_Status__c == 'Current', 'Status should be current');
        System.assert(c.Paid_thru_date__c == Date.newInstance(2018, 12,31), 'Paid through date should be 12/31/2018');

    }

    @IsTest
    static void test_Current_updateContactToMember() {
        TestDataFactory testData = new TestDataFactory();

        List<RecordType> rTypes = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact' AND Name='Member' ];
        testData.testContact.RecordTypeId = rTypes[0].Id;
        testData.testContact.Paid_Thru_Date__c = Date.newInstance(2017, 12,31);
        testData.testContact.Membership_Status__c = 'Current';
        update testData.testContact;

        Test.startTest();
        ROEContactUpdateHandler.updateContactToMember(testData.testContact.Id, Date.newInstance(2018, 12,31));
        Test.stopTest();

        Contact c = [SELECT Membership_Status__c, Paid_thru_date__c FROM Contact WHERE Id=:testData.testContact.Id LIMIT 1];

        System.assert(c.Membership_Status__c == 'Current', 'Status should be current');
        System.assert(c.Paid_thru_date__c == Date.newInstance(2018, 12,31), 'Paid through date should be 12/31/2018');

    }

}