src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</description>
        <inlineHelpText>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Current_Term_End_Date__c</fullName>
        <description>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</inlineHelpText>
        <label>Current Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Current_Term_Start_Date__c</fullName>
        <description>** System Calculated Required Override ** The start date for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The start date for the current subscription term.</inlineHelpText>
        <label>Current Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Grace_Period_End_Date__c</fullName>
        <description>This date is calculated by the Paid Through Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</description>
        <inlineHelpText>This date is calculated by the Paid Through Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</inlineHelpText>
        <label>Grace Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
        <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when the Subscription has expired.</description>
        <inlineHelpText>Checked when the Subscription has expired.</inlineHelpText>
        <label>Is Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Paid_Through_Date__c</fullName>
        <description>Defines the last active date of the subscription including all subscription renewals.</description>
        <inlineHelpText>Defines the last active date of the subscription including all subscription renewals.</inlineHelpText>
        <label>Paid Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</description>
        <inlineHelpText>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Schedule_SuspendMembersAfterGPTest.cls
/**
 * Created by lauren.lezberg on 1/23/2020.
 */
@isTest
private with sharing class Schedule_SuspendMembersAfterGPTest {

    @testSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;
        System.assertEquals(1, [SELECT Id FROM Account].size());

        // Build OrderApi__Subscription_Plan__c record
        OrderApi__Subscription_Plan__c subPlan = TestDataFactory.buildsubPlan();
        insert subPlan;
        System.assertEquals(1, [SELECT Id FROM OrderApi__Subscription_Plan__c].size());

        List<Contact> contacts = new List<Contact>();
        for(Integer i = 0; i<50; i++){
            Contact con = TestDataFactory.buildContactMemberCurrent(acc.id);
            contacts.add(con);
        }
        insert contacts;

        OrderApi__Item_Class__c membershipClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert membershipClass;

        OrderApi__Item__c membership = TestDataFactory.buildItem(membershipClass.Id, 'Active Membership');
        insert membership;

        List<OrderApi__Subscription__c> subscriptions = new List<OrderApi__Subscription__c>();

        for(Contact contact : contacts){
            OrderApi__Subscription__c sub = TestDataFactory.buildSubscription(contact.Id, subPlan.Id, membership.Id, membershipClass.Id);
            sub.OrderApi__Current_Term_Start_Date__c = Date.newInstance(system.today().year()-1, 1, 1);
            sub.OrderApi__Current_Term_End_Date__c = Date.newInstance(System.today().year() - 1, System.today().month()-1, System.today().day());
            sub.OrderApi__Is_Active__c = false;
            sub.OrderApi__Is_Expired__c = true;
            sub.OrderApi__Grace_Period_End_Date__c = Date.newInstance(System.today().year() - 1, System.today().month(), System.today().day() - 1);
            sub.OrderApi__Paid_Through_Date__c = Date.newInstance(System.today().year() - 1, System.today().month(), System.today().day() - 1);
            subscriptions.add(sub);
        }

        insert  subscriptions;

    }


    @isTest
    public static void testScheduledJob(){
        Integer memberCount = [SELECT COUNT() FROM Contact WHERE RecordType.Name='Member' AND Membership_Status__c = 'Current'];
        Test.StartTest();
        SchedulableContext sc = null;
        Schedule_SuspendMembersAfterGracePeriod obj = new Schedule_SuspendMembersAfterGracePeriod();
        obj.execute(sc);
        Test.stopTest();
        System.assertEquals(memberCount, [SELECT COUNT() FROM Contact WHERE RecordType.Name = 'Prior Member' AND Membership_Status__c = '1-YR Suspended']);

    }
}