src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Queue management field for the Membership Department.</description>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete Application</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Clarification</fullName>
                </value>
                <value>
                    <fullName>Former Applicant</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Pending Transfer</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement-Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Type__c</fullName>
        <description>Indicates what level of membership this individual possesses.</description>
        <inlineHelpText>Indicates what level of membership this individual possesses.</inlineHelpText>
        <label>Member Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paid_thru_date__c</fullName>
        <description>This field will track the date upto which the customer&apos;s subscription is paid</description>
        <inlineHelpText>***SYSTEM CALCULATED***This field tracks the paid thru date of the membership</inlineHelpText>
        <label>Paid Thru Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Current_Term_End_Date__c</fullName>
        <description>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</inlineHelpText>
        <label>Current Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
        <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubscriptionContactSyncTriggerHandler.cls
/**
 * Created by lauren.lezberg on 10/2/2019.
 */

public with sharing class SubscriptionContactSyncTriggerHandler {


    public static void updateContactFromSubscription(List<OrderApi__Subscription__c> subs, Boolean isUpdate){
        System.debug('updateContactFromSubscription...' + isUpdate);
        Set<Id> contactIds = new Set<Id>();

        for (OrderApi__Subscription__c sub : subs) {
            contactIds.add(sub.OrderApi__Contact__c);
        }


        Map<Id, Contact> contactMap = new Map<Id, Contact>([
                select id, Member_Type__c, Membership_Status__c, Paid_thru_date__c, Application_Status__c, RecordTypeId
                from Contact
                where Id IN:contactIds
        ]);

        List<Contact> toUpdate = new List<Contact>();

        Id memberRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();

        Set<Id> contactDirectoryUpdate = new Set<Id>();

        /* for each subscription */
        for (OrderApi__Subscription__c sub :subs) {
            //get contact
            Contact con = contactMap.get(sub.OrderApi__Contact__c);

            //get most recent membership subscription
//            List<OrderApi__Subscription__c> memSubs = RenewalUtils.getIndividualMembershipSubscription(con.Id);
            Map<Id, OrderApi__Subscription__c> memSubsMap = RenewalUtils.getContactMembershipMap(contactIds);
            System.debug('memSubsMap: ' + memSubsMap);

            if(memSubsMap.keySet().contains(con.Id)) {
                //if subscription is the most recent membership subscription and subscription is active and isUpdate OR is NOT update
                if ((sub.Id == memSubsMap.get(con.Id).Id && sub.OrderApi__Is_Active__c && isUpdate) || !isUpdate) {
                    System.debug('update contact from subscription...');
                    //set member type on contact record if contact member type is null or doesnt match item
                    if (sub.OrderApi__Item__r.Name.remove('ship') != con.Member_Type__c || con.Member_Type__c == null) {
                        con.Member_Type__c = sub.OrderApi__Item__r.Name.remove('ship');
                    }
                    //set paid through date on contact record if contact paid through date is null or doesnt match subscription
                    if (sub.OrderApi__Current_Term_End_Date__c != con.Paid_thru_date__c || con.Paid_thru_date__c == null) {
                        con.Paid_thru_date__c = sub.OrderApi__Current_Term_End_Date__c;
                    }

                    //if its not a new application, change record type and status to Member and Current
                    if (con.Application_Status__c == null || con.Application_Status__c == 'Awaiting Payment') {
                        System.debug('Renewal or Awaiting Payment');
                        if (con.RecordTypeId != memberRecordTypeId) {
                            con.RecordTypeId = memberRecordTypeId;
                        }
                        if (con.Membership_Status__c != 'Current') {
                            con.Membership_Status__c = 'Current';
                        }

                        if(con.Application_Status__c == 'Awaiting Payment'){
                            con.Application_Status__c = null;
                        }

                        //get contacts to enable directory badges for
                        contactDirectoryUpdate.add(con.Id);
                    }
                    toUpdate.add(con);
                }
            }
        }

        
        try {
            update toUpdate;

            if(!Test.isRunningTest()) {
                BadgeUtils.enableDirectoryAccess(contactDirectoryUpdate);
            }
        }catch(Exception e){
            System.debug('Could not update contact: ' + e.getMessage());
        }
    }
}