src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <description>Formula field reflecting either legacy iMIS ID or new Salesforce ID depending upon when record was created.</description>
        <formula>IF(ISBLANK( iMIS_ID__c ), Salesforce_ID__c, iMIS_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>EventApi__Description__c</fullName>
        <description>Optional event description.</description>
        <inlineHelpText>Optional event description.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event end date.</description>
        <inlineHelpText>**Required** The event end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Time__c</fullName>
        <description>**Required** The event end time (HH:MM).</description>
        <inlineHelpText>**Required** The event end time (HH:MM).</inlineHelpText>
        <label>End Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventApi__Event_Key__c</fullName>
        <description>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</description>
        <inlineHelpText>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</inlineHelpText>
        <label>Event Key</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EventApi__Logo_Image__c</fullName>
        <description>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</description>
        <inlineHelpText>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</inlineHelpText>
        <label>Logo Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event start date.</description>
        <inlineHelpText>**Required** The event start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Time__c</fullName>
        <description>**Required** The event start time (HH:MM).</description>
        <inlineHelpText>**Required** The event start time (HH:MM).</inlineHelpText>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MassRegistrationControllerTest.cls
/**
 * Created by afaf.awad on 6/11/2020.
 */

@IsTest
private class MassRegistrationControllerTest {

    @testSetup
    static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        List<Contact> contacts = new List<Contact>();
        for(Integer i=0; i<=2 ; i++) {
            Contact testContact = TestDataFactory.buildContact(acc.Id);
            testContact.LastName = 'Test Contact'+ i;
            testContact.Email = 'testEmail' + i + '@yopmail.com';
            contacts.add(testContact);
            System.debug('Test Contact = ' + testContact);
        }

        insert contacts;

        Contact dupContact = TestDataFactory.buildContact(acc.Id);
        dupContact.LastName = 'Test Contact0';
        dupContact.Email = 'testEmail0@yopmail.com';
        insert dupContact;

        EventApi__Event__c testEvt = TestDataFactory.buildEvent();
        testEvt.EventApi__Event_Key__c = '3847294726';
        testEvt.EventApi__Start_Date__c = Date.today();
        testEvt.EventApi__Start_Time__c = '08:00 AM';
        testEvt.EventApi__End_Time__c = '08:00 PM';
        testEvt.EventApi__End_Date__c = Date.today().addDays(2);
        testEvt.EventApi__Logo_Image__c = 'https://www.testImgurl.com';
        testEvt.EventApi__Description__c = 'THIS IS A TEST EVENT.';
        insert testEvt;

        System.debug('Test Contact List: ' + contacts);

        EventApi__Attendee__c testAtt = new EventApi__Attendee__c(EventApi__Event__c = testEvt.Id,
                EventApi__Contact__c = contacts.get(0).Id);
        insert testAtt;
    }

    @isTest
    static void test_isEligibleEvent(){
        String eventId = [Select Id from EventApi__Event__c WHERE Name LIKE 'Test Event' LIMIT 1].Id;

        Test.startTest();
         Boolean eligible = MassRegistrationController.isEligibleEvent(eventId);
        Test.stopTest();

        System.assertEquals(false, eligible);
    }

    @IsTest
    static void test_ValidateData(){
        List<Contact> contacts = [Select AACR_ID__c, Email FROM Contact];
        String eventId = [SELECT Id FROM EventApi__Event__c WHERE Name = 'Test Event'].Id;

        String fileData = 'Email,Id' + '\n'
                + contacts[0].Email + ',' + contacts[0].AACR_ID__c + '\n'
                + contacts[1].Email + ',' + contacts[1].AACR_ID__c;

        String fileDataNoEmail = 'Email,Id' + '\n'
                + contacts[0].Email + ',' + contacts[0].AACR_ID__c + '\n'
                + ' ,' + contacts[1].AACR_ID__c;

        System.debug('fileData = ' + fileData);

        List<String> fields = new List<String>();

        fields.add('Email');
        fields.add('Id');


        Test.startTest();
        Boolean noEmail = MassRegistrationController.validateData(fileDataNoEmail, fields, 'Id', 'Email');
        Boolean withEmail = MassRegistrationController.validateData(fileData, fields, 'Id', 'Email');
        Test.stopTest();
        System.assertEquals(false, noEmail);
        System.assertEquals(true, withEmail);
    }

    @isTest
    static void test_processData(){
        List<Contact> contacts = [Select AACR_ID__c, Email FROM Contact];
        String eventId = [SELECT Id FROM EventApi__Event__c WHERE Name = 'Test Event'].Id;

        String fileData = 'Email,Id' + '\n'
                + contacts[0].Email + ',' + contacts[0].AACR_ID__c + '\n'
                + contacts[1].Email + ',' + contacts[1].AACR_ID__c + '\n'
                + contacts[2].Email + ',' + contacts[2].AACR_ID__c + '\n'
                + 'idontexist@yopmail.com,';

        System.debug('fileData = ' + fileData);

        List<String> fields = new List<String>();

        fields.add('Email');
        fields.add('Id');


        Test.startTest();
        System.debug('FileData: ' + fileData);
        MassRegistrationController.processData(fileData, fields, 'Id', 'Email', eventId);
        Test.stopTest();

    }

    @IsTest
    static void test_GetAACRIds(){

        List<Contact> contacts = [SELECT AACR_ID__c FROM Contact];
        List<String> Ids = new List<String>();

        for(Contact c: contacts){
            Ids.add(c.AACR_ID__c);
        }

        Test.startTest();
        List<Contact> contacts2 = MassRegistrationController.queryContactsByAACRID(Ids);
        Test.stopTest();

        System.assertEquals(4, contacts2.size());

    }

    @isTest
    static void test_CreateAttendees(){

        String eventId = [SELECT Id FROM EventApi__Event__c WHERE Name LIKE 'Test Event' LIMIT 1].Id;
        List<Contact> contacts = [SELECT Id FROM Contact];

        Test.startTest();
        MassRegistrationController.createAttendees(contacts,eventId);
        Test.stopTest();

        List<EventApi__Attendee__c> attendees = [SELECT Id FROM EventApi__Attendee__c WHERE EventApi__Event__c =: eventId];

        System.assertEquals(4,attendees.size());
    }
}