src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Current Education Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Education__c.object
<CustomObject>
    <description>AACR custom object to reflect the historical information of a member&apos;s education.</description>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Degree Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Expected_Graduation__c</fullName>
        <label>Date of Expected Graduation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Degree_Completion_Year__c</fullName>
        <description>In what year was this degree be achieved (e.g. YYYY)?</description>
        <inlineHelpText>In what year was this degree be achieved (e.g. YYYY)?</inlineHelpText>
        <label>Degree Completion Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <description>Many to 1 relationship of educational degrees to a Contact record.</description>
        <inlineHelpText>What academic degree has this individual achieved?</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AAS</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BAAS</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BDS</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>B Eng</fullName>
                </value>
                <value>
                    <fullName>BMBCh</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>BPharm</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>BSN</fullName>
                </value>
                <value>
                    <fullName>DDS</fullName>
                </value>
                <value>
                    <fullName>DMD</fullName>
                </value>
                <value>
                    <fullName>DMSc</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>D Phil</fullName>
                </value>
                <value>
                    <fullName>DSc</fullName>
                </value>
                <value>
                    <fullName>DVM</fullName>
                </value>
                <value>
                    <fullName>DrPH</fullName>
                </value>
                <value>
                    <fullName>DrRerNat</fullName>
                </value>
                <value>
                    <fullName>EdD</fullName>
                </value>
                <value>
                    <fullName>EdM</fullName>
                </value>
                <value>
                    <fullName>HT</fullName>
                </value>
                <value>
                    <fullName>JD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education_Related_to_Contact__c</fullName>
        <description>Many to 1 relationship of educational degrees to a Contact record.</description>
        <label>Education Related to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education</relationshipLabel>
        <relationshipName>Education</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Education</label>
    <nameField>
        <label>Institution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/joinapi__Join_Process__c.object
<CustomObject>
    <description>The controlling object for join processes.</description>
    <fields>
        <fullName>joinapi__Is_Published__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked this field makes the join process page visible to end users.</description>
        <inlineHelpText>When checked this field makes the join process page visible to end users.</inlineHelpText>
        <label>Is Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>joinapi__Join_Process_Display_Name__c</fullName>
        <description>The name that will be presented at the top of the page.</description>
        <inlineHelpText>The name that will be presented at the top of the page.</inlineHelpText>
        <label>Join Process Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>joinapi__Landing_Url__c</fullName>
        <description>** System Calculated ** The landing Url calculated from the first step</description>
        <inlineHelpText>** System Calculated ** The landing Url calculated from the first step</inlineHelpText>
        <label>Landing Url</label>
        <type>Url</type>
    </fields>
    <label>Join Process</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Join Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Join Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/joinapi__Step__c.object
<CustomObject>
    <description>The configuration of what is presented to the customer during the join process.</description>
    <fields>
        <fullName>joinapi__Is_Custom_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines the step to be a custom page.</description>
        <inlineHelpText>Defines the step to be a custom page.</inlineHelpText>
        <label>Is Custom Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>joinapi__Is_First_Step__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked indicates this is the first step in the Join Process</description>
        <inlineHelpText>When checked indicates this is the first step in the Join Process</inlineHelpText>
        <label>Is First Step</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>joinapi__Is_Published__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked this step is visible to end users.</description>
        <inlineHelpText>When checked this step is visible to end users.</inlineHelpText>
        <label>Is Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>joinapi__Join_Process__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the join process step to the join process.</description>
        <inlineHelpText>Relates the join process step to the join process.</inlineHelpText>
        <label>Join Process</label>
        <referenceTo>joinapi__Join_Process__c</referenceTo>
        <relationshipName>Join_Process_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>joinapi__Next_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the step that is redirected after the current step is submitted</description>
        <inlineHelpText>This is the step that is redirected after the current step is submitted</inlineHelpText>
        <label>Next Step</label>
        <referenceTo>joinapi__Step__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>joinapi__Order__c</fullName>
        <description>Defines the order the steps are to be displayed.</description>
        <inlineHelpText>Defines the order the steps are to be displayed.</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>joinapi__Page_Title__c</fullName>
        <description>Defines the page title text that is displayed at the top of the page.</description>
        <inlineHelpText>Defines the page title text that is displayed at the top of the page.</inlineHelpText>
        <label>Page Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>joinapi__Visual_Force_Page_API_Name__c</fullName>
        <description>Define the VF page to be used for this step.</description>
        <inlineHelpText>Define the VF page to be used for this step.</inlineHelpText>
        <label>Visual Force Page API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DW_EducationInformationControllerTest.cls
/**
 *@Purpose      : Test class for DW_EducationInformationController
 *@Created Date : 03-10-2018
 *@Modified Date: 03-10-2018
 */
@isTest
public class DW_EducationInformationControllerTest {

    /**
     *@purpose   : build test data.
     */
    @testSetup
    private static void buildTestData(){ 
        
        // build Account record
        Account account = buildAccount('Test Account1');
        insert account;
        
        // Build Contact record
        Contact contact= buildContact(account.Id);
        insert contact;
        
        // Build User recod
        User user = buildUser(contact.Id);
        insert user;

        // Building education records
        List<Education__c> educationList = buildEducation(contact.Id);
        insert educationList;
        
        joinapi__Join_Process__c joinProcess =  buildJoinProcess();
        insert joinProcess;
        
        joinapi__Step__c step = buildPreviousStep();
        insert step;
        
        joinapi__Step__c firstStep = buildStep(step.Id, joinProcess.Id);
        insert firstStep;
        
        joinapi__Step__c secoundStep = buildCurrentStep(firstStep.Id, joinProcess.Id);
        insert secoundStep;
        
        joinapi__Step__c thirdStep = buildNextStep(secoundStep.Id, joinProcess.Id);
        insert thirdStep;
        
        joinapi__Step__c forthStep = buildFirstStep(thirdStep.Id, joinProcess.Id);
        insert forthStep;
    }
    
    /**
     *@purpose   : build Account record
     *@param     : accountName
     *@return    : Account record
     */
    static Account buildAccount(String accountName){
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Active Account').getRecordTypeId();
        
        return new Account(RecordTypeId = recordTypeId,
                           Name = accountName);
    }
    
    /**
     *@purpose   : Build Contact record
     *@param     : accountId
     *@return    : Contact record
     */
    static Contact buildContact(Id accountId){
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get( Label.Contact_Non_Member_Record_Type ).getRecordTypeId();
        
        // Creating Contact record
        return new Contact(LastName = 'Test contact',
                           AccountId = accountId,
                           RecordTypeId = recordTypeId,
                           Phone ='9878986789',
                           Fax = 'fax');
    }
    
    /**
     *@purpose   : Build User record
     *@param     : contactId
     *@return    : User record
     */
    static User buildUser(Id contactId){
        // Fetching profile record
        Profile profileRecord = [SELECT Id
                                 FROM Profile 
                                 WHERE Name =: 'Fonteva Customer Community Login User'
								 LIMIT 1];
        
        // Create users record
        User userRecord = new User(alias = 'test',
                                   ContactId = contactId,
                                  // AccountId = contactRecord1.AccountId,
                                   ProfileId = profileRecord.Id, 
                                   email = 'test@testorg.com', 
                                   emailencodingkey = 'UTF-8', 
                                   lastname = 'Test User2', 
                                   CommunityNickname = 'test user2',
                                   languagelocalekey = 'en_US', 
                                   localesidkey = 'en_US', 
                                   timezonesidkey = 'America/Los_Angeles', 
                                   username = System.now().millisecond() + 'test@testorg2.com');
        return userRecord;
    }
    
    /**
     *@purpose   : Build eduction records
     *@param     : ContactId 
     *@return    : Education List
     */
    static List<Education__c> buildEducation(Id contactId){
        List<Education__c> eductionList = new List<Education__c>();
        
        for(Integer index = 0; index < 5; index++){
           eductionList.add(new Education__c(Education_Related_to_Contact__c = contactId,
                                             Name = 'Engineering',
                                             Current_Education_Status__c = 'Graduate Student',
                                             Date_of_Expected_Graduation__c = System.today(),
                                             Degree__c = 'BE',
                                             Degree_Completion_Year__c = '2020'));
        }
        return eductionList;
    }
    
    /**
     *@purpose   : Build join process
     *@parameter : -
     *@return    : join process record
     */
    static joinapi__Join_Process__c buildJoinProcess(){
        return new joinapi__Join_Process__c(joinapi__Join_Process_Display_Name__c = 'CM-Custom JP',
                                            joinapi__Is_Published__c = true,
                                            joinapi__Landing_Url__c = '' );
    }
    
    /**
     *@purpose   : Build previous step record
     *@param     : -
     *@return    : step record
     */ 
    static joinapi__Step__c buildPreviousStep(){
       return new joinapi__Step__c (joinapi__Page_Title__c = 'DW_CommunicationPreferences',
                                    joinapi__Order__c = 3,
                                    joinapi__Visual_Force_Page_API_Name__c ='DW_CommunicationPreferences',
                                    joinapi__Is_Custom_Page__c = true);
    }
    
    /**
     *@purpose   : Build step record
     *@param     : nextStepId, joinProcessId
     *@return    : step record
     */ 
    static joinapi__Step__c buildStep(Id nextStepId, Id joinProcessId){
        return new joinapi__Step__c (joinapi__Page_Title__c = 'DW_WorkingGroups',
                                     joinapi__Next_Step__c = nextStepId,
                                     joinapi__Is_First_Step__c = true,
                                     joinapi__Order__c = 1,
                                     joinapi__Visual_Force_Page_API_Name__c ='DW_WorkingGroups',
                                     joinapi__Join_Process__c = joinProcessId,
                                     joinapi__Is_Custom_Page__c = true);
    }
    
    /**
     *@purpose   : Build step record
     *@param     : nextStepId, joinProcessId
     *@return    : step record
     */ 
    static joinapi__Step__c buildCurrentStep(Id nextStepId, Id joinProcessId){
        return new joinapi__Step__c (joinapi__Page_Title__c = 'DW_QualifyingQuestions',
                                     joinapi__Next_Step__c = nextStepId,
                                     joinapi__Order__c = 2,
                                     joinapi__Visual_Force_Page_API_Name__c ='DW_QualifyingQuestions',
                                     joinapi__Join_Process__c = joinProcessId,
                                     joinapi__Is_Custom_Page__c = true);
    }
    
    /**
     *@purpose   : Build step record
     *@param     : nextStepId, joinProcessId
     *@return    : step record
     */ 
    static joinapi__Step__c buildNextStep(Id nextStepId, Id joinProcessId){
        return new joinapi__Step__c (joinapi__Page_Title__c = 'DW_JPMembership',
                                     joinapi__Order__c = 4,
                                     joinapi__Next_Step__c = nextStepId,
                                     joinapi__Visual_Force_Page_API_Name__c ='DW_JPMembership',
                                     joinapi__Join_Process__c = joinProcessId,
                                     joinapi__Is_Custom_Page__c = true
                                   );
    }
       
    /**
     *@purpose   : Build step record
     *@param     : nextStepId, joinProcessId
     *@return    : step record
     */ 
    static joinapi__Step__c buildFirstStep(Id nextStepId, Id joinProcessId){
        return new joinapi__Step__c (joinapi__Page_Title__c = 'DW_JournalSubscription',
                                     joinapi__Next_Step__c = nextStepId,
                                     joinapi__Order__c = 5,
                                     joinapi__Visual_Force_Page_API_Name__c ='DW_JournalSubscription',
                                     joinapi__Join_Process__c = joinProcessId,
                                     joinapi__Is_Custom_Page__c = true);
    }
    
    /**
     *@purpose   : Build EducationInfoDTO record
     *@param     : 
     *@return    : EducationInfoDTO serialize string
     */ 
    static String buildEducationInfoDTO(){
        
        List<String> deletedEducationIdList = new List<String>();
        for(Education__c eductaion : [SELECT Id FROM Education__c WHERE Name = 'Engineering']){
            deletedEducationIdList.add(eductaion.Id);
        }
        
        Contact contact = [SELECT Id FROM Contact WHERE LastName =: 'Test contact'];
        List<Education__c> eductionList = buildEducation(contact.Id);
        insert eductionList; 
        
        DW_ECRMDTO.EducationInfoDTO educationInfo = new DW_ECRMDTO.EducationInfoDTO();
        educationInfo.Educations = eductionList;
        educationInfo.DeletedEducationIdList = deletedEducationIdList;
        
        return JSON.serialize(educationInfo);
    }
    
    /**
     *@Purpose : test getEducationInformation() positively
     */
    static testMethod void testGetEducationInfo(){
        Test.startTest();
        
        User user = [SELECT Id, ContactId 
                     FROM User 
                     WHERE lastname =: 'Test User2'];
        
        System.runAs(user){
            DW_EducationInformationController eductionCon = new DW_EducationInformationController();
            // fetching step record
            joinapi__Step__c step = [SELECT Id, joinapi__Order__c, joinapi__Next_Step__c 
                                     FROM joinapi__Step__c 
                                     WHERE joinapi__Page_Title__c = 'DW_QualifyingQuestions'];
            
            DW_ECRMDTO.Response response = DW_EducationInformationController.getEducationInformation(step.Id);
            System.assertEquals('User Contact Data & Page Metadata', response.message);
            System.assertEquals(true, response.isSuccess);
            System.debug('response1==>'+response);
            
        }
        Test.stopTest();
    }
    
    /**
     *@Purpose : test saveEducationInformation() positively
     */
    private static testMethod void testSaveEducationInformation(){
        Test.startTest();
        
        User user = [SELECT Id, ContactId 
                     FROM User 
                     WHERE lastname =: 'Test User2'];
        
        System.runAs(user){
            
            String educationString = buildEducationInfoDTO();
            // fetching step record
            joinapi__Step__c step = [SELECT Id, joinapi__Order__c, joinapi__Next_Step__c 
                                     FROM joinapi__Step__c 
                                     WHERE joinapi__Page_Title__c = 'DW_QualifyingQuestions'];
            
            DW_ECRMDTO.Response response = DW_EducationInformationController.saveEducationInformation(educationString, step.Id);
            System.assertEquals('User education information updated successfully', response.message);
            System.assertEquals(true, response.isSuccess);
        }
        Test.stopTest();
    }
}