src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Degrees_Held__c</fullName>
        <label>Degrees Held</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No Degree</fullName>
                </value>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AAS</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BAAS</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BDS</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>B Eng</fullName>
                </value>
                <value>
                    <fullName>BMBCh</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>B Pharm</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>BSN</fullName>
                </value>
                <value>
                    <fullName>DDS</fullName>
                </value>
                <value>
                    <fullName>DMD</fullName>
                </value>
                <value>
                    <fullName>DMSc</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>D Phil</fullName>
                </value>
                <value>
                    <fullName>DSc</fullName>
                </value>
                <value>
                    <fullName>DVM</fullName>
                </value>
                <value>
                    <fullName>Dr PH</fullName>
                </value>
                <value>
                    <fullName>Dr Rer Nat</fullName>
                </value>
                <value>
                    <fullName>Ed D</fullName>
                </value>
                <value>
                    <fullName>EdM</fullName>
                </value>
                <value>
                    <fullName>JD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Display_in_Directory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field as criteria in directory to not display contact record.  Does not automatically remove contact unless configured in directory.</description>
        <inlineHelpText>Use this field as criteria in directory to not display contact record.  Does not automatically remove contact unless configured in directory.</inlineHelpText>
        <label>Do Not Display in Directory</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EU_Countries__mdt.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>EU Country</label>
    <pluralLabel>EU Countries</pluralLabel>
</CustomObject>

src/objects/Join_Process__mdt.object
<CustomObject>
    <description>Types of membership join/renewal processes</description>
    <label>Join Process</label>
    <pluralLabel>Join Processes</pluralLabel>
</CustomObject>

src/objects/OrderApi__Known_Address__c.object
<CustomObject>
    <description>Known Addresses allows Contacts and Accounts to have multiple related address records.</description>
    <fields>
        <fullName>OrderApi__City__c</fullName>
        <description>Address City</description>
        <inlineHelpText>Address City</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the known address to a contact.</description>
        <inlineHelpText>Relates the known address to a contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Known Addresses</relationshipLabel>
        <relationshipName>Known_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Country__c</fullName>
        <description>Address Country</description>
        <inlineHelpText>Address Country</inlineHelpText>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this will be the pre-populated address when a user is checking out. Only one address
            can be checked for a contact at any given time.</description>
        <inlineHelpText>When checked, this will be the pre-populated address when a user is checking out. Only one
            address can be checked for a contact at any given time.</inlineHelpText>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Postal_Code__c</fullName>
        <description>Address Zip/Postal Code</description>
        <inlineHelpText>Address Zip/Postal Code</inlineHelpText>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Province__c</fullName>
        <description>Address State</description>
        <inlineHelpText>Address State</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Street__c</fullName>
        <description>Address Street</description>
        <inlineHelpText>Address Street</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Known Address</label>
    <nameField>
        <displayFormat>KA-{000000000}</displayFormat>
        <label>Known Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JP_PersonalInfoController.cls
/**
 * Created by lauren.lezberg on 2/25/2019.
 */

public without sharing class JP_PersonalInfoController {
 
    public class PersonalInfo{

        @AuraEnabled
        public Contact currentContact;

        @AuraEnabled
        public Boolean disableDoNotDisplay;

        @AuraEnabled
        public Boolean hideDoNotDisplay;

        @AuraEnabled
        public List<String> degreesHeldValues;

        @AuraEnabled
        public List<OrderApi__Known_Address__c> addresses;


        public PersonalInfo(Contact con, Boolean disable, Boolean hide){
            this.currentContact = con;
            this.addresses = new List<OrderApi__Known_Address__c>();
            this.addresses = [SELECT Id, OrderApi__Is_Default__c, OrderApi__Street__c, OrderApi__City__c, OrderApi__Province__c, OrderApi__Country__c, OrderApi__Postal_Code__c, Type__c FROM OrderApi__Known_Address__c WHERE OrderApi__Contact__c=:con.Id];
            this.disableDoNotDisplay = disable;
            this.hideDoNotDisplay = hide;
            this.degreesHeldValues = ECRMUtils.getPicklistValues('Contact','Degrees_Held__c');

        }
    }

    @AuraEnabled
    public static Boolean setContactAccount(String contactId, String accountId){
        Boolean success = false;
        Contact con = [SELECT FirstName, LastName, Email FROM Contact WHERE Id = :contactId];
        if(accountId==null) {
            Account acc = ECRMUtils.createOrFindIndividualAccount(con.FirstName, con.LastName, con.Email, contactId);
            accountId = acc.Id;
        }
//        else {
            try {
                con.AccountId = accountId;
                update con;

                success = true;
            } catch (Exception e) {
                System.debug('Could not update account: ' + e.getMessage());
                return null;
            }
//        }

        return success;
    }

    @AuraEnabled
    public static Contact getCurrentContact(){
        return ECRMUtils.getCurrentLoginContact();
    }

    /**
     * @purpose Gets current contact record information
     *
     * @return PersonalInfo wrapper object
     */
    @AuraEnabled
    public static PersonalInfo getPersonalInfo(Id joinId){

        Contact currentContact = ECRMUtils.getCurrentLoginContact();
        Boolean disableDoNotDisplay = false;
        Boolean hideDoNotDisplay = false;

        if(joinId!=null){
            String selfRegId = [SELECT Id FROM Join_Process__mdt WHERE DeveloperName = 'myAACR_Registration'].Id;
            if (selfRegId == joinId) {
                hideDoNotDisplay = true;
            }
        }

        if(currentContact.Birthdate!=null) {
            Decimal age = Math.floor(currentContact.Birthdate.daysBetween(Date.today()) / 365.2425);

            if (age <= 17) {
                currentContact.Do_Not_Display_in_Directory__c = true;
                update currentContact;
                disableDoNotDisplay = true;
            }

        }

        return new PersonalInfo(currentContact, disableDoNotDisplay, hideDoNotDisplay);

    }


    /**
     * @purpose Retrieves map of states based on specified country value
     *
     * @param countryVal
     *
     * @return map of states within country
     */
    @AuraEnabled
    public static Map<String, String> getStates(String countryVal, String mailingCountryCode, String otherCountryCode){
        System.debug('getStates was just called with country : ' + countryVal);
        List<EU_Countries__mdt> countries = [SELECT Label, Country_Code__c FROM EU_Countries__mdt];
        Set<String> countryCodes = new Set<String>();
        for (EU_Countries__mdt country : countries) {
            countryCodes.add(country.Country_Code__c);
        }

            Contact currentContact = ECRMUtils.getCurrentLoginContact();
            if (countryCodes.contains(countryVal)) {
                System.debug('country code is in the EU');
                currentContact.Do_Not_Display_in_Directory__c = true;
            } else {
                System.debug('country code is NOT in the EU');
                if(mailingCountryCode!=null && otherCountryCode!=null) {
                    if (!countryCodes.contains(mailingCountryCode) && !countryCodes.contains(otherCountryCode)) {
                        currentContact.Do_Not_Display_in_Directory__c = false;
                    }
                }
            }

            try {
                update currentContact;
            } catch (Exception e) {
                System.debug('Could not update contact: ' + e.getMessage());
            }



        return ECRMUtils.getDependentPicklistValues('Contact', 'MailingCountryCode', 'MailingStateCode', countryVal);
    }

    @AuraEnabled
    public static Map<String, Boolean> verifyEmails(String workEmail, String personalEmail){
        Map<String, Boolean> emailValidityMap = new Map<String, Boolean>();
        if(workEmail!=null) {
            emailValidityMap.put('work', BriteVerifyHelper.verifyEmail(workEmail));
        }

        if(personalEmail!=null) {
            emailValidityMap.put('personal', BriteVerifyHelper.verifyEmail(personalEmail));
        }

        return emailValidityMap;
    }


}