src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Association_Journals_Type__c</fullName>
        <description>Classify association journals in Online only or Print. Originally created in UATF by Fonteva and recreated by JR.</description>
        <label>Association Journals Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Online Only</fullName>
                </value>
                <value>
                    <fullName>Print &amp; Online</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>International_Shipping_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>International Shipping Item</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.OrderApi__Item_Class__c</field>
                <operation>equals</operation>
                <value>a111I0000022dBxQAI</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Shipping Items</relationshipLabel>
        <relationshipName>Shipping_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>** System Calculated Override ** Enable Subscription specific controls and features for this Item. Defaults to the value of the same field on the Item&apos;s related Item Class.</description>
        <inlineHelpText>** System Calculated Override ** Enable Subscription specific controls and features for this Item. Defaults to the value of the same field on the Item&apos;s related Item Class.</inlineHelpText>
        <label>Is Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>OrderApi__Is_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra subscription related controls and features. Defaults unchecked.</description>
        <inlineHelpText>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra subscription related controls and features. Defaults unchecked.</inlineHelpText>
        <label>Is Subscription</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>Is2YR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the subscription plan a 2 year term</description>
        <label>Is2YR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Posting_Status__c</fullName>
        <description>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</description>
        <inlineHelpText>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>The status of the Sales Order.</description>
        <inlineHelpText>The status of the Sales Order.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Activation_Date__c</fullName>
        <description>** System Calculated Override Conditionally Required ** The date the Subscription will be activated is calculated based on conditions set on the related Subscription Plan and can be manually over-ridden if &quot;Auto Calculate Activation Date&quot; is unchecked.</description>
        <inlineHelpText>** System Calculated Override Conditionally Required ** The date the Subscription will be activated is calculated based on conditions set on the related Subscription Plan and can be manually over-ridden if &quot;Auto Calculate Activation Date&quot; is unchecked.</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Subscription__c</fullName>
        <defaultValue>false</defaultValue>
        <description>** System Calculated ** Checked when the Sales Order Line is linked to a &quot;Subscription&quot; Item.</description>
        <inlineHelpText>** System Calculated ** Checked when the Sales Order Line is linked to a &quot;Subscription&quot; Item.</inlineHelpText>
        <label>Is Subscription</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</inlineHelpText>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Transaction__c.object
<CustomObject>
    <description>Transactions store all debits and credits for double-entry accounting.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Inherited from the Contact on the linked source record.</description>
        <inlineHelpText>**System Calculated/Override** Inherited from the Contact on the linked source record.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Sales Order.</description>
        <inlineHelpText>Link to related Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Transactions (Summary)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateIntlShippingTransactionTest.cls
/**
 * Created by afaf.awad on 3/29/2019.
 */

@IsTest
private class CreateIntlShippingTransactionTest {

    @testSetup static void setup() {
        //Build contact
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;
        Contact testContact = TestDataFactory.buildContactMemberCurrent(acc.Id);
        testContact.MailingCountry = 'France';
        insert testContact;
        User u = TestDataFactory.buildUser(testContact.Id);
        insert u;

        //Build Item Classes to create Active Member with a Comp Journal
        OrderApi__Item_Class__c memClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert memClass;
        OrderApi__Item_Class__c compJournalClass = TestDataFactory.buildItemClass('Complimentary Journals');
        insert compJournalClass;
        OrderApi__Item_Class__c shippingClass = TestDataFactory.buildItemClass('Shipping Items');
        insert shippingClass;

        //Build Items to for each Item Class
        OrderApi__Item__c activeMem = TestDataFactory.buildItem(memClass.Id, 'Active Membership');
        insert activeMem;
        OrderApi__Item__c intlShipping = TestDataFactory.buildItem(shippingClass.Id, 'International Shipping - Cancer Research');
        insert intlShipping;
        OrderApi__Item__c journalItem = TestDataFactory.buildItem(compJournalClass.Id, 'Cancer Research');
        journalItem.Association_Journals_Type__c = 'Print & Online';
        journalItem.International_Shipping_Item__c = intlShipping.Id;
        insert journalItem;

        //Build Subscription Plan
        OrderApi__Subscription_Plan__c subPlan =TestDataFactory.buildsubPlan();
        insert subPlan;

        //Build Sale Order and Sale Order Lines (Active Membership and Comp Journal)
        OrderApi__Sales_Order__c so = TestDataFactory.buildOpenSalesOrder(acc.Id, testContact.Id);
        insert so;
        OrderApi__Sales_Order_Line__c soLine1 = TestDataFactory.buildSOLine(so.Id, activeMem.Id, memClass.Id);
        soLine1.OrderApi__Is_Subscription__c = true;
        soLine1.OrderApi__Subscription_Plan__c = subPlan.id;
        soLine1.OrderApi__Activation_Date__c = Date.newInstance(Date.today().year(), Date.today().month(), Date.today().day());
        insert soLine1;
        OrderApi__Sales_Order_Line__c soLine2 = TestDataFactory.buildSOLine(so.Id, journalItem.Id, compJournalClass.Id);
        soLine2.OrderApi__Is_Subscription__c = true;
        soLine2.OrderApi__Subscription_Plan__c = subPlan.id;
        soLine2.OrderApi__Activation_Date__c = Date.newInstance(Date.today().year(), Date.today().month(), Date.today().day());
        insert soLine2;
}


    @IsTest
    static void testIntlShippingTransaction() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        OrderApi__Sales_Order__c so = [Select Id From OrderApi__Sales_Order__c LIMIT 1];

        //Close and post Sale Order
        so.OrderApi__Status__c = 'Closed';
        so.OrderApi__Posting_Status__c = 'Posted';
        update so;

        //Create Transaction Summary
        OrderApi__Transaction__c transSummary = new OrderApi__Transaction__c();
        transSummary.OrderApi__Contact__c = testContact.Id;
        transSummary.OrderApi__Sales_Order__c = so.Id;
        insert transSummary;

        //Get Transaction Summary from posted Sale Order
        List<OrderApi__Transaction__c> transactions = [Select Id, OrderApi__Contact__c, OrderApi__Sales_Order__c from OrderApi__Transaction__c
                                                        WHERE OrderApi__Sales_Order__c =: so.id];

        test.startTest();
        CreateIntlShippingTransactionHelper.createTransactionLine(transactions);
        test.stopTest();

    }

    @IsTest
    static void testIntlShippingTransaction2YR() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        OrderApi__Sales_Order__c so = [Select Id From OrderApi__Sales_Order__c LIMIT 1];

        //Close and post Sale Order
        so.OrderApi__Status__c = 'Closed';
        so.OrderApi__Posting_Status__c = 'Posted';
        so.Is2YR__c = true;
        update so;

        //Create Transaction Summary
        OrderApi__Transaction__c transSummary = new OrderApi__Transaction__c();
        transSummary.OrderApi__Contact__c = testContact.Id;
        transSummary.OrderApi__Sales_Order__c = so.Id;
        insert transSummary;

        //Get Transaction Summary from posted Sale Order
        List<OrderApi__Transaction__c> transactions = [Select Id, OrderApi__Contact__c, OrderApi__Sales_Order__c from OrderApi__Transaction__c
        WHERE OrderApi__Sales_Order__c =: so.id];

        test.startTest();
        CreateIntlShippingTransactionHelper.createTransactionLine(transactions);
        test.stopTest();

    }
}