src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Member_Type__c</fullName>
        <description>Indicates what level of membership this individual possesses.</description>
        <inlineHelpText>Indicates what level of membership this individual possesses.</inlineHelpText>
        <label>Member Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>EventApi__Status__c</fullName>
        <description>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</description>
        <inlineHelpText>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                    <default>true</default>
                    <label>Invited</label>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Registered-DataLoad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>EventApi__Description__c</fullName>
        <description>Optional event description.</description>
        <inlineHelpText>Optional event description.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventApi__Display_Name__c</fullName>
        <description>Event name as you would like it to appear on registration pages, calendar reminders, and emails.</description>
        <inlineHelpText>Event name as you would like it to appear on registration pages, calendar reminders, and emails.</inlineHelpText>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event end date.</description>
        <inlineHelpText>**Required** The event end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__Location_And_Date_Text__c</fullName>
        <description>The value defined in this field will display in the upper right hand side of the navbar overriding the city, state, and date/time.</description>
        <inlineHelpText>The value defined in this field will display in the upper right hand side of the navbar overriding the city, state, and date/time.</inlineHelpText>
        <label>Location and Date Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EventApi__Logo_Image__c</fullName>
        <description>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</description>
        <inlineHelpText>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</inlineHelpText>
        <label>Logo Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event start date.</description>
        <inlineHelpText>**Required** The event start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__Status__c</fullName>
        <description>Status of the event. Must be &quot;active&quot; to be visible in the Portal.</description>
        <inlineHelpText>Status of the event. Must be &quot;active&quot; to be visible in the Portal.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <color>#78C953</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#E27001</color>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MyContent_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MyContent Settings</label>
</CustomObject>

src/objects/Virtual_Meeting_Links__mdt.object
<CustomObject>
    <description>links for virtual meetings</description>
    <fields>
        <fullName>CME_Link__c</fullName>
        <inlineHelpText>Link user will be directed to when they clink on the CME Link button.</inlineHelpText>
        <label>CME Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Check_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if computer check link is active</description>
        <label>Check IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Computer_Check_Link__c</fullName>
        <label>Computer Check Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if view link is active to users</description>
        <label>Event IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Freeman_Event_Id__c</fullName>
        <label>Freeman Event Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>My_Content_Image__c</fullName>
        <label>My Content Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Open__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Registration Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View_Link__c</fullName>
        <label>View Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>isCME__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the meeting CME eligible? If checked, the CME Link button will appear for this event.</inlineHelpText>
        <label>isCME</label>
        <type>Checkbox</type>
    </fields>
    <label>Virtual Meeting Links</label>
    <pluralLabel>Virtual Meetings Links</pluralLabel>
</CustomObject>

src/classes/MyContentController.cls
/**
 * Created by lauren.lezberg on 4/8/2020.
 */

public without sharing class MyContentController {
    public static List<Virtual_Meeting_Links__mdt> virtualMeetings = new List<Virtual_Meeting_Links__mdt>();

    @AuraEnabled
    public static MyContent_Settings__c getLiveRedirectMessage(){
        MyContent_Settings__c settings = MyContent_Settings__c.getOrgDefaults();
        return settings;
    }

    @AuraEnabled
    public static List<EventRegContent> getContent(){
        Id contactId = ECRMUtils.getCurrentLoginUserContactId();

        List<EventRegContent> contents = new List<EventRegContent>();

        //get all virtual meeting records
        List<Virtual_Meeting_Links__mdt> meetings = new List<Virtual_Meeting_Links__mdt>();
        if(Test.isRunningTest()){
            System.debug('running test: ' + virtualMeetings);
            meetings = virtualMeetings;
        } else{
            meetings = [SELECT Event_Id__c, My_Content_Image__c FROM Virtual_Meeting_Links__mdt];
        }
        Set<Id> eventIds = new Set<Id>();
        Map<Id, String> eventImageMap = new Map<Id, String>();
        //get all events with virtual meetings
        for(Virtual_Meeting_Links__mdt vml : meetings){
            eventIds.add(vml.Event_Id__c);
            eventImageMap.put(vml.Event_Id__c, vml.My_Content_Image__c);
        }

        if(!eventIds.isEmpty()) {

            List<EventApi__Attendee__c> tickets = [
                    SELECT Id, EventApi__Event__c, EventApi__Event__r.EventApi__Display_Name__c, EventApi__Event__r.EventApi__Location_And_Date_Text__c,
                            EventApi__Event__r.EventApi__Logo_Image__c, EventApi__Event__r.EventApi__Description__c, EventApi__Contact__c, EventApi__Contact__r.RecordType.Name, EventApi__Contact__r.Membership_Status__c,
                            EventApi__Event__r.EventApi__Start_Date__c,EventApi__Event__r.EventApi__End_Date__c, EventApi__Contact__r.Member_Type__c
                    FROM EventApi__Attendee__c
                    WHERE EventApi__Contact__c = :contactId AND EventApi__Status__c!='Cancelled' AND EventApi__Event__c IN:eventImageMap.keySet()
            ];
            Set<Id> uniqueEventIds = new Set<Id>();
            if (!tickets.isEmpty()) {
                for (EventApi__Attendee__c ticket : tickets) {
                    if(!uniqueEventIds.contains(ticket.EventApi__Event__c)) {
//                    if (ticket.EventApi__Event__r.EventApi__Start_Date__c >= Date.today()) {
                        EventRegContent erc = new EventRegContent();
                        erc.eventId = ticket.EventApi__Event__c;
                        erc.contactId = ticket.EventApi__Contact__c;
                        erc.imgURL = eventImageMap.get(ticket.EventApi__Event__c);
                        erc.eventName = ticket.EventApi__Event__r.EventApi__Display_Name__c;
                        erc.description = ticket.EventApi__Event__r.EventApi__Description__c;
                        erc.dateString = ticket.EventApi__Event__r.EventApi__Location_And_Date_Text__c;
                        erc.attendeeId = ticket.Id;
                        erc.showBusinessMessage = ticket.EventApi__Event__r.EventApi__Display_Name__c == '2020 Virtual Annual Meeting: Selected Presentations' && ticket.EventApi__Contact__r.RecordType.Name == 'Member' && ticket.EventApi__Contact__r.Membership_Status__c == 'Current' && ticket.EventApi__Contact__r.Member_Type__c!= 'Associate Member' && ticket.EventApi__Contact__r.Member_Type__c!= 'Student Member';
//                        erc.dateString = getDateString(ticket.EventApi__Event__r.EventApi__Start_Date__c, ticket.EventApi__Event__r.EventApi__End_Date__c);
                        contents.add(erc);
//                    }
                        uniqueEventIds.add(ticket.EventApi__Event__c);
                    }

                }
            }
        }

        return contents;

    }

    @AuraEnabled
    public static Virtual_Meeting_Links__mdt getVirtualEventLinks(String eventId){
        List<Virtual_Meeting_Links__mdt> meetings = new List<Virtual_Meeting_Links__mdt>();
        if(Test.isRunningTest()){
            System.debug('running test: ' + virtualMeetings);
            meetings = virtualMeetings;
        } else{
            meetings = [SELECT Computer_Check_Link__c, Registration_Open__c, Check_IsActive__c, Event_IsActive__c, View_Link__c, isCME__c, CME_Link__c FROM Virtual_Meeting_Links__mdt WHERE Event_Id__c=: eventId];
        }
        if(!meetings.isEmpty()){
            return meetings[0];
        }
//
        return null;
    }

//    private static String getDateString(Date startDate, Date endDate){
//        Map<Integer,String> monthNameMap=new Map<Integer, String>{1 =>'January', 2=>'February', 3=>'March', 4=>'April', 5=>'May',
//        6=>'June', 7=>'July', 8=>'August', 9=>'September',10=>'October',
//        11=>'November', 12=>'December'};
//        String dateString = monthNameMap.get(startDate.month()) + ' ' + startDate.day() + '-';
//        if(startDate.month() == endDate.month()){
//            dateString += endDate.day();
//        } else {
//            dateString += monthNameMap.get(endDate.month()) + ' ' + endDate.day();
//        }
//
//        dateString += ' ' + startDate.year();
//
//        return dateString;
//
//
//    }

    @AuraEnabled
    public static String getRegisterUrl(String eventId){
        List<Virtual_Meeting_Links__mdt> links = new List<Virtual_Meeting_Links__mdt>();
        if(Test.isRunningTest()){
            System.debug('running test: ' + virtualMeetings);
            links = virtualMeetings;
        } else{
            links = [SELECT Freeman_Event_Id__c FROM Virtual_Meeting_Links__mdt WHERE Event_Id__c=: eventId];
        }

        return '/VirtualRegisterForm?id=' + links[0].Freeman_Event_Id__c;
    }

    @AuraEnabled
    public static List<EventRegContent> getOpenRegistrations(){
        List<Virtual_Meeting_Links__mdt> links = new List<Virtual_Meeting_Links__mdt>();
        if(Test.isRunningTest()){
            System.debug('running test: ' + virtualMeetings);
            links = virtualMeetings;
        } else{
            links = [SELECT Event_Id__c, My_Content_Image__c FROM Virtual_Meeting_Links__mdt WHERE Registration_Open__c = true];
        }
        Set<Id> eventIds = new Set<Id>();
        Map<Id, String> eventImageMap = new Map<Id, String>();
        //get all events with virtual meetings
        for(Virtual_Meeting_Links__mdt vml : links){
            eventIds.add(vml.Event_Id__c);
            eventImageMap.put(vml.Event_Id__c, vml.My_Content_Image__c);
        }

        Id contactId = ECRMUtils.getCurrentLoginUserContactId();
        List<EventApi__Attendee__c> attendeeRecs = [SELECT Id, EventApi__Event__c FROM EventApi__Attendee__c WHERE EventApi__Event__c IN: eventIds AND EventApi__Contact__c=:contactId];
        Set<Id> attendingEvtIds = new Set<Id>();
        for(EventApi__Attendee__c att : attendeeRecs){
            attendingEvtIds.add(att.EventApi__Event__c);
        }

        List<EventApi__Event__c> events = [SELECT Id, EventApi__Description__c, EventApi__Logo_Image__c,EventApi__Display_Name__c, EventApi__Location_And_Date_Text__c FROM EventApi__Event__c WHERE Id IN: eventIds];
        List<EventRegContent> registrations = new List<EventRegContent>();
        for(EventApi__Event__c evt : events){
            if(!attendingEvtIds.contains(evt.Id)) {
                EventRegContent erc = new EventRegContent();
                erc.eventId = evt.Id;
                erc.imgURL = eventImageMap.get(evt.Id);
                erc.dateString = evt.EventApi__Location_And_Date_Text__c;
                erc.eventName = evt.EventApi__Display_Name__c;
                erc.description = evt.EventApi__Description__c;
                registrations.add(erc);
            } 
        }

        return registrations;

    }

    @AuraEnabled
    public static Contact getContactInfo(){

        String contactId = Apexpages.currentPage().getParameters().get('ContactID');

        Contact con = [Select Id, Name, Salutation, Title FROM Contact where Id =: contactId];

        return con;
    }


    @AuraEnabled
    public static String getLetterToDownload(String attendeeId){ 

        String servUrl = Url.getSalesforceBaseUrl().toExternalForm();

        List<EventApi__Attendee__c> attendees = [SELECT Id,EventApi__Contact__c, EventApi__Event__c FROM EventApi__Attendee__c WHERE Id =: attendeeId];

        for (EventApi__Attendee__c a : attendees) {
            if ( a.EventApi__Contact__c != null ) {
                servUrl += '/LetterOfParticipation?Id=' + a.EventApi__Contact__c + '&eventId=' + a.EventApi__Event__c;
            } else {
                system.debug('*** Contact is null ');
                servUrl += '/myAACRHelpCustom';
            }
        }

        system.debug('*** servUrl ' + servUrl);
        return servUrl;
    }


    public class EventRegContent{
        @AuraEnabled
        public String eventId;

        @AuraEnabled
        public String contactId;

        @AuraEnabled
        public String imgURL;

        @AuraEnabled
        public String dateString;

        @AuraEnabled
        public String eventName;

        @AuraEnabled
        public String description;

        @AuraEnabled
        public String attendeeId;

        @AuraEnabled
        public Boolean showBusinessMessage;
    }

}