src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Queue management field for the Membership Department.</description>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete Application</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Clarification</fullName>
                </value>
                <value>
                    <fullName>Former Applicant</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Pending Transfer</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement-Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Posting_Status__c</fullName>
        <description>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</description>
        <inlineHelpText>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DW_UpdateContactsAppStatusController.cls
/**
 *@Purpose      : Update contacts application status when sales order gets created or updated and its posting status is pending
 *@Created Date : 11-10-2018
 *@Modified Date: 11-10-2018
 */
public class DW_UpdateContactsAppStatusController {

    /**
     *@purpose : update contact's application status after update
     *@param   : newSalesOrderList, oldSalesOrderMap
     *@return  : 
     */
    public static void onafterUpdateSO(List<OrderApi__Sales_Order__c> newSalesOrderList, Map<Id,OrderApi__Sales_Order__c> oldSalesOrderMap){
        OrderApi__Sales_Order__c oldSalesOrder;
        List<OrderApi__Sales_Order__c> salesOderToUpdateList = new List<OrderApi__Sales_Order__c>();
        
        for(OrderApi__Sales_Order__c newSalesOrder : newSalesOrderList){
            oldSalesOrder = oldSalesOrderMap.get(newSalesOrder.Id);
            
            // check if previous sales order posting status not equals to new updated status
            if(newSalesOrder.OrderApi__Posting_Status__c != oldSalesOrder.OrderApi__Posting_Status__c ||
               newSalesOrder.OrderApi__Contact__c != oldSalesOrder.OrderApi__Contact__c){
                salesOderToUpdateList.add(newSalesOrder);                                                   
            }
        }
        if(! salesOderToUpdateList.isEmpty()){
            // update contact
            updateContactsAppStatus(salesOderToUpdateList);
        }
    }
    
    /**
     *@purpose : update contact's application status 
     *@param   : newSalesOrderList
     *@return  : 
     */
    public static void updateContactsAppStatus(List<OrderApi__Sales_Order__c> newSalesOrderList){
        List<Contact> contactToUpdateList = new List<Contact>();
        
        for(OrderApi__Sales_Order__c salesOrder : [SELECT Id, OrderApi__Posting_Status__c, OrderApi__Contact__c,
                                                          OrderApi__Contact__r.RecordType.Name,
                                                          OrderApi__Contact__r.Application_Status__c
                                                   FROM OrderApi__Sales_Order__c
                                                   WHERE Id IN : newSalesOrderList AND
                                                         OrderApi__Contact__r.RecordType.Name !=: Label.Contact_Non_Member_Record_Type]){
                                                             
          if(salesOrder.OrderApi__Posting_Status__c == Label.DW_SO_Posting_Status){
                // update contact application status
                salesOrder.OrderApi__Contact__r.Application_Status__c = Label.DW_Contact_App_Status;
                contactToUpdateList.add(salesOrder.OrderApi__Contact__r);
                System.debug('contactToUpdateList==>'+contactToUpdateList);
          }                                                 
       }
       if(! contactToUpdateList.isEmpty()){
          // Update contactToUpdateList 
          update contactToUpdateList;
       } 
    }
}