src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Initial_Join_Date__c</fullName>
        <label>Initial Join Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Type__c</fullName>
        <description>Indicates what level of membership this individual possesses.</description>
        <inlineHelpText>Indicates what level of membership this individual possesses.</inlineHelpText>
        <label>Member Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paid_thru_date__c</fullName>
        <description>This field will track the date upto which the customer&apos;s subscription is paid</description>
        <inlineHelpText>***SYSTEM CALCULATED***This field tracks the paid thru date of the membership</inlineHelpText>
        <label>Paid Thru Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Nonmember</fullName>
        <active>true</active>
        <label>Nonmember</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Maintenance_Mode_Config__mdt.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether maintenance mode is turned on</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maintenance_Message__c</fullName>
        <description>Messge to display to users about why page is not working</description>
        <label>Maintenance Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Page_API_Name__c</fullName>
        <description>Visualforce page api name where maintenance is occurring</description>
        <label>Page API Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Site Configurations</label>
    <pluralLabel>Maintenance Mode Configs</pluralLabel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</description>
        <inlineHelpText>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Account. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Account&quot;. Defaults to the same Account assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Account. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Account&quot;. Defaults to the same Account assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Current_Term_End_Date__c</fullName>
        <description>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</inlineHelpText>
        <label>Current Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Current_Term_Start_Date__c</fullName>
        <description>** System Calculated Required Override ** The start date for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The start date for the current subscription term.</inlineHelpText>
        <label>Current Term Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Entity__c</fullName>
        <description>** System Calculated Required Override ** Select &quot;Account&quot; if the primary subscriber is the linked Account, otherwise select &quot;Contact&quot;. Defaults to the value of the same field on the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Required Override ** Select &quot;Account&quot; if the primary subscriber is the linked Account, otherwise select &quot;Contact&quot;. Defaults to the value of the same field on the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Grace_Period_End_Date__c</fullName>
        <description>This date is calculated by the Paid Through Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</description>
        <inlineHelpText>This date is calculated by the Paid Through Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</inlineHelpText>
        <label>Grace Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
        <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</description>
        <inlineHelpText>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AuraHelper.cls
/**
 * Created by lauren.lezberg on 12/12/2018.
 */

public with sharing class AuraHelper {

//    public class membershipData{
//
//        @AuraEnabled
//        public List<RecordType> recordTypes;
//
//        @AuraEnabled
//        public List<OrderApi__Item__c> items;
//
//        public membershipData(List<RecordType> recordTypes, List<OrderApi__Item__c> membershipTypes){
//            this.recordTypes = recordTypes;
//            this.items = membershipTypes;
//        }
//    }
//
//    @AuraEnabled
//    public static membershipData getMembershipTypes(){
//        List<RecordType> recordTypes = getRecordTypes('Contact');
//        List<OrderApi__Item__c> items = [SELECT Name, Id FROM OrderApi__Item__c WHERE OrderApi__Item_Class__r.Name = 'Individual Memberships' AND OrderApi__Is_Active__c = true];
//        if(items.size()>0 && recordTypes.size()>0){
//            return new membershipData(recordTypes, items);
//        }
//        return null;
//    }
//
//
//    @AuraEnabled
//    public static Boolean createContactRecord(String lastName, Id recordTypeId, String membershipStatus, Boolean yopify, String memberType, Boolean nonMember ){
//        System.debug('createContactRecord was just called with lastname: ' + lastName + ' recordTypeId: ' + recordTypeId + ' membershipStatus: ' + membershipStatus + ' yopify: ' + yopify + ' memberType: ' + memberType + ' nonMember: ' + nonMember);
//
//        Account acct = [SELECT Id FROM Account WHERE Name='AACR Test Accounts' LIMIT 1];
//        Contact newContact = new Contact();
//        if(!nonMember){
//            newContact.FirstName = 'TEST';
//            newContact.LastName = lastName;
//            newContact.RecordTypeId = recordTypeId;
//            newContact.AccountId = acct.Id;
//            newContact.Email = lastName + '@yopmail.com';
//            newContact.Phone = '555-555-5555';
//            newContact.Initial_Join_Date__c = Date.newInstance(System.now().year()-6, 01, 03);
//        } else {
//            newContact.Member_Type__c = memberType;
//        }
//
//        OrderApi__Item__c item = [SELECT Id FROM OrderApi__Item__c WHERE Name=: memberType];
//        OrderApi__Subscription_Plan__c subPlan = [SELECT Id FROM OrderApi__Subscription_Plan__c ORDER BY CreatedDate LIMIT 1];
//
//        OrderApi__Subscription__c sub = new OrderApi__Subscription__c();
//        sub.OrderApi__Account__c = acct.Id;
//        sub.OrderApi__Contact__c = newContact.Id;
//        sub.OrderApi__Entity__c = 'Contact';
//        sub.OrderApi__Subscription_Plan__c = subPlan.Id;
//        sub.OrderApi__Item__c = item.Id;
//        if(membershipStatus == null && !nonMember){
//            newContact.Membership_Status__c = 'Current';
//            newContact.Paid_thru_date__c = Date.newInstance(System.now().year(), 12, 31);
//            sub.OrderApi__Current_Term_Start_Date__c = Date.newInstance(System.now().year(), 01, 01);
//            sub.OrderApi__Current_Term_End_Date__c = Date.newInstance(System.now().year(), 12, 31);
//            sub.OrderApi__Grace_Period_End_Date__c = Date.newInstance(System.now().year() + 1 , 01, 30);
//        } else{
//            newContact.Membership_Status__c = membershipStatus;
//            if(membershipStatus == '1-YR Suspended') {
//                newContact.Paid_thru_date__c = Date.newInstance(System.now().year()-1, 12, 31);
//                sub.OrderApi__Current_Term_Start_Date__c = Date.newInstance(System.now().year()-1, 01, 01);
//                sub.OrderApi__Current_Term_End_Date__c = Date.newInstance(System.now().year()-1, 12, 31);
//                sub.OrderApi__Grace_Period_End_Date__c = Date.newInstance(System.now().year(), 01, 30);
//            } else if(membershipStatus== '2-YR Suspended'){
//                newContact.Paid_thru_date__c = Date.newInstance(System.now().year()-2, 12, 31);
//                sub.OrderApi__Current_Term_Start_Date__c = Date.newInstance(System.now().year()-2, 01, 01);
//                sub.OrderApi__Current_Term_End_Date__c = Date.newInstance(System.now().year()-2, 12, 31);
//                sub.OrderApi__Grace_Period_End_Date__c = Date.newInstance(System.now().year()-1, 01, 30);
//            } else if(membershipStatus == 'Suspended(Delinquent)'){
//                newContact.Paid_thru_date__c = Date.newInstance(System.now().year()-3, 12, 31);
//                sub.OrderApi__Current_Term_Start_Date__c = Date.newInstance(System.now().year()-3, 01, 01);
//                sub.OrderApi__Current_Term_End_Date__c = Date.newInstance(System.now().year()-3, 12, 31);
//                sub.OrderApi__Grace_Period_End_Date__c = Date.newInstance(System.now().year()-2, 01, 30);
//            } else if (membershipStatus == 'Suspended(Resigned)'){
//                newContact.Paid_thru_date__c = Date.newInstance(System.now().year()-5, 12, 31);
//                sub.OrderApi__Current_Term_Start_Date__c = Date.newInstance(System.now().year()-5, 01, 01);
//                sub.OrderApi__Current_Term_End_Date__c = Date.newInstance(System.now().year()-5, 12, 31);
//                sub.OrderApi__Grace_Period_End_Date__c = Date.newInstance(System.now().year()-4, 01, 30);
//            }
//        }
//
//        try{
//            insert newContact;
//            insert sub;
//            return true;
//        } catch(DmlException e){
//            System.debug('Error: ' + e.getMessage());
//            return false;
//        }
//
//    }


    @AuraEnabled
    public static List<RecordType> getRecordTypes(String sObjectType){
        return [SELECT Id, Name FROM RecordType WHERE SobjectType =: sObjectType AND IsActive = true ORDER BY Name];
    }

//    @AuraEnabled
//    public static List<Maintenance_Mode_Config__mdt> getSiteConfigs(){
//        return [SELECT Id, Is_Active__c, Maintenance_Message__c,Page_API_Name__c, Label, DeveloperName, MasterLabel, Description__c FROM Maintenance_Mode_Config__mdt ORDER BY Is_Active__c DESC];
//    }
//
//    @AuraEnabled
//    public static void saveMdtConfig(Maintenance_Mode_Config__mdt record){
//
//        Metadata.CustomMetadata customMetadata =  new Metadata.CustomMetadata();
//        customMetadata.fullName = 'Maintenance_Mode_Config__mdt.' + record.DeveloperName;
//        customMetadata.label = record.MasterLabel;
//
//        Metadata.CustomMetadataValue isActive = new Metadata.CustomMetadataValue();
//        isActive.field = 'Is_Active__c';
//        isActive.value = record.Is_Active__c;
//        customMetadata.values.add(isActive);
//
//        Metadata.CustomMetadataValue message = new Metadata.CustomMetadataValue();
//        message.field = 'Maintenance_Message__c';
//        message.value = record.Maintenance_Message__c;
//        customMetadata.values.add(message);
//
//        Metadata.CustomMetadataValue pageName = new Metadata.CustomMetadataValue();
//        pageName.field = 'Page_API_Name__c';
//        pageName.value = record.Page_API_Name__c;
//        customMetadata.values.add(pageName);
//
//        Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
//        mdContainer.addMetadata(customMetadata);
//
//        MetadataCallback callback = new MetadataCallback();
//
//        Id jobId = Test.isRunningTest() ? '7074F00000TFipCQAT' : Metadata.Operations.enqueueDeployment(mdContainer, callback);
//        System.debug('jobId: ' + jobId);
//
//    }

}