src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Member_Type__c</fullName>
        <description>Indicates what level of membership this individual possesses.</description>
        <inlineHelpText>Indicates what level of membership this individual possesses.</inlineHelpText>
        <label>Member Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/contact_last_accessed_step__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>contacts last accessed step</relationshipLabel>
        <relationshipName>contacts_last_accessed_step</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JoinId__c</fullName>
        <description>Id of join process</description>
        <label>JoinId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Step_Order__c</fullName>
        <label>Step Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>contact last accessed step</label>
    <nameField>
        <displayFormat>SN-{0000}</displayFormat>
        <label>RN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>contacts last accessed step</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Join_Process__mdt.object
<CustomObject>
    <description>Types of membership join/renewal processes</description>
    <label>Join Process</label>
    <pluralLabel>Join Processes</pluralLabel>
</CustomObject>

src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Prefix__c</fullName>
        <inlineHelpText>Community user visible code prefix. Limit to 4 characters. Example: GENE</inlineHelpText>
        <label>Prefix</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SourceCode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Code</label>
        <referenceTo>OrderApi__Source_Code__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OfferMembership__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Offer Memberships</relationshipLabel>
        <relationshipName>Offer_Memberships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfferVersion__c</fullName>
        <label>Offer Version</label>
        <referenceTo>OfferVersion__c</referenceTo>
        <relationshipLabel>Offer Memberships</relationshipLabel>
        <relationshipName>Offer_Memberships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Memberships</relationshipLabel>
        <relationshipName>Offer_Memberships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SourceCode__c</fullName>
        <formula>Offer__r.SourceCode__r.Name</formula>
        <label>Source Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Used__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Used</label>
        <type>Checkbox</type>
    </fields>
    <label>Offer Membership</label>
    <nameField>
        <label>Offer Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OfferVersion__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <inlineHelpText>If Today&apos;s date lies on/between Start Date and End Date, the Offer Version will be Active</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <description>Lookup to the parent Offer record</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Versions</relationshipLabel>
        <relationshipName>Offer_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Use to override dates and make Offer Version Active</inlineHelpText>
        <label>Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publish__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Publish could be set to True when the Version is Active.  Then as days go by, the End Date could be in the past.  In this case the Publish will still be checked and Active would be False.</description>
        <inlineHelpText>Requires Active Offer Version</inlineHelpText>
        <label>Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOQLQuery__c</fullName>
        <description>Recording of the SOQL query that the user entered to create this version</description>
        <inlineHelpText>Query needs to return User records.  Must also contain the ContactId field.  Example: [SELECT Id, ContactId FROM User LIMIT 2]</inlineHelpText>
        <label>SOQL Query</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <inlineHelpText>If Today&apos;s date lies on/between Start Date and End Date, the Offer Version will be Active</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Offer Version</label>
    <nameField>
        <label>Offer Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Source_Code__c.object
<CustomObject>
    <description>Source Codes link Receipts to marketing activities.</description>
    <label>Source Code</label>
    <nameField>
        <label>Source Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JP_ContainerControllerTest.cls
/**
 * Created by lauren.lezberg on 12/17/2020.
 */

@IsTest
private class JP_ContainerControllerTest {
    public static String AccountName = 'Test Account';
    public static String SourceCodeName = 'BOGO';
    public static String OfferVersionName = SourceCodeName + ' ' + System.today().month() + System.today().year() + '.' + (Math.random() * 10000);
    public static String OVSOQLString = 'SELECT Id, ContactId FROM User WHERE IsActive = true AND ContactId IN (SELECT Id FROM Contact WHERE Member_Type__c=\'Active Member\' AND Membership_Status__c=\'Current\') LIMIT 10';
    public static String OfferMembersipName = OfferVersionName + '.' + (Math.random() * 10000);

    @TestSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;

    }

    @IsTest
    static void test_applyOffer() {
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];
        User u = [SELECT Id FROM User WHERE ContactId=:con.Id];

        OrderApi__Source_Code__c sourceCode = TestDataFactory.buildSourceCode('TEST');
        insert sourceCode;

        Offer__c o = new Offer__c(
                SourceCode__c = sourceCode.Id,
                Prefix__c = 'BOGO'
        );
        insert o;

        OfferVersion__c ov = new OfferVersion__c(
                StartDate__c = Date.today(),
                EndDate__c = Date.today().addDays(7),
                Offer__c = o.Id,
                Publish__c = true,
                Override__c = false,
                SOQLQuery__c = OVSOQLString
        );
        insert ov;

        OfferMembership__c om = new OfferMembership__c(
                Contact__c = con.Id,
                Offer__c = o.Id,
                OfferVersion__c = ov.Id,
                Used__c = false
        );
        insert om;

        Join_Process__mdt jp = [SELECT Id FROM Join_Process__mdt LIMIT 1];
        contact_last_accessed_step__c las = new contact_last_accessed_step__c(Step_Order__c = 1, JoinId__c = jp.Id, Contact__c = con.Id);
        insert las;

        SYstem.runAs(u) {
            Test.startTest();

            JP_ContainerController.ContainerInfo cInfo = JP_ContainerController.applyOffer(sourceCode.Id, null, om.Id, 'URL', jp.Id);
            System.assertEquals(false, cInfo.refresh);
            System.assertNotEquals(null, cInfo.salesOrderId);

            las.Step_Order__c = 2;
            update las;

            cInfo = JP_ContainerController.applyOffer(sourceCode.Id, cInfo.salesOrderId, om.Id, 'URL', jp.Id);
            System.assertEquals(true, cInfo.refresh);
            System.assertNotEquals(null, cInfo.salesOrderId);

        }

    }


    @IsTest
    static void test_startOrder() {
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];
        User u = [SELECT Id FROM User WHERE ContactId=:con.Id];

        Join_Process__mdt jp = [SELECT Id FROM Join_Process__mdt LIMIT 1];

        contact_last_accessed_step__c las = new contact_last_accessed_step__c(Step_Order__c = 1, JoinId__c = jp.Id, Contact__c = con.Id);
        insert las;

        SYstem.runAs(u) {
            Test.startTest();

            JP_ContainerController.ContainerInfo cInfo = JP_ContainerController.startOrder(jp.Id);
            System.assertEquals(false, cInfo.refresh);
            System.assertNotEquals(null, cInfo.salesOrderId);

            las.Step_Order__c = 2;
            update las;

            cInfo = JP_ContainerController.startOrder(jp.Id);
            System.assertEquals(true, cInfo.refresh);
            System.assertNotEquals(null, cInfo.salesOrderId);

            Test.stopTest();
        }
    }
}