src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Queue management field for the Membership Department.</description>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete Application</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Clarification</fullName>
                </value>
                <value>
                    <fullName>Former Applicant</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Pending Transfer</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement-Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Join_Process__mdt.object
<CustomObject>
    <description>Types of membership join/renewal processes</description>
    <fields>
        <fullName>Cancel_URL__c</fullName>
        <description>URL to redirect to on cancel. If none is specified, cancel will redirect with window.history.back();</description>
        <label>Cancel URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Join Process</label>
    <pluralLabel>Join Processes</pluralLabel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Future_Income_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GL account for purchases made in the current year that apply to next year</description>
        <label>Future Income Account</label>
        <referenceTo>OrderApi__GL_Account__c</referenceTo>
        <relationshipLabel>Items (Future Income Account)</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>Is_Reinstatement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Transfer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Transfer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Posting_Entity__c</fullName>
        <description>**System Calculated/Override** The entity the Sales Order posted too. Sales Orders either post through an Invoice(s) or through a single Receipt as a Cash Sale.</description>
        <inlineHelpText>**System Calculated/Override** The entity the Sales Order posted too. Sales Orders either post through an Invoice(s) or through a single Receipt as a Cash Sale.</inlineHelpText>
        <label>Posting Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                    <label>Receipt</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Posting_Status__c</fullName>
        <description>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</description>
        <inlineHelpText>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>The status of the Sales Order.</description>
        <inlineHelpText>The status of the Sales Order.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <description>**System Calculated**. Subtotal +</description>
        <formula>OrderApi__Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>**System Calculated** Subtotal +</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Required/Override** Link to the related GL Account.</description>
        <inlineHelpText>**System Calculated/Required/Override** Link to the related GL Account.</inlineHelpText>
        <label>GL Account</label>
        <referenceTo>OrderApi__GL_Account__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>**System Calculated** Total amount of Sales Order Line</description>
        <inlineHelpText>**System Calculated** Total amount of Sales Order Line</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Process_Steps__mdt.object
<CustomObject>
    <description>Steps related to an individual join process in order</description>
    <fields>
        <fullName>Process__c</fullName>
        <description>Associated join process</description>
        <label>Process</label>
        <referenceTo>Join_Process__mdt</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Process Step</label>
    <pluralLabel>Process Steps</pluralLabel>
</CustomObject>

src/classes/JP_CheckoutController.cls
/**
 * Created by lauren.lezberg on 2/15/2019.
 */

public without sharing class JP_CheckoutController {
//    public Id salesOrderId{get;set;}
//    public OrderApi__Store__c store {get;set;}
//    public String redirectURL {get;set;}


    /**
     * @purpose Determines if user is in community or in salesforce
     *
     * @return True or False
     */
    @AuraEnabled
    public static boolean isCommunity(){
        Id siteId = Site.getSiteId(); // take a look at the apex class Site, you may find more useful method concerning site/community
        if (siteId != null) {
            return true;
        }
        return false;
    }

    @AuraEnabled
    public static void submitApplication(String salesOrderId, String stepId){
        Contact con = ECRMUtils.getCurrentLoginContact();
        if(con.Id!=null) {

            Process_Steps__mdt ps = [SELECT Process__c FROM Process_Steps__mdt WHERE Id = :stepId];
            JP_Helper.deleteContactLastAccessedStep(ps.Process__c);

            OrderApi__Sales_Order__c so = [SELECT Id, Is_Transfer__c, Is_Reinstatement__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId];

            if(so.Is_Transfer__c && !so.Is_Reinstatement__c) {
                con.Application_Status__c = 'Pending Transfer';
            } else if(so.Is_Reinstatement__c && !so.Is_Transfer__c){
                con.Application_Status__c = 'Pending Reinstatement';
            } else if(so.Is_Reinstatement__c && so.Is_Transfer__c){
                con.Application_Status__c = 'Pending Reinstatement-Transfer';
            }
            //update application status
            update con;
        }
//        OrderApi__Sales_Order__c so = [SELECT Id, OrderApi__Total__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId];
////        so.OrderApi__Posting_Entity__c = 'Receipt';
//
//        so.OrderApi__Status__c = 'Closed';
//        so.OrderApi__Posting_Status__c = 'Pending';
//        try {
//            update so;
//        } catch (Exception e) {
//            System.debug('Could not close sales order: ' + e.getMessage());
//        }
    }



    /**
     * @purpose Closes sales order for check processing
     *
     * @param salesOrderId
     *
     * @return salesOrderId
     */
    @AuraEnabled
    public static String closeSalesOrder(String salesOrderId){
        OrderApi__Sales_Order__c so = [SELECT Id, OrderApi__Total__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId];
//        so.OrderApi__Posting_Entity__c = 'Receipt';
        so.OrderApi__Status__c = 'Closed';

        try {
            update so;
            return so.Id;
        } catch(Exception e){
            System.debug('Could not close sales order: ' + e.getMessage());
        }

        return null;
    }

    /**
     * @purpose Delete sales order and delete last accessed step
     *
     * @param salesOrderId
     * @param stepId
     */
    @AuraEnabled
    public static String deleteSalesOrder(String salesOrderId,Id stepId){
        System.debug('Deleting sales order: ' + salesOrderId + ' at step ' + stepId);
        List<Process_Steps__mdt> currentStep = [SELECT Process__c FROM Process_Steps__mdt WHERE Id =: stepId LIMIT 1];
        if (currentStep.size() == 1) {
            JP_Helper.deleteContactLastAccessedStep(currentStep[0].Process__c);
        }
        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId];
        try {
            delete so;
        } catch(Exception e){
            System.debug('Could not delete sales order: ' + e.getMessage());
        }

        Process_Steps__mdt pStep = [SELECT Process__r.Cancel_URL__c FROM Process_Steps__mdt WHERE Id=: stepId];
        if(pStep!=null){
            return pStep.Process__r.Cancel_URL__c;
        }

        return null;
    }


    /**
     * @purpose Retrieve all item information from the given sales order and upsert last accessed step
     *
     * @param salesOrderId
     * @param stepId
     *
     * @return CartData object instance
     */
    @AuraEnabled
    public static CartData getCartItems(String salesOrderId, Id stepId){
        if(stepId!=null) {
            JP_Helper.upsertLastAccessedStep(stepId);
        }
        return new CartData(salesOrderId, stepId);
    }




    /**
     * @purpose Delete sales order line from sales order. If item is a comp journal, delete and add decline journal item
     *
     * @param salesOrderLineId
     */
    @AuraEnabled
    public static void deleteCartItem(Id salesOrderLineId){
        System.debug('Deleting sales order line: ' + salesOrderLineId);
        OrderApi__Sales_Order_Line__c sol = [SELECT Id, OrderApi__Sales_Order__c, OrderApi__GL_Account__c, OrderApi__Item_Class__r.Name, OrderApi__Item__r.Future_Income_Account__c, OrderApi__Item__r.OrderApi__Income_Account__c FROM OrderApi__Sales_Order_Line__c WHERE Id=: salesOrderLineId LIMIT 1];
        if(sol.OrderApi__Item_Class__r.Name == 'Complimentary Journals'){
            OrderApi__Sales_Order_Line__c newLine = new OrderApi__Sales_Order_Line__c(OrderApi__Sales_Order__c = sol.OrderApi__Sales_Order__c);
            OrderApi__Item__c declineJournal = [SELECT Id, OrderApi__Income_Account__c, Future_Income_Account__c FROM OrderApi__Item__c WHERE OrderApi__Item_Class__r.Name = 'ZDecline of the Journals'];
            if(sol.OrderApi__GL_Account__c == sol.OrderApi__Item__r.Future_Income_Account__c){
                newLine.OrderApi__GL_Account__c = declineJournal.Future_Income_Account__c;
            } else {
                newLine.OrderApi__GL_Account__c = declineJournal.OrderApi__Income_Account__c;
            }
            newLine.OrderApi__Item__c = declineJournal.Id;
            insert newLine;
        }
            try {
                delete sol;
            } catch (Exception e) {
                System.debug('Could not remove item from cart: ' + e.getMessage());
            }

    }

    /**
     * @purpose Add discount code to sales order
     *
     * @param code
     * @param salesOrderId
     *
     * @return True or False
     */
    @AuraEnabled
    public static Boolean applyDiscountCode(String code, String salesOrderId){
        System.debug('Apply ' + code + ' to sales order ' + salesOrderId);
        OrderApi__Source_Code__c sCode = [SELECT Id, Name FROM OrderApi__Source_Code__c WHERE Name=: code LIMIT 1];

        OrderApi__Sales_Order__c so = [SELECT Id, OrderApi__Source_Code__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId];
        so.OrderApi__Source_Code__c = sCode.Id;

        List<OrderApi__Sales_Order_Line__c> lines = [SELECT Id FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c=: salesOrderId AND OrderApi__Item_Class__r.Name='Live Event Tickets'];
        for(OrderApi__Sales_Order_Line__c line : lines){
            line.OrderApi__Price_Override__c = false;  
        }

        try{
            update so;
            update lines;
            return true;
        } catch (Exception e){
            System.debug('Could not apply discount code: ' + e.getMessage());
            return false;
        }
    }

    private static String getVFHostName(){
        if(isCommunity()){
            Network myNetwork = [SELECT Id FROM Network WHERE Name ='AACR Community' ];
            ConnectApi.Community  myCommunity = ConnectApi.Communities.getCommunity(myNetwork.Id);
            System.debug('MyDebug : ' + myCommunity.siteUrl);
            return myCommunity.siteURL;
        } else {
            String hostname = Url.getSalesforceBaseUrl().getHost();
            // will support prod and sandboxes
            // e.g. https://mydomain--sandbox.lightning.force.com
            // and https://mydomain.lightning.force.com
            String myDomain = hostname.split('\\.')[0];
//            String namespace = ProxyController.class.getName().split('\\.')[0];
            String pod = [SELECT InstanceName FROM Organization].InstanceName.toLowerCase();

            return 'https://' + myDomain + '--c.visualforce.com';

        }
    }

    /* CartData class provides item list, sales order and other data required for OrderApi:PayNow component */
    public class CartData{
        @AuraEnabled
        public OrderApi__Sales_Order__c SO;

        @AuraEnabled
        public List<OrderApi__Sales_Order_Line__c> items;

        @AuraEnabled
        public String vfHostName;


        public CartData(String salesOrderId, Id stepId){
            vfHostName = getVFHostName();
            SO = [SELECT Id, OrderApi__Status__c,OrderApi__Contact__c, OrderApi__Account__c, OrderApi__Payment_Terms__c,OrderApi__Total__c, OrderApi__Entity__c, OrderApi__Schedule_Type__c, OrderApi__Shipping_Country__c, OrderApi__Posting_Status__c, OrderApi__Posting_Entity__c, OrderApi__Business_Group__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId];
            items = [SELECT OrderApi__Sales_Order__r.OrderApi__Source_Code__r.Name, OrderApi__Sales_Order__r.OrderApi__Source_Code__c, OrderApi__Sales_Order__r.OrderApi__Total__c, OrderApi__Item_Class__r.Name, OrderApi__Item__r.Portal_Label__c, OrderApi__Item__r.Name, OrderApi__Sale_Price__c, OrderApi__Quantity__c, OrderApi__Item__r.OrderApi__Image_Path__c, AC_User_Segment__r.Name FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c=: salesOrderId ORDER BY OrderApi__Item_Class__r.Name];
        }
    }



}