src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <description>Formula field reflecting either legacy iMIS ID or new Salesforce ID depending upon when record was created.</description>
        <formula>IF(ISBLANK( iMIS_ID__c ), Salesforce_ID__c, iMIS_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Preferred_Email__c</fullName>
        <description>**System Calculated** The Preferred Email for the Contact is calculated by mapping the Preferred Email Type to it&apos;s corresponding field&apos;s value.</description>
        <formula>IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Personal&quot;) &amp;&amp; NOT(OrderApi__Personal_Email_Opt_Out__c), OrderApi__Personal_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Work&quot;) &amp;&amp; NOT(OrderApi__Work_Email_Opt_Out__c), OrderApi__Work_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Other&quot;) &amp;&amp; NOT(OrderApi__Other_Email_Opt_Out__c),OrderApi__Other_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Assistant&quot;) &amp;&amp; NOT(OrderApi__Assistant_Email_Opt_Out__c),OrderApi__Assistant_Email__c, &apos;&apos;))))</formula>
        <inlineHelpText>**System Calculated** The Preferred Email for the Contact is calculated by mapping the Preferred Email Type to it&apos;s corresponding field&apos;s value.</inlineHelpText>
        <label>Preferred Email</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>EventApi__Status__c</fullName>
        <description>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</description>
        <inlineHelpText>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                    <default>true</default>
                    <label>Invited</label>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Registered-DataLoad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>EventApi__Status__c</fullName>
        <description>Status of the event. Must be &quot;active&quot; to be visible in the Portal.</description>
        <inlineHelpText>Status of the event. Must be &quot;active&quot; to be visible in the Portal.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <color>#78C953</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#E27001</color>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_AddAttendeesToEvent.cls
/**
 * Created by afaf.awad on 5/13/2020.
 */

global class Batch_AddAttendeesToEvent implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

    String pastEvent { get; set; }
    String newEvent { get; set; }
    Boolean setBusinessFlag { get; set; }

    global Batch_AddAttendeesToEvent( String pastEventId, String newEventId, Boolean setFlag) {
        pastEvent = pastEventId;
        newEvent = newEventId;
        setBusinessFlag = setFlag;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Title, AACR_Id__c, Salutation, FirstName, LastName, OrderApi__Preferred_Email__c FROM Contact WHERE Id IN (SELECT EventApi__Contact__c FROM EventApi__Attendee__c WHERE EventApi__Event__c =: newEvent)';
        System.debug('queryString: ' + query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        System.debug('Execute method running...');

        Set<Id> newEventSet = new Set<Id>();
        for (Contact c : scope) {
            newEventSet.add(c.Id);
        }

        List<EventApi__Attendee__c> oldAttendees = [SELECT EventApi__Contact__c FROM EventApi__Attendee__c WHERE EventApi__Event__c =: pastEvent AND EventApi__Contact__c IN: newEventSet];

        Set<Id> pastEventSet = new Set<Id>();
        for (EventApi__Attendee__c a : oldAttendees) {
            pastEventSet.add(a.EventApi__Contact__c);
        }

        List<Contact> conList = new List<Contact>();
        List<EventApi__Attendee__c> newAtt = new List<EventApi__Attendee__c>();

        for (Contact con : scope) {
            if ( !pastEventSet.contains(con.Id) ) {
                EventApi__Attendee__c a = new EventApi__Attendee__c();

                a.EventApi__Contact__c = con.Id;
                a.EventApi__Event__c = pastEvent;
                a.EventApi__Status__c ='Registered';
                newAtt.add(a);

                conList.add(con);
            }
        }

        System.debug('New attendees to insert: ' + newAtt.size());
        System.debug('Count of contact to send to freeman = ' + conList.size());

        try {
            System.debug('Sending ' + conList.size() + ' contacts to Freeman...');

            for (Contact con : conList) {
                FreemanIntegrationController.createFreemanAttendee(con, setBusinessFlag);
            }

            insert newAtt;
        } catch (Exception e) {
            System.debug('Error sending Contact to Freeman: ' + e.getMessage());
        }

//        try {
//            insert newAtt;
//        } catch (Exception e) {
//            System.debug('Error Message: ' + e.getMessage());
//        }

    }

    global void finish(Database.BatchableContext BC) {

    }
}