src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Paid_thru_date__c</fullName>
        <description>This field will track the date upto which the customer&apos;s subscription is paid</description>
        <inlineHelpText>***SYSTEM CALCULATED***This field tracks the paid thru date of the membership</inlineHelpText>
        <label>Paid Thru Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prior_Member_Status__c</fullName>
        <description>Hidden field: Ability to see movement of status between of Prior Member record type and current Member record type.</description>
        <label>Prior Member Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ROEContactUpdateHandler.cls
/**
 * Created by lauren.lezberg on 12/13/2018.
 */

public with sharing class ROEContactUpdateHandler {

    public static void updateContactToMember(Id contactId, Date paidThruDate){
        List<Contact> toUpdate = [SELECT Id, Paid_thru_date__c, RecordTypeId, Membership_Status__c, RecordType.Name, Prior_Member_Status__c FROM Contact WHERE Id =: contactId];
        List<RecordType> rType = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact' AND Name='Member'];

        for(Contact c: toUpdate){
            if(c.RecordType.Name == 'Prior Member') {
                System.debug('contact is prior member');
                c.RecordTypeId = rType[0].Id;
                if(paidThruDate==null){
                    //if member only catches up to current year with dues only purchase
                    if(c.Membership_Status__c == '1-YR Suspended'){
                        c.Paid_thru_date__c = c.Paid_thru_date__c.addYears(1);
                    }
                    if(c.Membership_Status__c == '2-YR Suspended'){
                        c.Paid_thru_date__c = c.Paid_thru_date__c.addYears(2);
                    }
                } else {
                    c.Paid_thru_date__c = paidThruDate;
                }
                c.Prior_Member_Status__c = c.Membership_Status__c;
                c.Membership_Status__c = 'Current';
            } else {
                c.Paid_thru_date__c = paidThruDate;
                c.Prior_Member_Status__c = c.Membership_Status__c;
                c.Membership_Status__c = 'Current';
            }
        }
        System.debug('contact: ' + toUpdate);
        try {
            update toUpdate;
        } catch(Exception e){
            System.debug('cannot update contacts '+ e.getMessage());
        }
    }


//    public static void updateContactToMember(Id contactId, Boolean setPaidThruDate){
//        List<Contact> toUpdate = [SELECT Id, Paid_thru_date__c, RecordTypeId, Membership_Status__c, RecordType.Name, Prior_Member_Status__c FROM Contact WHERE Id =: contactId];
//        List<RecordType> rType = [SELECT Id FROM RecordType WHERE SobjectType = 'Contact' AND Name='Member'];
//
//        for(Contact c: toUpdate){
//            if(c.RecordType.Name == 'Prior Member') {
//                System.debug('contact is prior member');
//                c.RecordTypeId = rType[0].Id;
//                if(setPaidThruDate){
//                    if(c.Membership_Status__c == '1-YR Suspended'){
//                        c.Paid_thru_date__c = c.Paid_thru_date__c.addYears(1);
//                    }
//                    if(c.Membership_Status__c == '2-YR Suspended'){
//                        c.Paid_thru_date__c = c.Paid_thru_date__c.addYears(2);
//                    }
//                }
//                c.Prior_Member_Status__c = c.Membership_Status__c;
//                c.Membership_Status__c = 'Current';
//            }
//        }
//        System.debug('contact: ' + toUpdate);
//        try {
//            update toUpdate;
//        } catch(Exception e){
//            System.debug('cannot update contacts '+ e.getMessage());
//        }
//    }

}