src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Queue management field for the Membership Department.</description>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete Application</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Clarification</fullName>
                </value>
                <value>
                    <fullName>Former Applicant</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Pending Transfer</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement-Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/contact_last_accessed_step__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>contacts last accessed step</relationshipLabel>
        <relationshipName>contacts_last_accessed_step</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Step_Order__c</fullName>
        <label>Step Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>contact last accessed step</label>
    <nameField>
        <displayFormat>SN-{0000}</displayFormat>
        <label>RN</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>contacts last accessed step</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactApplicationStatusTriggerHelper.cls
public class ContactApplicationStatusTriggerHelper {

    public static void setContactApplicationStatus(List<contact_last_accessed_step__c> contactLastAccessedList){
        contact_last_accessed_step__c contact=contactLastAccessedList[0];
		Contact updatecontact= [select id, Application_Status__c from Contact where id = :contact.Contact__c];
         if(contact.Step_Order__c  > 1 && contact.Step_Order__c  < =6){
            updatecontact.Application_Status__c = 'Incomplete Application';
        	}
        update updatecontact;
    }
}