src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <description>Formula field reflecting either legacy iMIS ID or new Salesforce ID depending upon when record was created.</description>
        <formula>IF(ISBLANK( iMIS_ID__c ), Salesforce_ID__c, iMIS_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <formula>Contact.AACR_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ORCID__c</fullName>
        <label>ORCID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MembershipWebService.cls
/**
 * Created by lauren.lezberg on 3/30/2021.
 */
@RestResource(urlMapping='/Membership/*')

global with sharing class MembershipWebService {

    @Httpget
    global static Boolean getMembership(){
        RestRequest req = RestContext.request;
        RestResponse res = Restcontext.response;

        String orcid = req.params.get('orcid');
        System.debug('orcid: ' + orcid);
        String aacrid = req.params.get('aacrid');
        System.debug('aacrid: ' + aacrid);

        Boolean hasValidMembership = false;

        if(aacrid!=null){
            List<Contact> contacts = [SELECT Id, RecordType.Name, Membership_Status__c FROM Contact WHERE AACR_ID__c =: aacrid];
            if(!contacts.isEmpty()){
                hasValidMembership = contacts[0].RecordType.Name == 'Member' && contacts[0].Membership_Status__c == 'Current';
                if(orcid!=null){
                    List<User> users = [SELECT ORCID__c FROM User WHERE ContactId =: contacts[0].Id AND IsActive=true];
                    if(!users.isEmpty()){
                        if(users[0].ORCID__c==null){
                            users[0].ORCID__c = orcid;
                            update users[0];
                        }
                    }
                }
            }
        } else if(orcid!=null) {
            List<User> users = [SELECT ORCID__c, ContactId FROM User WHERE ORCID__c =:orcid];
            if(!users.isEmpty()){
                List<Contact> contacts = [SELECT Id, RecordType.Name, Membership_Status__c FROM Contact WHERE Id=: users[0].ContactId];
                if(!contacts.isEmpty()){
                    hasValidMembership = contacts[0].RecordType.Name == 'Member' && contacts[0].Membership_Status__c == 'Current';
                }
            }
        }


        return hasValidMembership;

    }

}