src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Income_Level__c</fullName>
        <description>Income level based upon country of origin; reflects iMIS&apos; original Category field.</description>
        <inlineHelpText>The income level of contact based upon country.</inlineHelpText>
        <label>World Bank Income Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High Income</fullName>
                    <default>true</default>
                    <label>High Income</label>
                </value>
                <value>
                    <fullName>Upper Middle Income</fullName>
                </value>
                <value>
                    <fullName>Lower Middle Income</fullName>
                </value>
                <value>
                    <fullName>Low Income</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Association_Journals_Type__c</fullName>
        <description>Classify association journals in Online only or Print. Originally created in UATF by Fonteva and recreated by JR.</description>
        <label>Association Journals Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Online Only</fullName>
                </value>
                <value>
                    <fullName>Print &amp; Online</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>International_Shipping_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>International Shipping Item</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.OrderApi__Item_Class__c</field>
                <operation>equals</operation>
                <value>a111I0000022dBxQAI</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Shipping Items</relationshipLabel>
        <relationshipName>Shipping_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>Is2YR__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the subscription plan a 2 year term</description>
        <label>Is2YR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Activation_Date__c</fullName>
        <description>** System Calculated Override Conditionally Required ** The date the Subscription will be activated is calculated based on conditions set on the related Subscription Plan and can be manually over-ridden if &quot;Auto Calculate Activation Date&quot; is unchecked.</description>
        <inlineHelpText>** System Calculated Override Conditionally Required ** The date the Subscription will be activated is calculated based on conditions set on the related Subscription Plan and can be manually over-ridden if &quot;Auto Calculate Activation Date&quot; is unchecked.</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Transaction__c.object
<CustomObject>
    <description>Transactions store all debits and credits for double-entry accounting.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Inherited from the Contact on the linked source record.</description>
        <inlineHelpText>**System Calculated/Override** Inherited from the Contact on the linked source record.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Sales Order.</description>
        <inlineHelpText>Link to related Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Transactions (Summary)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Transaction_Line__c.object
<CustomObject>
    <description>Transaction Lines track the debits and credits associated with Transactions.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Transaction Line</relationshipLabel>
        <relationshipName>Transaction_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the related Item record. Derived from the related Invoice Line (only populates on receivable transactions).</description>
        <inlineHelpText>**System Calculated/Override** Link to the related Item record. Derived from the related Invoice Line (only populates on receivable transactions).</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated** Link to related Sales Order Line (where applicable).</description>
        <inlineHelpText>**System Calculated** Link to related Sales Order Line (where applicable).</inlineHelpText>
        <label>Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipName>Transaction_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Transaction__c</fullName>
        <description>**Required** All Transaction Lines must be associated with a parent Transaction.</description>
        <inlineHelpText>**Required** All Transaction Lines must be associated with a parent Transaction.</inlineHelpText>
        <label>Transaction</label>
        <referenceTo>OrderApi__Transaction__c</referenceTo>
        <relationshipName>Transaction_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Transaction Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateIntlShippingTransactionHelper.cls
//created By: Samip 
public class CreateIntlShippingTransactionHelper {

    public static void createTransactionLine(List<OrderApi__Transaction__c> transactions) {

        Set<Id> salesOrderIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();

        for (OrderApi__Transaction__c transactionSummary : transactions) {
            salesOrderIds.add(transactionSummary.OrderApi__Sales_Order__c);
            contactIds.add(transactionSummary.OrderApi__Contact__c);
        }
        //getting the sales order line list from the inserted salesorder ids
        List<OrderApi__Sales_Order_Line__c> salesOrderLineList = [
                select id
                        ,OrderApi__Item_Class__r.Name
                        ,OrderApi__Item__r.Name
                        ,OrderApi__Item__r.Association_Journals_Type__c
                from OrderApi__Sales_Order_Line__c
                where OrderApi__Sales_Order__c IN:salesOrderIds
        ];

        //getting the contact map for matching country from the set of contact id which we get from the sales order
        Map<Id, Contact> contactMap = new Map<Id, Contact>([
                select id,MailingCountry, OtherCountry, Income_Level__c
                from Contact
                where Id IN:contactIds
        ]);

        //Creat Sales Order Line map in order to match the fields conditions
        Map<Id, OrderApi__Sales_Order_Line__c> salesOrderLineMap = new Map<Id, OrderApi__Sales_Order_Line__c>([
                select id
                        ,OrderApi__Item_Class__r.Name
                        ,OrderApi__Item__r.Association_Journals_Type__c
                        ,OrderApi__Sales_Order_Line__c
                        ,OrderApi__Item__r.International_Shipping_Item__c
                        ,OrderApi__Sales_Order__r.Is2YR__c
                        ,OrderApi__Activation_Date__c
                from OrderApi__Sales_Order_Line__c
                where OrderApi__Sales_Order__c IN:salesOrderIds
        ]);

        Map<Id, OrderApi__Sales_Order__c> salesOrderMap = new Map<Id, OrderApi__Sales_Order__c>([
                SELECT Id, OrderApi__Has_Subscription__c
                FROM OrderApi__Sales_Order__c
                WHERE Id IN:salesOrderIds
        ]);

        System.Debug('Map of Sales Order Lines: ' + salesOrderLineMap);

        //Create list of International Shipping Items (from 'Shipping Items' Item Class) to find the shipping cost per journal.
        List<OrderApi__Item__c> internationalShipping = [
                Select Id
                        ,Name
                        ,OrderApi__Item_Class__c
                        ,OrderApi__Income_Account__c
                        ,Future_Income_Account__c
                        ,OrderApi__Price__c
                        ,OrderApi__Business_Group__c
                FROM OrderApi__Item__c
                WHERE OrderApi__Item_Class__r.Name = 'Shipping Items'
        ];

        List<OrderApi__Transaction_Line__c> transLines =[SELECT Id, OrderApi__Item__r.Name, OrderApi__Transaction__c
                                                        FROM OrderApi__Transaction_Line__c
                                                        WHERE OrderApi__Transaction__c = :transactions
                                                        AND OrderApi__Item__r.Name LIKE 'International Shipping%'];

        if (transLines.isEmpty()) {
            //Create list to insert new transaction line(s)
            List<OrderApi__Transaction_Line__c> transactionLineItems = new List<OrderApi__Transaction_Line__c>();

            for (OrderApi__Transaction__c transactionSummary : transactions) {
                System.debug('Contact Map values:' + contactMap.values());
                System.debug('Contact Id from Transaction Summary: ' + transactionSummary.OrderApi__Contact__c);
                System.debug('sales order of transactionSummary = ' + transactionSummary.OrderApi__Sales_Order__c);
                System.debug('Has Subscription = ' + salesOrderMap.get(transactionSummary.OrderApi__Sales_Order__c).OrderApi__Has_Subscription__c);
                System.debug('Mailing Country = ' + contactMap.get(transactionSummary.OrderApi__Contact__c).MailingCountry);


                //check if the sales order has a subscription and Contact's mailing country is not equal to US
                if ( salesOrderMap.get(transactionSummary.OrderApi__Sales_Order__c).OrderApi__Has_Subscription__c
                        && contactMap.get(transactionSummary.OrderApi__Contact__c).MailingCountry != 'United States'
                        && contactMap.get(transactionSummary.OrderApi__Contact__c).MailingCountry != null
                        && contactMap.get(transactionSummary.OrderApi__Contact__c).Income_Level__c == Label.Fon_Income_Level) {

                    //iterating through the salesOrderLine list to match the conditions
                    for (OrderApi__Sales_Order_Line__c soLine : salesOrderLineList) {
                        System.debug('Sale Order Item Class is "' + salesOrderLineMap.get(soLine.id).OrderApi__Item_Class__r.Name
                                + '" and Association Journal Type is "'
                                + salesOrderLineMap.get(soLine.id).OrderApi__Item__r.Association_Journals_Type__c + '"');

                        //if the item class name equal to 'Complimentary Journals' and Association Journal Type is 'Print & Online'
                        if ( salesOrderLineMap.get(soLine.id).OrderApi__Item_Class__r.Name == 'Complimentary Journals'
                                && salesOrderLineMap.get(soLine.id).OrderApi__Item__r.Association_Journals_Type__c == 'Print & Online' ) {

                            //iterating through the International Shipping items to find the shipping item that matches the journal
                            for (OrderApi__Item__c journalName : internationalShipping) {

                                //if shipping item equals Journal name, then insert the fields into Transaction Line object
                                if ( salesOrderLineMap.get(soLine.id).OrderApi__Item__r.International_Shipping_Item__c == journalName.id ) {
                                    OrderApi__Transaction_Line__c transactionLineItem = new OrderApi__Transaction_Line__c();
                                    transactionLineItem.OrderApi__Transaction__c = transactionSummary.id;
                                    transactionLineItem.OrderApi__Credit__c = journalName.OrderApi__Price__c;
                                    System.debug(Date.today().year() + 1);
                                    System.debug(salesOrderLineMap.get(soLine.id));


                                    if(salesOrderLineMap.get(soLine.id).OrderApi__Activation_Date__c.year()==Date.today().year()+1 && !salesOrderLineMap.get(soLine.id).OrderApi__Sales_Order__r.Is2YR__c){
                                        transactionLineItem.OrderApi__GL_Account__c = journalName.Future_Income_Account__c;
                                    } else {
                                        transactionLineItem.OrderApi__GL_Account__c = journalName.OrderApi__Income_Account__c;
                                    }
                                    transactionLineItem.OrderApi__Memo__c = journalName.Name;
                                    transactionLineItem.OrderApi__Item__c = journalName.Id;
                                    transactionLineItem.OrderApi__Item_Class__c = journalName.OrderApi__Item_Class__c;
                                    transactionLineItem.OrderApi__Sales_Order_Line__c = soLine.id;
                                    transactionLineItem.OrderApi__Business_Group__c = journalName.OrderApi__Business_Group__c;
                                    transactionLineItems.add(transactionLineItem);

                                    //add future GL transaction line for 2 YR subscriptions
                                    if(salesOrderLineMap.get(soLine.id).OrderApi__Sales_Order__r.Is2YR__c){
                                        transactionLineItem = new OrderApi__Transaction_Line__c();
                                        transactionLineItem.OrderApi__Transaction__c = transactionSummary.id;
                                        transactionLineItem.OrderApi__Credit__c = journalName.OrderApi__Price__c;
                                        transactionLineItem.OrderApi__GL_Account__c = journalName.Future_Income_Account__c;
                                        transactionLineItem.OrderApi__Memo__c = journalName.Name;
                                        transactionLineItem.OrderApi__Item__c = journalName.Id;
                                        transactionLineItem.OrderApi__Item_Class__c = journalName.OrderApi__Item_Class__c;
                                        transactionLineItem.OrderApi__Sales_Order_Line__c = soLine.id;
                                        transactionLineItem.OrderApi__Business_Group__c = journalName.OrderApi__Business_Group__c;
                                        transactionLineItems.add(transactionLineItem);
                                    }

                                }


                            }
                        }
                    }
                }
            }

            System.Debug('Count of transactionLineItems = ' + transactionLineItems.size());

            try {
                //insert data if the list has size greater than 0
                if ( transactionLineItems.size() > 0 ) {
                    insert transactionLineItems;
                }
            } catch (Exception Ex) {
                System.debug('Exception ' + Ex.getMessage());
            }
        }
    }
   // }
}