src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Current Education Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Education__c.object
<CustomObject>
    <description>AACR custom object to reflect the historical information of a member&apos;s education.</description>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Degree Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Expected_Graduation__c</fullName>
        <label>Date of Expected Graduation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Degree_Completion_Year__c</fullName>
        <description>In what year was this degree be achieved (e.g. YYYY)?</description>
        <inlineHelpText>In what year was this degree be achieved (e.g. YYYY)?</inlineHelpText>
        <label>Degree Completion Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <description>Many to 1 relationship of educational degrees to a Contact record.</description>
        <inlineHelpText>What academic degree has this individual achieved?</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AAS</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BAAS</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BDS</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>B Eng</fullName>
                </value>
                <value>
                    <fullName>BMBCh</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>BPharm</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>BSN</fullName>
                </value>
                <value>
                    <fullName>DDS</fullName>
                </value>
                <value>
                    <fullName>DMD</fullName>
                </value>
                <value>
                    <fullName>DMSc</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>D Phil</fullName>
                </value>
                <value>
                    <fullName>DSc</fullName>
                </value>
                <value>
                    <fullName>DVM</fullName>
                </value>
                <value>
                    <fullName>DrPH</fullName>
                </value>
                <value>
                    <fullName>DrRerNat</fullName>
                </value>
                <value>
                    <fullName>EdD</fullName>
                </value>
                <value>
                    <fullName>EdM</fullName>
                </value>
                <value>
                    <fullName>HT</fullName>
                </value>
                <value>
                    <fullName>JD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education_Related_to_Contact__c</fullName>
        <description>Many to 1 relationship of educational degrees to a Contact record.</description>
        <label>Education Related to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education</relationshipLabel>
        <relationshipName>Education</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Education</label>
    <nameField>
        <label>Institution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DW_EducationInformationHelper.cls
public class DW_EducationInformationHelper { 
	public static DW_ECRMDTO.EducationInfoDTO getPageMetadata( String stepId ) {
        DW_ECRMDTO.EducationInfoDTO pageMeta = new DW_ECRMDTO.EducationInfoDTO();
        String contactId = DW_ECRMUtils.getCurrentLoginUserContactId();
        // Populate Picklist Maps
        pageMeta.AcademicDegreeMap = DW_ECRMUtils.getPicklistEntries('Education__c', 'Degree__c');
        pageMeta.EducationStatusMap = DW_ECRMUtils.getPicklistEntries( 'Education__c', 'Current_Education_Status__c' );
		// Populate Redirect URL's
		pageMeta.NextStepURL = DW_EducationInformationHelper.getNextStepURL(stepId);
        pageMeta.PreviousStepURL = DW_EducationInformationHelper.getPreviousStepURL(stepId);
        pageMeta.CancelStepURL = DW_EducationInformationHelper.getCancelStepURL(stepId);
        // Fetch Related Educations Data
        pageMeta.Educations = DW_EducationInformationHelper.getEducationRelatedList( contactId );
        pageMeta.contactId = contactId;
        return pageMeta;
    }

    public static List<Education__c> getEducationRelatedList( String contactId ) {
    	List<Education__c> educations = new List<Education__c>();
    	educations = [SELECT Id, Name, Current_Education_Status__c, Date_of_Expected_Graduation__c,
                                      Degree__c, Degree_Completion_Year__c, Education_Related_to_Contact__c
                                      FROM Education__c 
                                      WHERE Education_Related_to_Contact__c = :contactId];
        return educations;
    }
    public static String getNextStepURL(String currentStepId) {
        return new joinApi.JoinUtils(currentStepId).navStepsMap.get('Next');
    }
    
    public static String getPreviousStepURL(String currentStepId) {
    	return new joinApi.JoinUtils(currentStepId).navStepsMap.get('Previous');
    }
    
    public static String getCancelStepURL(String currentStepId) {
        return new joinApi.JoinUtils(currentStepId).navStepsMap.get('First');
    }

    public static void saveEducationInformation( DW_ECRMDTO.EducationInfoDTO educationInfo ) {
            
        // Delete Educations
        if (!educationInfo.DeletedEducationIdList.isEmpty()) {
         	List<Education__c> deletedEducationList = [SELECT Id FROM Education__c WHERE Id IN :educationInfo.DeletedEducationIdList];
            DELETE deletedEducationList;
        }        
        
        // Upsert Contact's Educations Data
        if (!educationInfo.Educations.isEmpty()) {
            UPSERT educationInfo.Educations;
        }
    }
}