src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <description>Queue management field for the Membership Department.</description>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete Application</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Clarification</fullName>
                </value>
                <value>
                    <fullName>Former Applicant</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Pending Transfer</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Pending Reinstatement-Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Current Education Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <label>Member</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Education__c.object
<CustomObject>
    <description>AACR custom object to reflect the historical information of a member&apos;s education.</description>
    <fields>
        <fullName>Current_Education_Status__c</fullName>
        <description>What educational level does this individual currently have?</description>
        <inlineHelpText>What educational level does this individual currently have?</inlineHelpText>
        <label>Degree Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical Fellow</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral Fellow</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Expected_Graduation__c</fullName>
        <label>Date of Expected Graduation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Degree_Completion_Year__c</fullName>
        <description>In what year was this degree be achieved (e.g. YYYY)?</description>
        <inlineHelpText>In what year was this degree be achieved (e.g. YYYY)?</inlineHelpText>
        <label>Degree Completion Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Degree_Level__c</fullName>
        <description>Tracking of historical educational records (related to iMIS migration).</description>
        <label>Degree Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High School</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Post-Baccalaureate</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Medical Student</fullName>
                </value>
                <value>
                    <fullName>Resident</fullName>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>Postdoctoral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <description>Many to 1 relationship of educational degrees to a Contact record.</description>
        <inlineHelpText>What academic degree has this individual achieved?</inlineHelpText>
        <label>Degree</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AAS</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BAAS</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BDS</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>B Eng</fullName>
                </value>
                <value>
                    <fullName>BMBCh</fullName>
                </value>
                <value>
                    <fullName>BPS</fullName>
                </value>
                <value>
                    <fullName>BPharm</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>BSN</fullName>
                </value>
                <value>
                    <fullName>DDS</fullName>
                </value>
                <value>
                    <fullName>DMD</fullName>
                </value>
                <value>
                    <fullName>DMSc</fullName>
                </value>
                <value>
                    <fullName>DO</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>D Phil</fullName>
                </value>
                <value>
                    <fullName>DSc</fullName>
                </value>
                <value>
                    <fullName>DVM</fullName>
                </value>
                <value>
                    <fullName>DrPH</fullName>
                </value>
                <value>
                    <fullName>DrRerNat</fullName>
                </value>
                <value>
                    <fullName>EdD</fullName>
                </value>
                <value>
                    <fullName>EdM</fullName>
                </value>
                <value>
                    <fullName>HT</fullName>
                </value>
                <value>
                    <fullName>JD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education_Related_to_Contact__c</fullName>
        <description>Many to 1 relationship of educational degrees to a Contact record.</description>
        <label>Education Related to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education</relationshipLabel>
        <relationshipName>Education</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Education</label>
    <nameField>
        <label>Institution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>The status of the Sales Order.</description>
        <inlineHelpText>The status of the Sales Order.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JP_EducationInfoController.cls
/**
 * Created by lauren.lezberg on 1/28/2019.
 */

public without sharing class JP_EducationInfoController {

    @AuraEnabled
    public static void deferAndTransfer(String salesOrderId){
        OrderApi__Sales_Order__c so = [SELECT Id, OrderApi__Status__c, OrderApi__Contact__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId];
        so.OrderApi__Status__c = 'Cancelled';
        update so;

//        Contact con = [SELECT Id FROM Contact WHERE Id=: so.OrderApi__Contact__c];
//        con.Application_Status__c = 'Deferred';
//        update con;
    }

    @AuraEnabled
    public static void deferMember(String contactId){

        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage>();

        String orgWideEmailId = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'AACR Membership'].Id;
        EmailTemplate et = [SELECT Id, HtmlValue, Body FROM EmailTemplate WHERE Name='Membership: Ineligible' LIMIT 1];

        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTargetObjectId(contactId);
        message.setTreatTargetObjectAsRecipient(true);
        message.setTemplateId(et.Id);
        message.setOrgWideEmailAddressId(orgWideEmailId);
//        message.setSenderDisplayName('AACR Membership');

        messages.add(message);

        if (!messages.isEmpty()) {
            try {
                Messaging.sendEmail(messages);
            } catch (EmailException ex) {
                new AACRCustomException(ex.getMessage(), ex.getStackTraceString(), 'Ineligible Member');
            }
        }
    }
 
    /**
     * @purpose Retrieve any Education__c records for current contact
     *
     * @return EducationData wrapper object with all relevant education information
     */
    @AuraEnabled
    public static EducationData getEducationData(Id stepId){
        System.debug('getEducationData...');
        JP_Helper.upsertLastAccessedStep(stepId);
        Id contactId = ECRMUtils.getCurrentLoginUserContactId();
        System.debug('gettingEducationData for ' + contactId);
        List<Education__c> educationRecords = [SELECT Name, Current_Education_Status__c, Date_of_Expected_Graduation__c, Degree__c,
                                                Degree_Completion_Year__c,Degree_Level__c, Education_Related_to_Contact__c
                                                FROM Education__c
                                                WHERE Education_Related_to_Contact__c =: contactId];
        List<String> statusList = ECRMUtils.getPicklistValues('Education__c', 'Current_Education_Status__c');
        List<String> degrees = ECRMUtils.getPicklistValues('Education__c','Degree__c');
        return new EducationData(degrees, statusList, educationRecords, contactId);
    }

    @AuraEnabled
    public static void deleteEducation(Education__c record){
        delete record;
    }

    public class EducationData{
        @AuraEnabled
        public Id contactId;

        @AuraEnabled
        public List<String> degrees;

        @AuraEnabled
        public List<String> statusList;

        @AuraEnabled
        public List<Education__c> educations;

        public EducationData(List<String> degrees, List<String> statusList, List<Education__c> educations, Id contactId){
            this.degrees = degrees;
            this.statusList = statusList;
            this.educations  = educations;
            this.contactId = contactId;
        }

    }

}