src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AACR_ID__c</fullName>
        <description>Formula field reflecting either legacy iMIS ID or new Salesforce ID depending upon when record was created.</description>
        <formula>IF(ISBLANK( iMIS_ID__c ), Salesforce_ID__c, iMIS_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AACR ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Preferred_Email__c</fullName>
        <description>**System Calculated** The Preferred Email for the Contact is calculated by mapping the Preferred Email Type to it&apos;s corresponding field&apos;s value.</description>
        <formula>IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Personal&quot;) &amp;&amp; NOT(OrderApi__Personal_Email_Opt_Out__c), OrderApi__Personal_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Work&quot;) &amp;&amp; NOT(OrderApi__Work_Email_Opt_Out__c), OrderApi__Work_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Other&quot;) &amp;&amp; NOT(OrderApi__Other_Email_Opt_Out__c),OrderApi__Other_Email__c,
IF(ISPICKVAL(OrderApi__Preferred_Email_Type__c,&quot;Assistant&quot;) &amp;&amp; NOT(OrderApi__Assistant_Email_Opt_Out__c),OrderApi__Assistant_Email__c, &apos;&apos;))))</formula>
        <inlineHelpText>**System Calculated** The Preferred Email for the Contact is calculated by mapping the Preferred Email Type to it&apos;s corresponding field&apos;s value.</inlineHelpText>
        <label>Preferred Email</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/npe4__Relationship__c.object
<CustomObject>
    <fields>
        <fullName>npe4__Contact__c</fullName>
        <description>Related Contact is this Contact&apos;s ______.</description>
        <inlineHelpText>Related Contact is this Contact&apos;s ______.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>npe4__RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>npe4__Status__c</fullName>
        <description>Status of the Relationship.</description>
        <inlineHelpText>Status of the Relationship.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>npe4__Type__c</fullName>
        <description>Field that describes how the Related Contact is connected to the Contact.</description>
        <inlineHelpText>Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Nominator</fullName>
                </value>
                <value>
                    <fullName>Nominee</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Significant Other</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Grandchild</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Preferred_Email__c</fullName>
        <description>System field used for proforma invoice emails. Auto populated from related contact record&apos;s preferred email</description>
        <inlineHelpText>System field used for proforma invoice emails. Auto populated from related contact record&apos;s preferred email</inlineHelpText>
        <label>SYSTEM</label>
        <type>Email</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** The source Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated ** The source Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Sales Order Line (Source)</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JP_NominatorsController.cls
/**
 * Created by lauren.lezberg on 2/28/2019.
 */

public with sharing class JP_NominatorsController {

    @AuraEnabled
    public static NominationsData getNominationData(Id salesOrderId, Id stepId){
        System.debug('getNominationData was just called with salesOrderId: ' + salesOrderId);
        JP_Helper.upsertLastAccessedStep(stepId);

        Id contactId = ECRMUtils.getCurrentLoginUserContactId();
        System.debug('Current Contact ' + contactId);

        String itemName = getMembershipItemName(salesOrderId);
        System.debug('itemName: ' + itemName);

        List<Attachment> attachments = [SELECT Id, Name FROM Attachment WHERE ParentId=: contactId AND Description LIKE '%JoinProcess%' ORDER BY CreatedDate DESC];
        System.debug('attachments: ' + attachments);

        List<npe4__Relationship__c> relationships = [SELECT npe4__RelatedContact__r.OrderApi__Preferred_Email__c, npe4__RelatedContact__r.AACR_ID__c, npe4__Status__c, npe4__Type__c FROM npe4__Relationship__c WHERE npe4__Contact__c=: contactId];
        System.debug('relationships: ' + relationships);

        NominationsData nomData = new NominationsData(attachments, relationships, itemName);
        System.debug('getNominationData is returning ' + nomData);
        return nomData;
    }


    public static String getMembershipItemName(Id salesOrderId){
        System.debug('getMembershipItemName was just called with salesOrder: ' + salesOrderId);
        List<OrderApi__Sales_Order_Line__c> soLines = [SELECT Id, OrderApi__Item__r.Name FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c=: salesOrderId AND OrderApi__Item_Class__r.Name='Individual Memberships'];
        System.debug('found salesOrderLines: ' + soLines);
        if(soLines!=null && soLines.size()==1){
            System.debug('membershipItem found: ' + soLines[0].OrderApi__Item__r.Name);
            return soLines[0].OrderApi__Item__r.Name;
        }
        return null;
    }


    @AuraEnabled
    public static NominatorInfo verifyNominator(Id contactId, String emailAddress, String memberNumber){
        System.debug('verifyNominator was just called with contactId: ' + contactId + ' emailAddress: ' + emailAddress + ' and memberNumber: ' + memberNumber);
        Contact[] nominators = new List<Contact>();
        try{
            String queryString = buildNominatorQuery(contactId, memberNumber, emailAddress);
            if(queryString==null){
                return null;
            }
            //Firing query
            nominators = Database.query(queryString);
            System.debug('found nominators: ' + nominators);
        }catch(Exception e){
            System.debug('Error retrieving nominator data: ' + e.getMessage() + '\n' + e.getStackTraceString());
            return null;
        }

        //verify nominator is eligible
        if(nominators!=null && !nominators.isEmpty()) {
            if (nominators[0].Membership_Status__c == 'Current' && nominators[0].OrderApi__Subscriptions__r.size() > 0) {
                NominatorInfo nom = new NominatorInfo(nominators[0].Id, nominators[0].AACR_ID__c, nominators[0].Email,
                        nominators[0].Name, true);
                System.debug('Nominator was successfully verified: ' + nom);
                return nom;
            } else {
                NominatorInfo nom = new NominatorInfo(nominators[0].Id, nominators[0].AACR_ID__c, nominators[0].Email,
                        nominators[0].Name, false);
                System.debug('Nominator could not be verified: ' + nom);
                return nom;
            }
        }

        System.debug('Error verifying nominator.');
        return null;
    }

    @AuraEnabled
    public static JP_Helper.JPResponse saveNominationData(Id contactId, List<Object> nominators, Id stepId){
        System.debug('saveNominationData was just called with contactId: ' + contactId + ' and nominators: ' + nominators);
        Set<Id> relationshipIds = new Set<Id>();
        List<npe4__Relationship__c> oldRelationships = [SELECT npe4__RelatedContact__c FROM npe4__Relationship__c WHERE npe4__Contact__c =: contactId ];
        if(oldRelationships.size()>0) {
            for (npe4__Relationship__c rel : oldRelationships) {
                relationshipIds.add(rel.npe4__RelatedContact__c);
            }
        }
        List<npe4__Relationship__c> relationships = new List<npe4__Relationship__c>();

        for(Object nom : nominators){
            NominatorInfo nominator = (NominatorInfo)JSON.deserialize(JSON.serialize(nom), NominatorInfo.class);
            System.debug('nominator: ' + nominator);

            if(!relationshipIds.contains(nominator.nominatorId)&& nominator.nominatorId!=null ) {
                relationships.add(new npe4__Relationship__c(
                        npe4__Contact__c = contactId,
                        npe4__RelatedContact__c = nominator.nominatorId,
                        npe4__Status__c = 'Current',
                        npe4__Type__c = 'Nominator'
                ));
            }
        }

        try {
            if(relationships.size()>0){insert relationships;}
            return new JP_Helper.JPResponse(true, 'Successfully inserted nominators.', null);
        } catch(Exception e){
            System.debug('Error inserting relationships and attachments: ' + e.getMessage());
            return new JP_Helper.JPResponse(false, 'Error inserting relationships and attachments: ' + e.getMessage(), null);
        }
    }




    public class NominationsData{
        @AuraEnabled
        public String itemName;

        @AuraEnabled
        public String contactId;


        @AuraEnabled
        public List<Attachment> attachments;

        @AuraEnabled
        public List<npe4__Relationship__c> nominations;

        public NominationsData(List<Attachment> attach, List<npe4__Relationship__c> noms, String item){
            this.itemName = item;
            this.attachments = attach;
            this.nominations = noms;
            this.contactId = ECRMUtils.getCurrentLoginUserContactId();
        }
    }

    /**
    * @Purpose     : Builds soql string to be fired to verify nominator
    * @Parameter   : Current Step Id (String)
    * @Returns     : Response
    */
    public static String buildNominatorQuery(String contactId, String memberNo , String email){
        if(String.isBlank(memberNo) && String.isBlank(email)){
            return null;
        }

        //Building sql query string
        String soqlString = 'SELECT Id, Name, Lastname, Email, AACR_ID__c, OrderApi__Personal_Email__c, OrderApi__Other_Email__c, OrderApi__Work_Email__c, Membership_Status__c,'
                + ' (SELECT Id, OrderApi__Item__r.Eligible_Nominator_Membership__c FROM OrderApi__Subscriptions__r WHERE OrderApi__Item__r.Eligible_Nominator_Membership__c = true)'
                + ' FROM ' + Schema.SobjectType.Contact.Name
                + ' WHERE ';

        //Adding where clause to the query
        soqlString += String.isNotBlank(memberNo) ? 'AACR_ID__c =\'' + memberNo + '\' ' : '';
        soqlString += String.isNotBlank(memberNo) && String.isNotBlank(email) ? ' OR ' : '';
        soqlString += String.isNotBlank(email) ? 'Email =\'' + email + '\' ' : '';

        System.debug('soqlString: ' + soqlString);

        return soqlString;
    }

    /*
     * @Purpose     : Wrapper to store each nominators details
     */
    public class NominatorInfo{
        @AuraEnabled
        public String nominatorId;

        @AuraEnabled
        public String memberNo;

        @AuraEnabled
        public String emailAddr;

        @AuraEnabled
        public String name;

        @AuraEnabled
        public Boolean isVerified;


        public NominatorInfo(String nominatorId, String memberNo, String email, String name, Boolean isVerified){
            this.nominatorId = nominatorId;
            this.memberNo = memberNo;
            this.emailAddr = email;
            this.name = name;
            this.isVerified = isVerified;
        }
    }


    public class StudentNominator{

        @AuraEnabled
        public String nomName;

        @AuraEnabled
        public String nomTitle;

        @AuraEnabled
        public String nomType;

        public StudentNominator(String name, String title, String type){
            this.nomName = name;
            this.nomTitle = title;
            this.nomType = type;
        }
    }

}