src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Membership_Status__c</fullName>
        <description>Identifies the current membership status of an individual.</description>
        <inlineHelpText>What is the current status of this member?</inlineHelpText>
        <label>Membership Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nonmember</fullName>
                    <default>true</default>
                    <label>Nonmember</label>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Candidate_Incomplete</fullName>
                    <label>Candidate - Incomplete</label>
                </value>
                <value>
                    <fullName>Candidate_Complete</fullName>
                    <label>Candidate - Complete</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>1-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>2-YR Suspended</fullName>
                </value>
                <value>
                    <fullName>Suspended (Delinquent)</fullName>
                </value>
                <value>
                    <fullName>Suspended (Resigned)</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Deceased</fullName>
        <active>true</active>
        <label>Deceased</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the system will inactivate all related Subscribers and unassign any related benefits.</description>
        <inlineHelpText>When checked, the system will inactivate all related Subscribers and unassign any related benefits.</inlineHelpText>
        <label>Is Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MakeDeceasedControllerTest.cls
/**
 * Created by lauren.lezberg on 12/9/2019.
 */
@isTest
private with sharing class MakeDeceasedControllerTest {

    @testSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];



        User u = new User(Alias = 'standt', Email='deceasedUser@yopmail.com',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='deceasedUser@yopmail.com');
        insert u;

        OrderApi__Subscription_Plan__c subPlan = TestDataFactory.buildsubPlan();
        insert subPlan;

        OrderApi__Item_Class__c membershipClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert membershipClass;

        OrderApi__Item__c membership = TestDataFactory.buildItem(membershipClass.Id, 'Active Membership');
        insert membership;

        OrderApi__Subscription__c membershipSub = TestDataFactory.buildSubscription(con.Id, subPlan.Id, membership.Id, membershipClass.Id);
        insert membershipSub;

    }


    @isTest
    public static void test_getButtonVisibility(){

        Contact con = [SELECT Id FROM Contact WHERE Account.Name='Test Account'];

        User u = [SELECT Id FROM User WHERE Email ='deceasedUser@yopmail.com'];

        PermissionSet ps = new PermissionSet();
        ps.Name = 'Test';
        ps.Label = 'Test';
        insert ps;

        SetupEntityAccess sea = new SetupEntityAccess();
        sea.ParentId = ps.Id;
        sea.SetupEntityId = [SELECT Id, DeveloperName FROM CustomPermission WHERE DeveloperName = 'Mark_As_Deceased'][0].Id;
        insert sea;

        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = ps.Id;
        insert psa;


        System.runAs(u) {
            Test.startTest();

            Boolean showDeceased = MakeDeceasedController.getButtonVisibility(con.Id);
            System.assertEquals(true, showDeceased);

            Test.stopTest();
        }
    }


    @isTest
    public static void test_moveContactToDeceased(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name='Test Account'];

        User u = [SELECT Id FROM User WHERE Email ='deceasedUser@yopmail.com'];

        PermissionSet ps = new PermissionSet();
        ps.Name = 'Test';
        ps.Label = 'Test';
        insert ps;

        SetupEntityAccess sea = new SetupEntityAccess();
        sea.ParentId = ps.Id;
        sea.SetupEntityId = [SELECT Id, DeveloperName FROM CustomPermission WHERE DeveloperName = 'Mark_As_Deceased'][0].Id;
        insert sea;

        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = ps.Id;
        insert psa;

        System.runAs(u) {
            Test.startTest();

            MakeDeceasedController.moveContactToDeceased(con.Id, 'TEST NOTE BODY');

            Test.stopTest();

            con = [SELECT RecordTypeId, Membership_Status__c FROM Contact WHERE Id=: con.Id];
            System.assertEquals(ECRMUtils.deceasedRecordTypeId, con.RecordTypeId);
            System.assertEquals('Deceased', con.Membership_Status__c);

            ContentVersion cv = [SELECT Id FROM ContentVersion WHERE FirstPublishLocationId=: con.Id];
            System.assertNotEquals(null, cv);

            List<OrderApi__Subscription__c> cancelledSubs = [SELECT Id FROM OrderApi__Subscription__c WHERE OrderApi__Contact__c=:con.Id AND OrderApi__Is_Cancelled__c= true];
            System.assertEquals(1, cancelledSubs.size());
        }
    }


}