src/objects/Dimension_Tags__mdt.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>BR_Event__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                    <default>true</default>
                    <label>Public</label>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dimension Tag</label>
    <pluralLabel>Dimension Tags</pluralLabel>
</CustomObject>

src/classes/ExportHelper_LeadTest.cls
/**
 * Created by afaf.awad on 9/9/2021.
 */
@IsTest
public with sharing class ExportHelper_LeadTest {

    @IsTest
    public static void test_exportTagsLeads() {

        Lead lead = TestDataFactory.buildLead();
        insert lead;

        Dimension_Tags__mdt DMT = [SELECT Id FROM Dimension_Tags__mdt WHERE Object__c = 'Lead' AND Visibility__c = 'Public' LIMIT 1];
        SObject publicObj = DimensionTagHelper.createTagRecord(DMT.Id,  lead.Id);
        insert publicObj;

        ExportHelper_Lead.LeadExport le = ExportHelper_Lead.queryLeads(DMT.Id);

        System.assertEquals(1, le.Leads.size());
    }

}