src/objects/Dimension_Tags__mdt.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>BR_Event__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                    <default>true</default>
                    <label>Public</label>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dimension Tag</label>
    <pluralLabel>Dimension Tags</pluralLabel>
</CustomObject>

src/classes/ExportHelper_AccountTest.cls
/**
 * Created by afaf.awad on 7/7/2021.
 */

@IsTest
private class ExportHelper_AccountTest {
    @IsTest
    public static void test_exportTagsAccount() {

        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Dimension_Tags__mdt DMT = [SELECT Id FROM Dimension_Tags__mdt WHERE Object__c = 'Account' AND Visibility__c = 'Public' LIMIT 1];
        SObject publicObj = DimensionTagHelper.createTagRecord(DMT.Id,  acc.Id);
        insert publicObj;

        ExportHelper_Account.AccountExport ae = ExportHelper_Account.queryAccounts(DMT.Id);

        System.assertEquals(1, ae.Accounts.size());
    }
}