src/objects/EC_Email__c.object
<CustomObject>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Exhibitor Emails</relationshipLabel>
        <relationshipName>Exhibitor_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhibitor_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Setting</label>
        <referenceTo>EC_Exhibitor_Setting__c</referenceTo>
        <relationshipLabel>Exhibitor Emails</relationshipLabel>
        <relationshipName>Exhibitor_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exhibitor Email</label>
    <nameField>
        <displayFormat>EE-{0000}</displayFormat>
        <label>Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Exhibitor_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exhibitor Settings</relationshipLabel>
        <relationshipName>Exhibitor_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Invoice_To__c</fullName>
        <label>Send Invoice To</label>
        <type>Email</type>
    </fields>
    <label>Exhibitor Setting</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exhibitor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Order__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exhibitor Orders</relationshipLabel>
        <relationshipName>Exhibitor_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhibitor_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Setting</label>
        <referenceTo>EC_Exhibitor_Setting__c</referenceTo>
        <relationshipLabel>Exhibitor Orders</relationshipLabel>
        <relationshipName>Exhibitor_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exhibitor Order</label>
    <nameField>
        <displayFormat>EO-{0000}</displayFormat>
        <label>EO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>EC_Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Email</label>
        <referenceTo>EC_Email__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Slot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_QueueableStripeInvoice.cls
/**
 * Created by afaf.awad on 3/22/2021.
 */

public class EC_QueueableStripeInvoice implements Queueable {

    private Integer totalParts;
    private Time_Slot__c timeSlot;

    public EC_QueueableStripeInvoice(Integer totalCount, Time_Slot__c timeSlot) {
        this.totalParts = totalCount;
        this.timeSlot = timeSlot;
    }

    public void execute(QueueableContext context) {
        try {
         EC_InvoiceHelper.createStripeInvoice(Date.today().addMonths(1),totalParts, timeSlot.EC_Order__c, timeSlot.Id, timeSlot.EC_Order__r.Company__c, timeSlot.EC_Email__r.Exhibitor_Setting__r.Send_Invoice_To__c);
        } catch (Exception e) {
            System.debug('Error Message : ' + e.getMessage());
        }
    }

}