src/objects/EC_Email__c.object
<CustomObject>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Exhibitor Emails</relationshipLabel>
        <relationshipName>Exhibitor_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhibitor_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Setting</label>
        <referenceTo>EC_Exhibitor_Setting__c</referenceTo>
        <relationshipLabel>Exhibitor Emails</relationshipLabel>
        <relationshipName>Exhibitor_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Body__c</fullName>
        <label>Template Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exhibitor Email</label>
    <nameField>
        <displayFormat>EE-{0000}</displayFormat>
        <label>Email Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Exhibitor_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exhibitor Settings</relationshipLabel>
        <relationshipName>Exhibitor_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reply_To__c</fullName>
        <label>Reply To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sender_Name__c</fullName>
        <label>Sender Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Exhibitor Setting</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Exhibitor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EC_Order__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exhibitor Orders</relationshipLabel>
        <relationshipName>Exhibitor_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exhibitor_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exhibitor Setting</label>
        <referenceTo>EC_Exhibitor_Setting__c</referenceTo>
        <relationshipLabel>Exhibitor Orders</relationshipLabel>
        <relationshipName>Exhibitor_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exhibitor Order</label>
    <nameField>
        <displayFormat>EO-{0000}</displayFormat>
        <label>EO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_OrderEmailController.cls
/**
 * Created by afaf.awad on 2/15/2021.
 */

public without sharing class EC_OrderEmailController {

    @AuraEnabled
    public static EC_Email__c getEmailRecord(String orderId, String stepId){
        JP_Helper.upsertLastAccessedStep(stepId);

        try {
            EC_Email__c emailRec = EC_Helper.getEmailRecordFromOrder(orderId);
            return emailRec;

        }catch(Exception e) {
            Contact con = ECRMUtils.getCurrentLoginContact();
            EC_Email__c newEmail = new EC_Email__c(EC_Order__c = orderId, Exhibitor_Setting__c = EC_Helper.getExhibitorSetting(con.AccountId).Id);
            insert newEmail;
            return newEmail;
        }

    }

//    @AuraEnabled
//    public static Boolean updateEmailRecord(String emailId, String emailBody){
//        EC_Email__c ecEmail = new EC_Email__c();
//        ecEmail.Id = emailId;
////        ecEmail.Template_Body__c = emailBody;
//
//        try{
//            update ecEmail;
//            return true;
//        } catch(Exception e){
//            System.debug('Could not update email template: ' + e.getMessage());
//            return false;
//        }
//    }

    @AuraEnabled
    public static Boolean sendTestEmail(String testEmail, String emailId){

        EC_Email__c email = EC_Helper.getEmailRecord(emailId);
        String emailbody = EC_Helper.buildEmailTemplate(emailId);

        Map<String,String> emailMap = new Map<String, String>();
        emailMap.put(testEmail, 'AACR Test Email');

            return PlatformEmailService.callSendGridAPI(emailMap
                    , email.Subject__c
                    , testEmail
                    , email.Exhibitor_Setting__r.Sender_Name__c != null ? email.Exhibitor_Setting__r.Sender_Name__c : email.Exhibitor_Setting__r.Company__r.Name
                    , email.Exhibitor_Setting__r.Reply_To__c != null ? email.Exhibitor_Setting__r.Reply_To__c : testEmail
                    , emailbody);

    }

//    @AuraEnabled
//    public static String buildEmailTemplate(String emailId){
//
//        return EC_Helper.buildEmailTemplate((emailId));
//
//    }

}