src/objects/EC_Order__c.object
<CustomObject>
    <label>Exhibitor Order</label>
    <nameField>
        <displayFormat>EO-{0000}</displayFormat>
        <label>EO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Process_Steps__mdt.object
<CustomObject>
    <description>Steps related to an individual join process in order</description>
    <fields>
        <fullName>Process__c</fullName>
        <description>Associated join process</description>
        <label>Process</label>
        <referenceTo>Join_Process__mdt</referenceTo>
        <relationshipLabel>Process Steps</relationshipLabel>
        <relationshipName>Process_Steps</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Process Step</label>
    <pluralLabel>Process Steps</pluralLabel>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Slot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_OrderReviewController.cls
/**
 * Created by afaf.awad on 2/24/2021.
 */

public without sharing class EC_OrderReviewController {

    @AuraEnabled
    public static ReviewOrder getReviewOrder(String stepId, String orderId){
        if(stepId != null) {
            JP_Helper.upsertLastAccessedStep(stepId);
        }
        EC_Order__c  order = EC_Helper.getOrderRecord(orderId);
        List<Time_Slot__c> timeSlots = [SELECT Id, Start_Time__c, End_Time__c, Delivery_Date__c FROM Time_Slot__c WHERE EC_Order__c =: orderId];

        if(!timeSlots.isEmpty()){
            return new ReviewOrder(order, timeSlots[0]);
        }else
        {
            return new ReviewOrder(order, null);

        }

    }

    @AuraEnabled
    public static Boolean clearLastStep(String stepId){
        List<Process_Steps__mdt> currentStep = [SELECT Process__c FROM Process_Steps__mdt WHERE Id =: stepId LIMIT 1];
        if (currentStep.size() == 1) {
            JP_Helper.deleteContactLastAccessedStep(currentStep[0].Process__c);
        }

        return true;
    }

    @AuraEnabled
    public static String getPreviousStep(String stepId){
        return EC_Helper.getPreviousStep(stepId, 'New_Exhibitor_Order');
    }

    public class ReviewOrder{
        @AuraEnabled
        public EC_Order__c order;
        @AuraEnabled
        public Time_Slot__c timeSlot;

        public ReviewOrder(EC_Order__c exOrder, Time_Slot__c timeRange){
            this.order = exOrder;
            this.timeSlot = timeRange;
        }
    }

}