src/objects/EC_Order__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Targeted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Targeted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exhibitor Orders</relationshipLabel>
        <relationshipName>Exhibitor_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                    <label>Incomplete</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Over Budget</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Exhibitor Order</label>
    <nameField>
        <displayFormat>EO-{0000}</displayFormat>
        <label>EO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exhibitor Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EC_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>EC_Order__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Review</fullName>
                    <default>true</default>
                    <label>In Review</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Over Budget</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Time Slot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EC_MarketingDashboardController.cls
/**
 * Created by afaf.awad on 3/1/2021.
 */

public without sharing class EC_MarketingDashboardController {


    @AuraEnabled
    public static List<Integer> getAvailableYears(){
        List<Integer> years = new List<Integer>();
        list<Schema.AggregateResult> results = [SELECT COUNT(Id), Calendar_Year(Delivery_Date__c) sendYear
        FROM Time_Slot__c
        WHERE Blocked__c = false
        GROUP BY Calendar_Year(Delivery_Date__c)
        ORDER BY Calendar_Year(Delivery_Date__c) ASC];
        if(!results.isEmpty()) {
            for (AggregateResult r : results) {
                years.add((Integer) r.get('sendYear'));
            }
        } else {
            years.add(System.now().year());
        }

        return years;
    }


    /**
     * @purpose Retrieve all published and non-cancelled events for a specified month
     *
     * @param month
     *
     * @return
     */
    @AuraEnabled
    public static List<Time_Slot__c> getEventsPerMonth(String month, Integer year) {
        Date monthStart = Date.newInstance(year, Integer.valueOf(month), 1);
        Date nextMonthStart = Date.newInstance(year, Integer.valueOf(month) + 1, 1);
        List<Time_Slot__c> timeSlots = [SELECT Id, Start_Time__c, End_Time__c, Delivery_Date__c, EC_Order__c, EC_Order__r.Name,
                                                EC_Order__r.Company__r.Name, EC_Order__r.Company__c,
                                                Status__c, EC_Order__r.Amount_Targeted__c
                                        FROM Time_Slot__c WHERE  Delivery_Date__c >= :monthStart
                                                            AND Delivery_Date__c < :nextMonthStart
                                                            AND Blocked__c = false
                                        ORDER BY Delivery_Date__c, Start_Time__c ASC];

        return timeSlots;
    }


}