src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>Calendar_Invite_Msg__c</fullName>
        <label>Calendar Invite Msg</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventApi__Description__c</fullName>
        <description>Optional event description.</description>
        <inlineHelpText>Optional event description.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Date_Time__c</fullName>
        <description>**Required** The event end date and time (mm/dd/yyyy hh:mm:ss).</description>
        <inlineHelpText>**Required** The event end date and time (mm/dd/yyyy hh:mm:ss).</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event end date.</description>
        <inlineHelpText>**Required** The event end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__Logo_Image__c</fullName>
        <description>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</description>
        <inlineHelpText>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</inlineHelpText>
        <label>Logo Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Date_Time__c</fullName>
        <description>**Required** The event start date and time (mm/dd/yyyy hh:mm:ss).</description>
        <inlineHelpText>**Required** The event start date and time (mm/dd/yyyy hh:mm:ss).</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event start date.</description>
        <inlineHelpText>**Required** The event start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Meeting_Links__mdt.object
<CustomObject>
    <description>links for virtual meetings</description>
    <fields>
        <fullName>Check_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if computer check link is active</description>
        <label>Check IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Computer_Check_Link__c</fullName>
        <label>Computer Check Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Email_Template_Id__c</fullName>
        <description>Registration email template id</description>
        <label>Email Template Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if view link is active to users</description>
        <label>Event IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Login_Background_Image__c</fullName>
        <label>Login Background Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_Header_Image__c</fullName>
        <label>Login Header Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Open__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Registration Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View_Link__c</fullName>
        <label>View Link</label>
        <type>Url</type>
    </fields>
    <label>Virtual Meeting Links</label>
    <pluralLabel>Virtual Meetings Links</pluralLabel>
</CustomObject>

src/classes/Schedule_VirtualRegConfirmationsTest.cls
/**
 * Created by lauren.lezberg on 5/22/2020.
 */

@isTest
private with sharing class Schedule_VirtualRegConfirmationsTest {

    @testsetup
    public static void setup(){
        Account testAcc = TestDataFactory.buildAccount('Test Account');
        insert testAcc;

        Contact con = TestDataFactory.buildContact(testAcc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;

        EventApi__Event__c testEvt = TestDataFactory.buildEvent();
        testEvt.Calendar_Invite_Msg__c = 'TEST';
        testEvt.EventApi__Start_Date__c = Date.today();
        testEvt.EventApi__Start_Date_Time__c = System.now();
        testEvt.EventApi__End_Date_Time__c = SYstem.now().addDays(2);
        testEvt.EventApi__End_Date__c = Date.today().addDays(2);
        testEvt.EventApi__Logo_Image__c = 'https://www.testImgurl.com';
        testEvt.EventApi__Description__c = 'THIS IS A TEST EVENT.';
        insert testEvt;

        EventApi__Attendee__c att = new EventApi__Attendee__c();
        att.EventApi__Contact__c = con.Id;
        att.EventApi__Event__c = testEvt.Id;
        insert att;
    }


    @isTest
    public static void test_sendBatchEmails(){
        EventApi__Event__c evt = [SELECT id FROM EventApi__Event__c WHERE Name='Test Event'];

        EmailTemplate validEmailTemplate = new EmailTemplate();
        validEmailTemplate.isActive = true;
        validEmailTemplate.Name = 'name';
        validEmailTemplate.DeveloperName = 'unique_name_addSomethingSpecialHere';
        validEmailTemplate.TemplateType = 'text';
        validEmailTemplate.FolderId = UserInfo.getUserId();

        insert validEmailTemplate;

            Virtual_Meeting_Links__mdt vml = [SELECT Id, Email_Template_Id__c FROM Virtual_Meeting_Links__mdt WHERE DeveloperName='Virtual_AM_2' LIMIT 1];

            vml.Login_Background_Image__c = 'https://s3.us-east-1.amazonaws.com/fonteva-customer-media/undefined/lYVgTwcf_myAACR_4C_Oct22_2018_horiz3_png';
            vml.Login_Header_Image__c = 'https://s3.us-east-1.amazonaws.com/fonteva-customer-media/undefined/lYVgTwcf_myAACR_4C_Oct22_2018_horiz3_png';
            vml.Event_Id__c = evt.Id;
            vml.View_Link__c = 'https://www.google.com';
            vml.Event_IsActive__c = true;
            vml.Computer_Check_Link__c = 'https://www.salesforce.com';
            vml.Check_IsActive__c = true;
            vml.Registration_Open__c = true;
            vml.Email_Template_Id__c = validEmailTemplate.Id;

            Scheduled_VirtualRegConfirmations.virtualMeetings.add(vml);


            Test.StartTest();
            SchedulableContext sc = null;
            Scheduled_VirtualRegConfirmations obj = new Scheduled_VirtualRegConfirmations();
            obj.execute(sc);
            Test.stopTest();
        }
}