src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>EventApi__End_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event end date.</description>
        <inlineHelpText>**Required** The event end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__Event_Key__c</fullName>
        <description>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</description>
        <inlineHelpText>This field is used as a unique identifier for events. The value in this field will also be used to concatenate item class names to be easily identified in lookup searches.</inlineHelpText>
        <label>Event Key</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EventApi__Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event start date.</description>
        <inlineHelpText>**Required** The event start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Event.</description>
        <inlineHelpText>Link to related Event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <description>** System Calculated Override ** Enable event specific controls and features for this Item. Defaults to the value of the same field on the Item&apos;s related Item Class.</description>
        <inlineHelpText>** System Calculated Override ** Enable event specific controls and features for this Item. Defaults to the value of the same field on the Item&apos;s related Item Class.</inlineHelpText>
        <label>Is Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Event.</description>
        <inlineHelpText>Link to related Event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Item Classes</relationshipLabel>
        <relationshipName>Item_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</description>
        <inlineHelpText>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra event specific controls and features. Defaults unchecked.</description>
        <inlineHelpText>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra event specific controls and features. Defaults unchecked.</inlineHelpText>
        <label>Is Event</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ItemQuickAddControllerTest.cls
/**
 * Created by lauren.lezberg on 10/11/2019.
 */
@isTest
private with sharing class ItemQuickAddControllerTest {

    @testSetup
    public static void setup(){
        OrderApi__Item_Class__c membershipClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert membershipClass;

        OrderApi__Item__c activeItem = TestDataFactory.buildItem(membershipClass.Id, 'Active Membership');
        insert activeItem;

        OrderApi__Item__c affiliateItem = TestDataFactory.buildItem(membershipClass.Id, 'Affiliate Membership');
        insert affiliateItem;

        OrderApi__Item__c associateItem = TestDataFactory.buildItem(membershipClass.Id, 'Associate Membership');
        insert associateItem;

        OrderApi__Item_Class__c journalClass = TestDataFactory.buildItemClass('Journal Subscriptions');
        insert journalClass;

        OrderApi__Item__c cancerDiscoveryO = TestDataFactory.buildItem(journalClass.Id, 'Cancer Discovery Journal - Online');
        insert cancerDiscoveryO;

        OrderApi__Item__c cancerDiscoveryP = TestDataFactory.buildItem(journalClass.Id, 'Cancer Discovery Journal - Print & Online');
        insert cancerDiscoveryP;

        OrderApi__Item__c cancerResearchO = TestDataFactory.buildItem(journalClass.Id, 'Cancer Research Journal - Online');
        insert cancerResearchO;

        OrderApi__Item__c cancerResearchP = TestDataFactory.buildItem(journalClass.Id, 'Cancer Research Journal - Print & Online');
        insert cancerResearchP;

        EventApi__Event__c newEvent = new EventApi__Event__c(Name='Test Event', EventApi__Start_Date__c = Date.valueOf(System.now().addDays(2)), EventApi__End_Date__c= Date.valueOf(System.now().addDays(8)), EventApi__Event_Key__c='289375983475');
        insert newEvent;

        OrderApi__Item_Class__c eventClass = TestDataFactory.buildItemClass('Event Tickets');
        eventClass.EventApi__Event__c = newEvent.Id;
        eventClass.OrderApi__Is_Event__c = true;
        insert eventClass;

        OrderApi__Item__c ticket1 = TestDataFactory.buildItem(eventClass.Id, 'Ticket Type 1');
        insert ticket1;

        OrderApi__Item__c ticket2 = TestDataFactory.buildItem(eventClass.Id, 'Ticket Type 2');
        insert ticket2;
    }


    @isTest
    public static void test_fetchItems(){

        Test.startTest();
        List<OrderApi__Item__c> foundItems = ItemQuickAddController.fetchItems('Membership', 'OrderApi__Is_Active__c = true');
        System.assertEquals(3, foundItems.size());

        foundItems = ItemQuickAddController.fetchItems('Journal', 'OrderApi__Is_Active__c = true');
        System.assertEquals(4, foundItems.size());

        List<OrderApi__Item__c> eventItems = [SELECT ID FROM OrderApi__Item__c WHERE OrderApi__Item_Class__r.OrderApi__Is_Event__c= true];
        SYstem.debug('eventItems: ' + eventItems.size());
        foundItems = ItemQuickAddController.fetchItems('Ticket', 'OrderApi__Item_Class__r.OrderApi__Is_Event__c= true');
        System.assertEquals(2, foundItems.size());

        Test.stopTest();
    }
}