src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>EventApi__Display_Name__c</fullName>
        <description>Event name as you would like it to appear on registration pages, calendar reminders, and emails.</description>
        <inlineHelpText>Event name as you would like it to appear on registration pages, calendar reminders, and emails.</inlineHelpText>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event end date.</description>
        <inlineHelpText>**Required** The event end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event start date.</description>
        <inlineHelpText>**Required** The event start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ROEApi__Active_Ticket_Type_Count__c</fullName>
        <description>Total number of active ticket types</description>
        <inlineHelpText>Total number of active ticket types.</inlineHelpText>
        <label>SYSTEM</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Event.</description>
        <inlineHelpText>Link to related Event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <description>** System Calculated Override ** Enable event specific controls and features for this Item. Defaults to the value of the same field on the Item&apos;s related Item Class.</description>
        <inlineHelpText>** System Calculated Override ** Enable event specific controls and features for this Item. Defaults to the value of the same field on the Item&apos;s related Item Class.</inlineHelpText>
        <label>Is Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price__c</fullName>
        <description>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</description>
        <inlineHelpText>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</inlineHelpText>
        <label>Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Event.</description>
        <inlineHelpText>Link to related Event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Item Classes</relationshipLabel>
        <relationshipName>Item_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra event specific controls and features. Defaults unchecked.</description>
        <inlineHelpText>When checked, Items created that are associated with this Item Class will automatically be
enabled with extra event specific controls and features. Defaults unchecked.</inlineHelpText>
        <label>Is Event</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ItemQuickAddController.cls
/**
 * Created by lauren.lezberg on 10/7/2019.
 */

public with sharing class ItemQuickAddController {

    /**
     * @purpose Retrieves records based on search keyword from specific object type
     *
     * @param searchKeyWord
     * @param ObjectName
     *
     * @return List of records matching the search keyword
     */
    @AuraEnabled
    public static List <OrderApi__Item__c> fetchItems(String searchKeyWord, String filterString) {
        String searchKey = '%' + searchKeyWord + '%';
        Date today = Date.today();

        List < OrderApi__Item__c> returnList = new List < OrderApi__Item__c > ();

        String sQuery =  'SELECT id, Name, OrderApi__Price__c, OrderApi__Item_Class__r.EventApi__Event__r.ROEApi__Active_Ticket_Type_Count__c, OrderApi__Item_Class__r.Name, OrderApi__Item_Class__r.EventApi__Event__r.EventApi__Start_Date__c, OrderApi__Item_Class__r.OrderApi__Is_Event__c, OrderApi__Item_Class__r.EventApi__Event__r.EventApi__Display_Name__c from OrderApi__Item__c WHERE Name LIKE: searchKey';
        if(filterString !=null){
            //' AND (OrderApi__Item_Class__r.OrderApi__Is_Event__c = false OR OrderApi__Item_Class__r.EventApi__Event__r.EventApi__End_Date__c >= :today)'
            sQuery += ' AND ' + filterString;
        }
        sQuery += ' ORDER BY createdDate DESC limit 5';

        System.debug('squery: ' + sQuery);
        List <OrderApi__Item__c> lstOfRecords = Database.query(sQuery);

        for (OrderApi__Item__c obj: lstOfRecords) {
            returnList.add(obj);
        }
        return returnList;
    }

}