src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>EventApi__Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the Survey Form built using Fonteva&apos;s Publisher. Required and restricted to Events where &quot;Enable Surveys&quot; is checked.</description>
        <inlineHelpText>** Conditionally Required ** Link to the Survey Form built using Fonteva&apos;s Publisher. Required and restricted to Events where &quot;Enable Surveys&quot; is checked.</inlineHelpText>
        <label>Registration Interview</label>
        <referenceTo>PagesApi__Form__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EventApi__Ticket_Type__c.object
<CustomObject>
    <description>Tracks the various types of Tickets available for a Event.</description>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Event.</description>
        <inlineHelpText>Link to related Event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Ticket Types</relationshipLabel>
        <relationshipName>Ticket_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to a form created in the &quot;Form Builder&quot; app. Customers will see the form when they select the ticket type.</description>
        <inlineHelpText>Link to a form created in the &quot;Form Builder&quot; app. Customers will see the form when they select the ticket type.</inlineHelpText>
        <label>Ticket Type Form</label>
        <referenceTo>PagesApi__Form__c</referenceTo>
        <relationshipLabel>Ticket Types</relationshipLabel>
        <relationshipName>Ticket_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ticket Type</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Event.</description>
        <inlineHelpText>Link to related Event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Ticket_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to Ticket Type (Circular Reference) do not manually update.</description>
        <inlineHelpText>** System Calculated ** Link to Ticket Type (Circular Reference) do not manually update.</inlineHelpText>
        <label>Ticket Type</label>
        <referenceTo>EventApi__Ticket_Type__c</referenceTo>
        <relationshipLabel>DO NOT DISPLAY</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Event.</description>
        <inlineHelpText>Link to related Event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Item Classes</relationshipLabel>
        <relationshipName>Item_Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Event.</description>
        <inlineHelpText>Link to related Event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Ticket_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Ticket Type.</description>
        <inlineHelpText>Link to related Ticket Type.</inlineHelpText>
        <label>Ticket Type</label>
        <referenceTo>EventApi__Ticket_Type__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PagesApi__Field__c.object
<CustomObject>
    <description>Fields store data that drives the look and field and behavior of web forms published in the Web Publisher application.</description>
    <fields>
        <fullName>PagesApi__Field_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**Required** All fields must be associated with a Field Group. Field Groups can be used to update and create new records in the database.</description>
        <inlineHelpText>**Required** All fields must be associated with a Field Group. Field Groups can be used to update and create new records in the database.</inlineHelpText>
        <label>Field Group</label>
        <referenceTo>PagesApi__Field_Group__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PagesApi__Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associates this field to a form.</description>
        <inlineHelpText>Associates this field to a form.</inlineHelpText>
        <label>Form</label>
        <referenceTo>PagesApi__Form__c</referenceTo>
        <relationshipLabel>Fields</relationshipLabel>
        <relationshipName>Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field</label>
    <nameField>
        <label>Field Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PagesApi__Field_Group__c.object
<CustomObject>
    <description>Field Groups store data about the behavior of a set of fields published on a web form.</description>
    <fields>
        <fullName>PagesApi__Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**Required** Identifies the field group&apos;s related form.</description>
        <inlineHelpText>**Required** Identifies the field group&apos;s related form.</inlineHelpText>
        <label>Form</label>
        <referenceTo>PagesApi__Form__c</referenceTo>
        <relationshipLabel>Field Groups</relationshipLabel>
        <relationshipName>Field_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Group</label>
    <nameField>
        <label>Field Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PagesApi__Field_Response__c.object
<CustomObject>
    <description>Object used to identify the responses from form submissions.</description>
    <fields>
        <fullName>PagesApi__Field_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Field Group.</description>
        <inlineHelpText>** System Calculated ** Link to related Field Group.</inlineHelpText>
        <label>Field Group</label>
        <referenceTo>PagesApi__Field_Group__c</referenceTo>
        <relationshipLabel>Field Responses</relationshipLabel>
        <relationshipName>Field_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PagesApi__Field__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required ** Identifies the value&apos;s related field.</description>
        <inlineHelpText>** System Calculated Required ** Identifies the value&apos;s related field.</inlineHelpText>
        <label>Field</label>
        <referenceTo>PagesApi__Field__c</referenceTo>
        <relationshipLabel>Field Responses</relationshipLabel>
        <relationshipName>Field_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Field Response</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Field Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BackOfficeFormControllerTest.cls
/**
 * Created by afaf.awad on 12/18/2019.
 */

@IsTest
private class BackOfficeFormControllerTest {

    @testSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('TEST Account');
        insert acc;

        Contact con = TestDataFactory.buildContactMemberPrior(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;

        EventApi__Event__c event = TestDataFactory.buildEvent();
        insert event;

        PagesApi__Form__c form = TestDataFactory.buildForm();
        insert form;

        PagesApi__Field_Group__c fieldGroup = TestDataFactory.buildFieldGroup(form);
        insert fieldGroup;

        PagesApi__Field__c field = TestDataFactory.buildField(form, fieldGroup, 'text');
        insert field;

        EventApi__Ticket_Type__c ticketType = TestDataFactory.buildTicketType(event);
        ticketType.EventApi__Form__c = form.Id;
        insert ticketType;

        OrderApi__Item_Class__c ticketItemClass = TestDataFactory.buildItemClass('Test Tickets');
        insert ticketItemClass;

        OrderApi__Item__c ticketItem = TestDataFactory.buildItem(ticketItemClass.Id, 'Test Ticket');
        ticketItem.EventApi__Ticket_Type__c = ticketType.Id;
        insert ticketItem;

        OrderApi__Sales_Order__c SO = TestDataFactory.buildOpenSalesOrder(acc.Id, con.Id );
        insert SO;

        OrderApi__Sales_Order_Line__c sol = TestDataFactory.buildSOLine(SO.Id, ticketItem.Id, ticketItemClass.Id);
        insert sol;

        ContentVersion cv = TestDataFactory.buildFile('Test file');
        insert cv;

    }


    @isTest
    public static void test_getTicketTypeForm(){

        Contact con = [SELECT Id FROM Contact ORDER BY CreatedDate LIMIT 1];
        String salesOrderId = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c =: con.Id].Id;
        OrderApi__Sales_Order_Line__c sol = [SELECT Id, OrderApi__Item__r.EventApi__Ticket_Type__c FROM OrderApi__Sales_Order_Line__c
                                            WHERE OrderApi__Sales_Order__c =: salesOrderId LIMIT 1];

        EventApi__Ticket_Type__c tt = [
                SELECT Id, Name, EventApi__Item__c,EventApi__Is_Active__c, EventApi__Is_Published__c, EventApi__Form__c
                FROM EventApi__Ticket_Type__c
                WHERE Id = : sol.OrderApi__Item__r.EventApi__Ticket_Type__c];

        System.debug('tt = ' + tt);

        List<PagesApi__Field__c> fields =[SELECT Id, Name, PagesApi__Order__c, PagesApi__Type__c, PagesApi__Options__c, PagesApi__Is_Required__c,
                PagesApi__Help_Text__c, PagesApi__Field_Group__r.PagesApi__Instructions__c, PagesApi__Field_Group__r.Name,
                PagesApi__Field_Group__r.PagesApi__Order__c, PagesApi__Field_Group__c, PagesApi__Form__r.Name, PagesApi__Form__c
        FROM PagesApi__Field__c
        WHERE PagesApi__Form__c = :tt.EventApi__Form__c];

        System.debug('Fields = ' + fields);

        Test.startTest();
        BackOfficeFormController.BackOfficeFormData BOFData = BackOfficeFormController.getBackOfficeFormData(salesOrderId);
        System.debug('BOFData = ' + BOFData);
        Test.stopTest();

        System.assertNotEquals(null, BOFData);

    }

    @isTest
    public static void test_getFieldResponses() {

        Contact con = [SELECT Id FROM Contact ORDER BY CreatedDate LIMIT 1];
        String salesOrderId = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c = :con.Id].Id;

        Test.startTest();
        List<PagesApi__Field_Response__c> fieldResponses = BackOfficeFormController.getFieldResponses(salesOrderId);
        Test.stopTest();

        System.assertEquals(0, fieldResponses.size());
    }

    @isTest
    public static void test_createFieldResponses(){

        Contact con = [SELECT Id FROM Contact ORDER BY CreatedDate LIMIT 1];
        String salesOrderId = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c =: con.Id].Id;
        BackOfficeFormController.BackOfficeFormData BOFData = BackOfficeFormController.getBackOfficeFormData(salesOrderId);
        PagesApi__Field__c field = [SELECT Id, PagesApi__Field_Group__c FROM PagesApi__Field__c WHERE PagesApi__Form__c =: BOFData.form.Id];
        PagesApi__Field_Group__c fieldGroup= [SELECT Id FROM PagesApi__Field_Group__c WHERE PagesApi__Form__c =: BOFData.form.Id];
        String fieldResponse = '[{"fieldObj":"' + field.Id + '","response":"yes","formId":"' + BOFData.form.Id + '","fieldResponseId":""}]';

        Test.startTest();
        BackOfficeFormController.createFieldResponses(fieldResponse, BOFData.formResponse.Id);
        String fieldResponseId = [SELECT Id from PagesApi__Field_Response__c WHERE PagesApi__Field__c =: field.Id LIMIT 1].Id;
        String fieldResponse2 = '[{"fieldObj":"' + field.Id + '","response":"No","formId":"' + BOFData.form.Id + '","fieldResponseId":"'+ fieldResponseId + '"}]';
        BackOfficeFormController.createFieldResponses(fieldResponse2, BOFData.formResponse.Id);
        PagesApi__Field__c field2 = TestDataFactory.buildField(BOFData.form, fieldGroup, 'text');
        insert field2;
//        String fieldResponseId2 = [SELECT Id from PagesApi__Field_Response__c WHERE PagesApi__Field__c =: field2.Id LIMIT 1].Id;
        String fieldResponse3 = '[{"fieldObj":"' + field2.Id + '","response":"Maybe","formId":"' + BOFData.form.Id + '","fieldResponseId":""}]';
        BackOfficeFormController.createFieldResponses(fieldResponse3, BOFData.formResponse.Id);
        Test.stopTest();

        System.assertNotEquals(null, [SELECT Id from PagesApi__Field_Response__c where OrderApi__Form_Response__c =: BOFData.formResponse.Id]);


    }

    @isTest
    public static void test_getAndRemoveFile(){

        Contact con = [SELECT Id FROM Contact ORDER BY CreatedDate LIMIT 1];
        ContentVersion documentId = [SELECT Id, Title, ContentDocumentId FROM ContentVersion LIMIT 1];

        System.debug('documentId = ' + documentId);

        Test.startTest();
        ContentVersion cv = BackOfficeFormController.getAttachments(documentId.ContentDocumentId);
        BackOfficeFormController.removeFile('Test File', con.id);
        Test.stopTest();

    }

}