src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Meeting_Links__mdt.object
<CustomObject>
    <description>links for virtual meetings</description>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Virtual Meeting Links</label>
    <pluralLabel>Virtual Meetings Links</pluralLabel>
</CustomObject>

src/classes/UserPasswordResetTriggerHandler.cls
/**
 * Created by lauren.lezberg on 4/10/2020.
 */

public with sharing class UserPasswordResetTriggerHandler {
    public static List<Virtual_Meeting_Links__mdt> virtualMeetings = new List<Virtual_Meeting_Links__mdt>();

    public static void checkForVirtualAttendeeRecords(List<Id> userIds){

        //get all virtual meeting records
        List<Virtual_Meeting_Links__mdt> meetings = new List<Virtual_Meeting_Links__mdt>();
        if(Test.isRunningTest()){
            System.debug('running test: ' + virtualMeetings);
            meetings = virtualMeetings;
        } else{
            meetings = [SELECT Event_Id__c FROM Virtual_Meeting_Links__mdt];
        }
        Set<Id> eventIds = new Set<Id>();
        //get all events with virtual meetings
        for(Virtual_Meeting_Links__mdt vml : meetings){
            eventIds.add(vml.Event_Id__c);
        }


        if(!eventIds.isEmpty()) {
            List<EventApi__Attendee__c> attendees = [
                    SELECT EventApi__Contact__c
                    FROM EventApi__Attendee__c
                    WHERE EventApi__Contact__c IN (SELECT ContactId FROM User WHERE Id IN:userIds)
                    AND EventApi__Event__c IN:eventIds
            ];

            // get set of attendee contactIds
            Set<Id> contactIds = new Set<Id>();
            for (EventApi__Attendee__c attendee : attendees) {
                if(!contactIds.contains(attendee.EventApi__Contact__c)) {
                    contactIds.add(attendee.EventApi__Contact__c);
                }
            }

            //check if users have matching attendee record for virtual meeting & send password reset
//            database.executeBatch(new Batch_ResetUserPassword(userIds),100);
            for (User u : [SELECT ContactId FROM User WHERE Id IN:userIds]) {
                if (contactIds.contains(u.ContactId)) {
                    sendResetPasswordEmail(u.Id);
                }
            }
        }
    }


    private static void sendResetPasswordEmail(Id userId){
        System.resetPassword(userId, true);
    }
}