src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>EventApi__Status__c</fullName>
        <description>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</description>
        <inlineHelpText>** Required ** The current status of the Attendee Registration. Defaults to &quot;Registered&quot;.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                    <default>true</default>
                    <label>Invited</label>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Registered-DataLoad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>EventApi__Status__c</fullName>
        <description>Status of the event. Must be &quot;active&quot; to be visible in the Portal.</description>
        <inlineHelpText>Status of the event. Must be &quot;active&quot; to be visible in the Portal.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <color>#78C953</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#E27001</color>
                    <label>Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_C19CLymphomaUserUpdates.cls
/**
 * Created by lauren.lezberg on 7/14/2020.
 */

public with sharing class Batch_C19CLymphomaUserUpdates implements Database.Batchable<sObject>{
    public String eventId;

    public Batch_C19CLymphomaUserUpdates(String evtId){
        eventId = evtId;
    }

    public Database.Querylocator start(Database.BatchableContext bc) {
        String queryString = 'SELECT Id, EventApi__Contact__c, EventApi__Status__c, EventApi__Event__c FROM EventApi__Attendee__c WHERE EventApi__Event__c =: eventId';
        System.debug('queryString: ' + queryString);

        return Database.getQueryLocator(queryString);
    }

    public void execute(Database.BatchableContext bc, List<EventApi__Attendee__c > scope) {
        List<Id> registeredContactIds = new List<Id>();
        List<Id> cancelledContactIds = new List<Id>();
        for(EventApi__Attendee__c att : scope){
            if (att.EventApi__Status__c == 'Registered') {
                registeredContactIds.add(att.EventApi__Contact__c);
            } else if(att.EventApi__Status__c == 'Cancelled'){
                cancelledContactIds.add(att.EventApi__Contact__c);
            }
        }

        if(eventId == C19CLymphomaTriggerHandler.lymphomaEventId){
            C19CLymphomaTriggerHandler.updateLymphomaUserRecords(registeredContactIds, cancelledContactIds);
        } else if(eventId == C19CLymphomaTriggerHandler.covidEventId){
            C19CLymphomaTriggerHandler.updateC19CUserRecords(registeredContactIds, cancelledContactIds);
        }
    }


    public void finish(Database.BatchableContext BC) {
        AsyncApexJob a = [
                SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                        TotalJobItems, CreatedBy.Email
                FROM AsyncApexJob
                WHERE Id =
                        :BC.getJobId()
        ];
        System.debug('job summary: ' + a);

    }
}