src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <fields>
        <fullName>Calendar_Invite_Msg__c</fullName>
        <label>Calendar Invite Msg</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventApi__Description__c</fullName>
        <description>Optional event description.</description>
        <inlineHelpText>Optional event description.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventApi__Display_Name__c</fullName>
        <description>Event name as you would like it to appear on registration pages, calendar reminders, and emails.</description>
        <inlineHelpText>Event name as you would like it to appear on registration pages, calendar reminders, and emails.</inlineHelpText>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Date_Time__c</fullName>
        <description>**Required** The event end date and time (mm/dd/yyyy hh:mm:ss).</description>
        <inlineHelpText>**Required** The event end date and time (mm/dd/yyyy hh:mm:ss).</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event end date.</description>
        <inlineHelpText>**Required** The event end date.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__End_Time__c</fullName>
        <description>**Required** The event end time (HH:MM).</description>
        <inlineHelpText>**Required** The event end time (HH:MM).</inlineHelpText>
        <label>End Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventApi__Location_And_Date_Text__c</fullName>
        <description>The value defined in this field will display in the upper right hand side of the navbar overriding the city, state, and date/time.</description>
        <inlineHelpText>The value defined in this field will display in the upper right hand side of the navbar overriding the city, state, and date/time.</inlineHelpText>
        <label>Location and Date Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EventApi__Logo_Image__c</fullName>
        <description>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</description>
        <inlineHelpText>The image defined in this field appears in the lefthand side of the navbar in the microsite.
            Recommended size 90px by 90px. (Image will be cropped to these dimensions)</inlineHelpText>
        <label>Logo Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Date_Time__c</fullName>
        <description>**Required** The event start date and time (mm/dd/yyyy hh:mm:ss).</description>
        <inlineHelpText>**Required** The event start date and time (mm/dd/yyyy hh:mm:ss).</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>**Required** The event start date.</description>
        <inlineHelpText>**Required** The event start date.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EventApi__Start_Time__c</fullName>
        <description>**Required** The event start time (HH:MM).</description>
        <inlineHelpText>**Required** The event start time (HH:MM).</inlineHelpText>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventApi__Time_Zone__c</fullName>
        <description>The time zone of the event location.</description>
        <inlineHelpText>The time zone of the event location.</inlineHelpText>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(GMT+13:00) Pacific/Enderbury</fullName>
                </value>
                <value>
                    <fullName>(GMT+13:00) Pacific/Tongatapu</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:45) Pacific/Chatham</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) Asia/Kamchatka</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) Pacific/Auckland</fullName>
                </value>
                <value>
                    <fullName>(GMT+12:00) Pacific/Fiji</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:30) Pacific/Norfolk</fullName>
                </value>
                <value>
                    <fullName>(GMT+11:00) Pacific/Guadalcanal</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:30) Australia/Lord_Howe</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:00) Australia/Brisbane</fullName>
                </value>
                <value>
                    <fullName>(GMT+10:00) Australia/Sydney</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:30) Australia/Adelaide</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:30) Australia/Darwin</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:00) Asia/Seoul</fullName>
                </value>
                <value>
                    <fullName>(GMT+09:00) Asia/Tokyo</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Asia/Hong_Kong</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Asia/Kuala_Lumpur</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Asia/Manila</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Asia/Shanghai</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Asia/Singapore</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Asia/Taipei</fullName>
                </value>
                <value>
                    <fullName>(GMT+08:00) Australia/Perth</fullName>
                </value>
                <value>
                    <fullName>(GMT+07:00) Asia/Bangkok</fullName>
                </value>
                <value>
                    <fullName>(GMT+07:00) Asia/Ho_Chi_Minh</fullName>
                </value>
                <value>
                    <fullName>(GMT+07:00) Asia/Jakarta</fullName>
                </value>
                <value>
                    <fullName>(GMT+06:30) Asia/Rangoon</fullName>
                </value>
                <value>
                    <fullName>(GMT+06:00) Asia/Dhaka</fullName>
                </value>
                <value>
                    <fullName>(GMT+05:45) Asia/Kathmandu</fullName>
                </value>
                <value>
                    <fullName>(GMT+05:30) Asia/Colombo</fullName>
                </value>
                <value>
                    <fullName>(GMT+05:30) Asia/Kolkata</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Meeting_Links__mdt.object
<CustomObject>
    <description>links for virtual meetings</description>
    <fields>
        <fullName>Confirmation_Text__c</fullName>
        <description>Event specific text that displays on registration confirmation screen.</description>
        <label>Confirmation Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exhibit_Open__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is meeting open with SSO</description>
        <label>Exhibit Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Freeman_Event_Id__c</fullName>
        <label>Freeman Event Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_Background_Image__c</fullName>
        <label>Login Background Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Login_Header_Image__c</fullName>
        <label>Login Header Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Open__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Registration Open</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View_Link__c</fullName>
        <label>View Link</label>
        <type>Url</type>
    </fields>
    <label>Virtual Meeting Links</label>
    <pluralLabel>Virtual Meetings Links</pluralLabel>
</CustomObject>

src/classes/VirtualRegisterConfirmationController.cls
/**
 * Created by lauren.lezberg on 5/15/2020.
 */

public with sharing class VirtualRegisterConfirmationController extends PagesApi.DefaultTemplateController {

    public static List<Virtual_Meeting_Links__mdt> virtualMeetings = new List<Virtual_Meeting_Links__mdt>();

    public EventApi__Event__c event {get;set;}
    public String contactId {get;set;}
    public String viewLink {get;set;}
    public String confirmationTxt {get;set;}
    public String eventId {get;set;}
    public String backgroundImg {get;set;}
    public String headerImg {get;set;}



    public PageReference checkIsActive(){

        if(this.getIsAuthenticated()) {
            eventId = ApexPages.currentPage().getParameters().get('id');
            if (eventId != null) {
                List<Virtual_Meeting_Links__mdt> vmls = new List<Virtual_Meeting_Links__mdt>();
                if(Test.isRunningTest()){
                    System.debug('running test: ' + virtualMeetings);
                    vmls = virtualMeetings;
                } else{
                    vmls = [SELECT Id, Exhibit_Open__c, View_Link__c, Event_Id__c, Confirmation_Text__c, Registration_Open__c, Login_Background_Image__c, Login_Header_Image__c FROM Virtual_Meeting_Links__mdt WHERE Freeman_Event_Id__c = :eventId];
                }
                if(!vmls.isEmpty()){
                    if(vmls[0].Exhibit_Open__c){
                        return new PageReference('/FreemanRedirect?id=' + eventId);
                    }
                    if(vmls[0].Registration_Open__c) {
                        Contact con = ECRMUtils.getCurrentLoginContact();
                        event = [SELECT Calendar_Invite_Msg__c, EventApi__Start_Date_Time__c, EventApi__End_Date_Time__c, EventApi__Location_And_Date_Text__c, EventApi__Start_Date__c, EventApi__Start_Time__c, EventApi__End_Date__c, EventApi__Logo_Image__c, EventApi__End_Time__c, EventApi__Time_Zone__c, EventApi__Description__c, EventApi__Display_Name__c FROM EventApi__Event__c WHERE Id=: vmls[0].Event_Id__c];
                        if(event.Calendar_Invite_Msg__c!=null) {
                            event.Calendar_Invite_Msg__c = event.Calendar_Invite_Msg__c.removeStart('\'').removeEnd('\'');
                        }

                        TimeZone targetTimezone = TimeZone.getTimeZone('America/New_York');

                        // The targetDate is used here to decide whether
                        // Daylight Savings should apply.
                        Integer offsetSeconds = targetTimezone.getOffset(event.EventApi__Start_Date__c) / 1000;
                        Datetime targetDatetime = event.EventApi__Start_Date_Time__c.addSeconds(offsetSeconds);
                        event.EventApi__Start_Date_Time__c = targetDatetime;

                        offsetSeconds = targetTimezone.getOffset(event.EventApi__End_Date__c) / 1000;
                        targetDatetime = event.EventApi__End_Date_Time__c.addSeconds(offsetSeconds);
                        event.EventApi__End_Date_Time__c = targetDatetime;

                        contactId = con.Id;
                        viewLink = vmls[0].View_Link__c.remove('&regId=');
                        confirmationTxt = vmls[0].Confirmation_Text__c;
                        backgroundImg = vmls[0].Login_Background_Image__c;
                        headerImg = vmls[0].Login_Header_Image__c;
                        return null;
                    } else {
                        return new PageReference('/MemberProfile');
                    }
                } else {
                    return new PageReference('/MemberProfile');
                }

            } else {
                return new PageReference('/MemberProfile');
            }
        } else {
            return new PageReference('/VirtualEventLogin?id='+ eventId);
        }

    }
}