src/objects/EventApi__Attendee__c.object
<CustomObject>
    <description>Attendees track individuals registered for conference style or other &quot;registration&quot; style Events.</description>
    <fields>
        <fullName>EventApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related Contact. Required only if &quot;Require Contact Link for Attendees&quot; is checked on the parent Event.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventApi__Event__c</fullName>
        <description>** Required ** Master-detail link to event.</description>
        <inlineHelpText>** Required ** Master-detail link to event.</inlineHelpText>
        <label>Event</label>
        <referenceTo>EventApi__Event__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventApi__Event__c.object
<CustomObject>
    <description>Primary configuration object for all events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Meeting_Links__mdt.object
<CustomObject>
    <description>links for virtual meetings</description>
    <fields>
        <fullName>Check_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if computer check link is active</description>
        <label>Check IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Computer_Check_Link__c</fullName>
        <label>Computer Check Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Email_Template_Id__c</fullName>
        <description>Registration email template id</description>
        <label>Email Template Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Id__c</fullName>
        <label>Event Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if view link is active to users</description>
        <label>Event IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View_Link__c</fullName>
        <label>View Link</label>
        <type>Url</type>
    </fields>
    <label>Virtual Meeting Links</label>
    <pluralLabel>Virtual Meetings Links</pluralLabel>
</CustomObject>

src/classes/SendIndividualRegEmailControllerTest.cls
/**
 * Created by lauren.lezberg on 4/21/2020.
 */
@isTest
private with sharing class SendIndividualRegEmailControllerTest {

    @testSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('test account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;

        EventApi__Event__c evt = TestDataFactory.buildEvent();
        insert evt;

        EventApi__Attendee__c att = new EventApi__Attendee__c();
        att.EventApi__Contact__c = con.Id;
        att.EventApi__Event__c = evt.Id;
        insert att;
    }

    @isTest
    public static void test_getEventId(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'test account'];
        EventApi__Attendee__c att = [SELECT Id, EventApi__Event__c FROM EventApi__Attendee__c WHERE EventApi__Contact__c=: con.Id];

        User u = [SELECT Id FROM User WHERE ContactId=: con.Id];

        PermissionSet ps = new PermissionSet();
        ps.Name = 'Test';
        ps.Label = 'Test';
        insert ps;

        SetupEntityAccess sea = new SetupEntityAccess();
        sea.ParentId = ps.Id;
        sea.SetupEntityId = [SELECT Id, DeveloperName FROM CustomPermission WHERE DeveloperName = 'Send_Reg_Emails'][0].Id;
        insert sea;

        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = ps.Id;
        insert psa;

        Virtual_Meeting_Links__mdt vml = [SELECT Id FROM Virtual_Meeting_Links__mdt LIMIT 1];
        vml.DeveloperName='Virtual_Test_Event';
        vml.Event_Id__c = att.EventApi__Event__c;
        vml.View_Link__c = 'https://www.google.com';
        vml.Event_IsActive__c = false;
        vml.Computer_Check_Link__c = 'https://www.salesforce.com';
        vml.Check_IsActive__c = true;
        vml.Email_Template_Id__c = null;



        System.runAs(u) {
            Test.startTest();

            SendIndividualRegEmailController.virtualMeetings.add(vml);

            String eventId = SendIndividualRegEmailController.getEventId(att.Id);

            System.assertNotEquals(null, eventId);
            System.assertEquals(att.EventApi__Event__c, eventId);

            Test.stopTest();
        }
    }

    @isTest
    public static void test_sendEmail(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'test account'];
        EventApi__Attendee__c att = [SELECT Id, EventApi__Event__c FROM EventApi__Attendee__c WHERE EventApi__Contact__c=: con.Id];

        Test.startTest();

        Boolean response = SendIndividualRegEmailController.sendRegistrationEmail(att.EventApi__Event__c, con.Id,null);
        System.assertEquals(true, response);

        response = SendIndividualRegEmailController.sendRegistrationEmail(att.EventApi__Event__c, con.Id,att.Id);
        System.assertEquals(true, response);

        Test.stopTest();
    }
}