src/objects/Join_Process__mdt.object
<CustomObject>
    <description>Types of membership join/renewal processes</description>
    <fields>
        <fullName>Item__c</fullName>
        <description>List of items that can be processed for a particular join process</description>
        <label>Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Join Process</label>
    <pluralLabel>Join Processes</pluralLabel>
</CustomObject>

src/objects/OrderApi__Badge_Type__c.object
<CustomObject>
    <description>Configure Badge Types to assign to Contacts to allow greater control and flexibility around pricing and content accessibility.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked the Badge Type is active and available for assignment to a Contact</description>
        <inlineHelpText>When checked the Badge Type is active and available for assignment to a Contact</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Badge Type</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price__c</fullName>
        <description>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</description>
        <inlineHelpText>The default price for the item will be used to automatically create the default price rule which can only be edited by updating the price of the item.</inlineHelpText>
        <label>Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</description>
        <inlineHelpText>When checked, Items will be allowed to be linked to the Item Class. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Price_Rule__c.object
<CustomObject>
    <description>Flexible price rules allow you to configure custom price scenarios for items based on a variety of different rules.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Item Class -- only valid if the Price Rule is not linked to a Item. When linked to a Item Class the Price Rule will automatically be created for all Items created as a child of the Item Class.</description>
        <inlineHelpText>Link to the Item Class -- only valid if the Price Rule is not linked to a Item. When linked to a Item Class the Price Rule will automatically be created for all Items created as a child of the Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Default Price Rules</relationshipLabel>
        <relationshipName>Price_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The item the price rule record is assigning a price for.</description>
        <inlineHelpText>The item the price rule record is assigning a price for.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Pricing Rules</relationshipLabel>
        <relationshipName>Price_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price__c</fullName>
        <description>Enter the price for the pricing rule.</description>
        <inlineHelpText>Enter the price for the pricing rule.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OrderApi__Required_Badge_Types__c</fullName>
        <description>Comma separated list of Badge Types required to be considered eligible for the Price Rule.</description>
        <inlineHelpText>Comma separated list of Badge Types required to be considered eligible for the Price Rule.</inlineHelpText>
        <label>Required Badge Types</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Price Rule</label>
    <nameField>
        <label>Price Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Rules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Price_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The price rule related to the sales order line. When added or changed, the unit price will reflect the price defined on the price rule.</description>
        <inlineHelpText>The price rule related to the sales order line. When added or changed, the unit price will reflect the price defined on the price rule.</inlineHelpText>
        <label>Price Rule</label>
        <referenceTo>OrderApi__Price_Rule__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** The source Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated ** The source Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Sales Order Line (Source)</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JP_HelperTest.cls
/**
 * Created by lauren.lezberg on 2/1/2019.
 */
@isTest 
private with sharing class JP_HelperTest {

    @testSetup static void setup(){ 
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;
        Contact testContact = TestDataFactory.buildContactMemberCurrent(acc.Id);
        insert testContact;
        User u = TestDataFactory.buildUser(testContact.Id);
        insert u;
        OrderApi__Sales_Order__c so = TestDataFactory.buildOpenSalesOrder(acc.Id, testContact.Id);
        insert so;

        OrderApi__Item_Class__c itemClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert itemClass;
        OrderApi__Item__c item = TestDataFactory.buildItem(itemClass.Id, 'Active Membership');
        insert item;
        OrderApi__Item__c item2 = TestDataFactory.buildItem(itemClass.Id, 'Associate Membership');
        insert item2;

        OrderApi__Item_Class__c wgClass = TestDataFactory.buildItemClass('Working Groups');
        insert wgClass;
        OrderApi__Item__c wgItem = TestDataFactory.buildItem(wgClass.Id, 'Test Working Group');
        insert wgItem;

        OrderApi__Sales_Order_Line__c soLine = TestDataFactory.buildSOLine(so.Id, item.Id, itemClass.Id);
        insert soLine;
        OrderApi__Sales_Order_Line__c wgLine = TestDataFactory.buildSOLine(so.Id, wgItem.Id, wgClass.Id);
        insert wgLine;

        OrderApi__Badge_Type__c bt = TestDataFactory.buildBadgeType('Active Membership');
        insert bt;

        OrderApi__Price_Rule__c pr = new OrderApi__Price_Rule__c(OrderApi__Item__c = wgItem.Id, OrderApi__Required_Badge_Types__c = bt.Id, OrderApi__Price__c = 0.0, OrderApi__Is_Active__c = true);
        insert pr;

    }

    


    @isTest
    public static void testHandleLastAccessedStep(){
        Join_Process__mdt jp = [SELECT Id FROM Join_Process__mdt WHERE Item__c LIKE '%Active Membership%' AND Is_Renewal__c = false];
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        User userRecord = [SELECT Id FROM User WHERE ContactId =: testContact.Id LIMIT 1];
        System.runAs(userRecord){
            Decimal lasStepOrder = JP_Helper.getLastAccessedStepOrder(jp.Id);
            System.assertEquals(lasStepOrder,1.0);

            JP_Helper.deleteContactLastAccessedStep(jp.Id);
            List<contact_last_accessed_step__c> las = [SELECT Id FROM contact_last_accessed_step__c WHERE Contact__c=: testContact.Id AND JoinId__c =: jp.Id];
            System.assert(las.isEmpty(), 'Last accessed step should be empty');

            List<Process_Steps__mdt> steps = [SELECT Id FROM Process_Steps__mdt WHERE Process__c =: jp.Id ORDER BY Step_Order__c ];
            JP_Helper.upsertLastAccessedStep(steps[0].Id);
            las = [SELECT Id, Step_Order__c FROM contact_last_accessed_step__c WHERE Contact__c=: testContact.Id AND JoinId__c =: jp.Id];
            System.assert(!las.isEmpty(), 'Last accessed step should not be empty');
            System.assertEquals(1.0, las[0].Step_Order__c);

        }

    }


    @isTest
    public static void testGetMostRecentSO(){
        Contact testContact = [SELECT Id, AccountId FROM Contact LIMIT 1];
        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c LIMIT 1];

        Test.startTest();
        OrderApi__Sales_Order__c recentSO = JP_Helper.getMostRecentSO(testContact.Id);
        Test.stopTest();

        System.assertEquals(so.Id, recentSO.Id);
    }


    @isTest
    public static void testGetAndSavePortalItems(){
        Contact testContact = [SELECT Id, AccountId, MailingCountryCode FROM Contact LIMIT 1];
        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c LIMIT 1];
        Set<String> classNames = new Set<String>();
        classNames.add('Individual Memberships');
        List<Id> selectedItems = new List<Id>();

        OrderApi__Subscription_Plan__c subPlan = TestDataFactory.buildsubPlan();
        insert subPlan;



        Test.startTest();
        //get all portal items
        List<OrderApi__Item__c> items = JP_Helper.getPortalItemsByClass(classNames);
        System.assertEquals(2, items.size());

        OrderApi__Subscription__c sub = TestDataFactory.buildSubscription(testContact.Id, subPlan.Id, items[0].Id, items[0].OrderApi__Item_Class__c );
        insert sub;

        //get items price map
        Map<Id, Decimal> priceMap = JP_Helper.getItemPriceMap(items, testContact, null, null, null, so.Id);
        System.assertNotEquals(priceMap, null);

        //add items to selected list
        selectedItems.add(items[0].Id);
        selectedItems.add(items[1].Id);

        //save item selections as sales order lines
        JP_Helper.JPError returnMessage = JP_Helper.saveItemSelections(classNames, so.Id, selectedItems);
        Integer lines = [SELECT COUNT() FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c=: so.Id];
        System.assertEquals(returnMessage.isSuccess, true);
        System.assertEquals(3, lines);

        Test.stopTest();

    }

    @isTest
    public static void testCreateNewMemberSO(){
        Contact testContact = [SELECT Id, AccountId FROM Contact LIMIT 1];
        OrderApi__Item__c item = [SELECT Id, OrderApi__Business_Group__c, OrderApi__Item_Class__c FROM OrderApi__Item__c LIMIT 1];

        OrderApi__Sales_Order__c newSO = JP_Helper.createNewMemberSOWithLine(testContact, item);

        System.assertNotEquals(newSO, null);
    }

    @isTest
    public static void testCreateReinstateTransferSO(){
        Contact testContact = [SELECT Id, AccountId FROM Contact LIMIT 1];
        OrderApi__Item__c item = [SELECT Id, OrderApi__Business_Group__c, OrderApi__Item_Class__c FROM OrderApi__Item__c LIMIT 1];

        OrderApi__Sales_Order__c newSO = JP_Helper.createReinstateTransferSOWithLine(testContact, item);

        System.assertNotEquals(newSO, null);
    }

    @isTest
    public static void testCreateTransferSO(){
        Contact testContact = [SELECT Id, AccountId FROM Contact LIMIT 1];
        OrderApi__Item__c item = [SELECT Id, OrderApi__Business_Group__c, OrderApi__Item_Class__c FROM OrderApi__Item__c LIMIT 1];

        OrderApi__Sales_Order__c newSO = JP_Helper.createTransferSOWithLine(testContact, item);

        System.assertNotEquals(newSO, null);
    }



}