src/objects/Join_Process__mdt.object
<CustomObject>
    <description>Types of membership join/renewal processes</description>
    <label>Join Process</label>
    <pluralLabel>Join Processes</pluralLabel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GetTicketsController.cls
/**
 * Created by lauren.lezberg on 10/7/2019.
 */

public with sharing class GetTicketsController {

    /**
     * @purpose Checks if user has access to the back office ticketing system
     *
     * @return True or False
     */
    @AuraEnabled
    public static Boolean checkAccess(){
        System.debug('checkAccess: ' + FeatureManagement.checkPermission('Ticketing') );
        return FeatureManagement.checkPermission('Ticketing');
    }

    /**
     * @purpose Creates a sales order and retrieves correct join id
     *
     * @param contactId
     *
     * @return Instance of TicketingInfo class
     */
    @AuraEnabled
    public static TicketingInfo createBackOfficeTicketSO(Id contactId){
        OrderApi__Sales_Order__c SO = new OrderApi__Sales_Order__c(OrderApi__Contact__c=contactId);
        try {
            insert SO;
            List<Join_Process__mdt> joinProcesses = [SELECT Id FROM Join_Process__mdt WHERE DeveloperName = 'Back_Office_Ticketing' LIMIT 1];
            return new TicketingInfo(SO.Id, joinProcesses[0].Id);
        } catch(Exception e){
            System.debug('Could not create sales order: ' + e.getMessage());
        }
        return null;
    }

    public class TicketingInfo{
        @AuraEnabled
        public String salesOrderId;

        @AuraEnabled
        public String joinId;

        public TicketingInfo(String soId, String jId){
            this.salesOrderId = soId;
            this.joinId = jId;
        }

    }
}