src/objects/Meeting_Role__c.object
<CustomObject>
    <description>Roles for meetings dept per event</description>
    <fields>
        <fullName>AC_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AC Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Meeting Roles</relationshipLabel>
        <relationshipName>Meeting_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Meetings Manager</fullName>
                </value>
                <value>
                    <fullName>Meetings Associate/Coordinator</fullName>
                </value>
                <value>
                    <fullName>Registration Contact</fullName>
                </value>
                <value>
                    <fullName>Program Staff</fullName>
                </value>
                <value>
                    <fullName>Program Owner</fullName>
                </value>
                <value>
                    <fullName>Creative Services &amp; Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Meeting_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Meeting Role</label>
    <nameField>
        <label>Meeting Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meeting Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventRolesController.cls
/**
 * Created by lauren.lezberg on 6/17/2020.
 */

public with sharing class EventRolesController {

    @AuraEnabled
    public static List<Meeting_Role__c> getRoles(String eventId){
        return [SELECT Id, Role__c, User__c, User__r.Name, Primary__c FROM Meeting_Role__c WHERE AC_Event__c=: eventId ORDER BY Role__c DESC, Primary__c DESC];
    }

    @AuraEnabled
    public static Boolean deleteRole(String roleId){
        try{
            Database.delete(roleId);

            return true;
        } catch(Exception e){
            new AACRCustomException(roleId, e.getMessage(), e.getStackTraceString(), 'Event Roles');
            return false;
        }
    }
}