src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Prefix__c</fullName>
        <inlineHelpText>Community user visible code prefix. Limit to 4 characters. Example: GENE</inlineHelpText>
        <label>Prefix</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SourceCode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Code</label>
        <referenceTo>OrderApi__Source_Code__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OfferMembership__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Offer Memberships</relationshipLabel>
        <relationshipName>Offer_Memberships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OfferVersion__c</fullName>
        <label>Offer Version</label>
        <referenceTo>OfferVersion__c</referenceTo>
        <relationshipLabel>Offer Memberships</relationshipLabel>
        <relationshipName>Offer_Memberships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Memberships</relationshipLabel>
        <relationshipName>Offer_Memberships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SourceCode__c</fullName>
        <formula>Offer__r.SourceCode__r.Name</formula>
        <label>Source Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Used__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Used</label>
        <type>Checkbox</type>
    </fields>
    <label>Offer Membership</label>
    <nameField>
        <label>Offer Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OfferVersion__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <inlineHelpText>If Today&apos;s date lies on/between Start Date and End Date, the Offer Version will be Active</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <description>Lookup to the parent Offer record</description>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipLabel>Offer Versions</relationshipLabel>
        <relationshipName>Offer_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Use to override dates and make Offer Version Active</inlineHelpText>
        <label>Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publish__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Publish could be set to True when the Version is Active.  Then as days go by, the End Date could be in the past.  In this case the Publish will still be checked and Active would be False.</description>
        <inlineHelpText>Requires Active Offer Version</inlineHelpText>
        <label>Publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOQLQuery__c</fullName>
        <description>Recording of the SOQL query that the user entered to create this version</description>
        <inlineHelpText>Query needs to return User records.  Must also contain the ContactId field.  Example: [SELECT Id, ContactId FROM User LIMIT 2]</inlineHelpText>
        <label>SOQL Query</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <inlineHelpText>If Today&apos;s date lies on/between Start Date and End Date, the Offer Version will be Active</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Offer Version</label>
    <nameField>
        <label>Offer Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offer Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt__c.object
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</description>
        <inlineHelpText>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to related Sales Order.</description>
        <inlineHelpText>**System Calculated/Override** Link to related Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Source_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optional source code for the receipt. This will populate on all invoices related to the receipt. If a source code is already on an invoice the receipt is applied to, the original source code will not be updated with the value of the source code on the receipt.</description>
        <inlineHelpText>Populates on all invoices related to the receipt. If a source code is already assigned to an invoice the receipt is applied to, the invoice will not be updated with the new source code.</inlineHelpText>
        <label>Source Code</label>
        <referenceTo>OrderApi__Source_Code__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Source_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to Source Code.</description>
        <inlineHelpText>**System Calculated/Override** Link to Source Code.</inlineHelpText>
        <label>Source Code</label>
        <referenceTo>OrderApi__Source_Code__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/setContactAppStatusTest.cls
@IsTest
public class setContactAppStatusTest {

    @testSetup static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        OrderApi__Item_Class__c itemClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert itemClass;
        OrderApi__Item__c item = TestDataFactory.buildItem(itemClass.Id, 'Active Membership');
        insert item;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;
        OrderApi__Sales_Order__c so = TestDataFactory.buildOpenSalesOrder(acc.Id, con.Id);
        insert so;
        OrderApi__Sales_Order_Line__c sol = TestDataFactory.buildSOLine(so.Id, item.Id, itemClass.Id);
        insert sol;

        Contact member = TestDataFactory.buildContactMemberCurrent(acc.Id);
        insert member;
        OrderApi__Sales_Order__c so2 = TestDataFactory.buildOpenSalesOrder(acc.Id, member.Id);
        insert so2;
        OrderApi__Sales_Order_Line__c sol2 = TestDataFactory.buildSOLine(so.Id, item.Id, itemClass.Id);
        insert sol2;

        //Appeal codes for Opportunity
        Appeal_Code__c appealCode = new Appeal_Code__c(Name = 'Test Appeal Code');
        insert appealCode;

        OrderApi__Source_Code__c sc = TestDataFactory.buildSourceCode('WAIVE');
        insert sc;

        Offer__c o = new Offer__c(
                SourceCode__c = sc.Id,
                Prefix__c = 'BOGO'
        );
        insert o;

        OfferVersion__c ov = new OfferVersion__c(
                StartDate__c = Date.today(),
                EndDate__c = Date.today().addDays(7),
                Offer__c = o.Id,
                Name = 'OfferVersionName',
                Publish__c = true,
                Override__c = false,
                SOQLQuery__c = 'SELECT Id, ContactId FROM User WHERE IsActive=true AND ContactId!=null'
        );
        insert ov;

        OfferMembership__c om = new OfferMembership__c(
                Contact__c = con.Id,
                Offer__c = o.Id,
                Name = 'OfferMembersipName',
                OfferVersion__c = ov.Id,
                Used__c = false
        );
        insert om;
    }

    @IsTest
    public static void test_useOffer(){
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        OrderApi__Source_Code__c sc = [SELECT id FROM OrderApi__Source_Code__c LIMIT 1];
        OfferMembership__c om = [SELECT Id FROM OfferMembership__c WHERE Contact__c=:con.Id];
        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=: con.Id];
        so.OrderApi__Source_Code__c = sc.Id;
        so.Offer_Membership__c = om.Id;
        update so;

        OrderApi__Receipt__c receipt = new OrderApi__Receipt__c();
        receipt.OrderApi__Contact__c = con.Id;
        receipt.OrderApi__Sales_Order__c = so.Id;
        test.startTest();
        insert receipt;

        receipt.OrderApi__Is_Posted__c = true;
        update receipt;
        test.stopTest();

        om = [SELECT Id, Used__c FROM OfferMembership__c WHERE Contact__c=:con.Id];
        System.assertEquals(true, om.Used__c);

    }

    @IsTest static void testAppStatus(){
        Contact con = [SELECT Id FROM Contact WHERE RecordType.Name='Nonmember' LIMIT 1];
        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=: con.Id];
        OrderApi__Receipt__c receipt = new OrderApi__Receipt__c();
        receipt.OrderApi__Contact__c = con.Id;
        receipt.OrderApi__Sales_Order__c = so.Id;
        test.startTest();
        insert receipt;
        test.stopTest();

        con = [SELECT Application_Status__c FROM Contact WHERE Id=: con.Id];
        System.assertEquals('Pending Approval', con.Application_Status__c);

    }

    @IsTest static void testAppStatusTransfer(){
        Contact con = [SELECT Id FROM Contact WHERE RecordType.Name='Member' LIMIT 1];

        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=: con.Id];
        so.OrderApi__Description__c = 'Transfer Application';
        update so;
        OrderApi__Receipt__c receipt = new OrderApi__Receipt__c();
        receipt.OrderApi__Contact__c = con.Id;
        receipt.OrderApi__Sales_Order__c = so.Id;
        test.startTest();
        insert receipt;
        test.stopTest();

        con = [SELECT Application_Status__c FROM Contact WHERE Id=: con.Id];
        System.assertEquals(null, con.Application_Status__c);

    }
}