src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is item type managed or unmanaged</description>
        <label>Managed</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Subscription_Plan__c.object
<CustomObject>
    <description>Links a &quot;Subscription&quot; Item to a Subscription Plan to enable the linked Item to be sold in conjunction with the linked Subscription Plan.</description>
    <fields>
        <fullName>OrderApi__Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines the default Subscription Plan for related Item.</description>
        <inlineHelpText>Defines the default Subscription Plan for related Item.</inlineHelpText>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <description>** Required ** Link to the Item enabled for the related Subscription Plan.</description>
        <inlineHelpText>** Required ** Link to the Item enabled for the related Subscription Plan.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscription Plans</relationshipLabel>
        <relationshipName>Subscription_Plan_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <description>** Required ** Link to the Subscription Plan that the related Subscription Item is being enabled for.</description>
        <inlineHelpText>** Required ** Link to the Subscription Plan that the related Subscription Item is being enabled for.</inlineHelpText>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Subscription_Plan_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Item Subscription Plan</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Item Subscription Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Subscription Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</inlineHelpText>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Subscription that is being upgraded or renewed.</description>
        <inlineHelpText>Link to the Subscription that is being upgraded or renewed.</inlineHelpText>
        <label>Subscription (Upgrade/Renew)</label>
        <referenceTo>OrderApi__Subscription__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Current_Term_End_Date__c</fullName>
        <description>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</inlineHelpText>
        <label>Current Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Paid_Through_Date__c</fullName>
        <description>Defines the last active date of the subscription including all subscription renewals.</description>
        <inlineHelpText>Defines the last active date of the subscription including all subscription renewals.</inlineHelpText>
        <label>Paid Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>OrderApi__Advanced_Calendar_Days__c</fullName>
        <description>Number of days before the start of the next calendar term, during which new subscriptions are automatically extended to include the next term.</description>
        <inlineHelpText>Number of days before the start of the next calendar term, during which new subscriptions are automatically extended to include the next term.</inlineHelpText>
        <label>Advanced Calendar Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrderApi__Type__c</fullName>
        <description>** Required ** Select the most appropriate option for the Subscription Plan Type.</description>
        <inlineHelpText>** Required ** Select the most appropriate option for the Subscription Plan Type.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calendar</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Lifetime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to hold dues renewal information and configurations</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Are renewals active (turned on)</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term_Year__c</fullName>
        <description>Renewal Term Year</description>
        <label>Term Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Renewal Settings</label>
</CustomObject>

src/classes/BackOfficeOrderController.cls
/**
 * Created by lauren.lezberg on 8/23/2019.
 */

public with sharing class BackOfficeOrderController {


    @AuraEnabled
    public static List<TermOptions> getTermOptions(String membershipItemId, String salesOrderId, Boolean isRenew){

        Renewal_Settings__c renewalProcess = Renewal_Settings__c.getInstance();
        List<OrderApi__Item_Subscription_Plan__c> subPlans = [SELECT Id, OrderApi__Subscription_Plan__c, OrderApi__Subscription_Plan__r.OrderApi__Type__c, OrderApi__Subscription_Plan__r.OrderApi__Advanced_Calendar_Days__c, OrderApi__Is_Default__c FROM OrderApi__Item_Subscription_Plan__c WHERE OrderApi__Item__c=:membershipItemId ORDER BY OrderApi__Subscription_Plan__r.OrderApi__Type__c, OrderApi__Subscription_Plan__r.OrderApi__Advanced_Calendar_Days__c ASC];
        List<TermOptions> termOpts = new List<TermOptions>();
        if(!isRenew) {
            //unmanaged memberships
            if (subPlans.size() == 1) {
                if(subPlans[0].OrderApi__Subscription_Plan__r.OrderApi__Type__c=='Lifetime'){
                    termOpts.add(new TermOptions(subPlans[0].OrderApi__Subscription_Plan__c, 'Lifetime'));
                } else {
                    termOpts.add(new TermOptions(subPlans[0].OrderApi__Subscription_Plan__c, String.valueOf(System.now().year())));
                }
            } else {
                termOpts.add(new TermOptions(subPlans[0].OrderApi__Subscription_Plan__c, String.valueOf(System.now().year())));
                termOpts.add(new TermOptions(subPlans[0].OrderApi__Subscription_Plan__c, String.valueOf(Integer.valueOf(renewalProcess.Term_Year__c))));
                termOpts.add(new TermOptions(subPlans[1].OrderApi__Subscription_Plan__c, String.valueOf(System.now().year() + ' - ' + Integer.valueOf(renewalProcess.Term_Year__c))));
            }
        } else {
            System.debug('is renewal');
            OrderApi__Sales_Order__c SO = [SELECT OrderApi__Contact__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId LIMIT 1];
            List<OrderApi__Subscription__c> memSubs = RenewalUtils.getIndividualMembershipSubscription(SO.OrderApi__Contact__c);
            Boolean canCatchUp = (Integer)renewalProcess.Term_Year__c - 1 == System.now().year() && memSubs[0].OrderApi__Current_Term_End_Date__c.year() < renewalProcess.Term_Year__c - 1;
            System.debug('canCatchUp: ' + canCatchUp);
            if(canCatchUp) {
                termOpts.add(new TermOptions(subPlans[0].OrderApi__Subscription_Plan__c, String.valueOf(System.now().year())));
                termOpts.add(new TermOptions(subPlans[1].OrderApi__Subscription_Plan__c, String.valueOf(Integer.valueOf(renewalProcess.Term_Year__c))));
            }

            if(renewalProcess.Is_Active__c || !memSubs[0].OrderApi__Item__r.Managed__c){
                System.debug('renewal process is active or item is unmanaged');
                if(memSubs[0].OrderApi__Paid_Through_Date__c.year() == System.now().year()){ // if paid through date is current
                    System.debug('PTD is current');
                    termOpts.add(new TermOptions(subPlans[0].OrderApi__Subscription_Plan__c, String.valueOf(System.now().year() + 1)));
                }
            }
        }
        return termOpts;
    }



    /**
     * @purpose Retrieves sales order information as well as available terms and renewal information
     *
     * @param salesOrderId
     *
     * @return BackOfficeOrderData
     */
    @AuraEnabled
    public static BackOfficeOrderData getBackOfficeData(String salesOrderId, Boolean isRenew){
        System.debug('getBackOfficeData was just called with salesOrderId: ' + salesOrderId);
        Renewal_Settings__c renewalProcess = Renewal_Settings__c.getInstance();
        List<OrderApi__Sales_Order_Line__c> lines = ECRMUtils.getAllSalesOrderLines(salesOrderId);
        List<TermOptions> termOpts = new List<TermOptions>();
        if(lines.size()>0){
            for(OrderApi__Sales_Order_Line__c line: lines){
                if(line.OrderApi__Item_Class__r.Name == 'Individual Memberships'){
                    termOpts = getTermOptions(line.OrderApi__Item__c, salesOrderId, isRenew);
                }
            }

        }
//        List<OrderApi__Subscription_Plan__c> subPlans = [SELECT Id, Name FROM OrderApi__Subscription_Plan__c WHERE OrderApi__Is_Active__c = true AND (Show_In_Portal__c=true OR OrderApi__Advanced_Calendar_Days__c=365) ORDER BY Name];
//        List<TermOptions> termOpts = new List<TermOptions>();
//        String subPlanId = null;
//
//        if(!isRenew) { // is not renewal
//            termOpts.add(new TermOptions(subPlans[0].Id, String.valueOf(System.now().year())));
//            termOpts.add(new TermOptions(subPlans[0].Id, String.valueOf(Integer.valueOf(renewalProcess.Term_Year__c))));
//            termOpts.add(new TermOptions(subPlans[1].Id, String.valueOf(System.now().year() + ' - ' + Integer.valueOf(renewalProcess.Term_Year__c))));
//        } else { // is renewal
//            System.debug('is renewal');
//            OrderApi__Sales_Order__c SO = [SELECT OrderApi__Contact__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId LIMIT 1];
//            List<OrderApi__Subscription__c> memSubs = RenewalUtils.getIndividualMembershipSubscription(SO.OrderApi__Contact__c);
//            Boolean canCatchUp = (Integer)renewalProcess.Term_Year__c - 1 == System.now().year() && memSubs[0].OrderApi__Current_Term_End_Date__c.year() < renewalProcess.Term_Year__c - 1;
//            if(canCatchUp) {
//                termOpts.add(new TermOptions(subPlans[0].Id, String.valueOf(System.now().year())));
//                termOpts.add(new TermOptions(subPlans[1].Id, String.valueOf(Integer.valueOf(renewalProcess.Term_Year__c))));
//            }
//
//            if(renewalProcess.Is_Active__c){
//                if(memSubs[0].OrderApi__Paid_Through_Date__c.year() == System.now().year()){ // if paid through date is current
//                    termOpts.add(new TermOptions(subPlans[0].Id, String.valueOf(Integer.valueOf(renewalProcess.Term_Year__c))));
//                }
//            }
//
//        }


        return new BackOfficeOrderData(lines, renewalProcess.Is_Active__c, termOpts);
    }


    /**
     * @purpose Adds a selected to item to a specified sales order with the specified subscription plan and activation date. Based on the subscription plan and activation date, the correct GL will be used.
     *
     * @param itemId
     * @param subPlanId
     * @param futureEndDate
     * @param salesOrderId
     *
     * @return List of all sales order lines including added line
     */
    @AuraEnabled
    public static List<OrderApi__Sales_Order_Line__c> addSelectedItem(String itemId, String subPlanId, Boolean futureEndDate, String salesOrderId){
        System.debug('adding selected item: ' + itemId );
        return OrderEntryFormController.addSelectedItem(itemId, subPlanId, futureEndDate, salesOrderId);
    }


    /**
     * @purpose Removes a sales order line from the specified sales order based on the item
     *
     * @param itemId
     * @param salesOrderId
     *
     * @return List of all remaining sales order lines
     */
    @AuraEnabled
    public static List<OrderApi__Sales_Order_Line__c> removeItem(String itemId, String salesOrderId){
        return OrderEntryFormController.removeItem(itemId, salesOrderId);
    }


    /**
     * @purpose Changes term(subscription plan) for all sales order lines in the specified sales order based on the given subscription plan id and term end date.
     * If the term is changed to a 2YR term, the sales order is updated to be an Is2YR sales order and vice versa for a term change to 1YR
     *
     * @param subPlanId
     * @param futureEndDate
     * @param salesOrderId
     *
     * @return List of all updated sales order lines
     */
    @AuraEnabled
    public static List<OrderApi__Sales_Order_Line__c> changeTerm(String subPlanId, Boolean futureEndDate, String salesOrderId ){
        OrderApi__Subscription_Plan__c subPlan = [SELECT OrderApi__Advanced_Calendar_Days__c FROM OrderApi__Subscription_Plan__c WHERE Id=: subPlanId];

        OrderApi__Sales_Order__c so = [SELECT Id, Is2YR__c FROM OrderApi__Sales_Order__c WHERE Id=: salesOrderId];
        if(subPlan.OrderApi__Advanced_Calendar_Days__c == 365){
            so.Is2YR__c = true;
        } else {
            so.Is2YR__c = false;
        }
        update so;

        Renewal_Settings__c renewalProcess = Renewal_Settings__c.getInstance();

        ECRMUtils.changeSubscriptionTerm(subPlan.Id, salesOrderId, futureEndDate?String.valueOf(renewalProcess.Term_Year__c):String.valueOf(Date.today().year()));

        return ECRMUtils.getAllSalesOrderLines(salesOrderId);
    }

    //Consolidation of back office order data
    public class BackOfficeOrderData{
        @AuraEnabled
        public List<OrderApi__Sales_Order_Line__c> lines;

        @AuraEnabled
        public Boolean renewalsOpen;

        @AuraEnabled
        public List<TermOptions> subscriptionPlans;


        public BackOfficeOrderData(List<OrderApi__Sales_Order_Line__c> lines, Boolean isOpen, List<TermOptions> subPlans){
            this.lines = lines;
            this.renewalsOpen = isOpen;
            this.subscriptionPlans = subPlans;
        }

    }

    //term option data
    public class TermOptions{
        @AuraEnabled
        public String subPlanId;

        @AuraEnabled
        public String termYear;

        public TermOptions(String subPlan, String termYear){
            this.subPlanId = subPlan;
            this.termYear = termYear;
        }
    }
}