src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Known_Address__c.object
<CustomObject>
    <description>Known Addresses allows Contacts and Accounts to have multiple related address records.</description>
    <fields>
        <fullName>OrderApi__City__c</fullName>
        <description>Address City</description>
        <inlineHelpText>Address City</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the known address to a contact.</description>
        <inlineHelpText>Relates the known address to a contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Known Addresses</relationshipLabel>
        <relationshipName>Known_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Country__c</fullName>
        <description>Address Country</description>
        <inlineHelpText>Address Country</inlineHelpText>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Province__c</fullName>
        <description>Address State</description>
        <inlineHelpText>Address State</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Street__c</fullName>
        <description>Address Street</description>
        <inlineHelpText>Address Street</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Known Address</label>
    <nameField>
        <displayFormat>KA-{000000000}</displayFormat>
        <label>Known Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt__c.object
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</description>
        <inlineHelpText>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to related Sales Order.</description>
        <inlineHelpText>**System Calculated/Override** Link to related Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt_Line__c.object
<CustomObject>
    <description>Receipt Lines apply cash related to either refunds or payments to Invoices or Items.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated to show the related contact.</description>
        <inlineHelpText>This field is populated to show the related contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**Required** Link to related Item.</description>
        <inlineHelpText>**Required** Link to related Item.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Posting_Status__c</fullName>
        <description>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</description>
        <inlineHelpText>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>The status of the Sales Order.</description>
        <inlineHelpText>The status of the Sales Order.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</description>
        <inlineHelpText>Sales Order Lines that link to &quot;Package&quot; Items will include the Items into the Sales Order as new Sales Order Lines which will have a parent/child relationship with the Sales Order Line that links to the &quot;Package&quot; Item.</inlineHelpText>
        <label>Parent Sales Order Line</label>
        <referenceTo>OrderApi__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StripePaymentControllerTest.cls
/**
 * Created by lauren.lezberg on 12/4/2020.
 */

@IsTest
private class StripePaymentControllerTest {

    @TestSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        OrderApi__Known_Address__c billingAddress = new OrderApi__Known_Address__c(Type__c='Billing', OrderApi__Contact__c=con.Id, OrderApi__Street__c='123 Main St', OrderApi__City__c='TEST', OrderApi__Province__c='PA', OrderApi__Country__c='United States');
        insert billingAddress;

        Appeal_Code__c appealCode = new Appeal_Code__c(Name = 'Test Appeal Code');
        insert appealCode;

        //adding membership item
        OrderApi__Item_Class__c itemClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert itemClass;
        OrderApi__Item__c item = TestDataFactory.buildItem(itemClass.Id, 'Active Membership');
        insert item;

        //create sales order and sales order lines
        OrderApi__Sales_Order__c so = TestDataFactory.buildOpenSalesOrder(acc.Id, con.Id);
        so.OrderApi__Status__c = 'Closed';
        so.OrderApi__Posting_Status__c = 'Posted';
        insert so;
        OrderApi__Sales_Order_Line__c soLine1 = TestDataFactory.buildSOLine(so.Id, item.Id, itemClass.Id);
        soLine1.OrderApi__Sale_Price__c = 315.00;
        soLine1.OrderApi__Price_Override__c = true;
        insert soLine1;

        OrderApi__Store__c eStore = new OrderApi__Store__c(Name='AACR eStore');
        insert eStore;
    }


    @IsTest
    public static void test_initialize(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Item__c item = [SELECT Id FROM OrderApi__Item__c LIMIT 1];

        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];
        so.Payment_Intent_Id__c = '1234567890';
        update so;


        Test.startTest();
        PageReference pageRef = Page.JP_Container;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id','123456');
        ApexPages.currentPage().getParameters().put('salesOrder',so.Id);


        StripePaymentController ctrl = new StripePaymentController();

        so.OrderApi__Status__c = 'Closed';
        so.OrderApi__Posting_Status__c = 'Posted';
        update so;

        ctrl = new StripePaymentController();

        Test.stopTest();
    }

    @IsTest
    public static void test_createNewPaymentIntent(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];

        Test.startTest();
        PageReference pageRef = Page.JP_Container;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id','123456');
        ApexPages.currentPage().getParameters().put('salesOrder',so.Id);

        Test.setMock(HttpCalloutMock.class, new CreateMockHttpResponseGenerator());

        StripePaymentController ctrl = new StripePaymentController();
        ctrl.createPaymentIntent();
        System.assertEquals(ctrl.piSecret!=null, true);

        Test.stopTest();
    }

    @IsTest
    public static void test_getOldPaymentIntent(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];
        so.Payment_Intent_Id__c = '1234567890';
        update so;

        Test.startTest();
        PageReference pageRef = Page.JP_Container;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id','123456');
        ApexPages.currentPage().getParameters().put('salesOrder',so.Id);

        Test.setMock(HttpCalloutMock.class, new CreateMockHttpResponseGenerator());

        StripePaymentController ctrl = new StripePaymentController();
        ctrl.createPaymentIntent();
        System.assertEquals(ctrl.piSecret!=null, true);

        Test.stopTest();
    }


    @IsTest
    public static void test_finalizePayment(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];

        Test.startTest();
        PageReference pageRef = Page.JP_Container;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id','123456');
        ApexPages.currentPage().getParameters().put('salesOrder',so.Id);
        ApexPages.currentPage().getParameters().put('pmID', 'pm_1234567890');

        Test.setMock(HttpCalloutMock.class, new CreateMockHttpResponseGenerator());

        StripePaymentController ctrl = new StripePaymentController();
        ctrl.finalizePayment();
        System.assertEquals(true, ctrl.processed);


        Test.stopTest();
    }

//    @IsTest
//    public static void test_processRefund(){
//        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];
//
//        OrderApi__Item__c item = [SELECT Id FROM OrderApi__Item__c LIMIT 1];
//
//        OrderApi__Sales_Order__c so = [SELECT Id, OrderApi__Total__c FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];
//        so.Payment_Intent_Id__c = '1234567890';
//        update so;
//
//        OrderApi__Receipt__c receipt = new OrderApi__Receipt__c(OrderApi__Sales_Order__c= so.Id, OrderApi__Contact__c=con.Id);
//        insert receipt;
//
//        OrderApi__Receipt_Line__c recLine = new OrderApi__Receipt_Line__c(OrderApi__Receipt__c=receipt.Id, OrderApi__Item__c=item.Id);
//        insert recLine;
//
//        Test.startTest();
//
//        Test.setMock(HttpCalloutMock.class, new CreateMockHttpResponseGenerator());
//
//        StripePaymentController.StripeDTO resp = RefundRequestController.processRefund(receipt.Id, so.OrderApi__Total__c);
//        System.assertEquals(true, resp.success);
//
//
//        Test.stopTest();
//    }

    @IsTest
    public static void test_Refund(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Item__c item = [SELECT Id FROM OrderApi__Item__c LIMIT 1];

        OrderApi__Sales_Order__c so = [SELECT Id, OrderApi__Total__c FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];
        so.Payment_Intent_Id__c = '1234567890';
        update so;

        OrderApi__Receipt__c receipt = new OrderApi__Receipt__c(OrderApi__Sales_Order__c= so.Id, OrderApi__Contact__c=con.Id);
        insert receipt;

        OrderApi__Receipt_Line__c recLine = new OrderApi__Receipt_Line__c(OrderApi__Receipt__c=receipt.Id, OrderApi__Item__c=item.Id);
        insert recLine;

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new CreateMockHttpResponseGenerator());

        StripePaymentController.StripeDTO resp = StripePaymentController.createStripeRefund('1234567890',receipt.Id, 315.00);
        System.assertEquals(true, resp.success);


        resp=StripePaymentController.getStripeRefund('392482394827934');
        System.assertEquals(true, resp.success);


        Test.stopTest();
    }

    @IsTest
    public static void test_RefundFailure(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Item__c item = [SELECT Id FROM OrderApi__Item__c LIMIT 1];

        OrderApi__Sales_Order__c so = [SELECT Id, OrderApi__Total__c FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];
        so.Payment_Intent_Id__c = '1234567890';
        update so;

        OrderApi__Receipt__c receipt = new OrderApi__Receipt__c(OrderApi__Sales_Order__c= so.Id, OrderApi__Contact__c=con.Id);
        insert receipt;

        OrderApi__Receipt_Line__c recLine = new OrderApi__Receipt_Line__c(OrderApi__Receipt__c=receipt.Id, OrderApi__Item__c=item.Id);
        insert recLine;

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new FailureMockHttpResponseGenerator());

        StripePaymentController.StripeDTO resp = StripePaymentController.createStripeRefund('1234567890',receipt.Id, 315.00);
        System.assertEquals(false, resp.success);


        resp=StripePaymentController.getStripeRefund('392482394827934');
        System.assertEquals(false, resp.success);


        Test.stopTest();
    }

    @IsTest
    public static void test_failureCallouts(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name = 'Test Account'];

        OrderApi__Sales_Order__c so = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];

        Test.startTest();
        PageReference pageRef = Page.JP_Container;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id','123456');
        ApexPages.currentPage().getParameters().put('salesOrder',so.Id);

        Test.setMock(HttpCalloutMock.class, new FailureMockHTTPResponseGenerator());

        StripePaymentController ctrl = new StripePaymentController();
        ctrl.createPaymentIntent();
        ctrl.finalizePayment();


        Test.stopTest();
    }

    public class CreateMockHTTPResponseGenerator implements HttpCalloutMock{
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            res.setBody('{"id": "1234567890", "client_secret": "83459843758947594", "status":"succeeded", "card" : {"last4": "4242", "brand":"visa", "exp_year" : "2050", "exp_month" : "4" }}');
            res.setStatusCode(200);
            return res;
        }
    }

    public class FailureMockHTTPResponseGenerator implements HttpCalloutMock{
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            res.setBody('{"error": {"message": "FAIL"}}');
            res.setStatusCode(402);
            return res;
        }
    }
}