src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GetTicketsControllerTest.cls
/**
 * Created by lauren.lezberg on 10/11/2019.
 */
@isTest
private with sharing class GetTicketsControllerTest {

    @testSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;



    }

    @isTest
    public static void test_checkAccess(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name='Test Account'];
        User u = [SELECT Id FROM User WHERE ContactId=:con.Id];

        Test.startTest();

        Boolean hasAccess = GetTicketsController.checkAccess();
        System.assertEquals(true, hasAccess);

        System.runAs(u){
            hasAccess = GetTicketsController.checkAccess();
            System.assertEquals(false, hasAccess);
        }

        Test.stopTest();

    }

    @isTest
    public static void test_createTicketSalesOrder(){
        Contact con = [SELECT Id FROM Contact WHERE Account.Name='Test Account'];

        Test.startTest();
        GetTicketsController.TicketingInfo tInfo = GetTicketsController.createBackOfficeTicketSO(con.Id);
        System.assert(tInfo!=null,'Ticket Info should not be null');
        System.assert(tInfo.salesOrderId!=null,'SalesOrderId should not be null');
        System.assert(tInfo.joinId!=null,'JoinId should not be null');

        OrderApi__Sales_Order__c SO = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id];
        System.assert(SO!=null, 'Contact should have a sales order');
        System.assertEquals(SO.Id, tInfo.salesOrderId);

        Test.stopTest();
    }
}