src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_In_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Display Item as selectable in portal</description>
        <label>Show In Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>Show_In_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show record in portal to users</description>
        <label>Show In Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MembershipCategoriesControllerTest.cls
/**
 * Created by lauren.lezberg on 12/11/2018.
 */

@IsTest
private class MembershipCategoriesControllerTest { 
    @testSetup static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;
        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;
        User u = TestDataFactory.buildUser(con.Id);
        insert u;

        OrderApi__Item_Class__c itemClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert itemClass;
        OrderApi__Item__c item1 = TestDataFactory.buildItem(itemClass.Id, 'Active Membership');
        item1.Show_In_Portal__c = true;
        insert item1;
        OrderApi__Item__c item2 = TestDataFactory.buildItem(itemClass.Id, 'Affiliate Membership');
        item2.Show_In_Portal__c = true;
        insert item2;
        OrderApi__Item__c item3 = TestDataFactory.buildItem(itemClass.Id, 'Associate Membership');
        item3.Show_In_Portal__c = true;
        insert item3;
        OrderApi__Item__c item4 = TestDataFactory.buildItem(itemClass.Id, 'Student Membership');
        item4.Show_In_Portal__c = true;
        insert item4;
        OrderApi__Item__c item5 = TestDataFactory.buildItem(itemClass.Id, 'Emeritus Membership');
        item5.Show_In_Portal__c = false;
        insert item5;

        OrderApi__Item_Class__c journalClass = TestDataFactory.buildItemClass('Journal Subscriptions');
        insert journalClass;
        OrderApi__Item__c bloodCancerJournal = TestDataFactory.buildItem(journalClass.Id, 'Blood Cancer Discovery - Online');
        insert bloodCancerJournal;

        OrderApi__Subscription_Plan__c subPlan1 = TestDataFactory.buildsubPlan();
        insert subPlan1;

        OrderApi__Subscription__c memSub = TestDataFactory.buildSubscription(con.Id, subPlan1.Id, item1.Id, itemClass.Id);
        insert memSub;


    }


    @isTest
    static void test_getMembershipItems() {
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        User u = [SELECT Id FROM User WHERE ContactId =: con.Id];


        System.runAs(u) {
            Test.startTest();
            List<OrderApi__Item__c> items = MembershipCategoriesController.getMembershipItems(false);
            System.assert(items != null, 'List of items is not null');
            System.assert(items.size() == 4, 'Method should return 4 items');

            items = MembershipCategoriesController.getMembershipItems(true);
            System.assert(items != null, 'List of items is not null');
            System.assert(items.size() == 1, 'Method should return 1 items');

            Test.stopTest();
        }
    }

    @isTest
    static void test_startNewMemberApplication(){
        OrderApi__Item__c membershipItem = [SELECT Id FROM OrderApi__Item__c LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        User u = [SELECT Id FROM User WHERE ContactId =: con.Id];

        System.runAs(u){
            String response = MembershipCategoriesController.startNewMemberApplication(membershipItem.Id);
            System.assertNotEquals(null, response);
        }
    }

    @isTest
    static void test_startTransferApplication(){
        OrderApi__Item__c membershipItem = [SELECT Id FROM OrderApi__Item__c LIMIT 1];
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        User u = [SELECT Id FROM User WHERE ContactId =: con.Id];

        System.runAs(u){
            String response = MembershipCategoriesController.startTransferApplication(membershipItem.Id);
            System.assertNotEquals(null, response);
        }
    }
}