src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>Marked_For_Delete__c</fullName>
        <formula>AND( NOT(OrderApi__Is_Posted__c), TODAY() - DATEVALUE( CreatedDate ) &gt; 30, ISPICKVAL(OrderApi__Status__c, &apos;Closed&apos;) )</formula>
        <label>Marked For Delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Posting_Status__c</fullName>
        <description>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</description>
        <inlineHelpText>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>The status of the Sales Order.</description>
        <inlineHelpText>The status of the Sales Order.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_DeleteUnpostedSO.cls
public class Batch_DeleteUnpostedSO implements Database.Batchable<sObject>,Database.Stateful{
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
//        String queryString = 'SELECT Id, OrderApi__Contact__c, Name FROM OrderApi__Sales_Order__c WHERE Marked_For_Delete__c = TRUE';
        String queryString;
        /** can't update lastmodifieddate in test class **/
        if(!Test.isRunningTest()){
            queryString = 'SELECT Id, OrderApi__Contact__c, Name FROM OrderApi__Sales_Order__c WHERE OrderApi__Posting_Status__c != \'Posted\' AND (OrderApi__Status__c = \'Cancelled\' OR OrderApi__Status__c = \'Open\') AND LastModifiedDate < LAST_N_DAYS:90';
        } else {
            queryString = 'SELECT Id, OrderApi__Contact__c, Name FROM OrderApi__Sales_Order__c WHERE OrderApi__Posting_Status__c != \'Posted\' AND (OrderApi__Status__c = \'Cancelled\' OR OrderApi__Status__c = \'Open\') AND CreatedDate < LAST_N_DAYS:90';
        }
        return Database.getQueryLocator(queryString);
    }

    public void execute(Database.BatchableContext BC, List<OrderApi__Sales_Order__c> scope){
        if(scope.size() > 0) {
            delete scope;
        } 
    }

    public void finish(Database.BatchableContext BC){
        AsyncApexJob job;
        List<AsyncApexJob> jobs = [SELECT Id, NumberOfErrors, Status, JobItemsProcessed FROM AsyncApexJob WHERE Id =: BC.getJobId()];
        if(jobs.size()==1){
           job = jobs[0];
        }
        System.debug(LoggingLevel.DEBUG, 'Batch_DeleteUnpostedSO processed ' + job.JobItemsProcessed + ' records with a status of ' + job.Status + ' and ' + job.NumberOfErrors + ' errors ');
    }
    

}