src/objects/OrderApi__Invoice__c.object
<CustomObject>
    <description>Invoices track sales to customers that are not immediately paid for.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the Sales Order that generated the Invoice.</description>
        <inlineHelpText>**System Calculated/Override** Link to the Sales Order that generated the Invoice.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <description>**System Calculated** Subtotal + Adjustments + Sales Tax</description>
        <formula>OrderApi__Subtotal__c + OrderApi__Adjustments__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>**System Calculated** Subtotal + Adjustments + Sales Tax</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt__c.object
<CustomObject>
    <description>Receipts track Customer Payments and Refunds.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</description>
        <inlineHelpText>**System Calculated/Override/Required** The contact the payment was received from or the refund is being sent to.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Refund__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked when the Receipt is for a customer refund</description>
        <inlineHelpText>Checked when the Receipt is for a customer refund</inlineHelpText>
        <label>Is Refund</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Payment_Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to payment gateway, populates automatically for all epayment transactions.</description>
        <inlineHelpText>Lookup to payment gateway, populates automatically for all epayment transactions.</inlineHelpText>
        <label>Payment Gateway</label>
        <referenceTo>OrderApi__Payment_Gateway__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Payment_Type__c</fullName>
        <description>**Required** The payment type (Check, Credit Card, EFT, or Other).</description>
        <inlineHelpText>**Required** The payment type (Check, Credit Card, EFT, or Other).</inlineHelpText>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                    <default>true</default>
                    <label>Check</label>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>EFT</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Caluclated** Lookup to the reciept for which you are refunding.</description>
        <inlineHelpText>**System Caluclated** Lookup to the reciept for which you are refunding.</inlineHelpText>
        <label>Receipt</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>OrderApi__Receipt__c.OrderApi__Is_Payment__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OrderApi__Receipt__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to related Sales Order.</description>
        <inlineHelpText>**System Calculated/Override** Link to related Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>**Conditionally Required** Receipt Total, required to post receipt to GL (Transactions).</description>
        <inlineHelpText>**Conditionally Required** Receipt Total, required to post receipt to GL (Transactions).</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Stripe_Payment_Intent_Id__c</fullName>
        <label>Stripe Payment Intent Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Receipt_Line__c.object
<CustomObject>
    <description>Receipt Lines apply cash related to either refunds or payments to Invoices or Items.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is populated to show the related contact.</description>
        <inlineHelpText>This field is populated to show the related contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipt Lines</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related Invoice that the customer is paying.</description>
        <inlineHelpText>Link to related Invoice that the customer is paying.</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>OrderApi__Invoice__c</referenceTo>
        <relationshipLabel>Payments &amp; Refunds</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Refund__c</fullName>
        <description>**System Calculated** Checked when the parent Receipt is a &quot;Refund&quot;</description>
        <formula>ISPICKVAL(OrderApi__Receipt__r.OrderApi__Type__c,&quot;Refund&quot;)</formula>
        <inlineHelpText>**System Calculated** Checked when the parent Receipt is a &quot;Refund&quot;</inlineHelpText>
        <label>Is Refund</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**Required** Link to related Item.</description>
        <inlineHelpText>**Required** Link to related Item.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Receipt_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to related parent Receipt Line.</description>
        <inlineHelpText>Link to related parent Receipt Line.</inlineHelpText>
        <label>Parent Receipt Line</label>
        <referenceTo>OrderApi__Receipt_Line__c</referenceTo>
        <relationshipLabel>Packaged Items</relationshipLabel>
        <relationshipName>Receipt_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Receipt__c</fullName>
        <description>**Required** All Receipt details require a parent receipt that summarizes all receipt lines.</description>
        <inlineHelpText>**Required** All Receipt details require a parent receipt that summarizes all receipt lines.</inlineHelpText>
        <label>Receipt</label>
        <referenceTo>OrderApi__Receipt__c</referenceTo>
        <relationshipName>Receipt_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Sale_Price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>**System Calculated/Override** The Sale Price (per unit) for the related Item. Default 0.00.</description>
        <inlineHelpText>**System Calculated/Override** The Sale Price (per unit) for the related Item. Default 0.00.</inlineHelpText>
        <label>Sale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>**Required** Total amount for the Receipt Line. Default is 0.00.</description>
        <inlineHelpText>**Required** Total amount for the Receipt Line. Default is 0.00.</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Receipt Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Receipt Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Payment_Gateway__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated**  The related payment gateway.</description>
        <inlineHelpText>**System Calculated** The related payment gateway.</inlineHelpText>
        <label>Payment Gateway</label>
        <referenceTo>OrderApi__Payment_Gateway__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Posting_Entity__c</fullName>
        <description>**System Calculated/Override** The entity the Sales Order posted too. Sales Orders either post through an Invoice(s) or through a single Receipt as a Cash Sale.</description>
        <inlineHelpText>**System Calculated/Override** The entity the Sales Order posted too. Sales Orders either post through an Invoice(s) or through a single Receipt as a Cash Sale.</inlineHelpText>
        <label>Posting Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Receipt</fullName>
                    <default>true</default>
                    <label>Receipt</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Total__c</fullName>
        <description>**System Calculated**. Subtotal +</description>
        <formula>OrderApi__Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>**System Calculated** Subtotal +</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Intent_Id__c</fullName>
        <label>Payment Intent Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RefundRequestController.cls
/**
 * Created by lauren.lezberg on 12/2/2020.
 */

public with sharing class RefundRequestController {


    @AuraEnabled
    public static List<OrderApi__Receipt_Line__c> getReceiptLines(String receiptId){
        return [SELECT Id, OrderApi__Invoice__c, OrderApi__Item__c, OrderApi__Item__r.Name, OrderApi__Sale_Price__c FROM OrderApi__Receipt_Line__c WHERE OrderApi__Receipt__c=:receiptId];
    }

    @AuraEnabled
    public static StripePaymentController.StripeDTO processPartialRefund(String receiptId, String recLinesJSON){
        System.debug('processPartialRefund was just called with receipt: ' + receiptId);

        /** get payment receipt & lines **/
        OrderApi__Receipt__c paymentReceipt = [SELECT Id, Stripe_Payment_Intent_Id__c, OrderApi__Payment_Gateway__c, OrderApi__Is_Refund__c, OrderApi__Payment_Type__c, OrderApi__Sales_Order__r.OrderApi__Posting_Entity__c, OrderApi__Sales_Order__r.Payment_Intent_Id__c, OrderApi__Total__c, OrderApi__Sales_Order__c, OrderApi__Contact__c FROM OrderApi__Receipt__c WHERE Id=: receiptId];
        List<OrderApi__Receipt_Line__c> lines = (List<OrderApi__Receipt_Line__c>)JSON.deserialize(recLinesJSON, List<OrderApi__Receipt_Line__c>.class);
        System.debug('lines: ' + lines);

        Decimal totalRefundAmnt = 0.0;

        //initialize refund response
        StripePaymentController.StripeDTO refundResponse = new StripePaymentController.StripeDTO();

        //check if order has already been refunded
        if(paymentReceipt.OrderApi__Is_Refund__c){
            refundResponse.success = false;
            refundResponse.errorMsg = 'This order has already been refunded.';
            return refundResponse;
        }

        //check to make sure order was processed through stripe
        if(paymentReceipt.Stripe_Payment_Intent_Id__c!=null && paymentReceipt.OrderApi__Payment_Gateway__c==null) {

            OrderApi__Receipt__c refundReceipt = new OrderApi__Receipt__c();
            List<OrderApi__Receipt_Line__c> recLines = new List<OrderApi__Receipt_Line__c>();

            for(OrderApi__Receipt_Line__c line: lines){
                if(line.OrderApi__Sale_Price__c!=0.0) {
                    totalRefundAmnt += line.OrderApi__Sale_Price__c;
                    recLines.add(new OrderApi__Receipt_Line__c(
                            OrderApi__Invoice__c = line.OrderApi__Invoice__c,
                            OrderApi__Item__c = line.OrderApi__Item__c,
                            OrderApi__Sale_Price__c = line.OrderApi__Sale_Price__c,
                            OrderApi__Price_Override__c = true
                    ));
                }
            }

            System.debug('totalRefundAmnt: ' + totalRefundAmnt);

            refundReceipt.OrderApi__Sales_Order__c = paymentReceipt.OrderApi__Sales_Order__c;
            refundReceipt.OrderApi__Contact__c = paymentReceipt.OrderApi__Contact__c;
            refundReceipt.OrderApi__Type__c = 'Refund';
            refundReceipt.OrderApi__Payment_Type__c = paymentReceipt.OrderApi__Payment_Type__c;
            refundReceipt.OrderApi__Is_Refund__c = true;
            refundReceipt.OrderApi__Total__c = totalRefundAmnt;
            refundReceipt.OrderApi__Calculate_Memo__c = true;
            refundReceipt.OrderApi__Entity__c = 'Contact';



            //call Stripe API
            refundResponse = StripePaymentController.createStripeRefund(paymentReceipt.Stripe_Payment_Intent_Id__c, paymentReceipt.Id, totalRefundAmnt);
            if(refundResponse.success ){
                /**Stripe Workaround: refunds happen asynchronously.
                 * "Note that because refund failures are asynchronous,
                 * the refund will appear to be successful at first
                 * and will only have the failed status on subsequent fetches."
                 * **/
                refundResponse = StripePaymentController.getStripeRefund(refundResponse.token);
            }

            //if successful, insert receipt & lines & post
            /** FONTEVA: we have to insert receipt first and then update to posted in order to automatically create transactions in Fonteva **/
            if (refundResponse.success) {

                OrderApi__Invoice__c inv;
                if(paymentReceipt.OrderApi__Sales_Order__r.OrderApi__Posting_Entity__c=='Invoice'){
                    inv = [SELECT Id, OrderApi__Amount_Paid__c, OrderApi__Amount_Refunded__c FROM OrderApi__Invoice__c WHERE OrderApi__Sales_Order__c=:paymentReceipt.OrderApi__Sales_Order__c];
                    System.debug('invoice: ' + inv);
                    inv.OrderApi__Amount_Refunded__c += totalRefundAmnt;
                    inv.OrderApi__Amount_Paid__c = inv.OrderApi__Amount_Paid__c;

                }

                Database.insert(refundReceipt);

                for(OrderApi__Receipt_Line__c line : recLines){
                    line.OrderApi__Receipt__c = refundReceipt.Id;
                }


                Database.insert(recLines);

                refundReceipt.OrderApi__Is_Posted__c = true;

                try {
                    update refundReceipt;

                    if(paymentReceipt.OrderApi__Sales_Order__r.OrderApi__Posting_Entity__c=='Invoice'){
                        update inv;
                    }

                    //redirect user to new refund receipt
                    refundResponse.redirectURL = '/' + refundReceipt.Id;
                } catch (Exception e) {
                    new AACRCustomException(receiptId, e.getMessage(), e.getStackTraceString(), 'Refund Request');
                }
            }
            //order was not processed through stripe
        } else {
            refundResponse.success = false;
            refundResponse.errorMsg = 'No stripe payment attached. Refund cannot be processed.';
        }


        return refundResponse;

    }



    /**
     * @purpose Creates fonteva refund receipt, processes refund using stripe API and then posts receipt to create associated transaction & lines
     *
     * @param receiptId
     *
     * @return StripeDTO api response
     */
    @AuraEnabled
    public static StripePaymentController.StripeDTO processRefund(String receiptId){
        System.debug('processRefund was just called with receipt: ' + receiptId);
        /** get receipt & lines **/
        OrderApi__Receipt__c paymentReceipt = [SELECT Id,Stripe_Payment_Intent_Id__c, OrderApi__Payment_Gateway__c, OrderApi__Is_Refund__c, OrderApi__Payment_Type__c, OrderApi__Sales_Order__r.OrderApi__Posting_Entity__c, OrderApi__Sales_Order__r.Payment_Intent_Id__c, OrderApi__Total__c, OrderApi__Sales_Order__c, OrderApi__Contact__c FROM OrderApi__Receipt__c WHERE Id=: receiptId];
        List<OrderApi__Receipt_Line__c> lines = [SELECT OrderApi__Invoice__c, OrderApi__Item__c, OrderApi__Sale_Price__c, OrderApi__Price_Override__c FROM OrderApi__Receipt_Line__c WHERE OrderApi__Receipt__c =: receiptId];

        Decimal refundAmount = paymentReceipt.OrderApi__Total__c;

        /** initialize refund response **/
        StripePaymentController.StripeDTO refundResponse = new StripePaymentController.StripeDTO();

        /** check if order has already been refunded **/
        if(paymentReceipt.OrderApi__Is_Refund__c){
            refundResponse.success = false;
            refundResponse.errorMsg = 'This order has already been refunded.';
            return refundResponse;
        }


        /** check to make sure order was processed through stripe **/
        if(paymentReceipt.Stripe_Payment_Intent_Id__c!=null && paymentReceipt.OrderApi__Payment_Gateway__c==null) {
            OrderApi__Receipt__c refundReceipt = new OrderApi__Receipt__c();
            refundReceipt.OrderApi__Sales_Order__c = paymentReceipt.OrderApi__Sales_Order__c;
            refundReceipt.OrderApi__Contact__c = paymentReceipt.OrderApi__Contact__c;
            refundReceipt.OrderApi__Type__c = 'Refund';
            refundReceipt.OrderApi__Payment_Type__c = paymentReceipt.OrderApi__Payment_Type__c;
            refundReceipt.OrderApi__Is_Refund__c = true;
            refundReceipt.OrderApi__Total__c = refundAmount;
            refundReceipt.OrderApi__Calculate_Memo__c = true;
            refundReceipt.OrderApi__Entity__c = 'Contact'; 



            /** process refund through stripe **/
            refundResponse = StripePaymentController.createStripeRefund(paymentReceipt.Stripe_Payment_Intent_Id__c, paymentReceipt.Id, refundAmount);
            if(refundResponse.success ){
                /**Stripe Workaround: refunds happen asynchronously.
                 * "Note that because refund failures are asynchronous,
                 * the refund will appear to be successful at first
                 * and will only have the failed status on subsequent fetches."
                 * **/
                refundResponse = StripePaymentController.getStripeRefund(refundResponse.token);
            }

            /** FONTEVA WORKAROUND: we have to insert receipt first and then update to posted in order to automatically create transactions in Fonteva **/
            if (refundResponse.success) {

                /** Update invoice if sales order is for an invoice **/
                OrderApi__Invoice__c inv;
                if(paymentReceipt.OrderApi__Sales_Order__r.OrderApi__Posting_Entity__c=='Invoice'){
                    inv = [SELECT Id, OrderApi__Amount_Paid__c, OrderApi__Amount_Refunded__c FROM OrderApi__Invoice__c WHERE OrderApi__Sales_Order__c=:paymentReceipt.OrderApi__Sales_Order__c];
                    System.debug('invoice: ' + inv);
                    inv.OrderApi__Amount_Refunded__c += refundAmount;
                    inv.OrderApi__Amount_Paid__c = inv.OrderApi__Amount_Paid__c;

                }

                /** insert refund receipt **/
                Database.insert(refundReceipt);


                /** create receipt lines **/
                List<OrderApi__Receipt_Line__c> recLines = new List<OrderApi__Receipt_Line__c>();
                for(OrderApi__Receipt_Line__c line: lines){
                    recLines.add(new OrderApi__Receipt_Line__c(
                            OrderApi__Receipt__c = refundReceipt.Id,
                            OrderApi__Invoice__c = line.OrderApi__Invoice__c,
                            OrderApi__Item__c = line.OrderApi__Item__c,
                            OrderApi__Sale_Price__c = line.OrderApi__Sale_Price__c,
                            OrderApi__Price_Override__c = line.OrderApi__Price_Override__c
                    ));
                }
                insert recLines;

                /** update receipt to posted --> see fonteva workaround above **/
                refundReceipt.OrderApi__Is_Posted__c = true;

                try {
                    /** update receipt **/
                    update refundReceipt;

                    /** update invoice if necessary **/
                    if(paymentReceipt.OrderApi__Sales_Order__r.OrderApi__Posting_Entity__c=='Invoice'){
                        update inv;
                    }
                    /** redirect user to new refund receipt **/
                    refundResponse.redirectURL = '/' + refundReceipt.Id;
                } catch (Exception e) {
                    new AACRCustomException(receiptId, e.getMessage(), e.getStackTraceString(), 'Refund Request');
                }
            }
        /** order was not processed through stripe **/
        } else {
            refundResponse.success = false;
            refundResponse.errorMsg = 'No stripe payment attached. Refund cannot be processed.';
        }

        return refundResponse;
    }

}