src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Posting_Status__c</fullName>
        <description>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</description>
        <inlineHelpText>**System Calculated/Conditional/Override** The posting status for the Sales Order represents the posting status of related Invoices or the posting status of the Cash Sale Receipt, depending on the Posting Entity.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApi__Status__c</fullName>
        <description>The status of the Sales Order.</description>
        <inlineHelpText>The status of the Sales Order.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Batch_DeleteUnpostedSOTest.cls
@isTest
public class Batch_DeleteUnpostedSOTest {
    
    @isTest public static void testDeleteWithNoRecords(){
        List<OrderApi__Sales_Order__c> SOToDelete = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Posting_Status__c != 'Posted' AND (OrderApi__Status__c = 'Cancelled' OR OrderApi__Status__c = 'Open') AND CreatedDate < LAST_N_DAYS:90];
        System.assert(SOToDelete.size()==0, 'There should be no sales orders marked for deletion');
        
        Test.startTest();
        Batch_DeleteUnpostedSO obj = new Batch_DeleteUnpostedSO();
        DataBase.executeBatch(obj);    
        Test.stopTest();
        
        SOToDelete = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Posting_Status__c != 'Posted' AND (OrderApi__Status__c = 'Cancelled' OR OrderApi__Status__c = 'Open') AND CreatedDate < LAST_N_DAYS:90];
        System.assert(SOToDelete.size()==0, 'There should still be no sales orders marked for deletion.');
        
    }
    
    @isTest public static void testBatchDeleteOpen(){
        TestDataFactory dataFactory = new TestDataFactory();
        List<OrderApi__Sales_Order__c> lstSO = dataFactory.createOpenUnpostedSalesOrders(200);
        
        Integer i=0;
        //set half creation dates to 90 days ago
        for(OrderApi__Sales_Order__c s: lstSO){
            if(math.mod(i, 2) == 0){
                Test.setCreatedDate(s.Id, Date.today().addDays(-90));
            }
            i++;
        }


        
        List<OrderApi__Sales_Order__c> SOToDelete = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Posting_Status__c != 'Posted' AND (OrderApi__Status__c = 'Cancelled' OR OrderApi__Status__c = 'Open') AND CreatedDate < LAST_N_DAYS:90];
        System.assertEquals(100, SOToDelete.size(), '100 Sales Orders should be marked for deletion');
        
        Test.startTest();
        Batch_DeleteUnpostedSO obj = new Batch_DeleteUnpostedSO();
        DataBase.executeBatch(obj);    
        Test.stopTest();
        
        SOToDelete = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Posting_Status__c != 'Posted' AND (OrderApi__Status__c = 'Cancelled' OR OrderApi__Status__c = 'Open') AND CreatedDate < LAST_N_DAYS:90];
        System.assert(SOToDelete.size()==0, 'No more sales orders should be marked for deletion');
    }

    @isTest public static void testBatchDeleteCancelled(){
        TestDataFactory dataFactory = new TestDataFactory();
        List<OrderApi__Sales_Order__c> lstSO = dataFactory.createCancelledUnpostedSalesOrders(200);

        Integer i=0;
        //set half creation dates to 90 days ago
        for(OrderApi__Sales_Order__c s: lstSO){
            if(math.mod(i, 2) == 0){
                Test.setCreatedDate(s.Id, Date.today().addDays(-91));
            }
            i++;
        }

        List<OrderApi__Sales_Order__c> SOToDelete = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Posting_Status__c != 'Posted' AND (OrderApi__Status__c = 'Cancelled' OR OrderApi__Status__c = 'Open') AND CreatedDate < LAST_N_DAYS:90];
        System.assertEquals(100, SOToDelete.size(), '100 Sales Orders should be marked for deletion');

        Test.startTest();
        Batch_DeleteUnpostedSO obj = new Batch_DeleteUnpostedSO();
        DataBase.executeBatch(obj);
        Test.stopTest();

        SOToDelete = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Posting_Status__c != 'Posted' AND (OrderApi__Status__c = 'Cancelled' OR OrderApi__Status__c = 'Open') AND CreatedDate < LAST_N_DAYS:90];
        System.assert(SOToDelete.size()==0, 'No more sales orders should be marked for deletion');
    }
}