src/objects/OrderApi__Badge_Type__c.object
<CustomObject>
    <description>Configure Badge Types to assign to Contacts to allow greater control and flexibility around pricing and content accessibility.</description>
    <label>Badge Type</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Class__c.object
<CustomObject>
    <description>Master categorization and logic driver for Items and Item purchase work flow.</description>
    <label>Item Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DirectoryControllerTest.cls
/**
 * Created by lauren.lezberg on 5/23/2019.
 */
@isTest
private with sharing class DirectoryControllerTest {

    @testSetup public static void setup(){
        OrderApi__Badge_Type__c bt = TestDataFactory.buildBadgeType('Directory Access');
        insert bt;
    }

    @isTest
    public static void testGetFilterCriteria(){

        DirectoryController.DirectoryFilters filters = DirectoryController.getFilterCriteria();
        System.assertNotEquals(null, filters);

    }

    @IsTest
    public static void test_getDirectoryLaunchData(){
        Account acc = TestDataFactory.buildAccount('Test Account 2');
        insert acc;

        Contact con = TestDataFactory.buildContactMemberCurrent(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;

        System.runAs(u){
            Test.startTest();
            DirectoryController.DirectoryLaunchData dld = DirectoryController.getDirectoryLaunchData();
            Test.stopTest();

            System.assertEquals(true, dld.showLaunchButton);
            System.assertNotEquals(null, dld.url);

        }
    }

    @isTest
    public static void testGetContactWorkingGroups(){

        Account acc = TestDataFactory.buildAccount('Test Account 2');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;
        OrderApi__Item_Class__c itemClass = TestDataFactory.buildItemClass('Working Groups');
        insert itemClass;
        OrderApi__Item__c item = TestDataFactory.buildItem(itemClass.Id, 'Chemistry in Cancer Research (CICR)');
        insert item;
        OrderApi__Subscription_Plan__c subPlan = TestDataFactory.buildsubPlan();
        insert subPlan;
        OrderApi__Subscription__c sub = TestDataFactory.buildSubscription(con.Id, subPlan.id, item.Id, itemClass.Id);
        insert sub;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;
        System.runAs(u) {
            Test.startTest();
            String wgs = DirectoryController.getContactWorkingGroups(u.contactId);
            Test.stopTest();

            System.assertNotEquals(null, wgs);
        }

    }

    @isTest
    public static void testCheckDirectoryAccess(){
        Account acc = TestDataFactory.buildAccount('Test Account 2');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;

        System.runAs(u){

            Test.startTest();
            DirectoryController controller = new DirectoryController();
            controller.checkDirectoryAccess();
            System.assertEquals(false, controller.showDirectory);
            BadgeUtils.enableDirectoryAccess(con.Id);
            controller.checkDirectoryAccess();
            System.assertEquals(true, controller.showDirectory);
            Test.stopTest();


        }
    }

    @isTest
    public static void testSendEmailToMember(){
        Account acc = TestDataFactory.buildAccount('Test Account 2');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;
        System.runAs(u){
            Test.startTest();
            Boolean emailSent = DirectoryController.sendEmailToMember('test123@yopmail.com', 'Test Subject', 'Test Body');
            Test.stopTest();

            System.assertEquals(true, emailSent);
        }
    }

    @isTest
    public static void testFetchContacts(){
        Account acc = TestDataFactory.buildAccount('Test Account 2');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;
        System.runAs(u) {
            Test.startTest();
            DirectoryController.DirectoryPagerWrapper wrapper = DirectoryController.fetchContacts(1, 25, new List<String>{'Cancer Therapeutics', 'Biophysics'}, new List<String>{'China', 'France'}, new List<String>{'Massachusetts', 'Texas'}, 'John', acc.Id, 'Name', 'ASC');
            Test.stopTest();

            System.assertNotEquals(null, wrapper);
        }
    }
}