src/objects/OrderApi__Known_Address__c.object
<CustomObject>
    <description>Known Addresses allows Contacts and Accounts to have multiple related address records.</description>
    <fields>
        <fullName>Bad_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Returned Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__City__c</fullName>
        <description>Address City</description>
        <inlineHelpText>Address City</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the known address to a contact.</description>
        <inlineHelpText>Relates the known address to a contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Known Addresses</relationshipLabel>
        <relationshipName>Known_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Country__c</fullName>
        <description>Address Country</description>
        <inlineHelpText>Address Country</inlineHelpText>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, this will be the pre-populated address when a user is checking out. Only one address
            can be checked for a contact at any given time.</description>
        <inlineHelpText>When checked, this will be the pre-populated address when a user is checking out. Only one
            address can be checked for a contact at any given time.</inlineHelpText>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Postal_Code__c</fullName>
        <description>Address Zip/Postal Code</description>
        <inlineHelpText>Address Zip/Postal Code</inlineHelpText>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Province__c</fullName>
        <description>Address State</description>
        <inlineHelpText>Address State</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderApi__Street__c</fullName>
        <description>Address Street</description>
        <inlineHelpText>Address Street</inlineHelpText>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Journal</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Known Address</label>
    <nameField>
        <displayFormat>KA-{000000000}</displayFormat>
        <label>Known Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateJournalAddressModalControllerTest.cls
/**
 * Created by lauren.lezberg on 9/18/2020.
 */

@IsTest
private class UpdateJournalAddressModalControllerTest {

    @TestSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

    }


    @IsTest
    static void test_getAndSaveJournalAddress() {
        Contact con = [SELECT Id FROM Contact WHERE Account.Name='Test Account'];

        OrderApi__Known_Address__c ka = new OrderApi__Known_Address__c(
                Type__c= 'Business',
                Bad_Address__c = false,
                OrderApi__Is_Default__c = true,
                OrderApi__Contact__c = con.Id,
                OrderApi__Street__c = '43 Coolidge Ave',
                OrderApi__City__c = 'Needham',
                OrderApi__Country__c = 'United States',
                OrderApi__Province__c = 'Massachusetts',
                OrderApi__Postal_Code__c = '02492'
        );
        insert ka;

        Test.startTest();

        //run code to copy primary into journal
        UpdateJournalAddressModalController.JournalAddressInfo jAddress = UpdateJournalAddressModalController.getJournalAddress(con.Id);
        System.assertEquals(jAddress.journalAddress.OrderApi__Street__c, ka.OrderApi__Street__c);

        jAddress.journalAddress.OrderApi__Street__c = '123 Main St';
        jAddress.journalAddress.OrderApi__City__c = 'Test';
        UpdateJournalAddressModalController.saveJournalAddress(jAddress.journalAddress);
        jAddress.journalAddress = [SELECT Id, OrderApi__Street__c, OrderApi__City__c FROM OrderApi__Known_Address__c WHERE OrderApi__Contact__c =: con.Id AND Type__c = 'Journal'];
        System.assertEquals('123 Main St', jAddress.journalAddress.OrderApi__Street__c );
        System.assertEquals('Test', jAddress.journalAddress.OrderApi__City__c);

        //run code with journal address
        jAddress = UpdateJournalAddressModalController.getJournalAddress(con.Id);
        System.assertEquals(jAddress.journalAddress.OrderApi__Street__c, '123 Main St');



        Test.stopTest();
    }
    
}