src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is item type managed or unmanaged</description>
        <label>Managed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Required ** Link to related Item Class</description>
        <inlineHelpText>** Required ** Link to related Item Class</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_In_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Display Item as selectable in portal</description>
        <label>Show In Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Item_Subscription_Plan__c.object
<CustomObject>
    <description>Links a &quot;Subscription&quot; Item to a Subscription Plan to enable the linked Item to be sold in conjunction with the linked Subscription Plan.</description>
    <fields>
        <fullName>OrderApi__Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines the default Subscription Plan for related Item.</description>
        <inlineHelpText>Defines the default Subscription Plan for related Item.</inlineHelpText>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <description>** Required ** Link to the Item enabled for the related Subscription Plan.</description>
        <inlineHelpText>** Required ** Link to the Item enabled for the related Subscription Plan.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscription Plans</relationshipLabel>
        <relationshipName>Subscription_Plan_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <description>** Required ** Link to the Subscription Plan that the related Subscription Item is being enabled for.</description>
        <inlineHelpText>** Required ** Link to the Subscription Plan that the related Subscription Item is being enabled for.</inlineHelpText>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Subscription_Plan_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Item Subscription Plan</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Item Subscription Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Subscription Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order__c.object
<CustomObject>
    <description>Sales Orders are the primary object for all sales related transactions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</description>
        <inlineHelpText>**System Calculated/Override** Link to the customer&apos;s contact record. Auto-populates with the related account&apos;s primary contact if not defined prior to entry.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Sales Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Sales_Order_Line__c.object
<CustomObject>
    <description>Sales Order Lines track the Items associated with Sales Orders.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</description>
        <inlineHelpText>** Conditionally Required System Calculated Override ** Link to the Contact who is the primary assignee of the Item purchased on the Sales Order Line. Required if &quot;Enable Assignments&quot; is checked on the related Item. Defaults to the Sales Order Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated / Override ** Link to the related Item Class.</description>
        <inlineHelpText>** System Calculated / Override ** Link to the related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Sales Order Lines</relationshipLabel>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the item related to the sales order.</description>
        <inlineHelpText>Link to the item related to the sales order.</inlineHelpText>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Sales_Order__c</fullName>
        <description>**Required** All Sales Order Lines require a linked Sales Order.</description>
        <inlineHelpText>**Required** All Sales Order Lines require a linked Sales Order.</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>OrderApi__Sales_Order__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</description>
        <inlineHelpText>** Conditionally Required ** Link to the related plan that controls Activation and Expiration dates related to any Subscription Item. Required when the Sales Order Line is linked to a Item that is the child of a &quot;Subscription&quot; Item Class.</inlineHelpText>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipName>Sales_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the Subscription that is being upgraded or renewed.</description>
        <inlineHelpText>Link to the Subscription that is being upgraded or renewed.</inlineHelpText>
        <label>Subscription (Upgrade/Renew)</label>
        <referenceTo>OrderApi__Subscription__c</referenceTo>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sales Order Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</description>
        <inlineHelpText>** System Calculated Conditionally Required ** Link to the subscribing Contact. Required if the Subscription &quot;Subscribing Entity&quot; is &quot;Contact&quot;. Defaults to the same Contact assigned to the Sales Order Line that created the Subscription.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Item Class.</description>
        <inlineHelpText>** System Calculated ** Link to related Item Class.</inlineHelpText>
        <label>Item Class</label>
        <referenceTo>OrderApi__Item_Class__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>OrderApi__Advanced_Calendar_Days__c</fullName>
        <description>Number of days before the start of the next calendar term, during which new subscriptions are automatically extended to include the next term.</description>
        <inlineHelpText>Number of days before the start of the next calendar term, during which new subscriptions are automatically extended to include the next term.</inlineHelpText>
        <label>Advanced Calendar Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Show_In_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show record in portal to users</description>
        <label>Show In Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to hold dues renewal information and configurations</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Are renewals active (turned on)</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term_Year__c</fullName>
        <description>Renewal Term Year</description>
        <label>Term Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Renewal Settings</label>
</CustomObject>

src/classes/ModifyMembershipControllerTest.cls
/**
 * Created by lauren.lezberg on 2/6/2020.
 */
@isTest
private with sharing class ModifyMembershipControllerTest {
    @testSetup
    public static void setup(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;

        User u = TestDataFactory.buildUser(con.Id);
        insert u;

        OrderApi__Subscription_Plan__c subPlan1 = TestDataFactory.buildsubPlan();
        insert subPlan1;


        OrderApi__Subscription_Plan__c subPlan2 = TestDataFactory.buildsubPlan();
        subPlan2.Name = '2YR Membership';
        subPlan2.Show_In_Portal__c = false;
        subPlan2.OrderApi__Advanced_Calendar_Days__c = 365;
        insert subPlan2;

        OrderApi__Item_Class__c membershipClass = TestDataFactory.buildItemClass('Individual Memberships');
        insert membershipClass;

        OrderApi__Item__c membership = TestDataFactory.buildItem(membershipClass.Id, 'Active Membership');
        membership.Managed__c = true;
        insert membership;

        OrderApi__Item_Subscription_Plan__c memSubPlan = TestDataFactory.buildItemSubPlan(membership.Id, subPlan1.Id);
        memSubPlan.OrderApi__Is_Default__c = true;
        insert memSubPlan;

        OrderApi__Item_Subscription_Plan__c memSubPlan2 = TestDataFactory.buildItemSubPlan(membership.Id, subPlan2.Id);
        insert memSubPlan2;

        OrderApi__Subscription__c membershipSub = TestDataFactory.buildSubscription(con.Id, subPlan1.Id, membership.Id, membershipClass.Id);
        insert membershipSub;

        Renewal_Settings__c renewalProcess = new Renewal_Settings__c();
        renewalProcess.Term_Year__c = System.now().year() + 1;
        renewalProcess.Is_Active__c = false;
        insert renewalProcess;
    }

    @isTest
    public static void test_getShowModify(){
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name='Test Account'];

        User u = [SELECT Id FROM User WHERE ContactId=: con.Id];

        PermissionSet ps = new PermissionSet();
        ps.Name = 'Test';
        ps.Label = 'Test';
        insert ps;

        SetupEntityAccess sea = new SetupEntityAccess();
        sea.ParentId = ps.Id;
        sea.SetupEntityId = [SELECT Id, DeveloperName FROM CustomPermission WHERE DeveloperName = 'Modify_Membership'][0].Id;
        insert sea;

        PermissionSetAssignment psa = new PermissionSetAssignment();
        psa.AssigneeId = u.Id;
        psa.PermissionSetId = ps.Id;
        insert psa;


        System.runAs(u) {

            Test.startTest();
                Boolean showModifyButton = ModifyMembershipController.getShowModify(con.Id);
                System.assertEquals(true, showModifyButton);
            Test.stopTest();

        }
    }

    @isTest
    public static void test_createModifySalesOrder(){
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name='Test Account'];

        Test.startTest();
        Map<String, String> modifySOInfo = ModifyMembershipController.createModifySalesOrder(con.Id);
        Test.stopTest();

        Id jpRecordId = [SELECT Id FROM Join_Process__mdt WHERE DeveloperName='Modify_Membership' LIMIT 1].Id;
        OrderApi__Sales_Order__c SO = [SELECT Id FROM OrderApi__Sales_Order__c WHERE OrderApi__Contact__c=:con.Id ORDER BY CreatedDate LIMIT 1];

        for(String key : modifySOInfo.keySet()){
            System.assertEquals(key, SO.Id);
            System.assertEquals(modifySOInfo.get(key), jpRecordId);
        }

    }

    @isTest
    public static void test_removeMembershipLine(){
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name='Test Account'];
        OrderApi__Item__c membership = [SELECT Id FROM OrderApi__Item__c WHERE OrderApi__Item_Class__r.Name='Individual Memberships'];
        OrderApi__Subscription_Plan__c subPlan = [SELECT Id FROM OrderApi__Subscription_Plan__c WHERE Show_In_Portal__c = true AND OrderApi__Advanced_Calendar_Days__c = null];

        List<String> subIds = new List<String>();
        for(OrderApi__Subscription__c sub: [SELECT Id FROM OrderApi__Subscription__c WHERE OrderApi__Contact__c=: con.Id]){
            subIds.add(sub.Id);
        }

        OrderApi__Sales_Order__c SO = new OrderApi__Sales_Order__c(OrderApi__Contact__c=con.Id);
        insert SO;

        Test.startTest();
            List<OrderApi__Sales_Order_Line__c> lines = ModifyMembershipController.addSelectedItemToSO(membership.Id, subPlan.Id, SO.Id);
            System.assertEquals(1, lines.size());

            lines = ModifyMembershipController.removeSelectedItemFromSO(membership.Id, SO.Id);
            System.assertEquals(0, lines.size());

            lines = ModifyMembershipController.addSelectedItemToSO(membership.Id, subPlan.Id, SO.Id);
            ModifyMembershipController.removeMembershipFromSO(SO.Id);
        Test.stopTest();

        Integer membershipLines = [SELECT COUNT() FROM OrderApi__Sales_Order_Line__c WHERE OrderApi__Sales_Order__c=: SO.Id AND OrderApi__Item_Class__r.Name='Individual Memberships'];
        System.assertEquals(0, membershipLines);
    }

    @isTest
    public static void test_getModifyInfo(){
        Contact con = [SELECT Id, AccountId FROM Contact WHERE Account.Name='Test Account'];
        OrderApi__Sales_Order__c SO = new OrderApi__Sales_Order__c(OrderApi__Contact__c=con.Id);
        insert SO;
        OrderApi__Subscription_Plan__c subPlan = [SELECT Id FROM OrderApi__Subscription_Plan__c WHERE Show_In_Portal__c = true AND OrderApi__Advanced_Calendar_Days__c = null];

        OrderApi__Subscription__c membershipSub = [SELECT Id FROM OrderApi__Subscription__c WHERE OrderApi__Contact__c=: con.Id AND OrderApi__Item_Class__r.Name='Individual Memberships' LIMIT 1];

        Test.startTest();
        //test with renewals off and 1 yr sub
        ModifyMembershipController.ModifyInfo mInfo = ModifyMembershipController.getModifyInfo(SO.Id);
        System.assertNotEquals(null, mInfo);
        System.assertNotEquals(0, mInfo.soLines.size());
        System.assertEquals(subPlan.Id, mInfo.subPlanId);

        Renewal_Settings__c renewalProcess = [SELECT Is_Active__c, Id, Term_Year__c FROM Renewal_Settings__c LIMIT 1];
        renewalProcess.Is_Active__c = true;
        update renewalProcess;

        //test with renewals on
        mInfo = ModifyMembershipController.getModifyInfo(SO.Id);
        System.assertNotEquals(null, mInfo);
        System.assertNotEquals(0, mInfo.soLines.size());
        System.assertEquals(subPlan.Id, mInfo.subPlanId);

        membershipSub.OrderApi__Paid_Through_Date__c = Date.newInstance((Integer)renewalProcess.Term_Year__c, 12, 31);
        update membershipSub;

        //test with renewals on and 2 yr sub
        mInfo = ModifyMembershipController.getModifyInfo(SO.Id);
        System.assertNotEquals(null, mInfo);
        System.assertNotEquals(0, mInfo.soLines.size());
        System.assertNotEquals(subPlan.Id, mInfo.subPlanId);

        Test.stopTest();
    }


}