src/objects/OrderApi__Badge__c.object
<CustomObject>
    <description>Badges are assigned to Contacts either automatically (Badge Workflow) or manually. Badges can enable Contacts for special Price Rules - as well as permission to read, update, or delete certain content types.</description>
    <fields>
        <fullName>OrderApi__Badge_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Badge Type</label>
        <referenceTo>OrderApi__Badge_Type__c</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the assigned Contact.</description>
        <inlineHelpText>Link to the assigned Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Badges</relationshipLabel>
        <relationshipName>Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked, the Badge is considered &quot;Awarded&quot; and &quot;Active&quot; and will be considered when calculating any permission or pricing configurations related to the linked Badge Type. Defaults checked.</description>
        <inlineHelpText>When checked, the Badge is considered &quot;Awarded&quot; and &quot;Active&quot; and will be considered when calculating any permission or pricing configurations related to the linked Badge Type. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Badge ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Badge_Type__c.object
<CustomObject>
    <description>Configure Badge Types to assign to Contacts to allow greater control and flexibility around pricing and content accessibility.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked the Badge Type is active and available for assignment to a Contact</description>
        <inlineHelpText>When checked the Badge Type is active and available for assignment to a Contact</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Badge Type</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badge Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BadgeUtilsTest.cls
/**
 * Created by lauren.lezberg on 5/15/2019.
 */
@isTest
private with sharing class BadgeUtilsTest {

    @testSetup public static void setup(){
        List<OrderApi__Badge_Type__c> badgeTypeList = TestDataFactory.createBadgeType();
        insert badgeTypeList;
        System.assertEquals(9, [SELECT Id FROM OrderApi__Badge_Type__c].size());
    }



    @isTest
    public static void test_ExpireAndActivateDirectoryBadges(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;

        Contact con = TestDataFactory.buildContact(acc.Id);

        insert con;

        OrderApi__Badge_Type__c bt = TestDataFactory.buildBadgeType('Directory Access');
        insert bt;

        Set<Id> contactIds = new Set<Id>();
        contactIds.add(con.Id);

        Test.startTest();

        BadgeUtils.enableDirectoryAccess(contactIds);

        List<OrderApi__Badge__c> badges = [SELECT OrderApi__Is_Active__c FROM OrderApi__Badge__c WHERE OrderApi__Contact__c=: con.Id AND OrderApi__Is_Active__c=true AND OrderApi__Badge_Type__r.Name='Directory Access'];
        System.assertEquals(1, badges.size());

        BadgeUtils.expireDirectoryBadges(badges);

        Integer badgeCount = [SELECT COUNT() FROM OrderApi__Badge__c WHERE OrderApi__Contact__c=: con.Id AND OrderApi__Is_Active__c=false AND OrderApi__Badge_Type__r.Name='Directory Access'];

        System.assertEquals(1, badgeCount);

        BadgeUtils.enableDirectoryAccess(contactIds);

        badges = [SELECT OrderApi__Is_Active__c FROM OrderApi__Badge__c WHERE OrderApi__Contact__c=: con.Id AND OrderApi__Is_Active__c=true AND OrderApi__Badge_Type__r.Name='Directory Access'];
        System.assertEquals(1, badges.size());

        Test.stopTest();


    }

    @isTest
    private static void test_DirectoryBadgeAccess(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;
        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;
        OrderApi__Badge_Type__c bt = TestDataFactory.buildBadgeType('Directory Access');
        insert bt;

        Test.startTest();
        Boolean badgeCreated = BadgeUtils.enableDirectoryAccess(con.Id);
        System.assertEquals(true, badgeCreated);

        Boolean badgeRevoked = BadgeUtils.revokeDirectoryAccess(con.Id);
        System.assertEquals(true, badgeRevoked);

        Boolean badgeEnabled = BadgeUtils.enableDirectoryAccess(con.Id);
        System.assertEquals(true, badgeEnabled);

        Test.stopTest();

    }


    @isTest
    private static void test_FellowBadgeAccess(){
        Account acc = TestDataFactory.buildAccount('Test Account');
        insert acc;
        Contact con = TestDataFactory.buildContact(acc.Id);
        insert con;
        OrderApi__Badge_Type__c bt = TestDataFactory.buildBadgeType('AACR Fellow');
        insert bt;

        Test.startTest();
        Boolean badgeCreated = BadgeUtils.enableFellowAccess(con.Id);
        System.assertEquals(true, badgeCreated);

        Boolean badgeRevoked = BadgeUtils.revokeFellowAccess(con.Id);
        System.assertEquals(true, badgeRevoked);

        Boolean badgeEnabled = BadgeUtils.enableFellowAccess(con.Id);
        System.assertEquals(true, badgeEnabled);

        Test.stopTest();

    }
}