src/objects/OrderApi__Item__c.object
<CustomObject>
    <description>Items store all products, services and funds an organization uses to generate revenue.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</description>
        <inlineHelpText>When checked, the Item is considered available for sale and will be made available for selection against Invoice, Sales Order, Receipt, and EPayment Lines. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Renewal__c.object
<CustomObject>
    <description>Terms track the Subscription terms, dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Grace_Period_End_Date__c</fullName>
        <description>This date is calculated by the Term End Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</description>
        <inlineHelpText>This date is calculated by the Term End Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</inlineHelpText>
        <label>Grace Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines the active subscription term.</description>
        <inlineHelpText>Defines the active subscription term.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated ** Link to related Subscription Plan</description>
        <inlineHelpText>** System Calculated ** Link to related Subscription Plan</inlineHelpText>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Renewals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription__c</fullName>
        <description>** System Calculated Required ** Link to related Subscription</description>
        <inlineHelpText>** System Calculated Required ** Link to related Subscription</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>OrderApi__Subscription__c</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Renewals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OrderApi__Term_End_Date__c</fullName>
        <description>** System Calculated Required Override ** The date the term ends.</description>
        <inlineHelpText>** System Calculated Required Override ** The date the term ends.</inlineHelpText>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <label>Term</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Term ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription__c.object
<CustomObject>
    <description>Subscriptions track the activation, expiration, and renewal dates for all Customer Subscriptions.</description>
    <fields>
        <fullName>OrderApi__Current_Term_End_Date__c</fullName>
        <description>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</description>
        <inlineHelpText>** System Calculated Required Override ** The end date (Expiration Date) for the current subscription term.</inlineHelpText>
        <label>Current Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Grace_Period_End_Date__c</fullName>
        <description>This date is calculated by the Paid Through Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</description>
        <inlineHelpText>This date is calculated by the Paid Through Date plus the number of days defined on the Subscription Plan&apos;s Grace Period field.</inlineHelpText>
        <label>Grace Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</description>
        <inlineHelpText>When checked the Subscription is considered &quot;Active&quot;. Defaults checked.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderApi__Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</description>
        <inlineHelpText>** System Calculated Required Override ** Link to the primary &quot;Subscription&quot; Item</inlineHelpText>
        <label>Item (Primary)</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderApi__Subscription_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Plan</label>
        <referenceTo>OrderApi__Subscription_Plan__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderApi__Subscription_Plan__c.object
<CustomObject>
    <description>Subscription Plans control the subscription dates with &quot;Termed&quot;, &quot;Evergreen&quot;, and &quot;Calendar&quot; options.</description>
    <fields>
        <fullName>OrderApi__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</description>
        <inlineHelpText>When checked, the Subscription Plan will be made available for selection - as configured for Subscription Plan Items.</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription Plan</label>
    <nameField>
        <label>Subscription Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscription Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LifetimeConverterButtonController.cls
/**
 * Created by lauren.lezberg on 5/18/2021.
 */

public with sharing class LifetimeConverterButtonController {

    @AuraEnabled
    public static Boolean getVisibility(String contactId){
        Boolean showBtn = false;
        List<OrderApi__Subscription__c> subscriptions = RenewalUtils.getIndividualMembershipSubscription(contactId);
        if(!subscriptions.isEmpty()){
            if(subscriptions[0].OrderApi__Is_Active__c && subscriptions[0].OrderApi__Item__r.Name=='Active Membership' && subscriptions[0].OrderApi__Subscription_Plan__r.Name!='Lifetime'){
                showBtn = true;
            }
        }

        showBtn = showBtn && FeatureManagement.checkPermission('Lifetime_Conversion');

        return showBtn;
    }

    @AuraEnabled
    public static void doConversion(String contactId){

        List<OrderApi__Subscription__c> subscriptions = RenewalUtils.getIndividualMembershipSubscription(contactId);
        if(!subscriptions.isEmpty()){
            OrderApi__Subscription__c memSub = subscriptions[0];
            List<OrderApi__Renewal__c> terms = [SELECT Id, OrderApi__Term_End_Date__c, OrderApi__Grace_Period_End_Date__c, OrderApi__Subscription_Plan__c FROM OrderApi__Renewal__c WHERE OrderApi__Subscription__c=:memSub.Id ORDER BY OrderApi__Term_End_Date__c DESC];
            List<OrderApi__Subscription_Plan__c> lifeTimePlans = [SELECT Id FROM OrderApi__Subscription_Plan__c WHERE Name='Lifetime'];
            memSub.OrderApi__Subscription_Plan__c = lifeTimePlans[0].Id;
            memSub.OrderApi__Current_Term_End_Date__c = memSub.OrderApi__Current_Term_End_Date__c.addYears(100);
            memSub.OrderApi__Grace_Period_End_Date__c = null;

            terms[0].OrderApi__Term_End_Date__c = terms[0].OrderApi__Term_End_Date__c.addYears(100);
            terms[0].OrderApi__Grace_Period_End_Date__c = null;
            terms[0].OrderApi__Subscription_Plan__c = lifeTimePlans[0].Id;

            try{
                update memSub;
                update terms[0];
            } catch(Exception e){
                System.debug('could not convert member to lifetime: ' + e.getMessage());
                new AACRCustomException(contactId, e.getMessage(), e.getStackTraceString(), 'Lifetime Conversion');
            }


        }
    }
}