src/objects/Session_Speaker__c.object
<CustomObject>
    <description>Speaker records associated with each session</description>
    <fields>
        <fullName>Assistant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assistant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Session Speakers (Assistant)</relationshipLabel>
        <relationshipName>Assistants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <description>Speaker roles for a particular session</description>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chair</fullName>
                </value>
                <value>
                    <fullName>Cochair</fullName>
                </value>
                <value>
                    <fullName>Program Committee Member</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Member</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Member</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Member</fullName>
                </value>
                <value>
                    <fullName>Program Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Program Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Scientific Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Keynote Speaker</fullName>
                </value>
                <value>
                    <fullName>Speaker</fullName>
                </value>
                <value>
                    <fullName>Session Chair</fullName>
                </value>
                <value>
                    <fullName>Discussant</fullName>
                </value>
                <value>
                    <fullName>Moderator</fullName>
                </value>
                <value>
                    <fullName>Panelist</fullName>
                </value>
                <value>
                    <fullName>Proffered Presenter</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Codirector</fullName>
                </value>
                <value>
                    <fullName>Faculty</fullName>
                </value>
                <value>
                    <fullName>Lab Director</fullName>
                </value>
                <value>
                    <fullName>Lab Assistant</fullName>
                </value>
                <value>
                    <fullName>Lecturer</fullName>
                </value>
                <value>
                    <fullName>Observer</fullName>
                </value>
                <value>
                    <fullName>Short-talk Presenter</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Organizing Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Chair</fullName>
                </value>
                <value>
                    <fullName>Executive Committee Cochair</fullName>
                </value>
                <value>
                    <fullName>Abstract Review Committee Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;--None--&quot;</defaultValue>
        <description>Status of speakers invitation</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Tentative</fullName>
                </value>
                <value>
                    <fullName>Negotiating</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Suggested</fullName>
                </value>
                <value>
                    <fullName>Considering</fullName>
                    <isActive>false</isActive>
                    <label>Considering</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Use_for_Invite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use for Invite</label>
        <type>Checkbox</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <label>Presentation Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChairPersonsController.cls
/**
 * Created by lauren.lezberg on 1/14/2020.
 */

public with sharing class ChairPersonsController {

    /**
     * @purpose Delete selected chair person
     * @param cpId
     */
    @AuraEnabled
    public static void deleteChairperson(String cpId){
        if(cpId!=null) {
            Session_Speaker__c speaker = [SELECT Id FROM Session_Speaker__c WHERE Id = :cpId];

            try {
                delete speaker;
            } catch (Exception e) {
                System.debug('could not delete chairperson: ' + e.getMessage());
                throw new AACRCustomException(cpId, e.getMessage(), e.getStackTraceString(), 'Chair Person');
            }
        }
    }

    /**
     * @purpose Retrieve all chair persons for an event
     *
     * @param eventId
     *
     * @return Chair Persons data instance with list of chair persons 
     */
    @AuraEnabled
    public static ChairPersonsData getChairPersonsData(String eventId){
        if(String.isBlank(eventId)){
            new AACRCustomException('Event Id is null', 'ChairPersonsController.getChairPersonsData', 'Chair Person');
            return null;
        }

        ChairPersonsData cpd = new ChairPersonsData();
        cpd.persons = [SELECT Speaker__r.Name,Use_for_Invite__c, Speaker__c, Roles__c, Status__c, Assistant__c, Assistant__r.Name FROM Session_Speaker__c WHERE Event__c=: eventId AND RecordType.Name='Chair Person'];
        cpd.cpRecordTypeId = Schema.SObjectType.Session_Speaker__c.getRecordTypeInfosByName().get('Chair Person').getRecordTypeId();
        return cpd;
    }

    public class ChairPersonsData{
        @AuraEnabled
        public List<Session_Speaker__c> persons;

        @AuraEnabled
        public String cpRecordTypeId;

    }

}