src/objects/Virtual_Event_Details__c.object
<CustomObject>
    <fields>
        <fullName>Custom_URL__c</fullName>
        <label>Custom URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipLabel>Virtual Event Details</relationshipLabel>
        <relationshipName>Virtual_Event_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Event_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Event Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Virtual Event Details</label>
    <nameField>
        <label>Virtual Event Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Event Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/V_SimpleHTMLRedirect.cls
/**
 * Created by lauren.lezberg on 4/28/2021.
 */

public without sharing class V_SimpleHTMLRedirect implements Callable, VirtualEventIntegration{
    public Object call(String action, Map<String, Object> args){
        switch on action {
            when 'sendAttendee' {
                return null;
            }
            when 'asyncSendAttendee' {
                return null;
            }
            when 'updateAttendee' {
                return null;
            }
            when 'deleteAttendee' {
                return null;
            }
            when 'goToVenue' {
                return this.goToVenue((String)args.get('contactId'), (String)args.get('SFEventId'));
            }
            when else {
                throw new AACRCustomException('Failure to execute action: ' + action, 'SimpleHTMLRedirectIntegration.call()', 'SimpleHTMLRedirectIntegration');
            }
        }
    }

    public static void deleteAttendee(String fuzionAttendeeId, String fuzionEventId){

    }

    public static void updateAttendee(String participantId){

    }

    public String sendAttendee(String contactId, String externalEventId, Boolean flag){

        return null;
    }

    @Future(callout=true)
    public static void asyncSendAttendee(String contactId, String externalEventId, Boolean flag){

    }

    public String goToVenue(String contactId, String SFEventId){

        Virtual_Event_Details__c ved = [SELECT External_Event_Id__c, Custom_URL__c FROM Virtual_Event_Details__c WHERE Event__c=: SFEventId];


        return ved.Custom_URL__c;
    }
}